option = {
    "color":[
        "#F58080",
        "#47D8BE",
        "#1E90FF"],
    "tooltip":{
        "trigger":"axis"
    },
    "grid":{
        "containLabel":true,
        "left":0,
        "right":0,
        "bottom":0,
        "top":60
    },
    "legend":{
        "left":"center",
        "top":"top"
    },
    "xAxis":{
        "type":"category",
        "data":[
            "2020-06-29",
            "2020-06-30",
            "2020-07-01",
            "2020-07-02",
            "2020-07-03",
            "2020-07-04",
            "2020-07-05",
            "2020-07-06",
            "2020-07-07",
            "2020-07-08"]
    },
    "yAxis":[
        {
            "type":"value",
            "name":"用户日增量",
            "splitLine":{
                "lineStyle":{
                    "type":"dashed",
                    "color":"#DDD"
                }
            }
        },
        {
            "type":"value",
            "name":"设备/非Yolanda用户日增量",
            "nameTextStyle":{
                "align":"right"
            },
            "position":"right",
            "splitLine":{
                "lineStyle":{
                    "type":"dashed",
                    "color":"#DDD"
                }
            },
            "min":565,
            "max":926
        }],
    "series":[
        {
            "name":"用户日增量",
            "type":"line",
            "smooth":true,
            "lineStyle":{
                "normal":{
                    "width":2,
                    "color":{
                        "type":"linear",
                        "colorStops":[
                            {
                                "offset":0,
                                "color":"#FFCAD4"
                            },
                            {
                                "offset":0.4,
                                "color":"#F58080"
                            },
                            {
                                "offset":1,
                                "color":"#F58080"
                            }],
                        "globalCoord":false
                    },
                    "shadowColor":"rgba(245,128,128, 0.5)",
                    "shadowBlur":2,
                    "shadowOffsetY":0
                }
            },
            "itemStyle":{
                "normal":{
                    "borderWidth":4,
                    "borderColor":"#F58080"
                }
            },
            "label":{
                "show":true,
                "fontSize":12
            },
            "data":[
                1547,
                1471,
                1540,
                1490,
                1530,
                1176,
                1094,
                1551,
                1739,
                1770]
        },
        {
            "name":"设备日增量",
            "type":"line",
            "smooth":true,
            "yAxisIndex":1,
            "lineStyle":{
                "normal":{
                    "width":2,
                    "color":{
                        "type":"linear",
                        "colorStops":[
                            {
                                "offset":0,
                                "color":"#AAF487"
                            },
                            {
                                "offset":0.4,
                                "color":"#47D8BE"
                            },
                            {
                                "offset":1,
                                "color":"#47D8BE"
                            }],
                        "globalCoord":false
                    },
                    "shadowColor":"rgba(71,216,190, 0.5)",
                    "shadowBlur":2,
                    "shadowOffsetY":0
                }
            },
            "itemStyle":{
                "normal":{
                    "borderWidth":4,
                    "borderColor":"#AAF487"
                }
            },
            "label":{
                "show":true,
                "fontSize":12,
                "position":"bottom"
            },
            "data":[
                794,
                818,
                871,
                781,
                872,
                682,
                652,
                807,
                848,
                916]
        },
        {
            "name":"非Yolanda用户日增量",
            "type":"line",
            "smooth":true,
            "yAxisIndex":1,
            "lineStyle":{
                "normal":{
                    "width":2,
                    "color":{
                        "type":"linear",
                        "colorStops":[
                            {
                                "offset":0,
                                "color":"#00BFFF"
                            },
                            {
                                "offset":0.4,
                                "color":"#1E90FF"
                            },
                            {
                                "offset":1,
                                "color":"#1E90FF"
                            }],
                        "globalCoord":false
                    },
                    "shadowColor":"rgba(71,216,190, 0.5)",
                    "shadowBlur":2,
                    "shadowOffsetY":0
                }
            },
            "itemStyle":{
                "normal":{
                    "borderWidth":4,
                    "borderColor":"#1E90FF"
                }
            },
            "label":{
                "show":true,
                "fontSize":12
            },
            "data":[
                733,
                714,
                743,
                692,
                733,
                621,
                575,
                745,
                794,
                825]
        }]
}
