var size = 60;
var size1 = 30;
var yy = 200;
var yy1 = 250;
option = {
    title: {
        text: "十九大报告解读",
        top: "top",
        left: "middle",
        textStyle: {
            color: '#4d4d4d'
        }
    },
    tooltip: {
        formatter: '{b}'
    },
    toolbox: {
        show: true,
        feature: {
            restore: {
                show: true
            },
            saveAsImage: {
                show: true
            }
        }
    },
    backgroundColor: '#r0g0b0',
    animationDuration: 1000,
    animationEasingUpdate: 'quinticInOut',
    series: [{
        name: '知识体系',
        type: 'graph',
        layout: 'force',
        force: {
            repulsion: 60,
            gravity: 0.1,
            edgeLength: 50,
            layoutAnimation: true,
        },
        data: [{
            "name": "十九大报告",
            x: 0,
            y: yy,
            "symbolSize": 100,
            "category": "十九大报告",
            "draggable": "true"
        }, {
            "name": "坚定文化自信，推动社会主义文化繁荣兴盛",
            x: 100,
            y: yy1,
            "symbolSize": size,
            "category": "坚定文化自信，推动社会主义文化繁荣兴盛",
            "draggable": "true"

        }, {
            "name": "HDFS",
            x: 20,
            y: yy,
            "symbolSize": size1,
            "category": "坚定文化自信，推动社会主义文化繁荣兴盛",
            "draggable": "true"
        }, {
            x: 30,
            y: yy1,
            "name": "MapReduce",
            "symbolSize": size1,
            "category": "坚定文化自信，推动社会主义文化繁荣兴盛",
            "draggable": "true"
        }, {
            x: 40,
            y: yy,
            "name": "YARN",
            "symbolSize": size1,
            "category": "坚定文化自信，推动社会主义文化繁荣兴盛",
            "draggable": "true",
            "value": 1
        }, {
            x: 60,
            y: yy,
            "name": "Zookeeper",
            "symbolSize": size1,
            "category": "过去五年的工作和历史性变革",
            "draggable": "true"
        }, {
            x: 80,
            y: yy,
            "name": "贯彻新发展理念，建设现代化经济体系",
            "symbolSize": size,
            "category": "贯彻新发展理念，建设现代化经济体系",
            "draggable": "true"
        }, {
            x: 90,
            y: yy1,
            "name": "Scala",
            "symbolSize": size1,
            "category": "贯彻新发展理念，建设现代化经济体系",
            "draggable": "true"
        }, {
            x: 100,
            y: yy,
            "name": "贯彻新发展理念，建设现代化经济体系 SQL",
            "symbolSize": size1,
            "category": "贯彻新发展理念，建设现代化经济体系",
            "draggable": "true"
        }, {
            x: 110,
            y: yy1,
            "name": "贯彻新发展理念，建设现代化经济体系 Streaming",
            "symbolSize": size1,
            "category": "贯彻新发展理念，建设现代化经济体系",
            "draggable": "true"
        }, {
            x: 120,
            y: yy,
            "name": "提高保障和改善民生水平，加强和创新社会治理",
            "symbolSize": size,
            "category": "提高保障和改善民生水平，加强和创新社会治理",
            "draggable": "true"
        }, {
            x: 130,
            y: yy1,
            "name": "过去五年的工作和历史性变革",
            "symbolSize": size,
            "category": "过去五年的工作和历史性变革",
            "draggable": "true"
        }, {
            x: 140,
            y: yy,
            "name": "取得了改革开放和社会主义现代化建设的历史性成就，党和国家事业全面开创新局面。",
            "symbolSize": size1,
            "category": "过去五年的工作和历史性变革",
            "draggable": "true"
        }, {
            x: 150,
            y: yy1,
            "name": "Kafka",
            "symbolSize": size1,
            "category": "过去五年的工作和历史性变革",
            "draggable": "true"
        }, {
            x: 170,
            y: yy1,
            "name": "新时代中国共产党的历史使命",
            "symbolSize": size,
            "category": "新时代中国共产党的历史使命",
            "draggable": "true"
        }, {
            x: 180,
            y: yy,
            "name": "Redis",
            "symbolSize": size1,
            "category": "新时代中国共产党的历史使命",
            "draggable": "true"
        }, {
            x: 190,
            y: yy1,
            "name": "MongoDB",
            "symbolSize": size1,
            "category": "新时代中国共产党的历史使命",
            "draggable": "true"
        }, {
            x: 200,
            y: yy,
            "name": "LevelDB",
            "symbolSize": size1,
            "category": "新时代中国共产党的历史使命",
            "draggable": "true"
        }, {
            x: 210,
            y: yy1,
            "name": "决胜全面建成小康社会，开启全面建设社会主义现代化国家新征程",
            "symbolSize": size,
            "category": "决胜全面建成小康社会，开启全面建设社会主义现代化国家新征程",
            "draggable": "true"
        }, {
            x: 220,
            y: yy,
            "name": "Mahout",
            "symbolSize": size1,
            "category": "决胜全面建成小康社会，开启全面建设社会主义现代化国家新征程",
            "draggable": "true"
        }, {
            x: 230,
            y: yy1,
            "name": "贯彻新发展理念，建设现代化经济体系 MLlib",
            "symbolSize": size1,
            "category": "决胜全面建成小康社会，开启全面建设社会主义现代化国家新征程",
            "draggable": "true"
        }, {
            x: 240,
            y: yy,
            "name": "Python",
            "symbolSize": size1,
            "category": "决胜全面建成小康社会，开启全面建设社会主义现代化国家新征程",
            "draggable": "true"
        }, {
            x: 250,
            y: yy1,
            "name": "R语言",
            "symbolSize": size1,
            "category": "决胜全面建成小康社会，开启全面建设社会主义现代化国家新征程",
            "draggable": "true"
        }, {
            x: 260,
            y: yy,
            "name": "新时代中国特色社会主义思想和基本方略",
            "symbolSize": size,
            "category": "新时代中国特色社会主义思想和基本方略",
            "draggable": "true"
        }, {
            x: 270,
            y: yy1,
            "name": "交通大数据",
            "symbolSize": size1,
            "category": "新时代中国特色社会主义思想和基本方略",
            "draggable": "true"
        }, {
            x: 280,
            y: yy,
            "name": "搜索引擎",
            "symbolSize": size1,
            "category": "新时代中国特色社会主义思想和基本方略",
            "draggable": "true"
        }, {
            x: 290,
            y: yy1,
            "name": "精确营销",
            "symbolSize": size1,
            "category": "新时代中国特色社会主义思想和基本方略",
            "draggable": "true"
        }, {
            x: 300,
            y: yy,
            "name": "环境大数据",
            "symbolSize": size1,
            "category": "新时代中国特色社会主义思想和基本方略",
            "draggable": "true"
        }, {
            x: 310,
            y: yy1,
            "name": "物联网",
            "symbolSize": size1,
            "category": "新时代中国特色社会主义思想和基本方略",
            "draggable": "true"
        }, {
            x: 320,
            y: yy,
            "name": "银行贷款风险评估",
            "symbolSize": size1,
            "category": "新时代中国特色社会主义思想和基本方略",
            "draggable": "true"
        }],
        links: [{
            "source": "十九大报告",
            "target": "坚定文化自信，推动社会主义文化繁荣兴盛"
        }, {
            "source": "十九大报告",
            "target": "贯彻新发展理念，建设现代化经济体系"
        }, {
            "source": "十九大报告",
            "target": "提高保障和改善民生水平，加强和创新社会治理"
        }, {
            "source": "十九大报告",
            "target": "过去五年的工作和历史性变革"
        }, {
            "source": "十九大报告",
            "target": "新时代中国共产党的历史使命"
        }, {
            "source": "十九大报告",
            "target": "决胜全面建成小康社会，开启全面建设社会主义现代化国家新征程"
        }, {
            "source": "十九大报告",
            "target": "新时代中国特色社会主义思想和基本方略"
        }, {
            "source": "坚定文化自信，推动社会主义文化繁荣兴盛",
            "target": "HDFS"
        }, {
            "source": "坚定文化自信，推动社会主义文化繁荣兴盛",
            "target": "YARN"
        }, {
            "source": "坚定文化自信，推动社会主义文化繁荣兴盛",
            "target": "MapReduce"
        }, {
            "source": "过去五年的工作和历史性变革",
            "target": "Zookeeper"
        }, {
            "source": "贯彻新发展理念，建设现代化经济体系",
            "target": "Scala"
        }, {
            "source": "贯彻新发展理念，建设现代化经济体系",
            "target": "贯彻新发展理念，建设现代化经济体系 SQL"
        }, {
            "source": "贯彻新发展理念，建设现代化经济体系",
            "target": "贯彻新发展理念，建设现代化经济体系 Streaming"
        }, {
            "source": "过去五年的工作和历史性变革",
            "target": "取得了改革开放和社会主义现代化建设的历史性成就，党和国家事业全面开创新局面。"
        }, {
            "source": "过去五年的工作和历史性变革",
            "target": "Kafka"
        }, {
            "source": "健全人民当家作主制度体系，发展社会主义民主政治",
            "target": "Pig"
        }, {
            "source": "新时代中国共产党的历史使命",
            "target": "Redis"
        }, {
            "source": "新时代中国共产党的历史使命",
            "target": "MongoDB"
        }, {
            "source": "新时代中国共产党的历史使命",
            "target": "LevelDB"
        }, {
            "source": "决胜全面建成小康社会，开启全面建设社会主义现代化国家新征程",
            "target": "Mahout"
        }, {
            "source": "决胜全面建成小康社会，开启全面建设社会主义现代化国家新征程",
            "target": "贯彻新发展理念，建设现代化经济体系 MLlib"
        }, {
            "source": "决胜全面建成小康社会，开启全面建设社会主义现代化国家新征程",
            "target": "Python"
        }, {
            "source": "决胜全面建成小康社会，开启全面建设社会主义现代化国家新征程",
            "target": "R语言"
        }, {
            "source": "新时代中国特色社会主义思想和基本方略",
            "target": "交通大数据"
        }, {
            "source": "新时代中国特色社会主义思想和基本方略",
            "target": "搜索引擎"
        }, {
            "source": "新时代中国特色社会主义思想和基本方略",
            "target": "精确营销"
        }, {
            "source": "新时代中国特色社会主义思想和基本方略",
            "target": "环境大数据"
        }, {
            "source": "新时代中国特色社会主义思想和基本方略",
            "target": "物联网"
        }, {
            "source": "新时代中国特色社会主义思想和基本方略",
            "target": "银行贷款风险评估"
        }],
        categories: [{
            'name': '十九大报告'
        }, {
            'name': '坚定文化自信，推动社会主义文化繁荣兴盛'
        }, {
            'name': '贯彻新发展理念，建设现代化经济体系'
        }, {
            'name': '提高保障和改善民生水平，加强和创新社会治理'
        }, {
            'name': '过去五年的工作和历史性变革'
        }, {
            'name': '新时代中国共产党的历史使命'
        }, {
            'name': '决胜全面建成小康社会，开启全面建设社会主义现代化国家新征程'
        }, {
            'name': '新时代中国特色社会主义思想和基本方略'
        }],
        roam: false,
        label: {
            normal: {
                show: true,
                formatter: '{b}',           
                position: 'inside',
                fontSize: 16,
                fontStyle: '600',
            }
        },
        lineStyle: {
            normal: {
                width: 6,
                color: 'source',
                curveness: 0,
                type: "solid"
            }
        }
    }]
};
