option = {
    color: ['#66bdff', '#66ffbd', '#ff6666', '#ffe966', '#92ff66', '#9266ff', '#ff66e9'],
    title: {
        text: '数据地图',
    },
    tooltip: {},
    legend: {
        // 图例显示（显示在右上角），name:类别名称，icon:图例的形状（默认是roundRect圆角矩形）。
        show: true,
        data: [
            {
                name: '临床域',
            },
            {
                name: '物资域',
            },
            {
                name: '财务域',
            },
            {
                name: '人力域',
            },
            { name: '主数据' },
        ],
    },

    animationDurationUpdate: 1500,
    animationEasingUpdate: 'quinticInOut',
    series: [
        {
            type: 'graph',
            layout: 'none',
            focusNodeAdjacency: true,
            symbol: 'rect',
            symbolSize: [100, 32],
            roam: true,
            label: {
                normal: {
                    show: true,
                },
                textStyle: {
                    fontSize: 10,
                },
            },
            //edgeSymbol: ['rectangle', 'arrow'],
            edgeSymbolSize: [4, 20],
            edgeLabel: {
                normal: {
                    textStyle: {
                        fontSize: 10,
                    },
                },
            },

            data: [
                { defName: 'A2', name: '门诊收费明细', x: 1, y: 2, category: '临床域'
                },
                { defName: 'A3', name: '体检收费明细', x: 1, y: 3, category: '临床域' },
                { defName: 'A4', name: '住院收费明细', x: 1, y: 4, category: '临床域' },
                { defName: 'A5', name: '门诊预交金', x: 1, y: 5, category: '临床域' },
                { defName: 'A6', name: '住院预交金', x: 1, y: 6, category: '临床域' },
                { defName: 'A7', name: '门诊收费结算', x: 1, y: 7, category: '临床域' },
                { defName: 'A8', name: '住院收费结算', x: 1, y: 8, category: '临床域' },
                { defName: 'A9', name: '住院收费结算明细', x: 1, y: 9, category: '临床域' },
                { defName: 'A10', name: '门诊收入日报', x: 1, y: 10, category: '临床域' },
                { defName: 'A11', name: '体检收入日报', x: 1, y: 1, category: '临床域' },
                { defName: 'A12', name: '住院收入日报', x: 4, y: 2, category: '临床域' },
                { defName: 'A13', name: '门诊医保结算', x: 4, y: 3, category: '临床域' },
                { defName: 'A14', name: '住院医保结算', x: 4, y: 4, category: '临床域' },
                { defName: 'A15', name: '手术收入月报', x: 4, y: 5, category: '临床域' },
                { defName: 'A16', name: '门诊挂号表', x: 4, y: 6, category: '临床域' },
                { defName: 'A17', name: '门诊量明细', x: 4, y: 7, category: '临床域' },
                { defName: 'A18', name: '门诊工作量日报', x: 4, y: 8, category: '临床域' },
                { defName: 'A19', name: '门诊工作量月报', x: 4, y: 9, category: '临床域' },
                { defName: 'A20', name: '门诊工作量月报明细', x: 4, y: 10, category: '临床域' },
                { defName: 'A21', name: '体检工作量日报', x: 4, y: 1, category: '临床域' },
                { defName: 'A22', name: '入院明细', x: 7, y: 2, category: '临床域' },
                { defName: 'A23', name: '出院明细', x: 7, y: 3, category: '临床域' },
                { defName: 'A24', name: '在院明细', x: 7, y: 4, category: '临床域' },
                { defName: 'A25', name: '住院工作量日报', x: 7, y: 5, category: '临床域' },
                { defName: 'A26', name: '住院工作量月报', x: 7, y: 6, category: '临床域' },
                { defName: 'A27', name: '手术明细', x: 7, y: 7, category: '临床域' },
                { defName: 'A28', name: '手术工作量日报', x: 7, y: 8, category: '临床域' },
                { defName: 'A29', name: '手术工作量月报', x: 7, y: 9, category: '临床域' },
                { defName: 'A30', name: '检查项目工作量', x: 7, y: 10, category: '临床域' },
                { defName: 'A31', name: '药房工作量日报', x: 7, y: 1, category: '临床域' },
                { defName: 'A32', name: '护理工作量', x: 10, y: 2, category: '临床域' },
                { defName: 'A33', name: '药房工作量', x: 10, y: 3, category: '临床域' },
                { defName: 'A34', name: '药品入库', x: 10, y: 4, category: '临床域' },
                { defName: 'A35', name: '药品移库', x: 10, y: 5, category: '临床域' },
                { defName: 'A36', name: '药品发放', x: 10, y: 6, category: '临床域' },
                { defName: 'A37', name: '药品盘点', x: 10, y: 7, category: '临床域' },
                { defName: 'A38', name: '药品库存', x: 10, y: 8, category: '临床域' },
                { defName: 'A39', name: '药品周转天数统计', x: 10, y: 9, category: '临床域' },
                { defName: 'A40', name: '药品质控指标', x: 10, y: 10, category: '临床域' },
                { defName: 'A41', name: '门诊患者基本药物使用', x: 10, y: 1, category: '临床域' },
                { defName: 'A42', name: '住院患者基本药物使用', x: 13, y: 2, category: '临床域' },
                { defName: 'A43', name: '出勤表', x: 13, y: 3, category: '临床域' },
                { defName: 'A44', name: 'PACS工作量', x: 13, y: 4, category: '临床域' },
                { defName: 'A45', name: 'LIS工作量', x: 13, y: 5, category: '临床域' },
                { defName: 'A46', name: '内镜工作量', x: 13, y: 6, category: '临床域' },
                { defName: 'A47', name: '病案首页评估报告', x: 13, y: 7, category: '临床域' },
                { defName: 'A48', name: '病案首页诊断记录', x: 13, y: 8, category: '临床域' },
                { defName: 'A49', name: '病案首页手术记录', x: 13, y: 9, category: '临床域' },
                { defName: 'A50', name: '病案首页监护信息', x: 13, y: 10, category: '临床域' },
                { defName: 'A51', name: '病案首页费用信息', x: 13, y: 1, category: '临床域' },
                { defName: 'A52', name: '病案分组结果', x: 16, y: 2, category: '临床域' },
                { defName: 'A53', name: '病案质量信息', x: 16, y: 3, category: '临床域' },
                { defName: 'A54', name: '病案科室CMI', x: 16, y: 4, category: '临床域' },
                { defName: 'A55', name: '病案病种RW', x: 16, y: 5, category: '临床域' },
                { defName: 'A56', name: '病案麻醉工作量', x: 16, y: 6, category: '临床域' },
                { defName: 'A57', name: '病案住院工作量', x: 16, y: 7, category: '临床域' },
                { defName: 'A58', name: '耗材消耗汇总', x: 16, y: 8, category: '物资域' },
                { defName: 'A59', name: '耗材盘点主表', x: 16, y: 9, category: '物资域' },
                { defName: 'A60', name: '耗材盘点明细表', x: 16, y: 10, category: '物资域' },
                { defName: 'A61', name: '耗材库存', x: 16, y: 1, category: '物资域' },
                { defName: 'A62', name: '报账申请单', x: 19, y: 2, category: '物资域' },
                { defName: 'A63', name: '支持状态通知', x: 19, y: 3, category: '物资域' },
                { defName: 'A65', name: '物流出入库主表', x: 19, y: 5, category: '物资域' },
                { defName: 'A66', name: '物流出入库明细表', x: 19, y: 6, category: '物资域' },

                { defName: 'A68', name: '药品折扣率', x: 19, y: 8, category: '物资域' },
                { defName: 'A69', name: '三单匹配信息结果', x: 19, y: 9, category: '物资域' },
                { defName: 'A70', name: '药品结算单', x: 19, y: 10, category: '物资域' },
                { defName: 'A71', name: '入库明细查询', x: 19, y: 1, category: '物资域' },
                { defName: 'A72', name: '发票查询', x: 22, y: 2, category: '物资域' },
                { defName: 'A73', name: '固定资产卡片', x: 22, y: 3, category: '物资域' },
                { defName: 'A74', name: '固定资产折旧明细', x: 22, y: 4, category: '物资域' },
                { defName: 'A75', name: '固定资产折旧资金来源', x: 22, y: 5, category: '物资域' },
                { defName: 'A76', name: '固定资产入库', x: 22, y: 6, category: '物资域' },
                { defName: 'A77', name: '固定资产入库明细', x: 22, y: 7, category: '物资域' },
                { defName: 'A78', name: '固定资产出库', x: 22, y: 8, category: '物资域' },
                { defName: 'A79', name: '固定资产出库明细', x: 22, y: 9, category: '物资域' },
                { defName: 'A80', name: '固定资产处置', x: 22, y: 10, category: '物资域' },
                { defName: 'A81', name: '固定资产盘点主表', x: 22, y: 1, category: '物资域' },
                { defName: 'A82', name: '固定资产盘点明细表', x: 25, y: 2, category: '物资域' },
                { defName: 'A83', name: '固定资产余额表', x: 25, y: 3, category: '物资域' },
                { defName: 'A84', name: '入库单预算信息表', x: 25, y: 4, category: '物资域' },
                { defName: 'A85', name: '资产采购发票主表', x: 25, y: 5, category: '物资域' },
                { defName: 'A86', name: '资产采购发票明细表', x: 25, y: 6, category: '物资域' },
                { defName: 'A87', name: '资产采购付款单主表', x: 25, y: 7, category: '物资域' },
                { defName: 'A88', name: '资产采购付款单明细表', x: 25, y: 8, category: '物资域' },
                { defName: 'A89', name: '固定资产使用状态变动表', x: 25, y: 9, category: '物资域' },
                { defName: 'A90', name: '固定资产使用状态变动明细表', x: 25, y: 10, category: '物资域' },
                { defName: 'A91', name: '资产原值变动库主表', x: 25, y: 1, category: '物资域' },
                { defName: 'A92', name: '固定资产原值变动明细表', x: 28, y: 2, category: '物资域' },
                { defName: 'A93', name: '固定资产转移单', x: 28, y: 3, category: '物资域' },
                { defName: 'A94', name: '固定资产移交单明细', x: 28, y: 4, category: '物资域' },
                { defName: 'A95', name: '固定资产分布变动表', x: 28, y: 5, category: '物资域' },
                { defName: 'A96', name: '资产调入主表', x: 28, y: 6, category: '物资域' },

                {
                    defName: 'B2',
                    name: '科室',
                    x: 1,
                    y: 0,
                    category: '主数据',
                 
                },
                {
                    defName: 'B3',
                    name: '医生',
                    x: 4,
                    y: 0,
                    category: '主数据',
                   
                },
                {
                    defName: 'B4',
                    name: '药品',
                    x: 7,
                    y: 0,
                    category: '主数据',
                   
                },
                {
                    defName: 'B5',
                    name: '耗材',
                    x: 10,
                    y: 0,
                    category: '主数据',

                },
                {
                    defName: 'B6',
                    name: '设备/资产',
                    x: 13,
                    y: 0,
                   
                },
                {
                    defName: 'B7',
                    name: '服务项目',
                    x: 16,
                    y: 0,
                    category: '主数据',
                    
                },
                {
                    defName: 'B8',
                    name: '病种',
                    x: 19,
                    y: 0,
                    category: '主数据',
                  
                },
            ],
            links: [
                { source: '科室', target: '门诊收费明细' },
                { source: '科室', target: '体检收费明细' },
                { source: '科室', target: '住院收费明细' },
                { source: '科室', target: '门诊预交金' },
                { source: '科室', target: '住院预交金' },
                { source: '科室', target: '门诊收费结算' },
                { source: '科室', target: '住院收费结算' },
                { source: '科室', target: '住院收费结算明细' },
                { source: '科室', target: '门诊医保结算' },
                { source: '科室', target: '住院医保结算' },
                { source: '科室', target: '门诊挂号表' },
                { source: '科室', target: '门诊量明细' },
                { source: '科室', target: '入院明细' },
                { source: '科室', target: '出院明细' },
                { source: '科室', target: '在院明细' },
                { source: '科室', target: '手术明细' },
                { source: '科室', target: '门诊患者基本药物使用' },
                { source: '科室', target: '住院患者基本药物使用' },
                { source: '科室', target: '病案首页评估报告' },
                { source: '科室', target: '病案科室CMI' },
                { source: '科室', target: '耗材盘点明细表' },
                { source: '科室', target: '固定资产卡片' },
                { source: '科室', target: '资产调入主表' },
                { source: '科室', target: '预算计划' },
                { source: '科室', target: '科室预算编制与执行表' },
                { source: '科室', target: '凭证辅助核算' },
                { source: '科室', target: '科室成本收入' },
                { source: '科室', target: '科室成本直接成本' },
                { source: '科室', target: '科室直接药品成本明细' },
                { source: '科室', target: '科室直接人员成本明细' },
                { source: '科室', target: '科室直接折旧摊销明细' },
                { source: '科室', target: '科室直接其他费用明细' },
                { source: '科室', target: '科室直接物资成本明细' },
                { source: '科室', target: '科室直接风险基金明细' },
                { source: '科室', target: '科室间接成本分摊明细' },
                { source: '科室', target: '科室人员数量' },
                { source: '科室', target: '科室成本分摊系数' },
                { source: '科室', target: '科室成本全成本' },
                { source: '科室', target: '科室成本门诊工作量' },
                { source: '科室', target: '科室成本住院工作量' },
                { source: '科室', target: '科室成本分摊过程成本要素明细表历史表' },
                { source: '科室', target: '科室成本分摊方案' },
                { source: '科室', target: '科室成本分摊参数-含承担科室' },
                { source: '科室', target: '科室成本供应室服务量' },
                { source: '科室', target: '科室成本病区住院工作量' },
                { source: '科室', target: '科室成本亚专科住院工作量' },
                { source: '科室', target: '科室成本手术工作量' },
                { source: '科室', target: '科室成本明细记录原始表' },
                { source: '药品', target: '药品入库' },
                { source: '药品', target: '药品移库' },
                { source: '药品', target: '药品发放' },
                { source: '药品', target: '药品盘点' },
                { source: '药品', target: '药品库存' },
                { source: '药品', target: '药品周转天数统计' },
                { source: '药品', target: '药品质控指标' },
                { source: '服务项目', target: '门诊收费明细' },
                { source: '服务项目', target: '体检收费明细' },
                { source: '服务项目', target: '住院收费明细' },
                { source: '服务项目', target: '住院收费结算' },
                { source: '服务项目', target: '住院收费结算明细' },
                { source: '服务项目', target: '项目直接人力工时' },
                { source: '服务项目', target: '项目直接人力成本' },
                { source: '服务项目', target: '项目直接材料用量' },
                { source: '服务项目', target: '项目直接材料成本' },
                { source: '服务项目', target: '项目直接设备工时' },
                { source: '服务项目', target: '项目直接设备成本' },
                { source: '服务项目', target: '项目直接其他费用' },
                { source: '服务项目', target: '科室项目全成本' },
            ],

            categories: [
                // name(类别名称)要同legend(图例）按次序一致
                {
                    name: '临床域',
                    itemStyle: {
                        normal: {
                            color: '#ffe966',
                        },
                    },
                },
                {
                    name: '物资域',
                    itemStyle: {
                        normal: {
                            color: 'lightgray',
                        },
                    },
                },
                {
                    name: '财务域',
                    itemStyle: {
                        normal: {
                            color: '#ff66e9',
                        },
                    },
                },
                {
                    name: '人力域',
                    itemStyle: {
                        normal: {
                            color: '#92ff66',
                        },
                    },
                },
                {
                    name: '主数据',
                    itemStyle: {
                        normal: {
                            color: '#66bdff',
                        },
                    },
                },
            ],
            lineStyle: {
                normal: {
                    opacity: 0.9,
                    width: 2,
                    curveness: 0,
                },
            },
        },
    ],
};
