var uploadedDataURL = "/asset/get/s/data-1631412918406-pF8nQOWbp.png";

    var maskImage = new Image();
    maskImage.src = uploadedDataURL

    var data = [
        { value: 60, name: '运量' },
        { value: 41, name: '延安路' },
        { value: 37, name: '公交' },
        { value: 35, name: '中运量' },
        { value: 15, name: '申昆路' },
        { value: 14, name: '路' },
        { value: 13, name: '上海' },
        { value: 11, name: '车道' },
        { value: 10, name: '电车' },
        { value: 10, name: '终点站' },
        { value: 9, name: '公交车' },
        { value: 9, name: '专用道' },
        { value: 9, name: '载客' },
        { value: 8, name: '无轨电车' },
        { value: 7, name: '开通' },
        { value: 7, name: '外滩' },
        { value: 7, name: '专用' },
        { value: 5, name: '线路' },
        { value: 5, name: '全文' },
        { value: 5, name: '延安东路' },
        { value: 4, name: '延安西路' },
        { value: 4, name: '试运行' },
        { value: 3, name: 'brt' },
        { value: 3, name: '高架' },
        { value: 3, name: '司机' },
        { value: 3, name: '运营' },
        { value: 3, name: '枢纽站' },
        { value: 2, name: '联调' },
        { value: 2, name: '区间' },
        { value: 2, name: '巴士' },
        { value: 2, name: '巨龙' },
        { value: 2, name: '中山东一路' },
        { value: 2, name: '车辆' },
        { value: 2, name: '虹桥' },
        { value: 2, name: '青平公路' },
        { value: 2, name: '乘坐' },
        { value: 2, name: '巨龙车' },
        { value: 2, name: '乘客' },
        { value: 2, name: '线网' },
        { value: 2, name: '通车' },
        { value: 2, name: '车站' },
        { value: 2, name: '去外滩' },
        { value: 2, name: '空载' },
        { value: 2, name: '尝鲜' },
        { value: 2, name: '红灯' },
        { value: 2, name: '体验' },
        { value: 2, name: '安东路外滩' },
        { value: 2, name: '试车' },
        { value: 2, name: '速递' },
        { value: 2, name: '站台' },
        { value: 2, name: '延安' },
        { value: 1, name: '西藏' },
        { value: 1, name: '客流' },
        { value: 1, name: '车厢' },
        { value: 1, name: '上海·七莘' },
        { value: 1, name: '长宁' },
        { value: 1, name: '恶臭' },
        { value: 1, name: '娄山关' },
        { value: 1, name: '天桥' },
        { value: 1, name: '红绿灯' },
        { value: 1, name: '正式' },
        { value: 1, name: '路权' },
        { value: 1, name: '新片' },
        { value: 1, name: '视频' },
        { value: 1, name: '头班车' },
        { value: 1, name: '中路' },
        { value: 1, name: '北路站' },
        { value: 1, name: '传说' },
        { value: 1, name: '小时' },
        { value: 1, name: '路试' },
        { value: 1, name: '单程' },
        { value: 1, name: '路上' },
        { value: 1, name: '拥堵' },
        { value: 1, name: '启用' },
        { value: 1, name: '换乘' },
        { value: 1, name: '调试' },
        { value: 1, name: '中门' },
        { value: 1, name: '凯旋路' },
        { value: 1, name: '候车' },
        { value: 1, name: '双流路' },
        { value: 1, name: '上班' },
        { value: 1, name: '天山路' },
        { value: 1, name: '交通委' },
        { value: 1, name: '市民' },
        { value: 1, name: '发车' },
        { value: 1, name: '上车' },
        { value: 1, name: '开车' },
        { value: 1, name: '驾驶员' },
        { value: 1, name: '路线' },
        { value: 1, name: '样车' },
        { value: 1, name: '华山路' },
        { value: 1, name: '缩线' },
        { value: 1, name: '铰接' },
        { value: 1, name: '马路' },
        { value: 1, name: '凑热闹' },
        { value: 1, name: '高峰' },
        { value: 1, name: '中路站' },
        { value: 1, name: '你好' },
        { value: 1, name: '外滩站' }
    ]
    // 指定图表的配置项和数据
    var option = {
        series: [{
            type: 'wordCloud',
            shape: 'circle',
            rotationRange: [-90, 90],
            rotationStep: 1,
            maskImage: maskImage,
            data: data,
            height:'100%',
            width:'75%',
            sizeRange: [18, 80],
            textStyle: {
                color: function() {
                    // Random color
                    return 'rgb(' + [
                        Math.round(Math.random() * 160),
                        Math.round(Math.random() * 160),
                        Math.round(Math.random() * 160)
                    ].join(',') + ')'
                }
            }
        }],
    };
    maskImage.onload = function() {
        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);
    }