var size = 60;
var size1 = 30;
var yy = 200;
var yy1 = 250;
option = {
    title: {
        text: "华为技术有限公司",
        top: "top",
        left: "left",
        textStyle: {
            color: '#f7f7f7'
        }
    },
    tooltip: {
        formatter: '{b}'
    },
    toolbox: {
        show: true,
        feature: {
            restore: {
                show: true
            },
            saveAsImage: {
                show: true
            }
        }
    },
    backgroundColor: '#337ab7',
    animationDuration: 1000,
    animationEasingUpdate: 'quinticInOut',
    series: [{
        name: '知识体系',
        type: 'graph',
        layout: 'force',
        force: {
            repulsion: 60,
            gravity: 0.1,
            edgeLength: 30,
            layoutAnimation: true,
        },
        data: [{
            "name": "华为技术有限公司",
            x: 0,
            y: yy,
            "symbolSize": 100,
            "category": "华为技术有限公司",
            "draggable": "true"
        }, {
            "name": "董事",
            x: 10,
            y: yy1,
            "symbolSize": size,
            "category": "董事",
            "draggable": "true"

        }, {
            "name": "余承东",
            x: 20,
            y: yy,
            "symbolSize": size1,
            "category": "董事",
            "draggable": "true"
        }, {
            x: 30,
            y: yy1,
            "name": "孟晚舟",
            "symbolSize": size1,
            "category": "董事",
            "draggable": "true"
        }, {
            x: 40,
            y: yy,
            "name": "李杰",
            "symbolSize": size1,
            "category": "董事",
            "draggable": "true",
            "value": 1
        },{
            x: 50,
            y: yy,
            "name": "陈黎芳",
            "symbolSize": size1,
            "category": "董事",
            "draggable": "true",
            "value": 1
        },  {
            x: 60,
            y: yy,
            "name": "副董事",
            "symbolSize": size,
            "category": "副董事",
            "draggable": "true"
        }, {
            x: 70,
            y: yy1,
            "name": "任正非",
            "symbolSize": size1,
            "category": "副董事",
            "draggable": "true"
        }, {
            x: 80,
            y: yy,
            "name": "郭平",
            "symbolSize": size1,
            "category": "副董事",
            "draggable": "true"
        }, {
            x: 90,
            y: yy1,
            "name": "徐直军",
            "symbolSize": size1,
            "category": "副董事",
            "draggable": "true"
        }, {
            x: 100,
            y: yy1,
            "name": "胡厚崑",
            "symbolSize": size1,
            "category": "副董事",
            "draggable": "true"
        },{
            x: 110,
            y: yy1,
            "name": "税务登记",
            "symbolSize": size,
            "category": "税务登记",
            "draggable": "true"
        }, {
            x: 120,
            y: yy,
            "name": "地税登记",
            "symbolSize": size1,
            "category": "税务登记",
            "draggable": "true"
        }, {
            x: 130,
            y: yy1,
            "name": "国税登记",
            "symbolSize": size1,
            "category": "税务登记",
            "draggable": "true"
        }, {
            x: 140,
            y: yy1,
            "name": "监事",
            "symbolSize": size,
            "category": "监事",
            "draggable": "true"
        }, {
            x: 150,
            y: yy,
            "name": "田峰",
            "symbolSize": size1,
            "category": "监事",
            "draggable": "true"
        }, {
            x: 160,
            y: yy1,
            "name": "梁华",
            "symbolSize": size1,
            "category": "监事",
            "draggable": "true"
        }, {
            x: 170,
            y: yy,
            "name": "任树录",
            "symbolSize": size1,
            "category": "监事",
            "draggable": "true"
        },{
            x: 180,
            y: yy,
            "name": "邓彪",
            "symbolSize": size1,
            "category": "监事",
            "draggable": "true"
        },{
            x: 190,
            y: yy,
            "name": "张平安",
            "symbolSize": size1,
            "category": "监事",
            "draggable": "true"
        }, {
            x: 200,
            y: yy1,
            "name": "对外投资",
            "symbolSize": size,
            "category": "对外投资",
            "draggable": "true"
        }, {
            x: 210,
            y: yy,
            "name": "深圳市华为新技术有限公司",
            "symbolSize": size1,
            "category": "对外投资",
            "draggable": "true"
        }, {
            x: 220,
            y: yy1,
            "name": "深圳力捷科技有限公司",
            "symbolSize": size1,
            "category": "对外投资",
            "draggable": "true"
        }, {
            x: 230,
            y: yy,
            "name": "深圳市华为安捷信电气有限公司",
            "symbolSize": size1,
            "category": "对外投资",
            "draggable": "true"
        }, {
            x: 240,
            y: yy1,
            "name": "深圳市华为技术软件有限公司",
            "symbolSize": size1,
            "category": "对外投资",
            "draggable": "true"
        }, {
            x: 250,
            y: yy1,
            "name": "深圳市海思半导体有限公司",
            "symbolSize": size1,
            "category": "对外投资",
            "draggable": "true"
        }, {
            x: 260,
            y: yy1,
            "name": "华为终端（深圳）有限公司",
            "symbolSize": size1,
            "category": "对外投资",
            "draggable": "true"
        }, {
            x: 270,
            y: yy,
            "name": "分支机构",
            "symbolSize": size,
            "category": "分支机构",
            "draggable": "true"
        }, {
            x: 280,
            y: yy,
            "name": "深圳华为技术有限公司",
            "symbolSize": size1,
            "category": "分支机构",
            "draggable": "true"
        }, {
            x: 290,
            y: yy1,
            "name": "太原华为技术有限公司",
            "symbolSize": size1,
            "category": "分支机构",
            "draggable": "true"
        }, {
            x: 300,
            y: yy,
            "name": "华为技术有限公司长沙研究所",
            "symbolSize": size1,
            "category": "分支机构",
            "draggable": "true"
        }, {
            x: 310,
            y: yy1,
            "name": "华为技术有限公司成都研究所",
            "symbolSize": size1,
            "category": "分支机构",
            "draggable": "true"
        }, {
            x: 320,
            y: yy,
            "name": "成都华为技术有限公司",
            "symbolSize": size1,
            "category": "分支机构",
            "draggable": "true"
        }],
        links: [{
            "source": "华为技术有限公司",
            "target": "董事"
        }, {
            "source": "华为技术有限公司",
            "target": "副董事"
        }, {
            "source": "华为技术有限公司",
            "target": "税务登记"
        }, {
            "source": "华为技术有限公司",
            "target": "监事"
        }, {
            "source": "华为技术有限公司",
            "target": "对外投资"
        }, {
            "source": "华为技术有限公司",
            "target": "分支机构"
        }, {
            "source": "董事",
            "target": "余承东"
        }, {
            "source": "董事",
            "target": "孟晚舟"
        }, {
            "source": "董事",
            "target": "李杰"
        }, {
            "source": "董事",
            "target": "陈黎芳"
        },  {
            "source": "副董事",
            "target": "任正非"
        }, {
            "source": "副董事",
            "target": "徐直军"
        }, {
            "source": "副董事",
            "target": "郭平"
        },  {
            "source": "副董事",
            "target": "胡厚崑"
        },{
            "source": "税务登记",
            "target": "地税登记"
        }, {
            "source": "税务登记",
            "target": "国税登记"
        }, {
            "source": "监事",
            "target": "田峰"
        }, {
            "source": "监事",
            "target": "梁华"
        }, {
            "source": "监事",
            "target": "任树录"
        },{
            "source": "监事",
            "target": "邓彪"
        },{
            "source": "监事",
            "target": "张平安"
        }, {
            "source": "对外投资",
            "target": "深圳市华为新技术有限公司"
        }, {
            "source": "对外投资",
            "target": "深圳力捷科技有限公司"
        }, {
            "source": "对外投资",
            "target": "深圳市华为安捷信电气有限公司"
        }, {
            "source": "对外投资",
            "target": "深圳市华为技术软件有限公司"
        },  {
            "source": "对外投资",
            "target": "华为终端（深圳）有限公司"
        },  {
            "source": "对外投资",
            "target": "深圳市海思半导体有限公司"
        }, {
            "source": "分支机构",
            "target": "深圳华为技术有限公司"
        }, {
            "source": "分支机构",
            "target": "太原华为技术有限公司"
        }, {
            "source": "分支机构",
            "target": "华为技术有限公司长沙研究所"
        }, {
            "source": "分支机构",
            "target": "华为技术有限公司成都研究所"
        }, {
            "source": "分支机构",
            "target": "成都华为技术有限公司"
        }],
        categories: [{
            'name': '中国传媒大学'
        }, {
            'name': '经管学部'
        }, {
            'name': '雄安新区发展研究院'
        }, {
            'name': '文法学部'
        }, {
            'name': '直属学院（机构）'
        }, {
            'name': '协同创新中心'
        }, {
            'name': '新闻传播学部'
        }, {
            'name': '理工学部'
        }, {
            'name': '分支机构'
        }],
        roam: false,
        label: {
            normal: {
                show: true,
                position: 'inside',
                formatter: '{b}',
                fontSize: 16,
                fontStyle: '600',
            }
        },
        lineStyle: {
            normal: {
                width: 6,
                color: 'source',
                curveness: 0,
                type: "solid"
            }
        }
    }]
};