option = {
    title: {
        text: "",
        subtext: "",
        left: "center",
        textStyle: {
            color: "#fff",
            fontSize: 18
        },
    },

    backgroundColor: new echarts.graphic.RadialGradient(0, 0, 1, [{
        offset: 0,
        color: '#174b78'
    }, {
        offset: 1,
        color: '#174b78'
    }]),
    tooltip: {
        trigger: 'item',
        formatter: "{a} <br/>{b}:({d}%)"
    },
    series: [{
        name: '一级指标',
        type: 'pie',
        selectedMode: 'single',
        radius: [0, '30%'],

        label: {
            normal: {
                position: 'inner'
            }
        },
        labelLine: {
            normal: {
                show: false
            }
        },
        data: [{
            value: 37,
            name: '主要社会经济指标'
        }, {
            value: 2,
            name: '招商项目指标'
        }, {
            value: 11,
            name: '楼宇经济指标'
        }, {
            value: 9,
            name: '互联网电商指标'
        }]
    }, {
        name: '二级指标',
        type: 'pie',
        radius: ['32%', '60%'],
        label: {
            normal: {
                position: 'inner'
            }
        },
        data: [{
            value: 6,
            name: '地区生产总值情况'
        }, {
            value: 3,
            name: '财政收入情况'
        }, {
            value: 2,
            name: '税收情况'
        }, {
            value: 3,
            name: '区域固定资产投资情况'
        }, {
            value: 4,
            name: '招商引资情况'
        }, {
            value: 5,
            name: '工商登记注册情况'
        }, {
            value: 4,
            name: '增加就业情况'
        }, {
            value: 5,
            name: '重点企业指标情况'
        }, {
            value: 1,
            name: '消费品零售情况'
        }, {
            value: 1,
            name: '外贸出口情况'
        }, {
            value: 1,
            name: '居民收入情况'
        }, {
            value: 1,
            name: '市内六区对比情况'
        }, {
            value: 1,
            name: '友好城市对比情况'
        }, {
            value: 2,
            name: '招商项目情况'
        }, {
            value: 7,
            name: '楼宇情况'
        }, {
            value: 2,
            name: '亿元楼宇情况'
        }, {
            value: 2,
            name: '注册企业情况'
        }, {
            value: 3,
            name: '总体指标'
        }, {
            value: 3,
            name: '网商指标'
        }, {
            value: 3,
            name: '网购指标'
        }]
    }, {
        name: '三级指标',
        type: 'pie',
        radius: ['62%', '70%'],
        label: {
            normal: {
                position: 'outer'
            }
        },
        data: [{
            value: 2,
            name: '地区生产总值同比增长'
        }, {
            value: 1,
            name: '第二产业同比增长'
        }, {
            value: 1,
            name: '第三产业同比增长'
        }, {
            value: 1,
            name: '现代服务业同比增长'
        }, {
            value: 1,
            name: '民营经济同比增长'
        }, {
            value: 1,
            name: '财政收入同比增长'
        }, {
            value: 1,
            name: '留区一般预算财政收入同比增长'
        }, {
            value: 1,
            name: '区级财政支出金额同比增长'
        }, {
            value: 1,
            name: '地税税收同比增长'
        }, {
            value: 1,
            name: '国税税收同比增长'
        }, {
            value: 1,
            name: '区域固定资产投资同比增长'
        }, {
            value: 1,
            name: '开工项目同比增长'
        }, {
            value: 1,
            name: '开工面积同比增长'
        }, {
            value: 2,
            name: '直接利用外资同比增长'
        }, {
            value: 2,
            name: '国内招商引资同比增长'
        }, {
            value: 2,
            name: '实有经济主体数同比增长'
        }, {
            value: 2,
            name: '外资企业及分支机构注册数同比增长'
        }, {
            value: 1,
            name: '本年新增注册资金同比增长'
        }, {
            value: 4,
            name: '增加就业人数同比增长'
        }, {
            value: 2,
            name: '批发零售业前20名销售额同比增长'
        }, {
            value: 2,
            name: '房地产业前10名企业增加值同比增长'
        }, {
            value: 1,
            name: '其他服务业增加值同比增长'
        }, {
            value: 1,
            name: '消费品零售额同比增长'
        }, {
            value: 1,
            name: '外贸出口额同比增长'
        }, {
            value: 1,
            name: '居民人均可支配收入同比增长'
        }, {
            value: 1,
            name: '市内六区地域生产总值排名'
        }, {
            value: 1,
            name: '友好城市生产总值排名'
        }, {
            value: 1,
            name: '招商项目数量同比增长'
        }, {
            value: 1,
            name: '可招商面积同比增长'
        }, {
            value: 2,
            name: '统计楼宇数同比增长'
        }, {
            value: 3,
            name: '空置楼宇盘活量同比增长'
        }, {
            value: 2,
            name: '全口径税收金额同比增长'
        }, {
            value: 1,
            name: '亿元楼宇税收额同比增长'
        }, {
            value: 1,
            name: '亿元楼宇注册企业数同比增长'
        }, {
            value: 2,
            name: '注册企业数同比增长'
        }, {
            value: 1,
            name: '区域电商指数'
        }, {
            value: 1,
            name: '区域人口质量'
        }, {
            value: 1,
            name: '区域幸福指数'
        }, {
            value: 1,
            name: '网商指数'
        }, {
            value: 1,
            name: '店铺活跃度'
        }, {
            value: 1,
            name: '网商指数排名'
        }, {
            value: 1,
            name: '网购指数'
        }, {
            value: 1,
            name: '消费活跃度'
        }, {
            value: 1,
            name: '网购指数排名'
        }]
    }]
};