option = {
    "legend": {
        "data": [
            "实例A",
            "实例B",
            "实例C"
        ],
        "show": true,
        "icon": "rect",
        "bottom": 0
    },
    "tooltip": {
        "confine": true
    },
    "series": [{
            "type": "line",
            "coordinateSystem": "polar",
            "tooltip": {
                "show": false
            },
            "lineStyle": {
                "width": 1,
                "color": "rgba(0, 0, 0, 0)"
            },
            //  与图例顺序相反
            "name": "实例A",
            "data": [{
                    "value": 63377,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 23043,
                        "negativeSOV": 0.36,
                        "form": "Total",
                        "name": "实例A",
                        "neutral": 18782,
                        "positive": 21552,
                        "type": "产品",
                        "subform": "儿童牛奶",
                        "positiveSOV": 0.34,
                        "buzz": 63377,
                        "talkingangle": "价格",
                        "neutralSOV": 0.3,
                        "value": 63377,
                        "x": "价格",
                        "$rowSum": 1734568,
                        "$rowRate": "0.0365",
                        "$rowPercent": "4%",
                        "$rowPercent2": "3.65%",
                        "$value": 63377,
                        "$colSum": 292033,
                        "$colRate": "0.217",
                        "$colPercent": "22%",
                        "$colPercent2": "21.7%"
                    },
                    "itemStyle": {
                        "color": "#F39B44"
                    }
                },
                {
                    "value": 84229,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 22634,
                        "negativeSOV": 0.27,
                        "form": "Total",
                        "name": "实例A",
                        "neutral": 31716,
                        "positive": 29879,
                        "type": "产品",
                        "subform": "儿童牛奶",
                        "positiveSOV": 0.35,
                        "buzz": 84229,
                        "talkingangle": "便捷",
                        "neutralSOV": 0.38,
                        "value": 84229,
                        "x": "便捷",
                        "$rowSum": 1734568,
                        "$rowRate": "0.0486",
                        "$rowPercent": "5%",
                        "$rowPercent2": "4.86%",
                        "$value": 84229,
                        "$colSum": 293678,
                        "$colRate": "0.2868",
                        "$colPercent": "29%",
                        "$colPercent2": "28.68%"
                    },
                    "itemStyle": {
                        "color": "#F39B44"
                    }
                },
                {
                    "value": 168647,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 58718,
                        "negativeSOV": 0.35,
                        "form": "Total",
                        "name": "实例A",
                        "neutral": 56839,
                        "positive": 53090,
                        "type": "产品",
                        "subform": "儿童牛奶",
                        "positiveSOV": 0.31,
                        "buzz": 168647,
                        "talkingangle": "健康",
                        "neutralSOV": 0.34,
                        "value": 168647,
                        "x": "健康",
                        "$rowSum": 1734568,
                        "$rowRate": "0.0972",
                        "$rowPercent": "10%",
                        "$rowPercent2": "9.72%",
                        "$value": 168647,
                        "$colSum": 464103,
                        "$colRate": "0.3634",
                        "$colPercent": "36%",
                        "$colPercent2": "36.34%"
                    },
                    "itemStyle": {
                        "color": "#F39B44"
                    }
                },
                {
                    "value": 26859,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 13736,
                        "negativeSOV": 0.51,
                        "form": "Total",
                        "name": "实例A",
                        "neutral": 5049,
                        "positive": 8074,
                        "type": "产品",
                        "subform": "儿童牛奶",
                        "positiveSOV": 0.3,
                        "buzz": 26859,
                        "talkingangle": "口感",
                        "neutralSOV": 0.19,
                        "value": 26859,
                        "x": "口感",
                        "$rowSum": 1734568,
                        "$rowRate": "0.0155",
                        "$rowPercent": "2%",
                        "$rowPercent2": "1.55%",
                        "$value": 26859,
                        "$colSum": 316803,
                        "$colRate": "0.0848",
                        "$colPercent": "8%",
                        "$colPercent2": "8.48%"
                    },
                    "itemStyle": {
                        "color": "#F39B44"
                    }
                },
                {
                    "value": 214824,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 72839,
                        "negativeSOV": 0.34,
                        "form": "Total",
                        "name": "实例A",
                        "neutral": 75183,
                        "positive": 66802,
                        "type": "产品",
                        "subform": "儿童牛奶",
                        "positiveSOV": 0.31,
                        "buzz": 214824,
                        "talkingangle": "品牌认知",
                        "neutralSOV": 0.35,
                        "value": 214824,
                        "x": "品牌认知",
                        "$rowSum": 1734568,
                        "$rowRate": "0.1238",
                        "$rowPercent": "12%",
                        "$rowPercent2": "12.38%",
                        "$value": 214824,
                        "$colSum": 511135,
                        "$colRate": "0.4203",
                        "$colPercent": "42%",
                        "$colPercent2": "42.03%"
                    },
                    "itemStyle": {
                        "color": "#F39B44"
                    }
                },
                {
                    "value": 151507,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 53098,
                        "negativeSOV": 0.35,
                        "form": "Total",
                        "name": "实例A",
                        "neutral": 46250,
                        "positive": 52159,
                        "type": "产品",
                        "subform": "儿童牛奶",
                        "positiveSOV": 0.34,
                        "buzz": 151507,
                        "talkingangle": "场合",
                        "neutralSOV": 0.31,
                        "value": 151507,
                        "x": "场合",
                        "$rowSum": 1734568,
                        "$rowRate": "0.0873",
                        "$rowPercent": "9%",
                        "$rowPercent2": "8.73%",
                        "$value": 151507,
                        "$colSum": 520011,
                        "$colRate": "0.2914",
                        "$colPercent": "29%",
                        "$colPercent2": "29.14%"
                    },
                    "itemStyle": {
                        "color": "#F39B44"
                    }
                },
                {
                    "value": 150478,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 53518,
                        "negativeSOV": 0.36,
                        "form": "Total",
                        "name": "实例A",
                        "neutral": 42874,
                        "positive": 54086,
                        "type": "产品",
                        "subform": "儿童牛奶",
                        "positiveSOV": 0.36,
                        "buzz": 150478,
                        "talkingangle": "外观",
                        "neutralSOV": 0.28,
                        "value": 150478,
                        "x": "外观",
                        "$rowSum": 1734568,
                        "$rowRate": "0.0868",
                        "$rowPercent": "9%",
                        "$rowPercent2": "8.68%",
                        "$value": 150478,
                        "$colSum": 382005,
                        "$colRate": "0.3939",
                        "$colPercent": "39%",
                        "$colPercent2": "39.39%"
                    },
                    "itemStyle": {
                        "color": "#F39B44"
                    }
                },
                {
                    "value": 234138,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 82342,
                        "negativeSOV": 0.35,
                        "form": "Total",
                        "name": "实例A",
                        "neutral": 81823,
                        "positive": 69973,
                        "type": "产品",
                        "subform": "儿童牛奶",
                        "positiveSOV": 0.3,
                        "buzz": 234138,
                        "talkingangle": "感觉",
                        "neutralSOV": 0.35,
                        "value": 234138,
                        "x": "感觉",
                        "$rowSum": 1734568,
                        "$rowRate": "0.135",
                        "$rowPercent": "13%",
                        "$rowPercent2": "13.5%",
                        "$value": 234138,
                        "$colSum": 561054,
                        "$colRate": "0.4173",
                        "$colPercent": "42%",
                        "$colPercent2": "41.73%"
                    },
                    "itemStyle": {
                        "color": "#F39B44"
                    }
                },
                {
                    "value": 106819,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 30276,
                        "negativeSOV": 0.28,
                        "form": "Total",
                        "name": "实例A",
                        "neutral": 26971,
                        "positive": 49572,
                        "type": "产品",
                        "subform": "儿童牛奶",
                        "positiveSOV": 0.46,
                        "buzz": 106819,
                        "talkingangle": "明星",
                        "neutralSOV": 0.25,
                        "value": 106819,
                        "x": "明星",
                        "$rowSum": 1734568,
                        "$rowRate": "0.0616",
                        "$rowPercent": "6%",
                        "$rowPercent2": "6.16%",
                        "$value": 106819,
                        "$colSum": 409682,
                        "$colRate": "0.2607",
                        "$colPercent": "26%",
                        "$colPercent2": "26.07%"
                    },
                    "itemStyle": {
                        "color": "#F39B44"
                    }
                },
                {
                    "value": 189804,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 63145,
                        "negativeSOV": 0.33,
                        "form": "Total",
                        "name": "实例A",
                        "neutral": 67835,
                        "positive": 58824,
                        "type": "产品",
                        "subform": "儿童牛奶",
                        "positiveSOV": 0.31,
                        "buzz": 189804,
                        "talkingangle": "材质",
                        "neutralSOV": 0.36,
                        "value": 189804,
                        "x": "材质",
                        "$rowSum": 1734568,
                        "$rowRate": "0.1094",
                        "$rowPercent": "11%",
                        "$rowPercent2": "10.94%",
                        "$value": 189804,
                        "$colSum": 416568,
                        "$colRate": "0.4556",
                        "$colPercent": "46%",
                        "$colPercent2": "45.56%"
                    },
                    "itemStyle": {
                        "color": "#F39B44"
                    }
                },
                {
                    "value": 267980,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 87234,
                        "negativeSOV": 0.33,
                        "form": "Total",
                        "name": "实例A",
                        "neutral": 94294,
                        "positive": 86452,
                        "type": "产品",
                        "subform": "儿童牛奶",
                        "positiveSOV": 0.32,
                        "buzz": 267980,
                        "talkingangle": "设计",
                        "neutralSOV": 0.35,
                        "value": 267980,
                        "x": "设计",
                        "$rowSum": 1734568,
                        "$rowRate": "0.1545",
                        "$rowPercent": "15%",
                        "$rowPercent2": "15.45%",
                        "$value": 267980,
                        "$colSum": 741766,
                        "$colRate": "0.3613",
                        "$colPercent": "36%",
                        "$colPercent2": "36.13%"
                    },
                    "itemStyle": {
                        "color": "#F39B44"
                    }
                },
                {
                    "value": 75906,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 24375,
                        "negativeSOV": 0.32,
                        "form": "Total",
                        "name": "实例A",
                        "neutral": 26663,
                        "positive": 24868,
                        "type": "产品",
                        "subform": "儿童牛奶",
                        "positiveSOV": 0.33,
                        "buzz": 75906,
                        "talkingangle": "送礼",
                        "neutralSOV": 0.35,
                        "value": 75906,
                        "x": "送礼",
                        "$rowSum": 1734568,
                        "$rowRate": "0.0438",
                        "$rowPercent": "4%",
                        "$rowPercent2": "4.38%",
                        "$value": 75906,
                        "$colSum": 282121,
                        "$colRate": "0.2691",
                        "$colPercent": "27%",
                        "$colPercent2": "26.91%"
                    },
                    "itemStyle": {
                        "color": "#F39B44"
                    }
                }
            ],
            "z": 3
        },
        {
            "type": "line",
            "coordinateSystem": "polar",
            "tooltip": {
                "show": false
            },
            "lineStyle": {
                "width": 1,
                "color": "rgba(0, 0, 0, 0)"
            },
            "name": "实例B",
            "data": [{
                    "value": 118489,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 31579,
                        "negativeSOV": 0.27,
                        "form": "Total",
                        "name": "实例B",
                        "neutral": 35431,
                        "positive": 51479,
                        "type": "产品",
                        "subform": "儿童乳饮料",
                        "positiveSOV": 0.43,
                        "buzz": 118489,
                        "talkingangle": "价格",
                        "neutralSOV": 0.3,
                        "value": 118489,
                        "x": "价格",
                        "$rowSum": 1759287,
                        "$rowRate": "0.0674",
                        "$rowPercent": "7%",
                        "$rowPercent2": "6.74%",
                        "$value": 118489,
                        "$colSum": 292033,
                        "$colRate": "0.4057",
                        "$colPercent": "41%",
                        "$colPercent2": "40.57%"
                    },
                    "itemStyle": {
                        "color": "#71BCEA"
                    }
                },
                {
                    "value": 97579,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 33015,
                        "negativeSOV": 0.34,
                        "form": "Total",
                        "name": "实例B",
                        "neutral": 32640,
                        "positive": 31924,
                        "type": "产品",
                        "subform": "儿童乳饮料",
                        "positiveSOV": 0.33,
                        "buzz": 97579,
                        "talkingangle": "便捷",
                        "neutralSOV": 0.33,
                        "value": 97579,
                        "x": "便捷",
                        "$rowSum": 1759287,
                        "$rowRate": "0.0555",
                        "$rowPercent": "6%",
                        "$rowPercent2": "5.55%",
                        "$value": 97579,
                        "$colSum": 293678,
                        "$colRate": "0.3323",
                        "$colPercent": "33%",
                        "$colPercent2": "33.23%"
                    },
                    "itemStyle": {
                        "color": "#71BCEA"
                    }
                },
                {
                    "value": 122871,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 40549,
                        "negativeSOV": 0.33,
                        "form": "Total",
                        "name": "实例B",
                        "neutral": 47270,
                        "positive": 35052,
                        "type": "产品",
                        "subform": "儿童乳饮料",
                        "positiveSOV": 0.29,
                        "buzz": 122871,
                        "talkingangle": "健康",
                        "neutralSOV": 0.38,
                        "value": 122871,
                        "x": "健康",
                        "$rowSum": 1759287,
                        "$rowRate": "0.0698",
                        "$rowPercent": "7%",
                        "$rowPercent2": "6.98%",
                        "$value": 122871,
                        "$colSum": 464103,
                        "$colRate": "0.2647",
                        "$colPercent": "26%",
                        "$colPercent2": "26.47%"
                    },
                    "itemStyle": {
                        "color": "#71BCEA"
                    }
                },
                {
                    "value": 158822,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 50872,
                        "negativeSOV": 0.32,
                        "form": "Total",
                        "name": "实例B",
                        "neutral": 57939,
                        "positive": 50011,
                        "type": "产品",
                        "subform": "儿童乳饮料",
                        "positiveSOV": 0.31,
                        "buzz": 158822,
                        "talkingangle": "口感",
                        "neutralSOV": 0.36,
                        "value": 158822,
                        "x": "口感",
                        "$rowSum": 1759287,
                        "$rowRate": "0.0903",
                        "$rowPercent": "9%",
                        "$rowPercent2": "9.03%",
                        "$value": 158822,
                        "$colSum": 316803,
                        "$colRate": "0.5013",
                        "$colPercent": "50%",
                        "$colPercent2": "50.13%"
                    },
                    "itemStyle": {
                        "color": "#71BCEA"
                    }
                },
                {
                    "value": 200287,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 62264,
                        "negativeSOV": 0.31,
                        "form": "Total",
                        "name": "实例B",
                        "neutral": 76511,
                        "positive": 61512,
                        "type": "产品",
                        "subform": "儿童乳饮料",
                        "positiveSOV": 0.31,
                        "buzz": 200287,
                        "talkingangle": "品牌认知",
                        "neutralSOV": 0.38,
                        "value": 200287,
                        "x": "品牌认知",
                        "$rowSum": 1759287,
                        "$rowRate": "0.1138",
                        "$rowPercent": "11%",
                        "$rowPercent2": "11.38%",
                        "$value": 200287,
                        "$colSum": 511135,
                        "$colRate": "0.3918",
                        "$colPercent": "39%",
                        "$colPercent2": "39.18%"
                    },
                    "itemStyle": {
                        "color": "#71BCEA"
                    }
                },
                {
                    "value": 149372,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 49518,
                        "negativeSOV": 0.33,
                        "form": "Total",
                        "name": "实例B",
                        "neutral": 43567,
                        "positive": 56287,
                        "type": "产品",
                        "subform": "儿童乳饮料",
                        "positiveSOV": 0.38,
                        "buzz": 149372,
                        "talkingangle": "场合",
                        "neutralSOV": 0.29,
                        "value": 149372,
                        "x": "场合",
                        "$rowSum": 1759287,
                        "$rowRate": "0.0849",
                        "$rowPercent": "8%",
                        "$rowPercent2": "8.49%",
                        "$value": 149372,
                        "$colSum": 520011,
                        "$colRate": "0.2872",
                        "$colPercent": "29%",
                        "$colPercent2": "28.72%"
                    },
                    "itemStyle": {
                        "color": "#71BCEA"
                    }
                },
                {
                    "value": 187207,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 63165,
                        "negativeSOV": 0.34,
                        "form": "Total",
                        "name": "实例B",
                        "neutral": 60777,
                        "positive": 63265,
                        "type": "产品",
                        "subform": "儿童乳饮料",
                        "positiveSOV": 0.34,
                        "buzz": 187207,
                        "talkingangle": "外观",
                        "neutralSOV": 0.32,
                        "value": 187207,
                        "x": "外观",
                        "$rowSum": 1759287,
                        "$rowRate": "0.1064",
                        "$rowPercent": "11%",
                        "$rowPercent2": "10.64%",
                        "$value": 187207,
                        "$colSum": 382005,
                        "$colRate": "0.4901",
                        "$colPercent": "49%",
                        "$colPercent2": "49.01%"
                    },
                    "itemStyle": {
                        "color": "#71BCEA"
                    }
                },
                {
                    "value": 167558,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 55096,
                        "negativeSOV": 0.33,
                        "form": "Total",
                        "name": "实例B",
                        "neutral": 59877,
                        "positive": 52585,
                        "type": "产品",
                        "subform": "儿童乳饮料",
                        "positiveSOV": 0.31,
                        "buzz": 167558,
                        "talkingangle": "感觉",
                        "neutralSOV": 0.36,
                        "value": 167558,
                        "x": "感觉",
                        "$rowSum": 1759287,
                        "$rowRate": "0.0952",
                        "$rowPercent": "10%",
                        "$rowPercent2": "9.52%",
                        "$value": 167558,
                        "$colSum": 561054,
                        "$colRate": "0.2986",
                        "$colPercent": "30%",
                        "$colPercent2": "29.86%"
                    },
                    "itemStyle": {
                        "color": "#71BCEA"
                    }
                },
                {
                    "value": 213977,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 66358,
                        "negativeSOV": 0.31,
                        "form": "Total",
                        "name": "实例B",
                        "neutral": 68838,
                        "positive": 78781,
                        "type": "产品",
                        "subform": "儿童乳饮料",
                        "positiveSOV": 0.37,
                        "buzz": 213977,
                        "talkingangle": "明星",
                        "neutralSOV": 0.32,
                        "value": 213977,
                        "x": "明星",
                        "$rowSum": 1759287,
                        "$rowRate": "0.1216",
                        "$rowPercent": "12%",
                        "$rowPercent2": "12.16%",
                        "$value": 213977,
                        "$colSum": 409682,
                        "$colRate": "0.5223",
                        "$colPercent": "52%",
                        "$colPercent2": "52.23%"
                    },
                    "itemStyle": {
                        "color": "#71BCEA"
                    }
                },
                {
                    "value": 106314,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 36750,
                        "negativeSOV": 0.35,
                        "form": "Total",
                        "name": "实例B",
                        "neutral": 35164,
                        "positive": 34400,
                        "type": "产品",
                        "subform": "儿童乳饮料",
                        "positiveSOV": 0.32,
                        "buzz": 106314,
                        "talkingangle": "材质",
                        "neutralSOV": 0.33,
                        "value": 106314,
                        "x": "材质",
                        "$rowSum": 1759287,
                        "$rowRate": "0.0604",
                        "$rowPercent": "6%",
                        "$rowPercent2": "6.04%",
                        "$value": 106314,
                        "$colSum": 416568,
                        "$colRate": "0.2552",
                        "$colPercent": "26%",
                        "$colPercent2": "25.52%"
                    },
                    "itemStyle": {
                        "color": "#71BCEA"
                    }
                },
                {
                    "value": 114994,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 40478,
                        "negativeSOV": 0.35,
                        "form": "Total",
                        "name": "实例B",
                        "neutral": 34268,
                        "positive": 40248,
                        "type": "产品",
                        "subform": "儿童乳饮料",
                        "positiveSOV": 0.35,
                        "buzz": 114994,
                        "talkingangle": "设计",
                        "neutralSOV": 0.3,
                        "value": 114994,
                        "x": "设计",
                        "$rowSum": 1759287,
                        "$rowRate": "0.0654",
                        "$rowPercent": "7%",
                        "$rowPercent2": "6.54%",
                        "$value": 114994,
                        "$colSum": 741766,
                        "$colRate": "0.155",
                        "$colPercent": "16%",
                        "$colPercent2": "15.5%"
                    },
                    "itemStyle": {
                        "color": "#71BCEA"
                    }
                },
                {
                    "value": 121817,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 41670,
                        "negativeSOV": 0.34,
                        "form": "Total",
                        "name": "实例B",
                        "neutral": 42922,
                        "positive": 37225,
                        "type": "产品",
                        "subform": "儿童乳饮料",
                        "positiveSOV": 0.31,
                        "buzz": 121817,
                        "talkingangle": "送礼",
                        "neutralSOV": 0.35,
                        "value": 121817,
                        "x": "送礼",
                        "$rowSum": 1759287,
                        "$rowRate": "0.0692",
                        "$rowPercent": "7%",
                        "$rowPercent2": "6.92%",
                        "$value": 121817,
                        "$colSum": 282121,
                        "$colRate": "0.4318",
                        "$colPercent": "43%",
                        "$colPercent2": "43.18%"
                    },
                    "itemStyle": {
                        "color": "#71BCEA"
                    }
                }
            ],
            "z": 3
        },
        {
            "type": "line",
            "coordinateSystem": "polar",
            "tooltip": {
                "show": false
            },
            "lineStyle": {
                "width": 1,
                "color": "rgba(0, 0, 0, 0)"
            },
            "name": "实例C",
            "data": [{
                    "value": 110167,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 32060,
                        "negativeSOV": 0.29,
                        "form": "Total",
                        "name": "实例C",
                        "neutral": 37457,
                        "positive": 40650,
                        "type": "产品",
                        "subform": "Total",
                        "positiveSOV": 0.37,
                        "buzz": 110167,
                        "talkingangle": "价格",
                        "neutralSOV": 0.34,
                        "value": 110167,
                        "x": "价格",
                        "$rowSum": 1697104,
                        "$rowRate": "0.0649",
                        "$rowPercent": "6%",
                        "$rowPercent2": "6.49%",
                        "$value": 110167,
                        "$colSum": 292033,
                        "$colRate": "0.3772",
                        "$colPercent": "38%",
                        "$colPercent2": "37.72%"
                    },
                    "itemStyle": {
                        "color": "#B7D200"
                    }
                },
                {
                    "value": 111870,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 41809,
                        "negativeSOV": 0.37,
                        "form": "Total",
                        "name": "实例C",
                        "neutral": 43620,
                        "positive": 26441,
                        "type": "产品",
                        "subform": "Total",
                        "positiveSOV": 0.24,
                        "buzz": 111870,
                        "talkingangle": "便捷",
                        "neutralSOV": 0.39,
                        "value": 111870,
                        "x": "便捷",
                        "$rowSum": 1697104,
                        "$rowRate": "0.0659",
                        "$rowPercent": "7%",
                        "$rowPercent2": "6.59%",
                        "$value": 111870,
                        "$colSum": 293678,
                        "$colRate": "0.3809",
                        "$colPercent": "38%",
                        "$colPercent2": "38.09%"
                    },
                    "itemStyle": {
                        "color": "#B7D200"
                    }
                },
                {
                    "value": 172585,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 61109,
                        "negativeSOV": 0.35,
                        "form": "Total",
                        "name": "实例C",
                        "neutral": 57999,
                        "positive": 53477,
                        "type": "产品",
                        "subform": "Total",
                        "positiveSOV": 0.31,
                        "buzz": 172585,
                        "talkingangle": "健康",
                        "neutralSOV": 0.34,
                        "value": 172585,
                        "x": "健康",
                        "$rowSum": 1697104,
                        "$rowRate": "0.1017",
                        "$rowPercent": "10%",
                        "$rowPercent2": "10.17%",
                        "$value": 172585,
                        "$colSum": 464103,
                        "$colRate": "0.3719",
                        "$colPercent": "37%",
                        "$colPercent2": "37.19%"
                    },
                    "itemStyle": {
                        "color": "#B7D200"
                    }
                },
                {
                    "value": 131122,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 47104,
                        "negativeSOV": 0.36,
                        "form": "Total",
                        "name": "实例C",
                        "neutral": 42174,
                        "positive": 41844,
                        "type": "产品",
                        "subform": "Total",
                        "positiveSOV": 0.32,
                        "buzz": 131122,
                        "talkingangle": "口感",
                        "neutralSOV": 0.32,
                        "value": 131122,
                        "x": "口感",
                        "$rowSum": 1697104,
                        "$rowRate": "0.0773",
                        "$rowPercent": "8%",
                        "$rowPercent2": "7.73%",
                        "$value": 131122,
                        "$colSum": 316803,
                        "$colRate": "0.4139",
                        "$colPercent": "41%",
                        "$colPercent2": "41.39%"
                    },
                    "itemStyle": {
                        "color": "#B7D200"
                    }
                },
                {
                    "value": 96024,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 29977,
                        "negativeSOV": 0.31,
                        "form": "Total",
                        "name": "实例C",
                        "neutral": 36968,
                        "positive": 29079,
                        "type": "产品",
                        "subform": "Total",
                        "positiveSOV": 0.3,
                        "buzz": 96024,
                        "talkingangle": "品牌认知",
                        "neutralSOV": 0.38,
                        "value": 96024,
                        "x": "品牌认知",
                        "$rowSum": 1697104,
                        "$rowRate": "0.0566",
                        "$rowPercent": "6%",
                        "$rowPercent2": "5.66%",
                        "$value": 96024,
                        "$colSum": 511135,
                        "$colRate": "0.1879",
                        "$colPercent": "19%",
                        "$colPercent2": "18.79%"
                    },
                    "itemStyle": {
                        "color": "#B7D200"
                    }
                },
                {
                    "value": 219132,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 69843,
                        "negativeSOV": 0.32,
                        "form": "Total",
                        "name": "实例C",
                        "neutral": 71743,
                        "positive": 77546,
                        "type": "产品",
                        "subform": "Total",
                        "positiveSOV": 0.35,
                        "buzz": 219132,
                        "talkingangle": "场合",
                        "neutralSOV": 0.33,
                        "value": 219132,
                        "x": "场合",
                        "$rowSum": 1697104,
                        "$rowRate": "0.1291",
                        "$rowPercent": "13%",
                        "$rowPercent2": "12.91%",
                        "$value": 219132,
                        "$colSum": 520011,
                        "$colRate": "0.4214",
                        "$colPercent": "42%",
                        "$colPercent2": "42.14%"
                    },
                    "itemStyle": {
                        "color": "#B7D200"
                    }
                },
                {
                    "value": 44320,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 14675,
                        "negativeSOV": 0.33,
                        "form": "Total",
                        "name": "实例C",
                        "neutral": 14728,
                        "positive": 14917,
                        "type": "产品",
                        "subform": "Total",
                        "positiveSOV": 0.34,
                        "buzz": 44320,
                        "talkingangle": "外观",
                        "neutralSOV": 0.33,
                        "value": 44320,
                        "x": "外观",
                        "$rowSum": 1697104,
                        "$rowRate": "0.0261",
                        "$rowPercent": "3%",
                        "$rowPercent2": "2.61%",
                        "$value": 44320,
                        "$colSum": 382005,
                        "$colRate": "0.116",
                        "$colPercent": "12%",
                        "$colPercent2": "11.6%"
                    },
                    "itemStyle": {
                        "color": "#B7D200"
                    }
                },
                {
                    "value": 159358,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 51116,
                        "negativeSOV": 0.32,
                        "form": "Total",
                        "name": "实例C",
                        "neutral": 50364,
                        "positive": 57878,
                        "type": "产品",
                        "subform": "Total",
                        "positiveSOV": 0.36,
                        "buzz": 159358,
                        "talkingangle": "感觉",
                        "neutralSOV": 0.32,
                        "value": 159358,
                        "x": "感觉",
                        "$rowSum": 1697104,
                        "$rowRate": "0.0939",
                        "$rowPercent": "9%",
                        "$rowPercent2": "9.39%",
                        "$value": 159358,
                        "$colSum": 561054,
                        "$colRate": "0.284",
                        "$colPercent": "28%",
                        "$colPercent2": "28.4%"
                    },
                    "itemStyle": {
                        "color": "#B7D200"
                    }
                },
                {
                    "value": 88886,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 27667,
                        "negativeSOV": 0.31,
                        "form": "Total",
                        "name": "实例C",
                        "neutral": 33034,
                        "positive": 28185,
                        "type": "产品",
                        "subform": "Total",
                        "positiveSOV": 0.32,
                        "buzz": 88886,
                        "talkingangle": "明星",
                        "neutralSOV": 0.37,
                        "value": 88886,
                        "x": "明星",
                        "$rowSum": 1697104,
                        "$rowRate": "0.0524",
                        "$rowPercent": "5%",
                        "$rowPercent2": "5.24%",
                        "$value": 88886,
                        "$colSum": 409682,
                        "$colRate": "0.217",
                        "$colPercent": "22%",
                        "$colPercent2": "21.7%"
                    },
                    "itemStyle": {
                        "color": "#B7D200"
                    }
                },
                {
                    "value": 120450,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 49210,
                        "negativeSOV": 0.41,
                        "form": "Total",
                        "name": "实例C",
                        "neutral": 41230,
                        "positive": 30010,
                        "type": "产品",
                        "subform": "Total",
                        "positiveSOV": 0.25,
                        "buzz": 120450,
                        "talkingangle": "材质",
                        "neutralSOV": 0.34,
                        "value": 120450,
                        "x": "材质",
                        "$rowSum": 1697104,
                        "$rowRate": "0.071",
                        "$rowPercent": "7%",
                        "$rowPercent2": "7.1%",
                        "$value": 120450,
                        "$colSum": 416568,
                        "$colRate": "0.2891",
                        "$colPercent": "29%",
                        "$colPercent2": "28.91%"
                    },
                    "itemStyle": {
                        "color": "#B7D200"
                    }
                },
                {
                    "value": 358792,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 123721,
                        "negativeSOV": 0.34,
                        "form": "Total",
                        "name": "实例C",
                        "neutral": 118893,
                        "positive": 116178,
                        "type": "产品",
                        "subform": "Total",
                        "positiveSOV": 0.32,
                        "buzz": 358792,
                        "talkingangle": "设计",
                        "neutralSOV": 0.33,
                        "value": 358792,
                        "x": "设计",
                        "$rowSum": 1697104,
                        "$rowRate": "0.2114",
                        "$rowPercent": "21%",
                        "$rowPercent2": "21.14%",
                        "$value": 358792,
                        "$colSum": 741766,
                        "$colRate": "0.4837",
                        "$colPercent": "48%",
                        "$colPercent2": "48.37%"
                    },
                    "itemStyle": {
                        "color": "#B7D200"
                    }
                },
                {
                    "value": 84398,
                    "symbolSize": null,
                    "symbol": "none",
                    "source": {
                        "negative": 27672,
                        "negativeSOV": 0.33,
                        "form": "Total",
                        "name": "实例C",
                        "neutral": 28519,
                        "positive": 28207,
                        "type": "产品",
                        "subform": "Total",
                        "positiveSOV": 0.33,
                        "buzz": 84398,
                        "talkingangle": "送礼",
                        "neutralSOV": 0.34,
                        "value": 84398,
                        "x": "送礼",
                        "$rowSum": 1697104,
                        "$rowRate": "0.0497",
                        "$rowPercent": "5%",
                        "$rowPercent2": "4.97%",
                        "$value": 84398,
                        "$colSum": 282121,
                        "$colRate": "0.2992",
                        "$colPercent": "30%",
                        "$colPercent2": "29.92%"
                    },
                    "itemStyle": {
                        "color": "#B7D200"
                    }
                }
            ],
            "z": 3
        },
        {
            "type": "radar",
            "name": "实例C_radar-group",
            "data": [{
                    "name": "实例C",
                    "value": [
                        110167,
                        111870,
                        172585,
                        131122,
                        96024,
                        219132,
                        44320,
                        159358,
                        88886,
                        120450,
                        358792,
                        84398
                    ],
                    "source": [{
                            "negative": 32060,
                            "negativeSOV": 0.29,
                            "form": "Total",
                            "name": "实例C",
                            "neutral": 37457,
                            "positive": 40650,
                            "type": "产品",
                            "subform": "Total",
                            "positiveSOV": 0.37,
                            "buzz": 110167,
                            "talkingangle": "价格",
                            "neutralSOV": 0.34,
                            "value": 110167,
                            "x": "价格",
                            "$rowSum": 1697104,
                            "$rowRate": "0.0649",
                            "$rowPercent": "6%",
                            "$rowPercent2": "6.49%",
                            "$value": 110167,
                            "$colSum": 292033,
                            "$colRate": "0.3772",
                            "$colPercent": "38%",
                            "$colPercent2": "37.72%"
                        },
                        {
                            "negative": 41809,
                            "negativeSOV": 0.37,
                            "form": "Total",
                            "name": "实例C",
                            "neutral": 43620,
                            "positive": 26441,
                            "type": "产品",
                            "subform": "Total",
                            "positiveSOV": 0.24,
                            "buzz": 111870,
                            "talkingangle": "便捷",
                            "neutralSOV": 0.39,
                            "value": 111870,
                            "x": "便捷",
                            "$rowSum": 1697104,
                            "$rowRate": "0.0659",
                            "$rowPercent": "7%",
                            "$rowPercent2": "6.59%",
                            "$value": 111870,
                            "$colSum": 293678,
                            "$colRate": "0.3809",
                            "$colPercent": "38%",
                            "$colPercent2": "38.09%"
                        },
                        {
                            "negative": 61109,
                            "negativeSOV": 0.35,
                            "form": "Total",
                            "name": "实例C",
                            "neutral": 57999,
                            "positive": 53477,
                            "type": "产品",
                            "subform": "Total",
                            "positiveSOV": 0.31,
                            "buzz": 172585,
                            "talkingangle": "健康",
                            "neutralSOV": 0.34,
                            "value": 172585,
                            "x": "健康",
                            "$rowSum": 1697104,
                            "$rowRate": "0.1017",
                            "$rowPercent": "10%",
                            "$rowPercent2": "10.17%",
                            "$value": 172585,
                            "$colSum": 464103,
                            "$colRate": "0.3719",
                            "$colPercent": "37%",
                            "$colPercent2": "37.19%"
                        },
                        {
                            "negative": 47104,
                            "negativeSOV": 0.36,
                            "form": "Total",
                            "name": "实例C",
                            "neutral": 42174,
                            "positive": 41844,
                            "type": "产品",
                            "subform": "Total",
                            "positiveSOV": 0.32,
                            "buzz": 131122,
                            "talkingangle": "口感",
                            "neutralSOV": 0.32,
                            "value": 131122,
                            "x": "口感",
                            "$rowSum": 1697104,
                            "$rowRate": "0.0773",
                            "$rowPercent": "8%",
                            "$rowPercent2": "7.73%",
                            "$value": 131122,
                            "$colSum": 316803,
                            "$colRate": "0.4139",
                            "$colPercent": "41%",
                            "$colPercent2": "41.39%"
                        },
                        {
                            "negative": 29977,
                            "negativeSOV": 0.31,
                            "form": "Total",
                            "name": "实例C",
                            "neutral": 36968,
                            "positive": 29079,
                            "type": "产品",
                            "subform": "Total",
                            "positiveSOV": 0.3,
                            "buzz": 96024,
                            "talkingangle": "品牌认知",
                            "neutralSOV": 0.38,
                            "value": 96024,
                            "x": "品牌认知",
                            "$rowSum": 1697104,
                            "$rowRate": "0.0566",
                            "$rowPercent": "6%",
                            "$rowPercent2": "5.66%",
                            "$value": 96024,
                            "$colSum": 511135,
                            "$colRate": "0.1879",
                            "$colPercent": "19%",
                            "$colPercent2": "18.79%"
                        },
                        {
                            "negative": 69843,
                            "negativeSOV": 0.32,
                            "form": "Total",
                            "name": "实例C",
                            "neutral": 71743,
                            "positive": 77546,
                            "type": "产品",
                            "subform": "Total",
                            "positiveSOV": 0.35,
                            "buzz": 219132,
                            "talkingangle": "场合",
                            "neutralSOV": 0.33,
                            "value": 219132,
                            "x": "场合",
                            "$rowSum": 1697104,
                            "$rowRate": "0.1291",
                            "$rowPercent": "13%",
                            "$rowPercent2": "12.91%",
                            "$value": 219132,
                            "$colSum": 520011,
                            "$colRate": "0.4214",
                            "$colPercent": "42%",
                            "$colPercent2": "42.14%"
                        },
                        {
                            "negative": 14675,
                            "negativeSOV": 0.33,
                            "form": "Total",
                            "name": "实例C",
                            "neutral": 14728,
                            "positive": 14917,
                            "type": "产品",
                            "subform": "Total",
                            "positiveSOV": 0.34,
                            "buzz": 44320,
                            "talkingangle": "外观",
                            "neutralSOV": 0.33,
                            "value": 44320,
                            "x": "外观",
                            "$rowSum": 1697104,
                            "$rowRate": "0.0261",
                            "$rowPercent": "3%",
                            "$rowPercent2": "2.61%",
                            "$value": 44320,
                            "$colSum": 382005,
                            "$colRate": "0.116",
                            "$colPercent": "12%",
                            "$colPercent2": "11.6%"
                        },
                        {
                            "negative": 51116,
                            "negativeSOV": 0.32,
                            "form": "Total",
                            "name": "实例C",
                            "neutral": 50364,
                            "positive": 57878,
                            "type": "产品",
                            "subform": "Total",
                            "positiveSOV": 0.36,
                            "buzz": 159358,
                            "talkingangle": "感觉",
                            "neutralSOV": 0.32,
                            "value": 159358,
                            "x": "感觉",
                            "$rowSum": 1697104,
                            "$rowRate": "0.0939",
                            "$rowPercent": "9%",
                            "$rowPercent2": "9.39%",
                            "$value": 159358,
                            "$colSum": 561054,
                            "$colRate": "0.284",
                            "$colPercent": "28%",
                            "$colPercent2": "28.4%"
                        },
                        {
                            "negative": 27667,
                            "negativeSOV": 0.31,
                            "form": "Total",
                            "name": "实例C",
                            "neutral": 33034,
                            "positive": 28185,
                            "type": "产品",
                            "subform": "Total",
                            "positiveSOV": 0.32,
                            "buzz": 88886,
                            "talkingangle": "明星",
                            "neutralSOV": 0.37,
                            "value": 88886,
                            "x": "明星",
                            "$rowSum": 1697104,
                            "$rowRate": "0.0524",
                            "$rowPercent": "5%",
                            "$rowPercent2": "5.24%",
                            "$value": 88886,
                            "$colSum": 409682,
                            "$colRate": "0.217",
                            "$colPercent": "22%",
                            "$colPercent2": "21.7%"
                        },
                        {
                            "negative": 49210,
                            "negativeSOV": 0.41,
                            "form": "Total",
                            "name": "实例C",
                            "neutral": 41230,
                            "positive": 30010,
                            "type": "产品",
                            "subform": "Total",
                            "positiveSOV": 0.25,
                            "buzz": 120450,
                            "talkingangle": "材质",
                            "neutralSOV": 0.34,
                            "value": 120450,
                            "x": "材质",
                            "$rowSum": 1697104,
                            "$rowRate": "0.071",
                            "$rowPercent": "7%",
                            "$rowPercent2": "7.1%",
                            "$value": 120450,
                            "$colSum": 416568,
                            "$colRate": "0.2891",
                            "$colPercent": "29%",
                            "$colPercent2": "28.91%"
                        },
                        {
                            "negative": 123721,
                            "negativeSOV": 0.34,
                            "form": "Total",
                            "name": "实例C",
                            "neutral": 118893,
                            "positive": 116178,
                            "type": "产品",
                            "subform": "Total",
                            "positiveSOV": 0.32,
                            "buzz": 358792,
                            "talkingangle": "设计",
                            "neutralSOV": 0.33,
                            "value": 358792,
                            "x": "设计",
                            "$rowSum": 1697104,
                            "$rowRate": "0.2114",
                            "$rowPercent": "21%",
                            "$rowPercent2": "21.14%",
                            "$value": 358792,
                            "$colSum": 741766,
                            "$colRate": "0.4837",
                            "$colPercent": "48%",
                            "$colPercent2": "48.37%"
                        },
                        {
                            "negative": 27672,
                            "negativeSOV": 0.33,
                            "form": "Total",
                            "name": "实例C",
                            "neutral": 28519,
                            "positive": 28207,
                            "type": "产品",
                            "subform": "Total",
                            "positiveSOV": 0.33,
                            "buzz": 84398,
                            "talkingangle": "送礼",
                            "neutralSOV": 0.34,
                            "value": 84398,
                            "x": "送礼",
                            "$rowSum": 1697104,
                            "$rowRate": "0.0497",
                            "$rowPercent": "5%",
                            "$rowPercent2": "4.97%",
                            "$value": 84398,
                            "$colSum": 282121,
                            "$colRate": "0.2992",
                            "$colPercent": "30%",
                            "$colPercent2": "29.92%"
                        }
                    ],
                    "itemStyle": {
                        "color": "#B7D200"
                    },
                    "lineStyle": {
                        "type": "solid",
                        "width": 2,
                        "color": "#B7D200"
                    },
                    "areaStyle": {
                        "color": "#B7D200",
                        "opacity": 0.5
                    }
                },
                {
                    "name": "实例B",
                    "value": [
                        118489,
                        97579,
                        122871,
                        158822,
                        200287,
                        149372,
                        187207,
                        167558,
                        213977,
                        106314,
                        114994,
                        121817
                    ],
                    "source": [{
                            "negative": 31579,
                            "negativeSOV": 0.27,
                            "form": "Total",
                            "name": "实例B",
                            "neutral": 35431,
                            "positive": 51479,
                            "type": "产品",
                            "subform": "儿童乳饮料",
                            "positiveSOV": 0.43,
                            "buzz": 118489,
                            "talkingangle": "价格",
                            "neutralSOV": 0.3,
                            "value": 118489,
                            "x": "价格",
                            "$rowSum": 1759287,
                            "$rowRate": "0.0674",
                            "$rowPercent": "7%",
                            "$rowPercent2": "6.74%",
                            "$value": 118489,
                            "$colSum": 292033,
                            "$colRate": "0.4057",
                            "$colPercent": "41%",
                            "$colPercent2": "40.57%"
                        },
                        {
                            "negative": 33015,
                            "negativeSOV": 0.34,
                            "form": "Total",
                            "name": "实例B",
                            "neutral": 32640,
                            "positive": 31924,
                            "type": "产品",
                            "subform": "儿童乳饮料",
                            "positiveSOV": 0.33,
                            "buzz": 97579,
                            "talkingangle": "便捷",
                            "neutralSOV": 0.33,
                            "value": 97579,
                            "x": "便捷",
                            "$rowSum": 1759287,
                            "$rowRate": "0.0555",
                            "$rowPercent": "6%",
                            "$rowPercent2": "5.55%",
                            "$value": 97579,
                            "$colSum": 293678,
                            "$colRate": "0.3323",
                            "$colPercent": "33%",
                            "$colPercent2": "33.23%"
                        },
                        {
                            "negative": 40549,
                            "negativeSOV": 0.33,
                            "form": "Total",
                            "name": "实例B",
                            "neutral": 47270,
                            "positive": 35052,
                            "type": "产品",
                            "subform": "儿童乳饮料",
                            "positiveSOV": 0.29,
                            "buzz": 122871,
                            "talkingangle": "健康",
                            "neutralSOV": 0.38,
                            "value": 122871,
                            "x": "健康",
                            "$rowSum": 1759287,
                            "$rowRate": "0.0698",
                            "$rowPercent": "7%",
                            "$rowPercent2": "6.98%",
                            "$value": 122871,
                            "$colSum": 464103,
                            "$colRate": "0.2647",
                            "$colPercent": "26%",
                            "$colPercent2": "26.47%"
                        },
                        {
                            "negative": 50872,
                            "negativeSOV": 0.32,
                            "form": "Total",
                            "name": "实例B",
                            "neutral": 57939,
                            "positive": 50011,
                            "type": "产品",
                            "subform": "儿童乳饮料",
                            "positiveSOV": 0.31,
                            "buzz": 158822,
                            "talkingangle": "口感",
                            "neutralSOV": 0.36,
                            "value": 158822,
                            "x": "口感",
                            "$rowSum": 1759287,
                            "$rowRate": "0.0903",
                            "$rowPercent": "9%",
                            "$rowPercent2": "9.03%",
                            "$value": 158822,
                            "$colSum": 316803,
                            "$colRate": "0.5013",
                            "$colPercent": "50%",
                            "$colPercent2": "50.13%"
                        },
                        {
                            "negative": 62264,
                            "negativeSOV": 0.31,
                            "form": "Total",
                            "name": "实例B",
                            "neutral": 76511,
                            "positive": 61512,
                            "type": "产品",
                            "subform": "儿童乳饮料",
                            "positiveSOV": 0.31,
                            "buzz": 200287,
                            "talkingangle": "品牌认知",
                            "neutralSOV": 0.38,
                            "value": 200287,
                            "x": "品牌认知",
                            "$rowSum": 1759287,
                            "$rowRate": "0.1138",
                            "$rowPercent": "11%",
                            "$rowPercent2": "11.38%",
                            "$value": 200287,
                            "$colSum": 511135,
                            "$colRate": "0.3918",
                            "$colPercent": "39%",
                            "$colPercent2": "39.18%"
                        },
                        {
                            "negative": 49518,
                            "negativeSOV": 0.33,
                            "form": "Total",
                            "name": "实例B",
                            "neutral": 43567,
                            "positive": 56287,
                            "type": "产品",
                            "subform": "儿童乳饮料",
                            "positiveSOV": 0.38,
                            "buzz": 149372,
                            "talkingangle": "场合",
                            "neutralSOV": 0.29,
                            "value": 149372,
                            "x": "场合",
                            "$rowSum": 1759287,
                            "$rowRate": "0.0849",
                            "$rowPercent": "8%",
                            "$rowPercent2": "8.49%",
                            "$value": 149372,
                            "$colSum": 520011,
                            "$colRate": "0.2872",
                            "$colPercent": "29%",
                            "$colPercent2": "28.72%"
                        },
                        {
                            "negative": 63165,
                            "negativeSOV": 0.34,
                            "form": "Total",
                            "name": "实例B",
                            "neutral": 60777,
                            "positive": 63265,
                            "type": "产品",
                            "subform": "儿童乳饮料",
                            "positiveSOV": 0.34,
                            "buzz": 187207,
                            "talkingangle": "外观",
                            "neutralSOV": 0.32,
                            "value": 187207,
                            "x": "外观",
                            "$rowSum": 1759287,
                            "$rowRate": "0.1064",
                            "$rowPercent": "11%",
                            "$rowPercent2": "10.64%",
                            "$value": 187207,
                            "$colSum": 382005,
                            "$colRate": "0.4901",
                            "$colPercent": "49%",
                            "$colPercent2": "49.01%"
                        },
                        {
                            "negative": 55096,
                            "negativeSOV": 0.33,
                            "form": "Total",
                            "name": "实例B",
                            "neutral": 59877,
                            "positive": 52585,
                            "type": "产品",
                            "subform": "儿童乳饮料",
                            "positiveSOV": 0.31,
                            "buzz": 167558,
                            "talkingangle": "感觉",
                            "neutralSOV": 0.36,
                            "value": 167558,
                            "x": "感觉",
                            "$rowSum": 1759287,
                            "$rowRate": "0.0952",
                            "$rowPercent": "10%",
                            "$rowPercent2": "9.52%",
                            "$value": 167558,
                            "$colSum": 561054,
                            "$colRate": "0.2986",
                            "$colPercent": "30%",
                            "$colPercent2": "29.86%"
                        },
                        {
                            "negative": 66358,
                            "negativeSOV": 0.31,
                            "form": "Total",
                            "name": "实例B",
                            "neutral": 68838,
                            "positive": 78781,
                            "type": "产品",
                            "subform": "儿童乳饮料",
                            "positiveSOV": 0.37,
                            "buzz": 213977,
                            "talkingangle": "明星",
                            "neutralSOV": 0.32,
                            "value": 213977,
                            "x": "明星",
                            "$rowSum": 1759287,
                            "$rowRate": "0.1216",
                            "$rowPercent": "12%",
                            "$rowPercent2": "12.16%",
                            "$value": 213977,
                            "$colSum": 409682,
                            "$colRate": "0.5223",
                            "$colPercent": "52%",
                            "$colPercent2": "52.23%"
                        },
                        {
                            "negative": 36750,
                            "negativeSOV": 0.35,
                            "form": "Total",
                            "name": "实例B",
                            "neutral": 35164,
                            "positive": 34400,
                            "type": "产品",
                            "subform": "儿童乳饮料",
                            "positiveSOV": 0.32,
                            "buzz": 106314,
                            "talkingangle": "材质",
                            "neutralSOV": 0.33,
                            "value": 106314,
                            "x": "材质",
                            "$rowSum": 1759287,
                            "$rowRate": "0.0604",
                            "$rowPercent": "6%",
                            "$rowPercent2": "6.04%",
                            "$value": 106314,
                            "$colSum": 416568,
                            "$colRate": "0.2552",
                            "$colPercent": "26%",
                            "$colPercent2": "25.52%"
                        },
                        {
                            "negative": 40478,
                            "negativeSOV": 0.35,
                            "form": "Total",
                            "name": "实例B",
                            "neutral": 34268,
                            "positive": 40248,
                            "type": "产品",
                            "subform": "儿童乳饮料",
                            "positiveSOV": 0.35,
                            "buzz": 114994,
                            "talkingangle": "设计",
                            "neutralSOV": 0.3,
                            "value": 114994,
                            "x": "设计",
                            "$rowSum": 1759287,
                            "$rowRate": "0.0654",
                            "$rowPercent": "7%",
                            "$rowPercent2": "6.54%",
                            "$value": 114994,
                            "$colSum": 741766,
                            "$colRate": "0.155",
                            "$colPercent": "16%",
                            "$colPercent2": "15.5%"
                        },
                        {
                            "negative": 41670,
                            "negativeSOV": 0.34,
                            "form": "Total",
                            "name": "实例B",
                            "neutral": 42922,
                            "positive": 37225,
                            "type": "产品",
                            "subform": "儿童乳饮料",
                            "positiveSOV": 0.31,
                            "buzz": 121817,
                            "talkingangle": "送礼",
                            "neutralSOV": 0.35,
                            "value": 121817,
                            "x": "送礼",
                            "$rowSum": 1759287,
                            "$rowRate": "0.0692",
                            "$rowPercent": "7%",
                            "$rowPercent2": "6.92%",
                            "$value": 121817,
                            "$colSum": 282121,
                            "$colRate": "0.4318",
                            "$colPercent": "43%",
                            "$colPercent2": "43.18%"
                        }
                    ],
                    "itemStyle": {
                        "color": "#71BCEA"
                    },
                    "lineStyle": {
                        "type": "solid",
                        "width": 2,
                        "color": "#71BCEA"
                    },
                    "areaStyle": {
                        "color": "#71BCEA",
                        "opacity": 0.5
                    }
                },
                {
                    "name": "实例A",
                    "value": [
                        63377,
                        84229,
                        168647,
                        26859,
                        214824,
                        151507,
                        150478,
                        234138,
                        106819,
                        189804,
                        267980,
                        75906
                    ],
                    "source": [{
                            "negative": 23043,
                            "negativeSOV": 0.36,
                            "form": "Total",
                            "name": "实例A",
                            "neutral": 18782,
                            "positive": 21552,
                            "type": "产品",
                            "subform": "儿童牛奶",
                            "positiveSOV": 0.34,
                            "buzz": 63377,
                            "talkingangle": "价格",
                            "neutralSOV": 0.3,
                            "value": 63377,
                            "x": "价格",
                            "$rowSum": 1734568,
                            "$rowRate": "0.0365",
                            "$rowPercent": "4%",
                            "$rowPercent2": "3.65%",
                            "$value": 63377,
                            "$colSum": 292033,
                            "$colRate": "0.217",
                            "$colPercent": "22%",
                            "$colPercent2": "21.7%"
                        },
                        {
                            "negative": 22634,
                            "negativeSOV": 0.27,
                            "form": "Total",
                            "name": "实例A",
                            "neutral": 31716,
                            "positive": 29879,
                            "type": "产品",
                            "subform": "儿童牛奶",
                            "positiveSOV": 0.35,
                            "buzz": 84229,
                            "talkingangle": "便捷",
                            "neutralSOV": 0.38,
                            "value": 84229,
                            "x": "便捷",
                            "$rowSum": 1734568,
                            "$rowRate": "0.0486",
                            "$rowPercent": "5%",
                            "$rowPercent2": "4.86%",
                            "$value": 84229,
                            "$colSum": 293678,
                            "$colRate": "0.2868",
                            "$colPercent": "29%",
                            "$colPercent2": "28.68%"
                        },
                        {
                            "negative": 58718,
                            "negativeSOV": 0.35,
                            "form": "Total",
                            "name": "实例A",
                            "neutral": 56839,
                            "positive": 53090,
                            "type": "产品",
                            "subform": "儿童牛奶",
                            "positiveSOV": 0.31,
                            "buzz": 168647,
                            "talkingangle": "健康",
                            "neutralSOV": 0.34,
                            "value": 168647,
                            "x": "健康",
                            "$rowSum": 1734568,
                            "$rowRate": "0.0972",
                            "$rowPercent": "10%",
                            "$rowPercent2": "9.72%",
                            "$value": 168647,
                            "$colSum": 464103,
                            "$colRate": "0.3634",
                            "$colPercent": "36%",
                            "$colPercent2": "36.34%"
                        },
                        {
                            "negative": 13736,
                            "negativeSOV": 0.51,
                            "form": "Total",
                            "name": "实例A",
                            "neutral": 5049,
                            "positive": 8074,
                            "type": "产品",
                            "subform": "儿童牛奶",
                            "positiveSOV": 0.3,
                            "buzz": 26859,
                            "talkingangle": "口感",
                            "neutralSOV": 0.19,
                            "value": 26859,
                            "x": "口感",
                            "$rowSum": 1734568,
                            "$rowRate": "0.0155",
                            "$rowPercent": "2%",
                            "$rowPercent2": "1.55%",
                            "$value": 26859,
                            "$colSum": 316803,
                            "$colRate": "0.0848",
                            "$colPercent": "8%",
                            "$colPercent2": "8.48%"
                        },
                        {
                            "negative": 72839,
                            "negativeSOV": 0.34,
                            "form": "Total",
                            "name": "实例A",
                            "neutral": 75183,
                            "positive": 66802,
                            "type": "产品",
                            "subform": "儿童牛奶",
                            "positiveSOV": 0.31,
                            "buzz": 214824,
                            "talkingangle": "品牌认知",
                            "neutralSOV": 0.35,
                            "value": 214824,
                            "x": "品牌认知",
                            "$rowSum": 1734568,
                            "$rowRate": "0.1238",
                            "$rowPercent": "12%",
                            "$rowPercent2": "12.38%",
                            "$value": 214824,
                            "$colSum": 511135,
                            "$colRate": "0.4203",
                            "$colPercent": "42%",
                            "$colPercent2": "42.03%"
                        },
                        {
                            "negative": 53098,
                            "negativeSOV": 0.35,
                            "form": "Total",
                            "name": "实例A",
                            "neutral": 46250,
                            "positive": 52159,
                            "type": "产品",
                            "subform": "儿童牛奶",
                            "positiveSOV": 0.34,
                            "buzz": 151507,
                            "talkingangle": "场合",
                            "neutralSOV": 0.31,
                            "value": 151507,
                            "x": "场合",
                            "$rowSum": 1734568,
                            "$rowRate": "0.0873",
                            "$rowPercent": "9%",
                            "$rowPercent2": "8.73%",
                            "$value": 151507,
                            "$colSum": 520011,
                            "$colRate": "0.2914",
                            "$colPercent": "29%",
                            "$colPercent2": "29.14%"
                        },
                        {
                            "negative": 53518,
                            "negativeSOV": 0.36,
                            "form": "Total",
                            "name": "实例A",
                            "neutral": 42874,
                            "positive": 54086,
                            "type": "产品",
                            "subform": "儿童牛奶",
                            "positiveSOV": 0.36,
                            "buzz": 150478,
                            "talkingangle": "外观",
                            "neutralSOV": 0.28,
                            "value": 150478,
                            "x": "外观",
                            "$rowSum": 1734568,
                            "$rowRate": "0.0868",
                            "$rowPercent": "9%",
                            "$rowPercent2": "8.68%",
                            "$value": 150478,
                            "$colSum": 382005,
                            "$colRate": "0.3939",
                            "$colPercent": "39%",
                            "$colPercent2": "39.39%"
                        },
                        {
                            "negative": 82342,
                            "negativeSOV": 0.35,
                            "form": "Total",
                            "name": "实例A",
                            "neutral": 81823,
                            "positive": 69973,
                            "type": "产品",
                            "subform": "儿童牛奶",
                            "positiveSOV": 0.3,
                            "buzz": 234138,
                            "talkingangle": "感觉",
                            "neutralSOV": 0.35,
                            "value": 234138,
                            "x": "感觉",
                            "$rowSum": 1734568,
                            "$rowRate": "0.135",
                            "$rowPercent": "13%",
                            "$rowPercent2": "13.5%",
                            "$value": 234138,
                            "$colSum": 561054,
                            "$colRate": "0.4173",
                            "$colPercent": "42%",
                            "$colPercent2": "41.73%"
                        },
                        {
                            "negative": 30276,
                            "negativeSOV": 0.28,
                            "form": "Total",
                            "name": "实例A",
                            "neutral": 26971,
                            "positive": 49572,
                            "type": "产品",
                            "subform": "儿童牛奶",
                            "positiveSOV": 0.46,
                            "buzz": 106819,
                            "talkingangle": "明星",
                            "neutralSOV": 0.25,
                            "value": 106819,
                            "x": "明星",
                            "$rowSum": 1734568,
                            "$rowRate": "0.0616",
                            "$rowPercent": "6%",
                            "$rowPercent2": "6.16%",
                            "$value": 106819,
                            "$colSum": 409682,
                            "$colRate": "0.2607",
                            "$colPercent": "26%",
                            "$colPercent2": "26.07%"
                        },
                        {
                            "negative": 63145,
                            "negativeSOV": 0.33,
                            "form": "Total",
                            "name": "实例A",
                            "neutral": 67835,
                            "positive": 58824,
                            "type": "产品",
                            "subform": "儿童牛奶",
                            "positiveSOV": 0.31,
                            "buzz": 189804,
                            "talkingangle": "材质",
                            "neutralSOV": 0.36,
                            "value": 189804,
                            "x": "材质",
                            "$rowSum": 1734568,
                            "$rowRate": "0.1094",
                            "$rowPercent": "11%",
                            "$rowPercent2": "10.94%",
                            "$value": 189804,
                            "$colSum": 416568,
                            "$colRate": "0.4556",
                            "$colPercent": "46%",
                            "$colPercent2": "45.56%"
                        },
                        {
                            "negative": 87234,
                            "negativeSOV": 0.33,
                            "form": "Total",
                            "name": "实例A",
                            "neutral": 94294,
                            "positive": 86452,
                            "type": "产品",
                            "subform": "儿童牛奶",
                            "positiveSOV": 0.32,
                            "buzz": 267980,
                            "talkingangle": "设计",
                            "neutralSOV": 0.35,
                            "value": 267980,
                            "x": "设计",
                            "$rowSum": 1734568,
                            "$rowRate": "0.1545",
                            "$rowPercent": "15%",
                            "$rowPercent2": "15.45%",
                            "$value": 267980,
                            "$colSum": 741766,
                            "$colRate": "0.3613",
                            "$colPercent": "36%",
                            "$colPercent2": "36.13%"
                        },
                        {
                            "negative": 24375,
                            "negativeSOV": 0.32,
                            "form": "Total",
                            "name": "实例A",
                            "neutral": 26663,
                            "positive": 24868,
                            "type": "产品",
                            "subform": "儿童牛奶",
                            "positiveSOV": 0.33,
                            "buzz": 75906,
                            "talkingangle": "送礼",
                            "neutralSOV": 0.35,
                            "value": 75906,
                            "x": "送礼",
                            "$rowSum": 1734568,
                            "$rowRate": "0.0438",
                            "$rowPercent": "4%",
                            "$rowPercent2": "4.38%",
                            "$value": 75906,
                            "$colSum": 282121,
                            "$colRate": "0.2691",
                            "$colPercent": "27%",
                            "$colPercent2": "26.91%"
                        }
                    ],
                    "itemStyle": {
                        "color": "#F39B44"
                    },
                    "lineStyle": {
                        "type": "solid",
                        "width": 2,
                        "color": "#F39B44"
                    },
                    "areaStyle": {
                        "color": "#F39B44",
                        "opacity": 0.5
                    }
                }
            ],
            "symbol": "circle",
            "symbolSize": 0,
            "tooltip": {}
        },
        {
            "type": "pie",
            "name": "colorfulAnglePie",
            "data": [{
                    "value": 1,
                    "name": "abc0",
                    "itemStyle": {
                        "color": "#F39B44"
                    }
                },
                {
                    "value": 1,
                    "name": "abc1",
                    "itemStyle": {
                        "color": "#71BCEA"
                    }
                },
                {
                    "value": 1,
                    "name": "abc2",
                    "itemStyle": {
                        "color": "#B7D200"
                    }
                },
                {
                    "value": 1,
                    "name": "abc3",
                    "itemStyle": {
                        "color": "#FFB46E"
                    }
                },
                {
                    "value": 1,
                    "name": "abc4",
                    "itemStyle": {
                        "color": "#FFEE99"
                    }
                },
                {
                    "value": 1,
                    "name": "abc5",
                    "itemStyle": {
                        "color": "#FFE048"
                    }
                },
                {
                    "value": 1,
                    "name": "abc6",
                    "itemStyle": {
                        "color": "#A5DF99"
                    }
                },
                {
                    "value": 1,
                    "name": "abc7",
                    "itemStyle": {
                        "color": "#65D64D"
                    }
                },
                {
                    "value": 1,
                    "name": "abc8",
                    "itemStyle": {
                        "color": "#80D2DC"
                    }
                },
                {
                    "value": 1,
                    "name": "abc9",
                    "itemStyle": {
                        "color": "#3CD1E3"
                    }
                },
                {
                    "value": 1,
                    "name": "abc10",
                    "itemStyle": {}
                },
                {
                    "value": 1,
                    "name": "abc11",
                    "itemStyle": {}
                }
            ],
            "z": -1,
            "startAngle": 105,
            "label": {
                "show": false
            },
            "hoverAnimation": false,
            "tooltip": {
                "show": false
            }
        }
    ],
    "radar": {
        "indicator": [{
                "name": "价格",
                "max": 395568.18000000005,
                "min": 0
            },
            {
                "name": "便捷",
                "max": 395568.18000000005,
                "min": 0
            },
            {
                "name": "健康",
                "max": 395568.18000000005,
                "min": 0
            },
            {
                "name": "口感",
                "max": 395568.18000000005,
                "min": 0
            },
            {
                "name": "品牌认知",
                "max": 395568.18000000005,
                "min": 0
            },
            {
                "name": "场合",
                "max": 395568.18000000005,
                "min": 0
            },
            {
                "name": "外观",
                "max": 395568.18000000005,
                "min": 0
            },
            {
                "name": "感觉",
                "max": 395568.18000000005,
                "min": 0
            },
            {
                "name": "明星",
                "max": 395568.18000000005,
                "min": 0
            },
            {
                "name": "材质",
                "max": 395568.18000000005,
                "min": 0
            },
            {
                "name": "设计",
                "max": 395568.18000000005,
                "min": 0
            },
            {
                "name": "送礼",
                "max": 395568.18000000005,
                "min": 0
            }
        ],
        "splitNumber": 3,
        "shape": "circle",
        "name": {
            "color": "#999"
        },
        "axisLine": {
            "lineStyle": {
                "color": "#fff"
            }
        },
        "splitLine": {
            "lineStyle": {
                "color": "#fff"
            }
        },
        "splitArea": {
            "areaStyle": {
                "color": [
                    "rgba(255, 255, 255, .5)",
                    "rgba(255, 255, 255, .7)",
                    "rgba(255, 255, 255, .85)"
                ]
            }
        }
    },
    "polar": {
        "radius": "75%",
        "show": false
    },
    "radiusAxis": {
        "min": 0,
        "max": 395568.18000000005,
        "show": false
    },
    "angleAxis": {
        "show": false,
        "type": "category",
        "data": [
            "价格",
            "便捷",
            "健康",
            "口感",
            "品牌认知",
            "场合",
            "外观",
            "感觉",
            "明星",
            "材质",
            "设计",
            "送礼"
        ],
        "startAngle": 75,
        "clockwise": false
    },
    //  与图例颜色反转 reverse
    "color": [
        "#F39B44",
        "#71BCEA",
        "#B7D200"
    ]
}