var nodes = [{
            "name": "上海米哈游网络科技股份",
        "category": 1
    }, {
        "name": "上海游族信息技术",
        "category": 1
    }, {
        "name": "苏州齐思妙想信息科技",
        "category": 1
    }, {
        "name": "上海数龙科技",
        "category": 1
    }, {
        "name": "芜湖乐时网络科技",
        "category": 1
    }, {
        "name": "玩心（上海）网络科技",
        "category": 1
    }, {
        "name": "上海寒诀网络科技",
        "category": 1
    }, {
        "name": "上海弘贯网络科技",
        "category": 1
    }, {
        "name": "上海鹰狮互娱科技",
        "category": 1
    }, {
        "name": "江苏易乐网络科技",
        "category": 1
    }, {
        "name": "骨迪（上海）网络科技",
        "category": 1
    }, {
        "name": "上海天赐之恒网络科技",
        "category": 1
    }, {
        "name": "上海鹰角网络科技",
        "category": 1
    }, {
        "name": "上海番糖网络科技",
        "category": 1
    }, {
        "name": "盛趣信息技术（上海）",
        "category": 1
    }, {
        "name": "上海红月网络科技",
        "category": 1
    }, {
        "name": "拾梦文化发展（上海）",
        "category": 1
    }, {
        "name": "上海布鲁潘达网络技术",
        "category": 1
    }, {
        "name": "杭州浩游科技",
        "category": 1
    }, {
        "name": "上海慕和网络科技",
        "category": 1
    }, {
        "name": "上海游唐网络技术",
        "category": 1
    }, {
        "name": "浙江九翎网络科技",
        "category": 1
    }, {
        "name": "上海悠星网络科技",
        "category": 1
    }, {
        "name": "上海散爆网络科技",
        "category": 1
    }, {
        "name": "杭州心光流美网络科技",
        "category": 1
    }, {
        "name": "杭州掌派科技",
        "category": 1
    }, {
        "name": "上海墨灿网络科技",
        "category": 1
    }, {
        "name": "上海骏梦网络科技",
        "category": 1
    }, {
        "name": "上海久游网络科技",
        "category": 1
    }, {
        "name": "上海铂漫网络科技",
        "category": 1
    }, {
        "name": "上海焦扬网络科技",
        "category": 1
    }, {
        "name": "哈游文化传媒（上海）",
        "category": 1
    }, {
        "name": "米哈游科技（上海）",
        "category": 1
    }, {
        "name": "上海吼美科技",
        "category": 1
    }, {
        "name": "上海米哈游天命科技",
        "category": 1
    }, {
        "name": "霍尔果斯圣芙蕾雅科技",
        "category": 1
    }, {
        "name": "上海交宅科技",
        "category": 1
    }, {
        "name": "上海羽渡尘科技",
        "category": 1
    }, {
        "name": "上海米哈游影铁科技",
        "category": 1
    }, {
        "name": "上海米哈游重装小兔科技",
        "category": 1
    }, {
        "name": "上海游豪信息技术",
        "category": 1
    }, {
        "name": "上海游家信息技术",
        "category": 1
    }, {
        "name": "上海游娱信息技术",
        "category": 1
    }, {
        "name": "南京游族信息技术",
        "category": 1
    }, {
        "name": "苏州游族信息技术",
        "category": 1
    }, {
        "name": "上海驰游信息技术",
        "category": 1
    }, {
        "name": "上海游族互娱网络科技",
        "category": 1
    }, {
        "name": "成都游族信息技术",
        "category": 1
    }, {
        "name": "上海游梅信息技术",
        "category": 1
    }, {
        "name": "上海游辰信息技术",
        "category": 1
    }, {
        "name": "重庆游族互娱网络科技",
        "category": 1
    }, {
        "name": "上海完游网络技术",
        "category": 1
    }, {
        "name": "上海猫游网络科技",
        "category": 1
    }, {
        "name": "北京嘉智游时投资中心（有限合伙）",
        "category": 1
    }, {
        "name": "上海鹿扬网络科技",
        "category": 1
    }, {
        "name": "北京厚德众合咨询中心（有限合伙）",
        "category": 1
    }, {
        "name": "苏州齐思妙想孵化器管理",
        "category": 1
    }, {
        "name": "深圳中科启明股权投资基金合伙企业（有限合伙）",
        "category": 1
    }, {
        "name": "天津盛景贸易",
        "category": 1
    }, {
        "name": "天津游吉科技",
        "category": 1
    }, {
        "name": "宁夏智捷付电子支付服务",
        "category": 1
    }, {
        "name": "盐城市盛境网络科技",
        "category": 1
    }, {
        "name": "宁夏数龙科技网络",
        "category": 1
    }, {
        "name": "上海盛页信息科技",
        "category": 1
    }, {
        "name": "喀什盛启信息科技",
        "category": 1
    }, {
        "name": "成都游吉科技",
        "category": 1
    }, {
        "name": "南京数龙计算机科技",
        "category": 1
    }, {
        "name": "上海灵游科技",
        "category": 1
    }, {
        "name": "上海宁乐科技",
        "category": 1
    }, {
        "name": "郑州聚凡网络技术",
        "category": 1
    }, {
        "name": "上海秋千软件科技",
        "category": 1
    }, {
        "name": "上海炽宇网络科技",
        "category": 1
    }, {
        "name": "上海盛多网络科技",
        "category": 1
    }, {
        "name": "北京众诚协作科技开发",
        "category": 1
    }, {
        "name": "上海维莱信息科技",
        "category": 1
    }, {
        "name": "成都锦天科技发展有限责任公司",
        "category": 1
    }, {
        "name": "成都星漫科技",
        "category": 1
    }, {
        "name": "成都锦龙科技",
        "category": 1
    }, {
        "name": "海南妙酷网络科技",
        "category": 1
    }, {
        "name": "杭州乐港科技",
        "category": 1
    }, {
        "name": "芜湖蟠龙网络科技",
        "category": 1
    }, {
        "name": "北京冠智信息技术",
        "category": 1
    }, {
        "name": "上海乌普斯文化创意",
        "category": 1
    }, {
        "name": "上海竹墨网络科技",
        "category": 1
    }, {
        "name": "上海寒跃影视文化",
        "category": 1
    }, {
        "name": "霍尔果斯弘贯网络科技",
        "category": 1
    }, {
        "name": "广州明动网游网络科技",
        "category": 1
    }, {
        "name": "广州易博网游网络科技",
        "category": 1
    }, {
        "name": "广州暄武网络科技",
        "category": 1
    }, {
        "name": "广州玖霄网游网络科技",
        "category": 1
    }, {
        "name": "海南暄武网络科技",
        "category": 1
    }, {
        "name": "海南创超网络科技",
        "category": 1
    }, {
        "name": "海南侠游网络科技",
        "category": 1
    }, {
        "name": "海南朱雀网络科技",
        "category": 1
    }, {
        "name": "海南明动网络科技",
        "category": 1
    }, {
        "name": "海南弘贯网络科技",
        "category": 1
    }, {
        "name": "海南爱萌网络科技",
        "category": 1
    }, {
        "name": "海南逗爱玩网络科技",
        "category": 1
    }, {
        "name": "海南虾投网络科技",
        "category": 1
    }, {
        "name": "海南有乾网络科技",
        "category": 1
    }, {
        "name": "海南鹿头网络科技",
        "category": 1
    }, {
        "name": "海南伐彩网络科技",
        "category": 1
    }, {
        "name": "广州创超网络科技",
        "category": 1
    }, {
        "name": "广州朱雀网络科技",
        "category": 1
    }, {
        "name": "上海连娱网络科技",
        "category": 1
    }, {
        "name": "北京星火互娱科技",
        "category": 1
    }, {
        "name": "镇江傲游网络科技",
        "category": 1
    }, {
        "name": "霍尔果斯飓风网络科技",
        "category": 1
    }, {
        "name": "上海业巧企业管理咨询",
        "category": 1
    }, {
        "name": "上海宜儒企业管理咨询",
        "category": 1
    }, {
        "name": "广州铭侠网络科技",
        "category": 1
    }, {
        "name": "镇江嘻游网络科技",
        "category": 1
    }, {
        "name": "镇江乐韵网络科技",
        "category": 1
    }, {
        "name": "北京文易电竞文化传媒",
        "category": 1
    }, {
        "name": "北京八爪鱼互娱科技",
        "category": 1
    }, {
        "name": "广州火凤网络科技",
        "category": 1
    }, {
        "name": "海南玩的溜网络科技",
        "category": 1
    }, {
        "name": "杭州西钺网络科技",
        "category": 1
    }, {
        "name": "上海至玩领域网络科技",
        "category": 1
    }, {
        "name": "上海构堂网络科技",
        "category": 1
    }, {
        "name": "杭州天巽网络科技",
        "category": 1
    }, {
        "name": "上海白神企业管理",
        "category": 1
    }, {
        "name": "上海木鸢网络科技",
        "category": 1
    }, {
        "name": "霍尔果斯鹰角网络科技",
        "category": 1
    }, {
        "name": "上海彼方网络科技",
        "category": 1
    }, {
        "name": "上海番果网络科技",
        "category": 1
    }, {
        "name": "上海鸿利数码科技",
        "category": 1
    }, {
        "name": "天津盛启信息技术",
        "category": 1
    }, {
        "name": "上海盛鹏信息技术",
        "category": 1
    }, {
        "name": "上海盛展网络科技",
        "category": 1
    }, {
        "name": "无锡盛趣知识产权运营中心",
        "category": 1
    }, {
        "name": "宜春盛趣信息技术",
        "category": 1
    }, {
        "name": "上饶县志存投资中心（有限合伙）",
        "category": 1
    }, {
        "name": "深圳盛众科技",
        "category": 1
    }, {
        "name": "上海摩凡网络科技",
        "category": 1
    }, {
        "name": "上海麦石信息技术",
        "category": 1
    }, {
        "name": "广州奥兹软件科技发展",
        "category": 1
    }, {
        "name": "深圳市悠游数码科技",
        "category": 1
    }, {
        "name": "上海时迈信息技术",
        "category": 1
    }, {
        "name": "北京达意之都文化传播",
        "category": 1
    }, {
        "name": "北京锋盛时代科技",
        "category": 1
    }, {
        "name": "上海因菲尼迪网络科技发展",
        "category": 1
    }, {
        "name": "上海大秦信息技术",
        "category": 1
    }, {
        "name": "石家庄海澜网络游戏开发有限责任公司",
        "category": 1
    }, {
        "name": "上海蓝田信息科技",
        "category": 1
    }, {
        "name": "霍尔果斯绯夜网络科技",
        "category": 1
    }, {
        "name": "上海雷笛网络科技",
        "category": 1
    }, {
        "name": "拾梦网络科技（海南）",
        "category": 1
    }, {
        "name": "拾萌文化发展（上海）",
        "category": 1
    }, {
        "name": "上海优富广告",
        "category": 1
    }, {
        "name": "嘉兴智敏软件科技",
        "category": 1
    }, {
        "name": "北京盛娱时代科技",
        "category": 1
    }, {
        "name": "上海慕明网络科技",
        "category": 1
    }, {
        "name": "上海行星网络科技",
        "category": 1
    }, {
        "name": "上海修真网络科技",
        "category": 1
    }, {
        "name": "上海科奂信息科技",
        "category": 1
    }, {
        "name": "绍兴九麦网络科技",
        "category": 1
    }, {
        "name": "浙江彩虹糖网络科技",
        "category": 1
    }, {
        "name": "绍兴鼎烽网络科技",
        "category": 1
    }, {
        "name": "上饶市千星网络科技",
        "category": 1
    }, {
        "name": "霍尔果斯悠星网络科技",
        "category": 1
    }, {
        "name": "海南冰魂网络科技",
        "category": 1
    }, {
        "name": "上海星枭网络科技",
        "category": 1
    }, {
        "name": "上海暗冬网络科技",
        "category": 1
    }, {
        "name": "霍尔果斯心梦流成网络科技",
        "category": 1
    }, {
        "name": "绍兴萌派网络",
        "category": 1
    }, {
        "name": "上海萝莉网络科技",
        "category": 1
    }, {
        "name": "上海墨灿网络科技深圳分公司",
        "category": 1
    }, {
        "name": "北京骏游互动网络科技",
        "category": 1
    }, {
        "name": "上海骏业网络科技",
        "category": 1
    }, {
        "name": "上海骏统网络科技",
        "category": 1
    }, {
        "name": "新疆骏梦网络科技",
        "category": 1
    }, {
        "name": "骏梦网络科技（平潭）",
        "category": 1
    }, {
        "name": "上海游碧信息科技",
        "category": 1
    }, {
        "name": "上海雷笋网络科技",
        "category": 1
    }, {
        "name": "苏州棋雅网络科技",
        "category": 1
    }, {
        "name": "深圳奎托斯网络科技",
        "category": 1
    }, {
        "name": "凌游网络科技（北京）",
        "category": 1
    }, {
        "name": "北京云际传媒信息技术",
        "category": 1
    }, {
        "name": "上海久刃网络科技",
        "category": 1
    }, {
        "name": "上海游仕网络科技",
        "category": 1
    }, {
        "name": "上海灵禅网络科技股份",
        "category": 1
    }, {
        "name": "北京观颐投资顾问",
        "category": 1
    }, {
        "name": "上海久翼网络科技",
        "category": 1
    }, {
        "name": "上海布布乐育信息科技",
        "category": 1
    }, {
        "name": "河北焦墨信息技术",
        "category": 1
    }, {
        "name": "上海哈购网络科技",
        "category": 1
    }, {
        "name": "上海超米广告",
        "category": 1
    }, {
        "name": "广州卓游信息科技",
        "category": 2
    }, {
        "name": "深圳市创梦天地科技",
        "category": 2
    }, {
        "name": "福建网龙计算机网络信息技术",
        "category": 2
    }, {
        "name": "广州库洛科技",
        "category": 2
    }, {
        "name": "广州盈正信息技术",
        "category": 2
    }, {
        "name": "深圳凯撒网络科技",
        "category": 2
    }, {
        "name": "深圳市创世互动科技",
        "category": 2
    }, {
        "name": "深圳欣欣互动科技",
        "category": 2
    }, {
        "name": "广州明朝互动科技股份",
        "category": 2
    }, {
        "name": "广州诗悦网络科技",
        "category": 2
    }, {
        "name": "广州银汉科技",
        "category": 2
    }, {
        "name": "海南盛游信息科技",
        "category": 2
    }, {
        "name": "上海掌致信息科技",
        "category": 2
    }, {
        "name": "广州位面信息科技",
        "category": 2
    }, {
        "name": "深圳战艺网络科技",
        "category": 2
    }, {
        "name": "广州麟游信息科技",
        "category": 2
    }, {
        "name": "深圳市奥术信息科技",
        "category": 2
    }, {
        "name": "广州雷神信息科技",
        "category": 2
    }, {
        "name": "珠海市汇垠广奥股权投资基金管理",
        "category": 2
    }, {
        "name": "创梦无限（北京）信息技术",
        "category": 2
    }, {
        "name": "深圳市晨海之星科技",
        "category": 2
    }, {
        "name": "海南创梦天地科技",
        "category": 2
    }, {
        "name": "深圳市创享梦聚科技",
        "category": 2
    }, {
        "name": "湖南省崀山创梦天地文化传播",
        "category": 2
    }, {
        "name": "霍尔果斯创梦天地信息科技",
        "category": 2
    }, {
        "name": "深圳市未完待续科技",
        "category": 2
    }, {
        "name": "深圳市前海聚正投资管理",
        "category": 2
    }, {
        "name": "深圳市创梦互娱科技",
        "category": 2
    }, {
        "name": "深圳市梦作坊科技",
        "category": 2
    }, {
        "name": "深圳市创梦天地娱乐",
        "category": 2
    }, {
        "name": "广州提子网络科技",
        "category": 2
    }, {
        "name": "安徽思创体育发展",
        "category": 2
    }, {
        "name": "深圳市前海益启信元投资中心（有限合伙）",
        "category": 2
    }, {
        "name": "必盈图广告（上海）",
        "category": 2
    }, {
        "name": "北京微播科技发展",
        "category": 2
    }, {
        "name": "北京创联时讯信息科技",
        "category": 2
    }, {
        "name": "珠海君武投资管理合伙企业（有限合伙）",
        "category": 2
    }, {
        "name": "深圳市卓游科技",
        "category": 2
    }, {
        "name": "上海盛戏网络科技",
        "category": 2
    }, {
        "name": "福州天诺网络科技",
        "category": 2
    }, {
        "name": "福州天景网络科技",
        "category": 2
    }, {
        "name": "福州天人网络信息技术服务",
        "category": 2
    }, {
        "name": "福州畅裕网络科技",
        "category": 2
    }, {
        "name": "福建网龙艺术传播",
        "category": 2
    }, {
        "name": "福建天音文化传媒",
        "category": 2
    }, {
        "name": "福建省天晴互动娱乐",
        "category": 2
    }, {
        "name": "福建省华渔教育科技",
        "category": 2
    }, {
        "name": "福建天渔教育科技",
        "category": 2
    }, {
        "name": "福建天越现代教育发展",
        "category": 2
    }, {
        "name": "福州天时网络科技",
        "category": 2
    }, {
        "name": "海南天趣娱乐",
        "category": 2
    }, {
        "name": "上海天坤数码科技",
        "category": 2
    }, {
        "name": "厦门天盼网络科技",
        "category": 2
    }, {
        "name": "北京网中软件科技",
        "category": 2
    }, {
        "name": "福建省网云虚拟现实技术发展",
        "category": 2
    }, {
        "name": "福建天渺网络科技",
        "category": 2
    }, {
        "name": "福建省国腾信息科技",
        "category": 2
    }, {
        "name": "昆明网龙华渔科技发展",
        "category": 2
    }, {
        "name": "成都掌沃无限科技",
        "category": 2
    }, {
        "name": "广州库洛姆科技",
        "category": 2
    }, {
        "name": "广州市巧智数码科技",
        "category": 2
    }, {
        "name": "北京天雨网络科技",
        "category": 2
    }, {
        "name": "伊犁讯娱网络科技",
        "category": 2
    }, {
        "name": "四川天上友嘉网络科技",
        "category": 2
    }, {
        "name": "深圳前海凯撒文化",
        "category": 2
    }, {
        "name": "杭州幻文科技",
        "category": 2
    }, {
        "name": "霍尔果斯万家游戏信息科技",
        "category": 2
    }, {
        "name": "深圳市神话互娱科技",
        "category": 2
    }, {
        "name": "霍尔果斯神话互娱科技",
        "category": 2
    }, {
        "name": "深圳方圆互娱科技",
        "category": 2
    }, {
        "name": "广州梦次元信息科技",
        "category": 2
    }, {
        "name": "上海其趣网络科技",
        "category": 2
    }, {
        "name": "上海轻量网络科技",
        "category": 2
    }, {
        "name": "上海萌彩网络科技",
        "category": 2
    }, {
        "name": "珠海诗悦网络科技",
        "category": 2
    }, {
        "name": "海南诗悦网络科技",
        "category": 2
    }, {
        "name": "海南诚悦网络科技",
        "category": 2
    }, {
        "name": "海南晴空网络科技",
        "category": 2
    }, {
        "name": "海南欢悦网络科技",
        "category": 2
    }, {
        "name": "福州星环互动网络",
        "category": 2
    }, {
        "name": "银汉互娱（天津）科技",
        "category": 2
    }, {
        "name": "广州泳泳信息科技",
        "category": 2
    }, {
        "name": "霍尔果斯市银汉股权投资",
        "category": 2
    }, {
        "name": "海南银汉科技",
        "category": 2
    }, {
        "name": "霍尔果斯前见股权投资",
        "category": 2
    }, {
        "name": "深圳银创互娱科技",
        "category": 2
    }, {
        "name": "上海廿迷网络科技",
        "category": 2
    }, {
        "name": "广州果橙缤纷网络科技合伙企业（有限合伙）",
        "category": 2
    }, {
        "name": "广州飞雨网络科技",
        "category": 2
    }, {
        "name": "广州金楚信息技术",
        "category": 2
    }, {
        "name": "深圳市律动信息科技",
        "category": 2
    }, {
        "name": "广州子苏科技",
        "category": 2
    }, {
        "name": "上海侠娱网络科技",
        "category": 2
    }, {
        "name": "广州帝释天软件",
        "category": 2
    }, {
        "name": "广州市游毅坊网络科技",
        "category": 2
    }, {
        "name": "北京可为互娱文化科技",
        "category": 2
    }, {
        "name": "北京龙拳风暴科技",
        "category": 3
    }, {
        "name": "乐元素科技（北京）股份",
        "category": 3
    }, {
        "name": "百度移信网络技术（北京）",
        "category": 3
    }, {
        "name": "北京太能沃可网络科技股份",
        "category": 3
    }, {
        "name": "北京蓝鲸时代科技",
        "category": 3
    }, {
        "name": "蓝港在线（北京）科技",
        "category": 3
    }, {
        "name": "北京巴别时代科技股份",
        "category": 3
    }, {
        "name": "北京灵游坊网络科技",
        "category": 3
    }, {
        "name": "中手游移动科技",
        "category": 3
    }, {
        "name": "北京天马时空网络技术",
        "category": 3
    }, {
        "name": "必果互娱（北京）科技",
        "category": 3
    }, {
        "name": "北京大神圈文化科技",
        "category": 3
    }, {
        "name": "乐道互动（天津）科技",
        "category": 3
    }, {
        "name": "成都西山居互动娱乐科技",
        "category": 3
    }, {
        "name": "北京微笑科技",
        "category": 3
    }, {
        "name": "北京水琴铃信息技术",
        "category": 3
    }, {
        "name": "霍尔果斯龙拳网络科技",
        "category": 3
    }, {
        "name": "苏州工业园区龙拳风暴信息科技",
        "category": 3
    }, {
        "name": "天津龙拳风暴科技",
        "category": 3
    }, {
        "name": "天津乐浣科技发展有限责任公司",
        "category": 3
    }, {
        "name": "上海乐擎投资管理",
        "category": 3
    }, {
        "name": "天津乐爱豆科技发展有限责任公司",
        "category": 3
    }, {
        "name": "北京乐元素文化发展",
        "category": 3
    }, {
        "name": "北京创智汇聚科技",
        "category": 3
    }, {
        "name": "上海乐梨科技",
        "category": 3
    }, {
        "name": "元素创造（深圳）网络科技",
        "category": 3
    }, {
        "name": "北京零壹元素网络科技",
        "category": 3
    }, {
        "name": "北京丹晟投资基金中心（有限合伙）",
        "category": 3
    }, {
        "name": "上海绘界文化传播",
        "category": 3
    }, {
        "name": "北京百度移讯科技",
        "category": 3
    }, {
        "name": "北京百度多酷科技",
        "category": 3
    }, {
        "name": "天津多酷紫桐科技",
        "category": 3
    }, {
        "name": "海南多酷信息技术",
        "category": 3
    }, {
        "name": "自然光影（北京）图像科技",
        "category": 3
    }, {
        "name": "霍尔果斯闪电网络科技",
        "category": 3
    }, {
        "name": "苏州太能沃可网络科技",
        "category": 3
    }, {
        "name": "宁波梅山保税港区陶朱安达投资管理中心（有限合伙）",
        "category": 3
    }, {
        "name": "喀什蓝鲸时代网络科技",
        "category": 3
    }, {
        "name": "南京翊瑅网络科技",
        "category": 3
    }, {
        "name": "蓝港星云（北京）科技",
        "category": 3
    }, {
        "name": "手游通（北京）科技",
        "category": 3
    }, {
        "name": "北京蓝虎鲸科技",
        "category": 3
    }, {
        "name": "北京趣味指间网络科技",
        "category": 3
    }, {
        "name": "北京智讯天通信息技术",
        "category": 3
    }, {
        "name": "多边形（北京）科技",
        "category": 3
    }, {
        "name": "北京三栖人科技",
        "category": 3
    }, {
        "name": "天津八八六四网络技术",
        "category": 3
    }, {
        "name": "北京峰与隆互动文化",
        "category": 3
    }, {
        "name": "蓝港影业（天津）",
        "category": 3
    }, {
        "name": "多边形（海南）网络科技",
        "category": 3
    }, {
        "name": "珠海蓝港在线科技",
        "category": 3
    }, {
        "name": "霍尔果斯蓝港影业",
        "category": 3
    }, {
        "name": "星满天（海南）影视",
        "category": 3
    }, {
        "name": "北京古德时代科技",
        "category": 3
    }, {
        "name": "蓝港思必特（北京）科技",
        "category": 3
    }, {
        "name": "广州鸿娱网络科技",
        "category": 3
    }, {
        "name": "海南天辰网络科技",
        "category": 3
    }, {
        "name": "武汉极客猿教育科技",
        "category": 3
    }, {
        "name": "北京创享天下网络科技",
        "category": 3
    }, {
        "name": "苏州湖图网络科技",
        "category": 3
    }, {
        "name": "海南巴别时代科技",
        "category": 3
    }, {
        "name": "上海履冰科技",
        "category": 3
    }, {
        "name": "北京量子维度科技",
        "category": 3
    }, {
        "name": "中广娱文传媒",
        "category": 3
    }, {
        "name": "厦门优莱柏网络科技",
        "category": 3
    }, {
        "name": "北京灵游坊软件技术",
        "category": 3
    }, {
        "name": "海南灵游坊网络科技",
        "category": 3
    }, {
        "name": "北京灵动时光科技",
        "category": 3
    }, {
        "name": "北京灵徒文化传媒",
        "category": 3
    }, {
        "name": "北京酷者网络科技",
        "category": 3
    }, {
        "name": "深圳市岚悦网络科技",
        "category": 3
    }, {
        "name": "霍尔果斯中手游创业投资",
        "category": 3
    }, {
        "name": "宜春天成网络科技",
        "category": 3
    }, {
        "name": "北京天际启游科技",
        "category": 3
    }, {
        "name": "上海天銮网络技术",
        "category": 3
    }, {
        "name": "上海扎古网络科技",
        "category": 3
    }, {
        "name": "广州战法牧网络科技",
        "category": 3
    }, {
        "name": "北京必果互动网络技术",
        "category": 3
    }, {
        "name": "广州御和必果网络科技",
        "category": 3
    }, {
        "name": "北京大神圈影视文化",
        "category": 3
    }, {
        "name": "霍尔果斯大神圈影视传媒",
        "category": 3
    }, {
        "name": "上海大神圈影视文化",
        "category": 3
    }, {
        "name": "乐道互动（天津）软件技术",
        "category": 3
    }, {
        "name": "乐道互动（广东）科技",
        "category": 3
    }, {
        "name": "乐道互动（上海）软件技术",
        "category": 3
    }, {
        "name": "淮安德润网络科技",
        "category": 3
    }, {
        "name": "淮安易趣网络科技",
        "category": 3
    }, {
        "name": "乐道互动（北京）科技",
        "category": 3
    }, {
        "name": "上海游曳网络科技",
        "category": 3
    }, {
        "name": "大连金山互动娱乐科技",
        "category": 3
    }, {
        "name": "珠海金山网络游戏科技",
        "category": 3
    }, {
        "name": "北京西山居互动娱乐科技",
        "category": 3
    }, {
        "name": "广州西山居世游网络科技",
        "category": 3
    }, {
        "name": "珠海西山居移动游戏科技",
        "category": 3
    }, {
        "name": "珠海西山居互动娱乐科技",
        "category": 3
    }, {
        "name": "成都浣沙文化传媒",
        "category": 3
    }, {
        "name": "武汉西腾科技",
        "category": 3
    }, {
        "name": "成都可萌世界网络科技",
        "category": 3
    }, {
        "name": "珠海剑心互动娱乐",
        "category": 3
    }, {
        "name": "西山居多盈（北京）科技",
        "category": 3
    }, {
        "name": "上海越群网络科技",
        "category": 3
    }, {
        "name": "上海光爪网络科技",
        "category": 3
    }, {
        "name": "深圳绿碧时代网络",
        "category": 3
    }, {
        "name": "北京双米互动信息技术",
        "category": 3
    }, {
        "name": "珠海乐趣科技",
        "category": 3
    }, {
        "name": "深圳市趣上科技",
        "category": 3
    }, {
        "name": "深圳市霜刃科技",
        "category": 3
    }, {
        "name": "神游互动科技（深圳）",
        "category": 3
    }, {
        "name": "北京漫考拉文化传媒",
        "category": 3
    }, {
        "name": "厦门趣合怡科技",
        "category": 3
    }, {
        "name": "北京远鸣网络科技",
        "category": 3
    }, {
        "name": "成都龙渊网络科技",
        "category": 3
    }, {
        "name": "成都五维互娱科技",
        "category": 3
    }, {
        "name": "北京奇艺世纪科技",
        "category": 3
    }, {
        "name": "成都萤火虫信息技术",
        "category": 3
    }, {
        "name": "成都龙渊盛世科技",
        "category": 3
    }, {
        "name": "成都龙渊奇迹网络科技",
        "category": 3
    }, {
        "name": "成都蒙斯克网络科技",
        "category": 3
    }, {
        "name": "上海簇鹰网络科技",
        "category": 3
    }, {
        "name": "成都龙渊传奇网络科技",
        "category": 3
    }, {
        "name": "北京龙五网络科技",
        "category": 3
    }, {
        "name": "成都凯利丹网络科技",
        "category": 3
    }, {
        "name": "绵阳龙渊网络科技",
        "category": 3
    }, {
        "name": "成都词牌社文化传播",
        "category": 3
    }, {
        "name": "成都游理想科技",
        "category": 3
    }, {
        "name": "成都龙腾云卷网络科技",
        "category": 3
    }, {
        "name": "成都蛋卷科技",
        "category": 3
    }, {
        "name": "成都映霸龙渊文化传播",
        "category": 3
    }, {
        "name": "北京亿虎乐游网络科技",
        "category": 3
    }, {
        "name": "北京漫动科技",
        "category": 3
    }, {
        "name": "北京简娱科技",
        "category": 3
    }, {
        "name": "深圳市四楼无限科技",
        "category": 3
    }, {
        "name": "成都任客科技",
        "category": 3
    }, {
        "name": "成都牵手汇科技有限责任公司",
        "category": 3
    }, {
        "name": "上海爱奇艺互娱科技",
        "category": 3
    }, {
        "name": "北京国址地信息咨询有限责任公司",
        "category": 3
    }, {
        "name": "喀什乐线信息技术",
        "category": 3
    }, {
        "name": "霍尔果斯萤火虫信息技术",
        "category": 3
    }, {
        "name": "成都战魂信息技术",
        "category": 3
    }, {
        "name": "成都云奇信息技术",
        "category": 3
    }, {
        "name": "成都八九七文化传播",
        "category": 3
}];

var links = [{
        "source": "上海米哈游网络科技股份",
        "target": "哈游文化传媒（上海）",
        "name": "投资"
    }, {
        "source": "上海米哈游网络科技股份",
        "target": "米哈游科技（上海）",
        "name": "投资"
    }, {
        "source": "上海米哈游网络科技股份",
        "target": "上海吼美科技",
        "name": "投资"
    }, {
        "source": "上海米哈游网络科技股份",
        "target": "上海米哈游天命科技",
        "name": "投资"
    }, {
        "source": "上海米哈游网络科技股份",
        "target": "霍尔果斯圣芙蕾雅科技",
        "name": "投资"
    }, {
        "source": "上海米哈游网络科技股份",
        "target": "上海交宅科技",
        "name": "投资"
    }, {
        "source": "上海米哈游网络科技股份",
        "target": "上海羽渡尘科技",
        "name": "投资"
    }, {
        "source": "上海米哈游网络科技股份",
        "target": "上海米哈游影铁科技",
        "name": "投资"
    }, {
        "source": "上海米哈游网络科技股份",
        "target": "上海米哈游重装小兔科技",
        "name": "投资"
    }, {
        "source": "上海游族信息技术",
        "target": "上海游豪信息技术",
        "name": "投资"
    }, {
        "source": "上海游族信息技术",
        "target": "上海游家信息技术",
        "name": "投资"
    }, {
        "source": "上海游族信息技术",
        "target": "上海游娱信息技术",
        "name": "投资"
    }, {
        "source": "上海游族信息技术",
        "target": "南京游族信息技术",
        "name": "投资"
    }, {
        "source": "上海游族信息技术",
        "target": "苏州游族信息技术",
        "name": "投资"
    }, {
        "source": "上海游族信息技术",
        "target": "上海驰游信息技术",
        "name": "投资"
    }, {
        "source": "上海游族信息技术",
        "target": "上海游族互娱网络科技",
        "name": "投资"
    }, {
        "source": "上海游族信息技术",
        "target": "成都游族信息技术",
        "name": "投资"
    }, {
        "source": "上海游族信息技术",
        "target": "上海游梅信息技术",
        "name": "投资"
    }, {
        "source": "上海游族信息技术",
        "target": "上海游辰信息技术",
        "name": "投资"
    }, {
        "source": "上海游族信息技术",
        "target": "重庆游族互娱网络科技",
        "name": "投资"
    }, {
        "source": "上海游族信息技术",
        "target": "上海完游网络技术",
        "name": "投资"
    }, {
        "source": "上海游族信息技术",
        "target": "上海猫游网络科技",
        "name": "投资"
    }, {
        "source": "上海游族信息技术",
        "target": "北京嘉智游时投资中心（有限合伙）",
        "name": "投资"
    }, {
        "source": "上海游族信息技术",
        "target": "上海鹿扬网络科技",
        "name": "投资"
    }, {
        "source": "上海游族信息技术",
        "target": "北京厚德众合咨询中心（有限合伙）",
        "name": "投资"
    }, {
        "source": "苏州齐思妙想信息科技",
        "target": "苏州齐思妙想孵化器管理",
        "name": "投资"
    }, {
        "source": "苏州齐思妙想信息科技",
        "target": "深圳中科启明股权投资基金合伙企业（有限合伙）",
        "name": "投资"
    }, {
        "source": "上海数龙科技",
        "target": "天津盛景贸易",
        "name": "投资"
    }, {
        "source": "上海数龙科技",
        "target": "天津游吉科技",
        "name": "投资"
    }, {
        "source": "上海数龙科技",
        "target": "宁夏智捷付电子支付服务",
        "name": "投资"
    }, {
        "source": "上海数龙科技",
        "target": "盐城市盛境网络科技",
        "name": "投资"
    }, {
        "source": "上海数龙科技",
        "target": "宁夏数龙科技网络",
        "name": "投资"
    }, {
        "source": "上海数龙科技",
        "target": "上海盛页信息科技",
        "name": "投资"
    }, {
        "source": "上海数龙科技",
        "target": "喀什盛启信息科技",
        "name": "投资"
    }, {
        "source": "上海数龙科技",
        "target": "成都游吉科技",
        "name": "投资"
    }, {
        "source": "上海数龙科技",
        "target": "南京数龙计算机科技",
        "name": "投资"
    }, {
        "source": "上海数龙科技",
        "target": "上海灵游科技",
        "name": "投资"
    }, {
        "source": "上海数龙科技",
        "target": "上海宁乐科技",
        "name": "投资"
    }, {
        "source": "上海数龙科技",
        "target": "郑州聚凡网络技术",
        "name": "投资"
    }, {
        "source": "上海数龙科技",
        "target": "上海秋千软件科技",
        "name": "投资"
    }, {
        "source": "上海数龙科技",
        "target": "上海炽宇网络科技",
        "name": "投资"
    }, {
        "source": "上海数龙科技",
        "target": "上海盛多网络科技",
        "name": "投资"
    }, {
        "source": "上海数龙科技",
        "target": "北京众诚协作科技开发",
        "name": "投资"
    }, {
        "source": "上海数龙科技",
        "target": "上海维莱信息科技",
        "name": "投资"
    }, {
        "source": "上海数龙科技",
        "target": "成都锦天科技发展有限责任公司",
        "name": "投资"
    }, {
        "source": "上海数龙科技",
        "target": "成都星漫科技",
        "name": "投资"
    }, {
        "source": "上海数龙科技",
        "target": "成都锦龙科技",
        "name": "投资"
    }, {
        "source": "芜湖乐时网络科技",
        "target": "海南妙酷网络科技",
        "name": "投资"
    }, {
        "source": "芜湖乐时网络科技",
        "target": "杭州乐港科技",
        "name": "投资"
    }, {
        "source": "芜湖乐时网络科技",
        "target": "芜湖蟠龙网络科技",
        "name": "投资"
    }, {
        "source": "玩心（上海）网络科技",
        "target": "北京冠智信息技术",
        "name": "投资"
    }, {
        "source": "上海寒诀网络科技",
        "target": "上海乌普斯文化创意",
        "name": "投资"
    }, {
        "source": "上海寒诀网络科技",
        "target": "上海竹墨网络科技",
        "name": "投资"
    }, {
        "source": "上海寒诀网络科技",
        "target": "上海寒跃影视文化",
        "name": "投资"
    }, {
        "source": "上海弘贯网络科技",
        "target": "霍尔果斯弘贯网络科技",
        "name": "投资"
    }, {
        "source": "上海弘贯网络科技",
        "target": "广州明动网游网络科技",
        "name": "投资"
    }, {
        "source": "上海弘贯网络科技",
        "target": "广州易博网游网络科技",
        "name": "投资"
    }, {
        "source": "上海弘贯网络科技",
        "target": "广州暄武网络科技",
        "name": "投资"
    }, {
        "source": "上海弘贯网络科技",
        "target": "广州玖霄网游网络科技",
        "name": "投资"
    }, {
        "source": "上海弘贯网络科技",
        "target": "海南暄武网络科技",
        "name": "投资"
    }, {
        "source": "上海弘贯网络科技",
        "target": "海南创超网络科技",
        "name": "投资"
    }, {
        "source": "上海弘贯网络科技",
        "target": "海南侠游网络科技",
        "name": "投资"
    }, {
        "source": "上海弘贯网络科技",
        "target": "海南朱雀网络科技",
        "name": "投资"
    }, {
        "source": "上海弘贯网络科技",
        "target": "海南明动网络科技",
        "name": "投资"
    }, {
        "source": "上海弘贯网络科技",
        "target": "海南弘贯网络科技",
        "name": "投资"
    }, {
        "source": "上海弘贯网络科技",
        "target": "海南爱萌网络科技",
        "name": "投资"
    }, {
        "source": "上海弘贯网络科技",
        "target": "海南逗爱玩网络科技",
        "name": "投资"
    }, {
        "source": "上海弘贯网络科技",
        "target": "海南虾投网络科技",
        "name": "投资"
    }, {
        "source": "上海弘贯网络科技",
        "target": "海南有乾网络科技",
        "name": "投资"
    }, {
        "source": "上海弘贯网络科技",
        "target": "海南鹿头网络科技",
        "name": "投资"
    }, {
        "source": "上海弘贯网络科技",
        "target": "海南伐彩网络科技",
        "name": "投资"
    }, {
        "source": "上海弘贯网络科技",
        "target": "广州创超网络科技",
        "name": "投资"
    }, {
        "source": "上海弘贯网络科技",
        "target": "广州朱雀网络科技",
        "name": "投资"
    }, {
        "source": "上海鹰狮互娱科技",
        "target": "上海连娱网络科技",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "北京星火互娱科技",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "镇江傲游网络科技",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "霍尔果斯飓风网络科技",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "上海业巧企业管理咨询",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "上海宜儒企业管理咨询",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "广州铭侠网络科技",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "镇江嘻游网络科技",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "镇江乐韵网络科技",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "北京文易电竞文化传媒",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "北京八爪鱼互娱科技",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "广州火凤网络科技",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "海南玩的溜网络科技",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "杭州西钺网络科技",
        "name": "投资"
    }, {
        "source": "骨迪（上海）网络科技",
        "target": "上海至玩领域网络科技",
        "name": "投资"
    }, {
        "source": "骨迪（上海）网络科技",
        "target": "上海构堂网络科技",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "北京星火互娱科技",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "镇江傲游网络科技",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "霍尔果斯飓风网络科技",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "上海业巧企业管理咨询",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "上海宜儒企业管理咨询",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "广州铭侠网络科技",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "镇江嘻游网络科技",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "镇江乐韵网络科技",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "北京文易电竞文化传媒",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "北京八爪鱼互娱科技",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "广州火凤网络科技",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "海南玩的溜网络科技",
        "name": "投资"
    }, {
        "source": "江苏易乐网络科技",
        "target": "杭州西钺网络科技",
        "name": "投资"
    }, {
        "source": "上海天赐之恒网络科技",
        "target": "杭州天巽网络科技",
        "name": "投资"
    }, {
        "source": "上海鹰角网络科技",
        "target": "上海白神企业管理",
        "name": "投资"
    }, {
        "source": "上海鹰角网络科技",
        "target": "上海木鸢网络科技",
        "name": "投资"
    }, {
        "source": "上海鹰角网络科技",
        "target": "霍尔果斯鹰角网络科技",
        "name": "投资"
    }, {
        "source": "上海鹰角网络科技",
        "target": "上海悠星网络科技",
        "name": "投资"
    }, {
        "source": "上海鹰角网络科技",
        "target": "上海彼方网络科技",
        "name": "投资"
    }, {
        "source": "上海番糖网络科技",
        "target": "上海番果网络科技",
        "name": "投资"
    }, {
        "source": "盛趣信息技术（上海）",
        "target": "上海数龙科技",
        "name": "投资"
    }, {
        "source": "盛趣信息技术（上海）",
        "target": "上海鸿利数码科技",
        "name": "投资"
    }, {
        "source": "盛趣信息技术（上海）",
        "target": "天津盛启信息技术",
        "name": "投资"
    }, {
        "source": "盛趣信息技术（上海）",
        "target": "上海盛鹏信息技术",
        "name": "投资"
    }, {
        "source": "盛趣信息技术（上海）",
        "target": "上海盛展网络科技",
        "name": "投资"
    }, {
        "source": "盛趣信息技术（上海）",
        "target": "无锡盛趣知识产权运营中心",
        "name": "投资"
    }, {
        "source": "盛趣信息技术（上海）",
        "target": "宜春盛趣信息技术",
        "name": "投资"
    }, {
        "source": "盛趣信息技术（上海）",
        "target": "上饶县志存投资中心（有限合伙）",
        "name": "投资"
    }, {
        "source": "盛趣信息技术（上海）",
        "target": "深圳盛众科技",
        "name": "投资"
    }, {
        "source": "盛趣信息技术（上海）",
        "target": "上海摩凡网络科技",
        "name": "投资"
    }, {
        "source": "盛趣信息技术（上海）",
        "target": "上海麦石信息技术",
        "name": "投资"
    }, {
        "source": "盛趣信息技术（上海）",
        "target": "广州奥兹软件科技发展",
        "name": "投资"
    }, {
        "source": "盛趣信息技术（上海）",
        "target": "深圳市悠游数码科技",
        "name": "投资"
    }, {
        "source": "盛趣信息技术（上海）",
        "target": "上海时迈信息技术",
        "name": "投资"
    }, {
        "source": "盛趣信息技术（上海）",
        "target": "北京达意之都文化传播",
        "name": "投资"
    }, {
        "source": "盛趣信息技术（上海）",
        "target": "北京锋盛时代科技",
        "name": "投资"
    }, {
        "source": "盛趣信息技术（上海）",
        "target": "上海因菲尼迪网络科技发展",
        "name": "投资"
    }, {
        "source": "盛趣信息技术（上海）",
        "target": "上海大秦信息技术",
        "name": "投资"
    }, {
        "source": "盛趣信息技术（上海）",
        "target": "石家庄海澜网络游戏开发有限责任公司",
        "name": "投资"
    }, {
        "source": "盛趣信息技术（上海）",
        "target": "上海蓝田信息科技",
        "name": "投资"
    }, {
        "source": "上海红月网络科技",
        "target": "霍尔果斯绯夜网络科技",
        "name": "投资"
    }, {
        "source": "上海红月网络科技",
        "target": "上海雷笛网络科技",
        "name": "投资"
    }, {
        "source": "拾梦文化发展（上海）",
        "target": "拾梦网络科技（海南）",
        "name": "投资"
    }, {
        "source": "拾梦文化发展（上海）",
        "target": "拾萌文化发展（上海）",
        "name": "投资"
    }, {
        "source": "上海布鲁潘达网络技术",
        "target": "上海优富广告",
        "name": "投资"
    }, {
        "source": "杭州浩游科技",
        "target": "嘉兴智敏软件科技",
        "name": "投资"
    }, {
        "source": "上海慕和网络科技",
        "target": "北京盛娱时代科技",
        "name": "投资"
    }, {
        "source": "上海慕和网络科技",
        "target": "上海慕明网络科技",
        "name": "投资"
    }, {
        "source": "上海慕和网络科技",
        "target": "上海行星网络科技",
        "name": "投资"
    }, {
        "source": "上海慕和网络科技",
        "target": "上海修真网络科技",
        "name": "投资"
    }, {
        "source": "上海游唐网络技术",
        "target": "上海科奂信息科技",
        "name": "投资"
    }, {
        "source": "浙江九翎网络科技",
        "target": "绍兴九麦网络科技",
        "name": "投资"
    }, {
        "source": "浙江九翎网络科技",
        "target": "浙江彩虹糖网络科技",
        "name": "投资"
    }, {
        "source": "浙江九翎网络科技",
        "target": "绍兴鼎烽网络科技",
        "name": "投资"
    }, {
        "source": "浙江九翎网络科技",
        "target": "上饶市千星网络科技",
        "name": "投资"
    }, {
        "source": "上海悠星网络科技",
        "target": "霍尔果斯悠星网络科技",
        "name": "投资"
    }, {
        "source": "上海悠星网络科技",
        "target": "海南冰魂网络科技",
        "name": "投资"
    }, {
        "source": "上海悠星网络科技",
        "target": "上海鹰角网络科技",
        "name": "投资"
    }, {
        "source": "上海悠星网络科技",
        "target": "上海星枭网络科技",
        "name": "投资"
    }, {
        "source": "上海散爆网络科技",
        "target": "上海暗冬网络科技",
        "name": "投资"
    }, {
        "source": "杭州心光流美网络科技",
        "target": "霍尔果斯心梦流成网络科技",
        "name": "投资"
    }, {
        "source": "杭州掌派科技",
        "target": "绍兴萌派网络",
        "name": "投资"
    }, {
        "source": "杭州掌派科技",
        "target": "上海萝莉网络科技",
        "name": "投资"
    }, {
        "source": "上海墨灿网络科技",
        "target": "上海墨灿网络科技深圳分公司",
        "name": "投资"
    }, {
        "source": "上海骏梦网络科技",
        "target": "北京骏游互动网络科技",
        "name": "投资"
    }, {
        "source": "上海骏梦网络科技",
        "target": "上海骏业网络科技",
        "name": "投资"
    }, {
        "source": "上海骏梦网络科技",
        "target": "上海骏统网络科技",
        "name": "投资"
    }, {
        "source": "上海骏梦网络科技",
        "target": "新疆骏梦网络科技",
        "name": "投资"
    }, {
        "source": "上海骏梦网络科技",
        "target": "骏梦网络科技（平潭）",
        "name": "投资"
    }, {
        "source": "上海骏梦网络科技",
        "target": "上海游碧信息科技",
        "name": "投资"
    }, {
        "source": "上海久游网络科技",
        "target": "上海雷笋网络科技",
        "name": "投资"
    }, {
        "source": "上海久游网络科技",
        "target": "苏州棋雅网络科技",
        "name": "投资"
    }, {
        "source": "上海久游网络科技",
        "target": "深圳奎托斯网络科技",
        "name": "投资"
    }, {
        "source": "上海久游网络科技",
        "target": "凌游网络科技（北京）",
        "name": "投资"
    }, {
        "source": "上海久游网络科技",
        "target": "北京云际传媒信息技术",
        "name": "投资"
    }, {
        "source": "上海久游网络科技",
        "target": "上海久刃网络科技",
        "name": "投资"
    }, {
        "source": "上海久游网络科技",
        "target": "上海游仕网络科技",
        "name": "投资"
    }, {
        "source": "上海久游网络科技",
        "target": "上海灵禅网络科技股份",
        "name": "投资"
    }, {
        "source": "上海久游网络科技",
        "target": "北京观颐投资顾问",
        "name": "投资"
    }, {
        "source": "上海久游网络科技",
        "target": "上海久翼网络科技",
        "name": "投资"
    }, {
        "source": "上海铂漫网络科技",
        "target": "上海布布乐育信息科技",
        "name": "投资"
    }, {
        "source": "上海焦扬网络科技",
        "target": "河北焦墨信息技术",
        "name": "投资"
    }, {
        "source": "上海焦扬网络科技",
        "target": "上海哈购网络科技",
        "name": "投资"
    }, {
        "source": "上海焦扬网络科技",
        "target": "上海超米广告",
        "name": "投资"
    }, {
        "source": "北京龙拳风暴科技",
        "target": "霍尔果斯龙拳网络科技",
        "name": "投资"
    }, {
        "source": "北京龙拳风暴科技",
        "target": "苏州工业园区龙拳风暴信息科技",
        "name": "投资"
    }, {
        "source": "北京龙拳风暴科技",
        "target": "天津龙拳风暴科技",
        "name": "投资"
    }, {
        "source": "乐元素科技（北京）股份",
        "target": "天津乐浣科技发展有限责任公司",
        "name": "投资"
    }, {
        "source": "乐元素科技（北京）股份",
        "target": "上海乐擎投资管理",
        "name": "投资"
    }, {
        "source": "乐元素科技（北京）股份",
        "target": "天津乐爱豆科技发展有限责任公司",
        "name": "投资"
    }, {
        "source": "乐元素科技（北京）股份",
        "target": "北京乐元素文化发展",
        "name": "投资"
    }, {
        "source": "乐元素科技（北京）股份",
        "target": "北京创智汇聚科技",
        "name": "投资"
    }, {
        "source": "乐元素科技（北京）股份",
        "target": "上海乐梨科技",
        "name": "投资"
    }, {
        "source": "乐元素科技（北京）股份",
        "target": "元素创造（深圳）网络科技",
        "name": "投资"
    }, {
        "source": "乐元素科技（北京）股份",
        "target": "北京零壹元素网络科技",
        "name": "投资"
    }, {
        "source": "乐元素科技（北京）股份",
        "target": "北京丹晟投资基金中心（有限合伙）",
        "name": "投资"
    }, {
        "source": "乐元素科技（北京）股份",
        "target": "上海绘界文化传播",
        "name": "投资"
    }, {
        "source": "百度移信网络技术（北京）",
        "target": "北京百度移讯科技",
        "name": "投资"
    }, {
        "source": "百度移信网络技术（北京）",
        "target": "北京百度多酷科技",
        "name": "投资"
    }, {
        "source": "百度移信网络技术（北京）",
        "target": "天津多酷紫桐科技",
        "name": "投资"
    }, {
        "source": "百度移信网络技术（北京）",
        "target": "海南多酷信息技术",
        "name": "投资"
    }, {
        "source": "百度移信网络技术（北京）",
        "target": "自然光影（北京）图像科技",
        "name": "投资"
    }, {
        "source": "北京太能沃可网络科技股份",
        "target": "霍尔果斯闪电网络科技",
        "name": "投资"
    }, {
        "source": "北京太能沃可网络科技股份",
        "target": "苏州太能沃可网络科技",
        "name": "投资"
    }, {
        "source": "北京太能沃可网络科技股份",
        "target": "宁波梅山保税港区陶朱安达投资管理中心（有限合伙）",
        "name": "投资"
    }, {
        "source": "北京蓝鲸时代科技",
        "target": "喀什蓝鲸时代网络科技",
        "name": "投资"
    }, {
        "source": "北京蓝鲸时代科技",
        "target": "南京翊瑅网络科技",
        "name": "投资"
    }, {
        "source": "蓝港在线（北京）科技",
        "target": "蓝港星云（北京）科技",
        "name": "投资"
    }, {
        "source": "蓝港在线（北京）科技",
        "target": "手游通（北京）科技",
        "name": "投资"
    }, {
        "source": "蓝港在线（北京）科技",
        "target": "北京蓝虎鲸科技",
        "name": "投资"
    }, {
        "source": "蓝港在线（北京）科技",
        "target": "北京趣味指间网络科技",
        "name": "投资"
    }, {
        "source": "蓝港在线（北京）科技",
        "target": "北京智讯天通信息技术",
        "name": "投资"
    }, {
        "source": "蓝港在线（北京）科技",
        "target": "多边形（北京）科技",
        "name": "投资"
    }, {
        "source": "蓝港在线（北京）科技",
        "target": "北京三栖人科技",
        "name": "投资"
    }, {
        "source": "蓝港在线（北京）科技",
        "target": "天津八八六四网络技术",
        "name": "投资"
    }, {
        "source": "蓝港在线（北京）科技",
        "target": "北京峰与隆互动文化",
        "name": "投资"
    }, {
        "source": "蓝港在线（北京）科技",
        "target": "蓝港影业（天津）",
        "name": "投资"
    }, {
        "source": "蓝港在线（北京）科技",
        "target": "多边形（海南）网络科技",
        "name": "投资"
    }, {
        "source": "蓝港在线（北京）科技",
        "target": "珠海蓝港在线科技",
        "name": "投资"
    }, {
        "source": "蓝港在线（北京）科技",
        "target": "霍尔果斯蓝港影业",
        "name": "投资"
    }, {
        "source": "蓝港在线（北京）科技",
        "target": "星满天（海南）影视",
        "name": "投资"
    }, {
        "source": "蓝港在线（北京）科技",
        "target": "北京古德时代科技",
        "name": "投资"
    }, {
        "source": "蓝港在线（北京）科技",
        "target": "蓝港思必特（北京）科技",
        "name": "投资"
    }, {
        "source": "蓝港在线（北京）科技",
        "target": "广州鸿娱网络科技",
        "name": "投资"
    }, {
        "source": "蓝港在线（北京）科技",
        "target": "海南天辰网络科技",
        "name": "投资"
    }, {
        "source": "蓝港在线（北京）科技",
        "target": "武汉极客猿教育科技",
        "name": "投资"
    }, {
        "source": "蓝港在线（北京）科技",
        "target": "北京创享天下网络科技",
        "name": "投资"
    }, {
        "source": "北京巴别时代科技股份",
        "target": "苏州湖图网络科技",
        "name": "投资"
    }, {
        "source": "北京巴别时代科技股份",
        "target": "海南巴别时代科技",
        "name": "投资"
    }, {
        "source": "北京巴别时代科技股份",
        "target": "上海履冰科技",
        "name": "投资"
    }, {
        "source": "北京巴别时代科技股份",
        "target": "北京量子维度科技",
        "name": "投资"
    }, {
        "source": "北京巴别时代科技股份",
        "target": "中广娱文传媒",
        "name": "投资"
    }, {
        "source": "北京巴别时代科技股份",
        "target": "厦门优莱柏网络科技",
        "name": "投资"
    }, {
        "source": "北京灵游坊网络科技",
        "target": "北京灵游坊软件技术",
        "name": "投资"
    }, {
        "source": "北京灵游坊网络科技",
        "target": "海南灵游坊网络科技",
        "name": "投资"
    }, {
        "source": "北京灵游坊网络科技",
        "target": "北京灵动时光科技",
        "name": "投资"
    }, {
        "source": "北京灵游坊网络科技",
        "target": "北京灵徒文化传媒",
        "name": "投资"
    }, {
        "source": "北京灵游坊网络科技",
        "target": "北京酷者网络科技",
        "name": "投资"
    }, {
        "source": "中手游移动科技",
        "target": "深圳市岚悦网络科技",
        "name": "投资"
    }, {
        "source": "中手游移动科技",
        "target": "霍尔果斯中手游创业投资",
        "name": "投资"
    }, {
        "source": "北京天马时空网络技术",
        "target": "宜春天成网络科技",
        "name": "投资"
    }, {
        "source": "北京天马时空网络技术",
        "target": "北京天际启游科技",
        "name": "投资"
    }, {
        "source": "北京天马时空网络技术",
        "target": "上海天銮网络技术",
        "name": "投资"
    }, {
        "source": "北京天马时空网络技术",
        "target": "上海扎古网络科技",
        "name": "投资"
    }, {
        "source": "北京天马时空网络技术",
        "target": "广州战法牧网络科技",
        "name": "投资"
    }, {
        "source": "必果互娱（北京）科技",
        "target": "北京必果互动网络技术",
        "name": "投资"
    }, {
        "source": "必果互娱（北京）科技",
        "target": "广州御和必果网络科技",
        "name": "投资"
    }, {
        "source": "北京大神圈文化科技",
        "target": "北京大神圈影视文化",
        "name": "投资"
    }, {
        "source": "北京大神圈文化科技",
        "target": "霍尔果斯大神圈影视传媒",
        "name": "投资"
    }, {
        "source": "北京大神圈文化科技",
        "target": "上海大神圈影视文化",
        "name": "投资"
    }, {
        "source": "乐道互动（天津）科技",
        "target": "乐道互动（天津）软件技术",
        "name": "投资"
    }, {
        "source": "乐道互动（天津）科技",
        "target": "乐道互动（广东）科技",
        "name": "投资"
    }, {
        "source": "乐道互动（天津）科技",
        "target": "乐道互动（上海）软件技术",
        "name": "投资"
    }, {
        "source": "乐道互动（天津）科技",
        "target": "淮安德润网络科技",
        "name": "投资"
    }, {
        "source": "乐道互动（天津）科技",
        "target": "淮安易趣网络科技",
        "name": "投资"
    }, {
        "source": "乐道互动（天津）科技",
        "target": "乐道互动（北京）科技",
        "name": "投资"
    }, {
        "source": "乐道互动（天津）科技",
        "target": "上海游曳网络科技",
        "name": "投资"
    }, {
        "source": "成都西山居互动娱乐科技",
        "target": "大连金山互动娱乐科技",
        "name": "投资"
    }, {
        "source": "成都西山居互动娱乐科技",
        "target": "珠海金山网络游戏科技",
        "name": "投资"
    }, {
        "source": "成都西山居互动娱乐科技",
        "target": "北京西山居互动娱乐科技",
        "name": "投资"
    }, {
        "source": "成都西山居互动娱乐科技",
        "target": "广州西山居世游网络科技",
        "name": "投资"
    }, {
        "source": "成都西山居互动娱乐科技",
        "target": "珠海西山居移动游戏科技",
        "name": "投资"
    }, {
        "source": "成都西山居互动娱乐科技",
        "target": "珠海西山居互动娱乐科技",
        "name": "投资"
    }, {
        "source": "成都西山居互动娱乐科技",
        "target": "成都浣沙文化传媒",
        "name": "投资"
    }, {
        "source": "成都西山居互动娱乐科技",
        "target": "武汉西腾科技",
        "name": "投资"
    }, {
        "source": "成都西山居互动娱乐科技",
        "target": "成都可萌世界网络科技",
        "name": "投资"
    }, {
        "source": "成都西山居互动娱乐科技",
        "target": "珠海剑心互动娱乐",
        "name": "投资"
    }, {
        "source": "成都西山居互动娱乐科技",
        "target": "西山居多盈（北京）科技",
        "name": "投资"
    }, {
        "source": "成都西山居互动娱乐科技",
        "target": "上海越群网络科技",
        "name": "投资"
    }, {
        "source": "成都西山居互动娱乐科技",
        "target": "上海光爪网络科技",
        "name": "投资"
    }, {
        "source": "成都西山居互动娱乐科技",
        "target": "深圳绿碧时代网络",
        "name": "投资"
    }, {
        "source": "成都西山居互动娱乐科技",
        "target": "北京双米互动信息技术",
        "name": "投资"
    }, {
        "source": "成都西山居互动娱乐科技",
        "target": "珠海乐趣科技",
        "name": "投资"
    }, {
        "source": "成都西山居互动娱乐科技",
        "target": "深圳市趣上科技",
        "name": "投资"
    }, {
        "source": "成都西山居互动娱乐科技",
        "target": "深圳市霜刃科技",
        "name": "投资"
    }, {
        "source": "成都西山居互动娱乐科技",
        "target": "神游互动科技（深圳）",
        "name": "投资"
    }, {
        "source": "成都西山居互动娱乐科技",
        "target": "北京漫考拉文化传媒",
        "name": "投资"
    }, {
        "source": "北京微笑科技",
        "target": "厦门趣合怡科技",
        "name": "投资"
    }, {
        "source": "北京水琴铃信息技术",
        "target": "北京远鸣网络科技",
        "name": "投资"
    }, {
        "source": "广州卓游信息科技",
        "target": "海南盛游信息科技",
        "name": "投资"
    }, {
        "source": "广州卓游信息科技",
        "target": "上海掌致信息科技",
        "name": "投资"
    }, {
        "source": "广州卓游信息科技",
        "target": "广州位面信息科技",
        "name": "投资"
    }, {
        "source": "广州卓游信息科技",
        "target": "深圳战艺网络科技",
        "name": "投资"
    }, {
        "source": "广州卓游信息科技",
        "target": "广州麟游信息科技",
        "name": "投资"
    }, {
        "source": "广州卓游信息科技",
        "target": "深圳市奥术信息科技",
        "name": "投资"
    }, {
        "source": "广州卓游信息科技",
        "target": "广州雷神信息科技",
        "name": "投资"
    }, {
        "source": "广州卓游信息科技",
        "target": "珠海市汇垠广奥股权投资基金管理",
        "name": "投资"
    }, {
        "source": "深圳市创梦天地科技",
        "target": "创梦无限（北京）信息技术",
        "name": "投资"
    }, {
        "source": "深圳市创梦天地科技",
        "target": "深圳市晨海之星科技",
        "name": "投资"
    }, {
        "source": "深圳市创梦天地科技",
        "target": "海南创梦天地科技",
        "name": "投资"
    }, {
        "source": "深圳市创梦天地科技",
        "target": "深圳市创享梦聚科技",
        "name": "投资"
    }, {
        "source": "深圳市创梦天地科技",
        "target": "湖南省崀山创梦天地文化传播",
        "name": "投资"
    }, {
        "source": "深圳市创梦天地科技",
        "target": "霍尔果斯创梦天地信息科技",
        "name": "投资"
    }, {
        "source": "深圳市创梦天地科技",
        "target": "深圳市未完待续科技",
        "name": "投资"
    }, {
        "source": "深圳市创梦天地科技",
        "target": "深圳市前海聚正投资管理",
        "name": "投资"
    }, {
        "source": "深圳市创梦天地科技",
        "target": "深圳市创梦互娱科技",
        "name": "投资"
    }, {
        "source": "深圳市创梦天地科技",
        "target": "深圳市梦作坊科技",
        "name": "投资"
    }, {
        "source": "深圳市创梦天地科技",
        "target": "深圳市创梦天地娱乐",
        "name": "投资"
    }, {
        "source": "深圳市创梦天地科技",
        "target": "广州提子网络科技",
        "name": "投资"
    }, {
        "source": "深圳市创梦天地科技",
        "target": "安徽思创体育发展",
        "name": "投资"
    }, {
        "source": "深圳市创梦天地科技",
        "target": "深圳市前海益启信元投资中心（有限合伙）",
        "name": "投资"
    }, {
        "source": "深圳市创梦天地科技",
        "target": "必盈图广告（上海）",
        "name": "投资"
    }, {
        "source": "深圳市创梦天地科技",
        "target": "北京微播科技发展",
        "name": "投资"
    }, {
        "source": "深圳市创梦天地科技",
        "target": "北京创联时讯信息科技",
        "name": "投资"
    }, {
        "source": "深圳市创梦天地科技",
        "target": "珠海君武投资管理合伙企业（有限合伙）",
        "name": "投资"
    }, {
        "source": "深圳市创梦天地科技",
        "target": "深圳市卓游科技",
        "name": "投资"
    }, {
        "source": "深圳市创梦天地科技",
        "target": "上海盛戏网络科技",
        "name": "投资"
    }, {
        "source": "福建网龙计算机网络信息技术",
        "target": "福州天诺网络科技",
        "name": "投资"
    }, {
        "source": "福建网龙计算机网络信息技术",
        "target": "福州天景网络科技",
        "name": "投资"
    }, {
        "source": "福建网龙计算机网络信息技术",
        "target": "福州天人网络信息技术服务",
        "name": "投资"
    }, {
        "source": "福建网龙计算机网络信息技术",
        "target": "福州畅裕网络科技",
        "name": "投资"
    }, {
        "source": "福建网龙计算机网络信息技术",
        "target": "福建网龙艺术传播",
        "name": "投资"
    }, {
        "source": "福建网龙计算机网络信息技术",
        "target": "福建天音文化传媒",
        "name": "投资"
    }, {
        "source": "福建网龙计算机网络信息技术",
        "target": "福建省天晴互动娱乐",
        "name": "投资"
    }, {
        "source": "福建网龙计算机网络信息技术",
        "target": "福建省华渔教育科技",
        "name": "投资"
    }, {
        "source": "福建网龙计算机网络信息技术",
        "target": "福建天渔教育科技",
        "name": "投资"
    }, {
        "source": "福建网龙计算机网络信息技术",
        "target": "福建天越现代教育发展",
        "name": "投资"
    }, {
        "source": "福建网龙计算机网络信息技术",
        "target": "福州天时网络科技",
        "name": "投资"
    }, {
        "source": "福建网龙计算机网络信息技术",
        "target": "海南天趣娱乐",
        "name": "投资"
    }, {
        "source": "福建网龙计算机网络信息技术",
        "target": "上海天坤数码科技",
        "name": "投资"
    }, {
        "source": "福建网龙计算机网络信息技术",
        "target": "厦门天盼网络科技",
        "name": "投资"
    }, {
        "source": "福建网龙计算机网络信息技术",
        "target": "北京网中软件科技",
        "name": "投资"
    }, {
        "source": "福建网龙计算机网络信息技术",
        "target": "福建省网云虚拟现实技术发展",
        "name": "投资"
    }, {
        "source": "福建网龙计算机网络信息技术",
        "target": "福建天渺网络科技",
        "name": "投资"
    }, {
        "source": "福建网龙计算机网络信息技术",
        "target": "福建省国腾信息科技",
        "name": "投资"
    }, {
        "source": "福建网龙计算机网络信息技术",
        "target": "昆明网龙华渔科技发展",
        "name": "投资"
    }, {
        "source": "福建网龙计算机网络信息技术",
        "target": "成都掌沃无限科技",
        "name": "投资"
    }, {
        "source": "广州库洛科技",
        "target": "广州库洛姆科技",
        "name": "投资"
    }, {
        "source": "广州盈正信息技术",
        "target": "广州市巧智数码科技",
        "name": "投资"
    }, {
        "source": "广州盈正信息技术",
        "target": "北京天雨网络科技",
        "name": "投资"
    }, {
        "source": "深圳凯撒网络科技",
        "target": "伊犁讯娱网络科技",
        "name": "投资"
    }, {
        "source": "深圳凯撒网络科技",
        "target": "四川天上友嘉网络科技",
        "name": "投资"
    }, {
        "source": "深圳凯撒网络科技",
        "target": "深圳前海凯撒文化",
        "name": "投资"
    }, {
        "source": "深圳凯撒网络科技",
        "target": "杭州幻文科技",
        "name": "投资"
    }, {
        "source": "深圳市创世互动科技",
        "target": "霍尔果斯万家游戏信息科技",
        "name": "投资"
    }, {
        "source": "深圳欣欣互动科技",
        "target": "深圳市神话互娱科技",
        "name": "投资"
    }, {
        "source": "深圳欣欣互动科技",
        "target": "霍尔果斯神话互娱科技",
        "name": "投资"
    }, {
        "source": "深圳欣欣互动科技",
        "target": "深圳方圆互娱科技",
        "name": "投资"
    }, {
        "source": "广州明朝互动科技股份",
        "target": "广州梦次元信息科技",
        "name": "投资"
    }, {
        "source": "广州诗悦网络科技",
        "target": "上海其趣网络科技",
        "name": "投资"
    }, {
        "source": "广州诗悦网络科技",
        "target": "上海轻量网络科技",
        "name": "投资"
    }, {
        "source": "广州诗悦网络科技",
        "target": "上海萌彩网络科技",
        "name": "投资"
    }, {
        "source": "广州诗悦网络科技",
        "target": "珠海诗悦网络科技",
        "name": "投资"
    }, {
        "source": "广州诗悦网络科技",
        "target": "海南诗悦网络科技",
        "name": "投资"
    }, {
        "source": "广州诗悦网络科技",
        "target": "海南诚悦网络科技",
        "name": "投资"
    }, {
        "source": "广州诗悦网络科技",
        "target": "海南晴空网络科技",
        "name": "投资"
    }, {
        "source": "广州诗悦网络科技",
        "target": "海南欢悦网络科技",
        "name": "投资"
    }, {
        "source": "广州诗悦网络科技",
        "target": "福州星环互动网络",
        "name": "投资"
    }, {
        "source": "深圳市创世互动科技",
        "target": "霍尔果斯万家游戏信息科技",
        "name": "投资"
    }, {
        "source": "广州银汉科技",
        "target": "银汉互娱（天津）科技",
        "name": "投资"
    }, {
        "source": "广州银汉科技",
        "target": "广州泳泳信息科技",
        "name": "投资"
    }, {
        "source": "广州银汉科技",
        "target": "霍尔果斯市银汉股权投资",
        "name": "投资"
    }, {
        "source": "广州银汉科技",
        "target": "海南银汉科技",
        "name": "投资"
    }, {
        "source": "广州银汉科技",
        "target": "霍尔果斯前见股权投资",
        "name": "投资"
    }, {
        "source": "广州银汉科技",
        "target": "深圳银创互娱科技",
        "name": "投资"
    }, {
        "source": "广州银汉科技",
        "target": "上海廿迷网络科技",
        "name": "投资"
    }, {
        "source": "广州银汉科技",
        "target": "广州果橙缤纷网络科技合伙企业（有限合伙）",
        "name": "投资"
    }, {
        "source": "广州银汉科技",
        "target": "广州飞雨网络科技",
        "name": "投资"
    }, {
        "source": "广州银汉科技",
        "target": "广州金楚信息技术",
        "name": "投资"
    }, {
        "source": "广州银汉科技",
        "target": "深圳市律动信息科技",
        "name": "投资"
    }, {
        "source": "广州银汉科技",
        "target": "广州子苏科技",
        "name": "投资"
    }, {
        "source": "广州银汉科技",
        "target": "上海侠娱网络科技",
        "name": "投资"
    }, {
        "source": "广州银汉科技",
        "target": "广州帝释天软件",
        "name": "投资"
    }, {
        "source": "广州银汉科技",
        "target": "广州市游毅坊网络科技",
        "name": "投资"
    }, {
        "source": "广州银汉科技",
        "target": "北京可为互娱文化科技",
        "name": "投资"
    }, {
        "source": "成都龙渊网络科技",
        "target": "成都龙渊盛世科技",
        "name": "投资"
    }, {
        "source": "成都龙渊网络科技",
        "target": "成都龙渊奇迹网络科技",
        "name": "投资"
    }, {
        "source": "成都龙渊网络科技",
        "target": "成都蒙斯克网络科技",
        "name": "投资"
    }, {
        "source": "成都龙渊网络科技",
        "target": "上海簇鹰网络科技",
        "name": "投资"
    }, {
        "source": "成都龙渊网络科技",
        "target": "成都龙渊传奇网络科技",
        "name": "投资"
    }, {
        "source": "成都龙渊网络科技",
        "target": "北京龙五网络科技",
        "name": "投资"
    }, {
        "source": "成都龙渊网络科技",
        "target": "成都凯利丹网络科技",
        "name": "投资"
    }, {
        "source": "成都龙渊网络科技",
        "target": "绵阳龙渊网络科技",
        "name": "投资"
    }, {
        "source": "成都龙渊网络科技",
        "target": "成都词牌社文化传播",
        "name": "投资"
    }, {
        "source": "成都龙渊网络科技",
        "target": "成都游理想科技",
        "name": "投资"
    }, {
        "source": "成都龙渊网络科技",
        "target": "成都龙腾云卷网络科技",
        "name": "投资"
    }, {
        "source": "成都龙渊网络科技",
        "target": "成都蛋卷科技",
        "name": "投资"
    }, {
        "source": "成都龙渊网络科技",
        "target": "成都映霸龙渊文化传播",
        "name": "投资"
    }, {
        "source": "成都龙渊网络科技",
        "target": "北京亿虎乐游网络科技",
        "name": "投资"
    }, {
        "source": "成都龙渊网络科技",
        "target": "北京漫动科技",
        "name": "投资"
    }, {
        "source": "成都龙渊网络科技",
        "target": "北京简娱科技",
        "name": "投资"
    }, {
        "source": "成都龙渊网络科技",
        "target": "深圳市四楼无限科技",
        "name": "投资"
    }, {
        "source": "成都龙渊网络科技",
        "target": "成都任客科技",
        "name": "投资"
    }, {
        "source": "成都五维互娱科技",
        "target": "成都牵手汇科技有限责任公司",
        "name": "投资"
    }, {
        "source": "北京奇艺世纪科技",
        "target": "上海爱奇艺互娱科技",
        "name": "投资"
    }, {
        "source": "北京奇艺世纪科技",
        "target": "北京国址地信息咨询有限责任公司",
        "name": "投资"
    }, {
        "source": "成都萤火虫信息技术",
        "target": "喀什乐线信息技术",
        "name": "投资"
    }, {
        "source": "成都萤火虫信息技术",
        "target": "霍尔果斯萤火虫信息技术",
        "name": "投资"
    }, {
        "source": "成都萤火虫信息技术",
        "target": "成都战魂信息技术",
        "name": "投资"
    }, {
        "source": "成都萤火虫信息技术",
        "target": "成都云奇信息技术",
        "name": "投资"
    }, {
        "source": "成都萤火虫信息技术",
        "target": "成都八九七文化传播",
        "name": "投资"
}]



// 第一处
let searchedValue = '';
let resOld = '';
if (!document.getElementById('searchInput')) {
    document.getElementById('chart-panel').style.marginTop = '100px'
    var text = document.createElement('span');
    text.innerHTML = '节点名称搜索：';
    text.style.fontSize = '12px';
    document.body.appendChild(text);
    var input = document.createElement('input');
    input.id = 'searchInput';
    document.body.appendChild(input);
}
setInterval(() => {
    searchedValue = document.getElementById('searchInput').value;
    if (resOld !== searchedValue) {
        init();
    }
    resOld = searchedValue;
}, 1000);



function init() {
    // 第二处 - 将主要逻辑封装为init函数（注意下面的nodes，使用JSON.parse(JSON.stringify(nodes))）
    let data = {
        nodes: JSON.parse(JSON.stringify(nodes)),
        links: links,
    }
    const color1 = '#006acc';
    const color2 = '#ff7d18';
    const color3 = '#10a050';
    data.nodes.forEach(node => {
        if (node.category === 1) {
            node.symbolSize = 100;
            node.itemStyle = {
                color: color1
            };
        } else if (node.category === 2) {
            node.itemStyle = {
                color: color2
            };
        } else if (node.category === 3) {
            node.itemStyle = {
                color: color3
            };
        }
        //  第三处
        //  精准匹配
        // if (searchedValue &&  node.name === searchedValue) {
        
        // 模糊匹配
        if (searchedValue && node.name.toLowerCase().indexOf(searchedValue.toLowerCase()) > -1) {
            node.itemStyle = {
                color: 'black'
            };
        }
    });

    data.links.forEach(link => {
        link.label = {
            align: 'center',
            fontSize: 12
        };

        if (link.name === '') {
            link.lineStyle = {
                color: color2
            }
        } else if (link.name === '') {
            link.lineStyle = {
                color: color1
            }
        } else if (link.name === '') {
            link.lineStyle = {
                color: color3
            }
        }
    });

    let categories = [{
            name: '华东',
            itemStyle: {
                color: color1
            }
        },
        {
            name: '华南',
            itemStyle: {
                color: color2
            }
        },
        {
            name: '西南',
            itemStyle: {
                color: color3
            }
        },
        {
            name: '华北',
            itemStyle: {
                color: color3
            }
        }
    ]

    option = {
        title: {
            text: '关系图谱',
        },
        legend: [{
            // selectedMode: 'single',
            data: categories.map(x => x.name),
            // icon: 'circle'
        }],
        series: [{
            type: 'graph',
            layout: 'force',
            symbolSize: 58,
            draggable: true,
            roam: true,
            focusNodeAdjacency: true,
            categories: categories,
            edgeSymbol: ['', 'arrow'],
            // edgeSymbolSize: [80, 10],
            edgeLabel: {
                normal: {
                    show: false,
                    textStyle: {
                        fontSize: 20
                    },
                    formatter(x) {
                        return x.data.name;
                    }
                }
            },
            label: {
                show: false,
            },
            force: {
                repulsion: 2000,
                edgeLength: 120
            },
            data: data.nodes,
            links: data.links
        }]
    }
    // 第四处：
    myChart.setOption(option);
}


// 第五处
init();
