var uploadedDataURL = "/asset/get/s/data-1574675536693-Fb_nXJTa.png";



option = {
    "grid":{
        "left":50,
        "top":50,
        "right":50,
        "bottom":"10%",
        "containLabel":true
    },
    backgroundColor:"#0E233E",
    "tooltip":{
        "show":false,
        "trigger":"axis",
        "backgroundColor":"rgba(0,0,0,0)",
        "axisPointer":{
            "lineStyle":{
                "width":0
            }
        },
        "textStyle":{
            "color":"#ffdc70",
            "fontSize":20,
            "fontWeight":"bold"
        }
    },
    "xAxis":{
        "type":"value",
        "axisLine":{
            "show":false,
            "lineStyle":{
                "color":"#00BBFB"
            }
        },
        "axisTick":{
            "show":false
        },
        "name":"",
        "nameTextStyle":{
            "color":"#00BBFB",
            "fontSize":"16"
        },
        "axisLabel":{
            "show":false,
            "color":"#00BBFB",
            "fontSize":"16",
            "interval":0
        },
        "splitLine":{
            "show":false
        }
    },
    "yAxis":{
        "splitLine":{
            "show":false,
            "lineStyle":{
                "color":"#00BBFB",
                "type":"dotted",
                "width":1
            }
        },
        "data":[
            "网络举报",
            "来访",
            "来信",
            "来电"
        ],
        "type":"category",
        "axisTick":{
            "show":false
        },
        "name":"",
        "nameTextStyle":{
            "color":"#00BBFB",
            "fontSize":"16"
        },
        "axisLine":{
            "show":false,
            "lineStyle":{
                "color":"#00BBFB"
            }
        },
        "axisLabel":{
            "show":false,
            "color":"#00BBFB",
            "fontSize":"16"
        }
    },
    "series":[
        {
            "name":"多边形",
            "type":"pictorialBar",
            "itemStyle":{
                "color":"#01d3f9"
            },
            "symbol":"image://"+uploadedDataURL,
            "symbolClip":true,
            "z":10,
            "symbolSize":35,
            "symbolMargin":5,
            "symbolRepeat":true,
            "label":{
                "show":false
            },
            "data":[
                20,
                10,
                30,
                8
            ]
        },
        {
            "name":"多边形",
            "type":"pictorialBar",
            "itemStyle":{
                "color":"rgba(112,143,212,0.5)",
                "opacity":0.3
            },
            "symbol":"image://"+uploadedDataURL,
            "symbolClip":false,
            "symbolSize":25,
            "symbolMargin":5,
            "symbolRepeat":true,
            "data":[
                20,
                10,
                30,
                8
            ]
        }
    ]
}