option = {
    // 图表标题
    title: {
        show:true,//显示策略，默认值true,可选为：true（显示） | false（隐藏）
        text: '#一张图看懂新冠肺炎#话题图谱',//主标题文本，'\n'指定换行
        x: 'center',        // 水平安放位置，默认为左对齐，可选为：
                          // 'center' ¦ 'left' ¦ 'right'
                          // ¦ {number}（x坐标，单位px）
        y: 'bottom',             // 垂直安放位置，默认为全图顶端，可选为：
                          // 'top' ¦ 'bottom' ¦ 'center'
                          // ¦ {number}（y坐标，单位px）
        //textAlign: null          // 水平对齐方式，默认根据x设置自动调整
        backgroundColor: 'rgba(0,0,0,0)',
        borderColor: '#ccc',    // 标题边框颜色
        borderWidth: 0,         // 标题边框线宽，单位px，默认为0（无边框）
        padding: 5,             // 标题内边距，单位px，默认各方向内边距为5，
                                // 接受数组分别设定上右下左边距，同css
        itemGap: 10,            // 主副标题纵向间隔，单位px，默认为10，
        textStyle: {
            fontSize: 18,
            fontWeight: 'bolder',
            color: '#333'        // 主标题文字颜色
        },
        subtextStyle: {
            color: '#aaa'        // 副标题文字颜色
        }
    },
    tooltip: {
        show: true, // 默认显示
        showContent: true, // 是否显示提示框浮层
        trigger: 'item', // 触发类型，默认数据项触发
        triggerOn: 'mousemove', // 提示触发条件，mousemove鼠标移至触发，还有click点击触发
        alwaysShowContent: false, // 默认离开提示框区域隐藏，true为一直显示
        showDelay: 100, // 浮层显示的延迟，单位为 ms，默认没有延迟，也不建议设置。在 triggerOn 为 'mousemove' 时有效。
        hideDelay: 2000, // 浮层隐藏的延迟，单位为 ms，在 alwaysShowContent 为 true 的时候无效。
        enterable: false, // 鼠标是否可进入提示框浮层中，默认为false，如需详情内交互，如添加链接，按钮，可设置为 true。
        position: 'right', // 提示框浮层的位置，默认不设置时位置会跟随鼠标的位置。只在 trigger 为'item'的时候有效。
        confine: false, // 是否将 tooltip 框限制在图表的区域内。
        // 外层的 dom 被设置为 'overflow: hidden'，或者移动端窄屏，导致 tooltip 超出外界被截断时，此配置比较有用。
        transitionDuration: 0.2, // 提示框浮层的移动动画过渡时间，单位是秒，设置为 0 的时候会紧跟着鼠标移动。
    },
    legend: { // 图例显示（显示在右上角），name:类别名称，icon:图例的形状（默认是roundRect圆角矩形）。
        show: true,
        data: [
            {
                name: '积极'
            },
            {
                name: '中立'
            },
            {
                name: '消极'
            }
        ]
    },
    series: [{
        type: 'graph', // 关系图
        name: '#一张图看懂新冠肺炎#:', // 系列名称，用于tooltip的显示，legend 的图例筛选，在 setOption 更新数据和配置项时用于指定对应的系列。
        layout: 'force', // 图的布局，类型为力导图，'circular' 采用环形布局，见示例 Les Miserables
        legendHoverLink: true, // 是否启用图例 hover(悬停) 时的联动高亮。
        hoverAnimation: true, // 是否开启鼠标悬停节点的显示动画
        coordinateSystem: null, // 坐标系可选
        xAxisIndex: 0, // x轴坐标 有多种坐标系轴坐标选项
        yAxisIndex: 0, // y轴坐标 
        force: { // 力引导图基本配置
            // initLayout: , // 力引导的初始化布局，默认使用xy轴的标点
            repulsion: 500, // 节点之间的斥力因子。支持数组表达斥力范围，值越大斥力越大。
            gravity: 0.02, // 节点受到的向中心的引力因子。该值越大节点越往中心点靠拢。
            edgeLength: 200, // 边的两个节点之间的距离，这个距离也会受 repulsion影响 。值越大则长度越长
            layoutAnimation: true // 因为力引导布局会在多次迭代后才会稳定，这个参数决定是否显示布局的迭代动画
            // 在浏览器端节点数据较多（>100）的时候不建议关闭，布局过程会造成浏览器假死。                        
        },
        roam: true, // 是否开启鼠标缩放和平移漫游。默认不开启，true 为都开启。如果只想要开启缩放或者平移，可以设置成 'scale' 或者 'move'
        nodeScaleRatio: 0.6, // 鼠标漫游缩放时节点的相应缩放比例，当设为0时节点不随着鼠标的缩放而缩放
        draggable: true, // 节点是否可拖拽，只在使用力引导布局的时候有用。
        focusNodeAdjacency: true, // 是否在鼠标移到节点上的时候突出显示节点以及节点的边和邻接节点。
        // symbol:'roundRect', // 关系图节点标记的图形。
        // ECharts 提供的标记类型包括：'circle'(圆形), 'rect'（矩形）, 'roundRect'（圆角矩形）,
        // 'triangle'（三角形）, 'diamond'（菱形）, 'pin'（大头针）, 'arrow'（箭头）
        // 也可以通过 'image://url' 设置为图片，其中 url 为图片的链接。'path:// 这种方式可以任意改变颜色并且抗锯齿
        // symbolSize: 10 , // 也可以用数组分开表示宽和高，例如 [20, 10] 如果需要每个数据的图形大小不一样，
        // 可以设置为如下格式的回调函数：(value: Array|number, params: Object) => number|Array
        // symbolRotate:, // 关系图节点标记的旋转角度。注意在 markLine 中当 symbol 为 'arrow' 时会忽略 symbolRotate 强制设置为切线的角度。
        // symbolOffset:[0,0], // 关系图节点标记相对于原本位置的偏移。[0, '50%']
        edgeSymbol: ['none', 'none'], // 边两端的标记类型，可以是一个数组分别指定两端，也可以是单个统一指定。
        // 默认不显示标记，常见的可以设置为箭头，如下：edgeSymbol: ['circle', 'arrow']
        edgeSymbolSize: 10, // 边两端的标记大小，可以是一个数组分别指定两端，也可以是单个统一指定。

        itemStyle: { // ========图形样式，有 normal 和 emphasis 两个状态。
            // normal 是图形在默认状态下的样式；
            // emphasis 是图形在高亮状态下的样式，比如在鼠标悬浮或者图例联动高亮时。
            normal: { // 默认样式
                label: {
                    show: true
                },
                // borderType: 'solid', // 图形描边类型，默认为实线，支持 'solid'（实线）, 'dashed'(虚线), 'dotted'（点线）。
                // borderColor: 'rgba(205, 149, 12, 0.4)', // 设置图形边框为淡金色,透明度为0.4
                // borderWidth: 2, // 图形的描边线宽。为 0 时无描边。
                opacity: 1 // 图形透明度。支持从 0 到 1 的数字，为 0 时不绘制该图形。默认0.5

            },
            emphasis: { // 高亮状态

            }
        },
        lineStyle: { // ========关系边的公用线条样式。
            normal: {
                color: 'rgba(255, 0, 255, 0.4)',
                width: '1', //线的粗细
                type: 'solid', // 线的类型 'solid'（实线）'dashed'（虚线）'dotted'（点线）
                curveness: 0.3, // 线条的曲线程度，从0到1
                opacity: 0.5 // 图形透明度。支持从 0 到 1 的数字，为 0 时不绘制该图形。默认0.5
            },
            emphasis: { // 高亮状态

            }
        },
        label: { // ========结点图形上的文本标签
            normal: {
                show: false, // 是否显示标签。
                position: 'inside', // 标签的位置。['50%', '50%'] [x,y]
                textStyle: { // 标签的字体样式
                    color: '#d3d7d4', // 字体颜色 #cde6c7 #d1c7b7 #d9d6c3 #d3d7d4
                    fontStyle: 'normal', // 文字字体的风格 'normal'标准 'italic'斜体 'oblique' 倾斜
                    fontWeight: 'bolder', // 'normal'标准，'bold'粗的，'bolder'更粗的，'lighter'更细的，或100 | 200 | 300 | 400...
                    fontFamily: 'sans-serif', // 文字的字体系列
                    fontSize: 12, // 字体大小
                }
            },
            emphasis: { // 高亮状态

            }
        },
        edgeLabel: { // ========连接线上的文本标签 
            normal: {
                show: false // 不显示连接线上的文字，如果显示只能显示结点的value值，而不是连接线的值
            },
            emphasis: { // 高亮状态

            }
        },
        categories: [ // name(类别名称)要同legend(图例）按次序一致
            {
                name: '积极',
                itemStyle: {
                    normal: {
                        color: 'red'
                    }
                }
            },
            {
                name: '中立',
                itemStyle: {
                    normal: {
                        color: 'lightgray'
                    }
                }
            },
            {
                name: '消极',
                itemStyle: {
                    normal: {
                        color: 'green'
                    }
                }
            }
        ],
        // 设置结点node的数据
        // category: 类别序号，从0开始
        // name: 结点图形显示的文字
        // value: 鼠标点击结点，显示的数字
        // symbolSize: 结点图形的大小
        // symbol: 类目节点标记图形，默然为圆形
        // label: 标签样式
        data: [
{ category: '积极', name: 'lolo521345', value: 1, symbolSize: 10 },
{ category: '积极', name: '头条新闻', value: 175, symbolSize: 130,
label: {
        show: true,
        color: "#333"
    } },
{ category: '消极', name: 'CHEN七又二分之一', value: 5, symbolSize: 20 },
{ category: '积极', name: '张日龙在熬鷄汤', value: 6, symbolSize: 20 },
{ category: '积极', name: '李隶浩', value: 2, symbolSize: 10 },
{ category: '积极', name: '驾校同学74977', value: 1, symbolSize: 10 },
{ category: '消极', name: '张潮洋', value: 1, symbolSize: 10 },
{ category: '积极', name: '脱单奔现社', value: 19, symbolSize: 40 ,
label: {
        show: true,
        color: "#333"
    }},
{ category: '积极', name: '每天一个小目标哦', value: 2, symbolSize: 10 },
{ category: '中立', name: 'Dingdu叮嘟', value: 16, symbolSize: 40 ,
label: {
        show: true,
        color: "#333"
    }},
{ category: '消极', name: '泣血一梦解千愁', value: 1, symbolSize: 10 },
{ category: '消极', name: '唯物辩证阿尔德', value: 1, symbolSize: 10 },
{ category: '积极', name: 'rattyraet', value: 1, symbolSize: 10 },
{ category: '积极', name: 'PdsS', value: 2, symbolSize: 10 },
{ category: '积极', name: '会飞的小鹌鹑_', value: 1, symbolSize: 10 },
{ category: '积极', name: '痞人私人专属03', value: 1, symbolSize: 10 },
{ category: '积极', name: '你自己想吧201911', value: 1, symbolSize: 10 },
{ category: '消极', name: '一只轮回', value: 1, symbolSize: 10 },
{ category: '积极', name: 'Vans-匡威-工-厂-店--', value: 2, symbolSize: 10 },
{ category: '积极', name: '唐斩俗叔', value: 1, symbolSize: 10 },
{ category: '中立', name: '哎呀咿呀耳语呢喃', value: 1, symbolSize: 10 },
{ category: '中立', name: '北俱无聊者', value: 1, symbolSize: 10 },
{ category: '消极', name: '上发条的猴子', value: 1, symbolSize: 10 },
{ category: '消极', name: 'TonyLau1981', value: 1, symbolSize: 10 },
{ category: '中立', name: '李少林林', value: 1, symbolSize: 10 },
{ category: '积极', name: 'hi張陽', value: 1, symbolSize: 10 },
{ category: '消极', name: '南栀沁寒sun', value: 1, symbolSize: 10 },
{ category: '中立', name: '夜神月455', value: 2, symbolSize: 10 },
{ category: '消极', name: '土申哆哆', value: 1, symbolSize: 10 },
{ category: '中立', name: '在云海相望', value: 3, symbolSize: 10 },
{ category: '中立', name: '彬彬胡呀', value: 1, symbolSize: 10 },
{ category: '消极', name: '青羽米兔', value: 1, symbolSize: 10 },
{ category: '中立', name: '踏水_无痕', value: 1, symbolSize: 10 },
{ category: '积极', name: '开欲燃', value: 1, symbolSize: 10 },
{ category: '积极', name: '牧天Mutian', value: 5, symbolSize: 20 },
{ category: '消极', name: 'fenggewo', value: 4, symbolSize: 20 },
{ category: '消极', name: '二次元的二', value: 2, symbolSize: 10 },
{ category: '消极', name: 'SWMHH', value: 1, symbolSize: 10 },
{ category: '消极', name: '玉雪纷飞飞', value: 1, symbolSize: 10 },
{ category: '中立', name: '比奥利奥还ao的姑娘', value: 1, symbolSize: 10 },
{ category: '中立', name: '殷小迪', value: 1, symbolSize: 10 },
{ category: '积极', name: '樱顶老法师', value: 1, symbolSize: 10 },
{ category: '中立', name: 'tyn宝宝贝呀', value: 1, symbolSize: 10 },
{ category: '中立', name: 'xx是春风', value: 1, symbolSize: 10 },
{ category: '消极', name: '雪若王', value: 1, symbolSize: 10 },
{ category: '积极', name: '-刘户口-', value: 1, symbolSize: 10 },
{ category: '积极', name: '悲观的乐观dimi', value: 1, symbolSize: 10 },
{ category: '积极', name: '梅梢玲萧', value: 1, symbolSize: 10 },
{ category: '积极', name: '胡元阿', value: 1, symbolSize: 10 },
{ category: '积极', name: '二-200004', value: 1, symbolSize: 10 },
{ category: '中立', name: '天空宠儿呀', value: 1, symbolSize: 10 },
{ category: '积极', name: '我要rushB了', value: 1, symbolSize: 10 },
{ category: '积极', name: '沈阗求约稿', value: 11, symbolSize: 30 ,
label: {
        show: true,
        color: "#333"
    }},
{ category: '积极', name: '大钰儿', value: 1, symbolSize: 10 },
{ category: '积极', name: '孤独诗意', value: 1, symbolSize: 10 },
{ category: '中立', name: '书生-问道', value: 1, symbolSize: 10 },
{ category: '消极', name: '优雅的污粑粑', value: 1, symbolSize: 10 },
{ category: '消极', name: '怪脾气的胡萝卜', value: 2, symbolSize: 10 },
{ category: '积极', name: 'heygirl-ya', value: 4, symbolSize: 20 },
{ category: '积极', name: '就是小迷妹啊', value: 1, symbolSize: 10 },
{ category: '积极', name: '屋顶上散步的人', value: 1, symbolSize: 10 },
{ category: '中立', name: '我行我素-E63', value: 1, symbolSize: 10 },
{ category: '消极', name: '起你妹名字啊', value: 22, symbolSize: 40,
label: {
        show: true,
        color: "#333"
    } },
{ category: '积极', name: '老年人李冠杰', value: 2, symbolSize: 10 },
{ category: '积极', name: '晋太元中0152', value: 1, symbolSize: 10 },
{ category: '积极', name: '先森您是喜脉啊', value: 1, symbolSize: 10 },
{ category: '积极', name: '一只仙女turbo', value: 1, symbolSize: 10 },
{ category: '中立', name: '好多二妮', value: 1, symbolSize: 10 },
{ category: '中立', name: '拾光流年ya', value: 1, symbolSize: 10 },
{ category: '消极', name: 'Mike涛_', value: 1, symbolSize: 10 },
{ category: '消极', name: '墨离莫失', value: 1, symbolSize: 10 },
{ category: '消极', name: '徐kellen', value: 1, symbolSize: 10 },
{ category: '消极', name: '番茄小肥羊_', value: 1, symbolSize: 10 },
{ category: '中立', name: '月半小夜曲丹', value: 1, symbolSize: 10 },
{ category: '积极', name: '吃大份的', value: 1, symbolSize: 10 },
{ category: '积极', name: '西子捺', value: 1, symbolSize: 10 },
{ category: '消极', name: '小刘冲鸭最棒棒', value: 1, symbolSize: 10 },
{ category: '积极', name: '人可可每天都不非', value: 1, symbolSize: 10 },
{ category: '积极', name: 'SugarPlummmm', value: 1, symbolSize: 10 },
{ category: '积极', name: '铁铁铁铁铁鱼', value: 1, symbolSize: 10 },
{ category: '中立', name: '笑笑笑笑笑笑够了就睡了', value: 1, symbolSize: 10 },
{ category: '消极', name: '臭鹏鹏Eddie', value: 1, symbolSize: 10 },
{ category: '积极', name: '随遇而安53744', value: 1, symbolSize: 10 },
{ category: '积极', name: '依依西望', value: 1, symbolSize: 10 },
{ category: '中立', name: '大见家的田田', value: 2, symbolSize: 10 },
{ category: '积极', name: 'Samantha_wan', value: 6, symbolSize: 20 },
{ category: '中立', name: 'Champagne啊', value: 2, symbolSize: 10 },
{ category: '消极', name: '有态度的喵喵大人', value: 7, symbolSize: 20 },
{ category: '中立', name: 'Alloycius', value: 1, symbolSize: 10 },
{ category: '积极', name: '好起来了憨憨', value: 4, symbolSize: 20 },
{ category: '积极', name: '我不是康利同學', value: 1, symbolSize: 10 },
{ category: '积极', name: '鼓手E939', value: 2, symbolSize: 10 },
{ category: '积极', name: '惠翎Whitney', value: 1, symbolSize: 10 },
{ category: '积极', name: '肉肉肥新', value: 2, symbolSize: 10 },
{ category: '积极', name: '是甜菜叶子', value: 3, symbolSize: 10 },
{ category: '积极', name: 'Merry7you', value: 1, symbolSize: 10 },
{ category: '积极', name: '我要去找你43', value: 1, symbolSize: 10 },
{ category: '积极', name: '字母数字控N', value: 1, symbolSize: 10 },
{ category: '积极', name: '菩萨保佑868686', value: 2, symbolSize: 10 },
{ category: '积极', name: '阿狸要天天开心', value: 1, symbolSize: 10 },
{ category: '积极', name: '喝着可乐的孔明先生', value: 1, symbolSize: 10 },
{ category: '消极', name: 'Crazyspud', value: 1, symbolSize: 10 },
{ category: '积极', name: '一个大朋友la', value: 1, symbolSize: 10 },
{ category: '积极', name: 'd属于你的我', value: 1, symbolSize: 10 },
{ category: '中立', name: 'StellaSuxx', value: 1, symbolSize: 10 },
{ category: '积极', name: '兴化新鲜事', value: 1, symbolSize: 10 },
{ category: '积极', name: 'Lese删除站', value: 1, symbolSize: 10 },
{ category: '积极', name: '十一点十八分00', value: 1, symbolSize: 10 },
{ category: '积极', name: '冰可樂走冰1127', value: 1, symbolSize: 10 },
{ category: '消极', name: '非草木人', value: 1, symbolSize: 10 },
{ category: '积极', name: 'mangomxx', value: 1, symbolSize: 10 },
{ category: '积极', name: '大可VVV', value: 1, symbolSize: 10 },
{ category: '中立', name: '垚士555', value: 4, symbolSize: 20 },
{ category: '积极', name: '海盐berry布丁', value: 1, symbolSize: 10 },
{ category: '积极', name: '起风了943', value: 1, symbolSize: 10 },
{ category: '积极', name: '超酷的毒鸡汤大叔', value: 1, symbolSize: 10 },
{ category: '中立', name: '四川轻化工Levy', value: 2, symbolSize: 10 },
{ category: '积极', name: '唯有暴富能解忧愁', value: 1, symbolSize: 10 },
{ category: '积极', name: '非野飒', value: 4, symbolSize: 20 },
{ category: '积极', name: '三皮皮012', value: 2, symbolSize: 10 },
{ category: '中立', name: 'Gravity_Falls_', value: 1, symbolSize: 10 },
{ category: '积极', name: '同学大蒜吐你一口大粘痰', value: 2, symbolSize: 10 },
{ category: '积极', name: 'Someone05333', value: 1, symbolSize: 10 },
{ category: '积极', name: '用户dyesj8l9ol', value: 1, symbolSize: 10 },
{ category: '积极', name: '六火六火', value: 1, symbolSize: 10 },
{ category: '积极', name: '风过落影rai', value: 1, symbolSize: 10 },
{ category: '中立', name: '口十蕾llll', value: 1, symbolSize: 10 },
{ category: '消极', name: 'yes是我W', value: 1, symbolSize: 10 },
{ category: '积极', name: '鹿岚i', value: 1, symbolSize: 10 },
{ category: '积极', name: '睿爷的爷', value: 1, symbolSize: 10 },
{ category: '积极', name: 'sailingyu322', value: 1, symbolSize: 10 },
{ category: '积极', name: 'Siven_Han', value: 1, symbolSize: 10 },
{ category: '积极', name: '晓秋君尔', value: 1, symbolSize: 10 },
{ category: '积极', name: 'One_Chou', value: 2, symbolSize: 10 },
{ category: '积极', name: 'Hsia小超', value: 1, symbolSize: 10 },
{ category: '中立', name: '你就是演技好', value: 1, symbolSize: 10 },
{ category: '消极', name: '柳随风', value: 1, symbolSize: 10 },
{ category: '积极', name: '一个二毫六', value: 2, symbolSize: 10 },
{ category: '积极', name: '芝士布丁配冰棍', value: 8, symbolSize: 20 },
{ category: '积极', name: '芝士榴莲cj', value: 1, symbolSize: 10 },
{ category: '中立', name: '虎牙君233', value: 1, symbolSize: 10 },
{ category: '消极', name: '长风渡', value: 1, symbolSize: 10 },
{ category: '消极', name: '天蝎sG', value: 1, symbolSize: 10 },
{ category: '消极', name: 'Summer-1928', value: 1, symbolSize: 10 },
{ category: '积极', name: '台州椒江扫一扫家政', value: 1, symbolSize: 10 },
{ category: '积极', name: '笑看社会不看股市', value: 1, symbolSize: 10 },
{ category: '积极', name: '一年只能修改一次先用一年', value: 1, symbolSize: 10 },
{ category: '消极', name: '擤擤Ma爱喝粥', value: 1, symbolSize: 10 },
{ category: '积极', name: '早睡早起身体好不秃头', value: 1, symbolSize: 10 },
{ category: '积极', name: '青我你他', value: 1, symbolSize: 10 },
{ category: '积极', name: '冷冷酷酷不穿秋裤', value: 1, symbolSize: 10 },
{ category: '积极', name: '谁的韭菜啊', value: 1, symbolSize: 10 },
{ category: '积极', name: '拉忽酱', value: 1, symbolSize: 10 },
{ category: '积极', name: '黑人张t', value: 1, symbolSize: 10 },
{ category: '中立', name: '阿简zj', value: 1, symbolSize: 10 },
{ category: '积极', name: '晒太阳看大海', value: 1, symbolSize: 10 },
{ category: '积极', name: '宅宅在家睡大觉', value: 1, symbolSize: 10 },
{ category: '中立', name: '杨牧笛1935969121', value: 2, symbolSize: 10 },
{ category: '积极', name: '小虫虫呀', value: 2, symbolSize: 10 },
{ category: '积极', name: 'zytcool', value: 9, symbolSize: 30 },
{ category: '消极', name: '动感光波-bi6238', value: 1, symbolSize: 10 },
{ category: '积极', name: '冷凝集试验', value: 1, symbolSize: 10 },
{ category: '消极', name: '番薯妹-Fei', value: 1, symbolSize: 10 },
{ category: '积极', name: '莹-silence', value: 1, symbolSize: 10 },
{ category: '积极', name: '科二挂科', value: 1, symbolSize: 10 },
{ category: '积极', name: '徽虎子', value: 1, symbolSize: 10 },
{ category: '积极', name: '刘刘yuki', value: 1, symbolSize: 10 },
{ category: '积极', name: 'Rachel-courage', value: 1, symbolSize: 10 },
{ category: '消极', name: '张日龙在熬鸡杨', value: 1, symbolSize: 10 },
{ category: '积极', name: '心内一米', value: 1, symbolSize: 10 },
{ category: '积极', name: '-朴实-无华', value: 1, symbolSize: 10 },
{ category: '积极', name: '西贝蓉儿', value: 1, symbolSize: 10 },
{ category: '积极', name: '装修苏小哥', value: 1, symbolSize: 10 },
{ category: '消极', name: 'ailsa1345', value: 2, symbolSize: 10 },
{ category: '积极', name: '食肉目的叛徒', value: 1, symbolSize: 10 },
{ category: '消极', name: '果塘湖的夏天', value: 1, symbolSize: 10 },
{ category: '积极', name: '揣着意大利炮的二营长', value: 1, symbolSize: 10 },
{ category: '消极', name: '树里潜龙', value: 1, symbolSize: 10 },
{ category: '积极', name: '杨瑞哇啦啦', value: 2, symbolSize: 10 },
{ category: '中立', name: '反正记不住何必想这个昵称的意义', value: 1, symbolSize: 10 },
{ category: '积极', name: '义特别', value: 1, symbolSize: 10 },
{ category: '积极', name: '纸重江湖', value: 1, symbolSize: 10 },
{ category: '中立', name: '额就是个普通人', value: 1, symbolSize: 10 },
{ category: '积极', name: '·福气满满·', value: 1, symbolSize: 10 },
{ category: '积极', name: '谦虚认真努力yz', value: 1, symbolSize: 10 },
{ category: '消极', name: 'ZoeMiu-', value: 1, symbolSize: 10 },
{ category: '消极', name: 'zyhh121', value: 1, symbolSize: 10 },
{ category: '消极', name: '阿米米尼', value: 1, symbolSize: 10 },
{ category: '中立', name: '0寂寞的云0', value: 1, symbolSize: 10 },
{ category: '消极', name: '吹吹冷风2017', value: 1, symbolSize: 10 },
{ category: '积极', name: 'Miraculous_BK', value: 1, symbolSize: 10 },
{ category: '消极', name: '猫九动次胖次', value: 1, symbolSize: 10 },
{ category: '积极', name: 'Lilylovechili', value: 1, symbolSize: 10 },
{ category: '消极', name: '许肉肉先生', value: 1, symbolSize: 10 },
{ category: '消极', name: '深夜里的袍哥人家', value: 1, symbolSize: 10 },
{ category: '消极', name: 'qwerqwre1', value: 1, symbolSize: 10 },
{ category: '积极', name: '军令部长', value: 1, symbolSize: 10 },
{ category: '中立', name: '小张在线被锤', value: 1, symbolSize: 10 },
{ category: '消极', name: '鸡腿你干嘛', value: 1, symbolSize: 10 },
{ category: '中立', name: '把时间停住', value: 1, symbolSize: 10 },
{ category: '积极', name: '大了个清儿', value: 1, symbolSize: 10 },
{ category: '积极', name: '99得81', value: 1, symbolSize: 10 },
{ category: '积极', name: 'Freedom0010', value: 1, symbolSize: 10 },
{ category: '消极', name: '醉逍遥6519280886', value: 1, symbolSize: 10 },
{ category: '积极', name: '小张很糊涂', value: 1, symbolSize: 10 },
{ category: '消极', name: '山竹丸', value: 1, symbolSize: 10 },
{ category: '积极', name: 'URYTSTYH', value: 1, symbolSize: 10 },
{ category: '消极', name: '唸唸唸奴嬌', value: 1, symbolSize: 10 },
{ category: '积极', name: '段阿紫紫紫', value: 1, symbolSize: 10 },
{ category: '积极', name: '期货萌新V', value: 1, symbolSize: 10 },
{ category: '积极', name: '期货萌新', value: 2, symbolSize: 10 },
{ category: '消极', name: '乌龟骑脚踏车', value: 1, symbolSize: 10 },
{ category: '中立', name: 'saki300', value: 1, symbolSize: 10 },
{ category: '积极', name: '纳兰性德·容若', value: 1, symbolSize: 10 },
{ category: '积极', name: '一路上有你ZL', value: 1, symbolSize: 10 },
{ category: '中立', name: '小屁孩我爱', value: 1, symbolSize: 10 },
{ category: '积极', name: '奋斗怪青年', value: 1, symbolSize: 10 },
{ category: '积极', name: '武汉二手车生产队', value: 1, symbolSize: 10 },
{ category: '积极', name: '一句话入你心', value: 1, symbolSize: 10 },
{ category: '积极', name: '李淳风L', value: 1, symbolSize: 10 },
{ category: '积极', name: 'Commonpeople1991', value: 1, symbolSize: 10 },
{ category: '积极', name: '与孙先生异地恋的倒数呀', value: 1, symbolSize: 10 },
{ category: '中立', name: '臧柳升', value: 1, symbolSize: 10 },
{ category: '积极', name: '太厚', value: 1, symbolSize: 10 },
{ category: '积极', name: '醒麻皮别闹', value: 1, symbolSize: 10 },
{ category: '积极', name: '中国日报', value: 46, symbolSize: 60,
label: {
        show: true,
        color: "#333"
    } },
{ category: '消极', name: '栀这同轩上', value: 2, symbolSize: 10 },
{ category: '积极', name: 'miss叮', value: 1, symbolSize: 10 },
{ category: '消极', name: 'You-xg2020', value: 1, symbolSize: 10 },
{ category: '积极', name: '火锅和养老', value: 1, symbolSize: 10 },
{ category: '中立', name: 'XXX0004', value: 8, symbolSize: 20 },
{ category: '积极', name: '周周周清啊', value: 1, symbolSize: 10 },
{ category: '中立', name: 'YeseniaWong', value: 3, symbolSize: 10 },
{ category: '积极', name: '叶飞色', value: 1, symbolSize: 10 },
{ category: '中立', name: '道乎于心--DFYX', value: 3, symbolSize: 10 },
{ category: '消极', name: '余生一个张雲雷201011', value: 1, symbolSize: 10 },
{ category: '消极', name: '钟离白桦', value: 1, symbolSize: 10 },
{ category: '消极', name: '安之若素201002', value: 1, symbolSize: 10 },
{ category: '积极', name: '做一只狂飙的二哈', value: 1, symbolSize: 10 },
{ category: '积极', name: 'A温澜潮生0211', value: 1, symbolSize: 10 },
{ category: '积极', name: '毛兜啊', value: 3, symbolSize: 10 },
{ category: '积极', name: '战略忽悠局新闻编辑部', value: 1, symbolSize: 10 },
{ category: '积极', name: '一堆红梅', value: 5, symbolSize: 20 },
{ category: '积极', name: 'Lin林琳霖淋', value: 4, symbolSize: 20 },
{ category: '消极', name: 'actionpieforreal', value: 1, symbolSize: 10 },
{ category: '中立', name: '才华横溢的哼哼', value: 2, symbolSize: 10 },
{ category: '中立', name: '抹茶雪糕啊', value: 2, symbolSize: 10 },
{ category: '消极', name: '恰似少年1240', value: 1, symbolSize: 10 },
{ category: '中立', name: '速溶果子狸', value: 1, symbolSize: 10 },
{ category: '消极', name: '菠萝啊哈嘿', value: 1, symbolSize: 10 },
{ category: '积极', name: 'WQGMLLY', value: 1, symbolSize: 10 },
{ category: '积极', name: '不雅一一', value: 1, symbolSize: 10 },
{ category: '积极', name: '见了鬼的大柠檬', value: 1, symbolSize: 10 },
{ category: '中立', name: '你们熬夜但我不', value: 1, symbolSize: 10 },
{ category: '积极', name: '王桐赫', value: 2, symbolSize: 10 },
{ category: '中立', name: '湖北人民加油哇', value: 1, symbolSize: 10 },
{ category: '积极', name: '期货修道院', value: 1, symbolSize: 10 },
{ category: '积极', name: '考上中传再改名', value: 1, symbolSize: 10 },
{ category: '积极', name: '用户phrlw5iktp', value: 1, symbolSize: 10 },
{ category: '积极', name: '我是盖世英雄lerry', value: 1, symbolSize: 10 },
{ category: '消极', name: 'Rain丶stray', value: 1, symbolSize: 10 },
{ category: '中立', name: 'connietable', value: 1, symbolSize: 10 },
{ category: '积极', name: '九州微言', value: 1, symbolSize: 10 },
{ category: '消极', name: '神楽殁兮丶', value: 2, symbolSize: 10 },
{ category: '积极', name: '皓奇君', value: 1, symbolSize: 10 },
{ category: '积极', name: '金bulingbum', value: 1, symbolSize: 10 },
{ category: '消极', name: '天下一人·', value: 1, symbolSize: 10 },
{ category: '积极', name: 'M傻天真作业什么的都去', value: 2, symbolSize: 10 },
{ category: '积极', name: '燕西紫苏', value: 1, symbolSize: 10 },
{ category: '积极', name: 'JWZ的喽哈菜', value: 1, symbolSize: 10 },
{ category: '积极', name: 'Tiunl', value: 3, symbolSize: 10 },
{ category: '中立', name: '嘉尔灼桃', value: 1, symbolSize: 10 },
{ category: '积极', name: '真名都能被抢占', value: 1, symbolSize: 10 },
{ category: '积极', name: 'Mr杰森哥', value: 1, symbolSize: 10 },
{ category: '积极', name: 'Minoz·Zz玲玲kL', value: 1, symbolSize: 10 },
{ category: '消极', name: 'A0殊途', value: 1, symbolSize: 10 },
{ category: '积极', name: '羊角Chips', value: 3, symbolSize: 10 },
{ category: '积极', name: '污鸡汤大表哥', value: 1, symbolSize: 10 },
{ category: '中立', name: '狂揍小豆', value: 1, symbolSize: 10 },
{ category: '积极', name: '未来的东东东', value: 1, symbolSize: 10 },
{ category: '中立', name: '泽越先生啊', value: 1, symbolSize: 10 },
{ category: '中立', name: 'DangDangJ_Elva', value: 1, symbolSize: 10 },
{ category: '消极', name: '秋风的芦笛', value: 1, symbolSize: 10 },
{ category: '积极', name: 'CATAN-T', value: 2, symbolSize: 10 },
{ category: '积极', name: '帝幻锁死fp吹爆', value: 1, symbolSize: 10 },
{ category: '积极', name: '医美吖-', value: 1, symbolSize: 10 },
{ category: '中立', name: 'starlight-晗', value: 1, symbolSize: 10 },
{ category: '积极', name: '础础_进口冷榨椰子油', value: 1, symbolSize: 10 },
{ category: '积极', name: '中国新闻周刊', value: 32, symbolSize: 50,
label: {
        show: true,
        color: "#333"
    } },
{ category: '积极', name: '孟门江氏', value: 2, symbolSize: 10 },
{ category: '积极', name: '临蒙橙橙', value: 2, symbolSize: 10 },
{ category: '积极', name: 'jm庸人', value: 1, symbolSize: 10 },
{ category: '积极', name: '吕小菜-Lin', value: 1, symbolSize: 10 },
{ category: '中立', name: '改来改去没得改', value: 1, symbolSize: 10 },
{ category: '中立', name: '谭嗣侗', value: 2, symbolSize: 10 },
{ category: '消极', name: '不是酸奶·', value: 1, symbolSize: 10 },
{ category: '中立', name: '仓鼠仓鼠开飞机的仓鼠', value: 1, symbolSize: 10 },
{ category: '积极', name: 'vs麦兜儿', value: 1, symbolSize: 10 },
{ category: '消极', name: '城市调查局', value: 1, symbolSize: 10 },
{ category: '消极', name: '小图图tututu', value: 1, symbolSize: 10 },
{ category: '中立', name: '落花公子2020', value: 1, symbolSize: 10 },
{ category: '积极', name: '只做不寻的人', value: 1, symbolSize: 10 },
{ category: '积极', name: '香菜全球粉丝后援会会长', value: 2, symbolSize: 10 },
{ category: '积极', name: '恋上寳寳', value: 1, symbolSize: 10 },
{ category: '中立', name: '韩77_', value: 1, symbolSize: 10 },
{ category: '积极', name: '王同学windy', value: 2, symbolSize: 10 },
{ category: '积极', name: '企鹅电竞哒哒', value: 1, symbolSize: 10 },
{ category: '消极', name: '未别离c', value: 1, symbolSize: 10 },
{ category: '消极', name: '林夕pan', value: 1, symbolSize: 10 },
{ category: '消极', name: '166的小气鬼', value: 2, symbolSize: 10 },
{ category: '消极', name: 'Inshairstyles', value: 1, symbolSize: 10 },
{ category: '积极', name: '秋风袅袅夕阳红', value: 1, symbolSize: 10 },
{ category: '积极', name: '上官明月5520715315', value: 1, symbolSize: 10 },
{ category: '消极', name: '今天阿白爬窗格了吗', value: 1, symbolSize: 10 },
{ category: '中立', name: '普宁市代办员', value: 1, symbolSize: 10 },
{ category: '中立', name: '飞侠哎呦喂', value: 1, symbolSize: 10 },
{ category: '中立', name: '可乐硬糖', value: 1, symbolSize: 10 },
{ category: '中立', name: '小曾73074', value: 1, symbolSize: 10 },
{ category: '积极', name: '丅lemontree_', value: 1, symbolSize: 10 },
{ category: '中立', name: 'hyjq314', value: 1, symbolSize: 10 },
{ category: '消极', name: '蜉蝣不耀眼', value: 1, symbolSize: 10 },
{ category: '积极', name: '同学刘蒙蒙', value: 1, symbolSize: 10 },
{ category: '中立', name: '提笔ding乾坤', value: 1, symbolSize: 10 },
{ category: '中立', name: '小湾湾wanwan', value: 1, symbolSize: 10 },
        ],
        links: [ // 设置连线edges的数据
            { source: 'lolo521345', target: '头条新闻', value: 1 },
{ source: 'CHEN七又二分之一', target: '张日龙在熬鷄汤', value: 2 },
{ source: '张日龙在熬鷄汤', target: 'CHEN七又二分之一', value: 2 },
{ source: 'CHEN七又二分之一', target: 'CHEN七又二分之一', value: 1 },
{ source: 'CHEN七又二分之一', target: '李隶浩', value: 1 },
{ source: '驾校同学74977', target: '头条新闻', value: 1 },
{ source: '张潮洋', target: '脱单奔现社', value: 1 },
{ source: '张潮洋', target: '头条新闻', value: 2 },
{ source: '每天一个小目标哦', target: 'Dingdu叮嘟', value: 2 },
{ source: '泣血一梦解千愁', target: '头条新闻', value: 1 },
{ source: 'Dingdu叮嘟', target: '每天一个小目标哦', value: 1 },
{ source: '唯物辩证阿尔德', target: '头条新闻', value: 1 },
{ source: 'rattyraet', target: 'PdsS', value: 1 },
{ source: '会飞的小鹌鹑_', target: '头条新闻', value: 1 },
{ source: '痞人私人专属03', target: '头条新闻', value: 1 },
{ source: '你自己想吧201911', target: '头条新闻', value: 1 },
{ source: '一只轮回', target: 'Vans-匡威-工-厂-店--', value: 1 },
{ source: '张日龙在熬鷄汤', target: 'Dingdu叮嘟', value: 5 },
{ source: 'Dingdu叮嘟', target: '张日龙在熬鷄汤', value: 2 },
{ source: '唐斩俗叔', target: '头条新闻', value: 1 },
{ source: '哎呀咿呀耳语呢喃', target: '头条新闻', value: 1 },
{ source: '北俱无聊者', target: '头条新闻', value: 1 },
{ source: '上发条的猴子', target: '头条新闻', value: 1 },
{ source: 'TonyLau1981', target: '头条新闻', value: 1 },
{ source: '李少林林', target: '头条新闻', value: 1 },
{ source: 'hi張陽', target: '头条新闻', value: 1 },
{ source: '南栀沁寒sun', target: '夜神月455', value: 1 },
{ source: '土申哆哆', target: '头条新闻', value: 1 },
{ source: 'Dingdu叮嘟', target: '在云海相望', value: 1 },
{ source: '彬彬胡呀', target: '头条新闻', value: 1 },
{ source: '青羽米兔', target: '头条新闻', value: 1 },
{ source: '踏水_无痕', target: '脱单奔现社', value: 1 },
{ source: '开欲燃', target: '牧天Mutian', value: 1 },
{ source: 'fenggewo', target: '二次元的二', value: 1 },
{ source: 'SWMHH', target: '头条新闻', value: 1 },
{ source: '玉雪纷飞飞', target: '头条新闻', value: 1 },
{ source: '比奥利奥还ao的姑娘', target: '头条新闻', value: 1 },
{ source: '殷小迪', target: '头条新闻', value: 1 },
{ source: '樱顶老法师', target: '头条新闻', value: 1 },
{ source: 'tyn宝宝贝呀', target: '头条新闻', value: 1 },
{ source: 'xx是春风', target: '头条新闻', value: 1 },
{ source: '雪若王', target: '脱单奔现社', value: 1 },
{ source: '-刘户口-', target: '头条新闻', value: 1 },
{ source: '悲观的乐观dimi', target: '头条新闻', value: 1 },
{ source: '梅梢玲萧', target: '头条新闻', value: 1 },
{ source: '胡元阿', target: '头条新闻', value: 2 },
{ source: '二-200004', target: '头条新闻', value: 1 },
{ source: '张日龙在熬鷄汤', target: '牧天Mutian', value: 1 },
{ source: '天空宠儿呀', target: '头条新闻', value: 1 },
{ source: '我要rushB了', target: '沈阗求约稿', value: 1 },
{ source: '大钰儿', target: '头条新闻', value: 1 },
{ source: '孤独诗意', target: '头条新闻', value: 1 },
{ source: '书生-问道', target: '头条新闻', value: 1 },
{ source: '我要rushB了', target: '脱单奔现社', value: 1 },
{ source: '优雅的污粑粑', target: '沈阗求约稿', value: 1 },
{ source: '怪脾气的胡萝卜', target: 'heygirl-ya', value: 2 },
{ source: '就是小迷妹啊', target: '头条新闻', value: 1 },
{ source: 'heygirl-ya', target: '怪脾气的胡萝卜', value: 1 },
{ source: '屋顶上散步的人', target: '头条新闻', value: 1 },
{ source: '我行我素-E63', target: '在云海相望', value: 1 },
{ source: '在云海相望', target: 'Dingdu叮嘟', value: 1 },
{ source: '怪脾气的胡萝卜', target: '头条新闻', value: 1 },
{ source: '起你妹名字啊', target: '老年人李冠杰', value: 1 },
{ source: '晋太元中0152', target: 'Dingdu叮嘟', value: 1 },
{ source: '先森您是喜脉啊', target: '沈阗求约稿', value: 1 },
{ source: '老年人李冠杰', target: '起你妹名字啊', value: 1 },
{ source: '一只仙女turbo', target: '头条新闻', value: 1 },
{ source: '先森您是喜脉啊', target: '脱单奔现社', value: 1 },
{ source: '在云海相望', target: '脱单奔现社', value: 1 },
{ source: '好多二妮', target: '头条新闻', value: 1 },
{ source: '拾光流年ya', target: '沈阗求约稿', value: 1 },
{ source: 'Mike涛_', target: '头条新闻', value: 1 },
{ source: '墨离莫失', target: '沈阗求约稿', value: 1 },
{ source: '徐kellen', target: '头条新闻', value: 1 },
{ source: '番茄小肥羊_', target: '头条新闻', value: 1 },
{ source: '李隶浩', target: 'CHEN七又二分之一', value: 1 },
{ source: '月半小夜曲丹', target: '牧天Mutian', value: 1 },
{ source: '吃大份的', target: '头条新闻', value: 1 },
{ source: '西子捺', target: '头条新闻', value: 1 },
{ source: '小刘冲鸭最棒棒', target: '沈阗求约稿', value: 1 },
{ source: '人可可每天都不非', target: '头条新闻', value: 1 },
{ source: '张日龙在熬鷄汤', target: '沈阗求约稿', value: 1 },
{ source: '小刘冲鸭最棒棒', target: '脱单奔现社', value: 1 },
{ source: 'SugarPlummmm', target: '沈阗求约稿', value: 1 },
{ source: '铁铁铁铁铁鱼', target: '头条新闻', value: 1 },
{ source: '二次元的二', target: 'fenggewo', value: 1 },
{ source: '笑笑笑笑笑笑够了就睡了', target: '头条新闻', value: 1 },
{ source: '臭鹏鹏Eddie', target: '头条新闻', value: 1 },
{ source: '随遇而安53744', target: 'Dingdu叮嘟', value: 1 },
{ source: '依依西望', target: '头条新闻', value: 1 },
{ source: '大见家的田田', target: 'Samantha_wan', value: 2 },
{ source: 'Champagne啊', target: '有态度的喵喵大人', value: 2 },
{ source: 'Alloycius', target: '头条新闻', value: 1 },
{ source: 'Samantha_wan', target: '大见家的田田', value: 1 },
{ source: '张日龙在熬鷄汤', target: '好起来了憨憨', value: 1 },
{ source: '我不是康利同學', target: '有态度的喵喵大人', value: 1 },
{ source: 'Samantha_wan', target: '鼓手E939', value: 1 },
{ source: '惠翎Whitney', target: '头条新闻', value: 1 },
{ source: '夜神月455', target: 'Dingdu叮嘟', value: 1 },
{ source: '肉肉肥新', target: '是甜菜叶子', value: 2 },
{ source: '有态度的喵喵大人', target: 'Champagne啊', value: 1 },
{ source: 'Merry7you', target: '头条新闻', value: 1 },
{ source: 'Samantha_wan', target: '有态度的喵喵大人', value: 2 },
{ source: '我要去找你43', target: '头条新闻', value: 1 },
{ source: '字母数字控N', target: '菩萨保佑868686', value: 1 },
{ source: '鼓手E939', target: 'Samantha_wan', value: 1 },
{ source: '阿狸要天天开心', target: '沈阗求约稿', value: 1 },
{ source: '是甜菜叶子', target: '肉肉肥新', value: 1 },
{ source: '有态度的喵喵大人', target: 'Samantha_wan', value: 2 },
{ source: 'Champagne啊', target: '头条新闻', value: 1 },
{ source: '阿狸要天天开心', target: 'Dingdu叮嘟', value: 1 },
{ source: '喝着可乐的孔明先生', target: '头条新闻', value: 1 },
{ source: 'Crazyspud', target: '头条新闻', value: 1 },
{ source: '有态度的喵喵大人', target: '头条新闻', value: 5 },
{ source: '一个大朋友la', target: '头条新闻', value: 1 },
{ source: '阿狸要天天开心', target: '脱单奔现社', value: 1 },
{ source: 'd属于你的我', target: '头条新闻', value: 1 },
{ source: 'StellaSuxx', target: '头条新闻', value: 1 },
{ source: '兴化新鲜事', target: '头条新闻', value: 1 },
{ source: 'Samantha_wan', target: '好起来了憨憨', value: 1 },
{ source: 'Lese删除站', target: '头条新闻', value: 1 },
{ source: '十一点十八分00', target: '头条新闻', value: 1 },
{ source: '冰可樂走冰1127', target: '有态度的喵喵大人', value: 1 },
{ source: '非草木人', target: '头条新闻', value: 1 },
{ source: 'mangomxx', target: '头条新闻', value: 2 },
{ source: '大可VVV', target: '头条新闻', value: 1 },
{ source: '起你妹名字啊', target: '垚士555', value: 3 },
{ source: '海盐berry布丁', target: '头条新闻', value: 1 },
{ source: '垚士555', target: '起你妹名字啊', value: 2 },
{ source: '起风了943', target: '头条新闻', value: 1 },
{ source: '超酷的毒鸡汤大叔', target: '四川轻化工Levy', value: 1 },
{ source: '唯有暴富能解忧愁', target: '头条新闻', value: 1 },
{ source: '冰可樂走冰1127', target: '脱单奔现社', value: 1 },
{ source: '非野飒', target: '三皮皮012', value: 1 },
{ source: 'Gravity_Falls_', target: '同学大蒜吐你一口大粘痰', value: 1 },
{ source: 'Someone05333', target: '头条新闻', value: 1 },
{ source: '三皮皮012', target: '非野飒', value: 1 },
{ source: '用户dyesj8l9ol', target: '非野飒', value: 1 },
{ source: '六火六火', target: '头条新闻', value: 1 },
{ source: 'Gravity_Falls_', target: '非野飒', value: 1 },
{ source: '风过落影rai', target: '头条新闻', value: 1 },
{ source: '用户dyesj8l9ol', target: '头条新闻', value: 1 },
{ source: '口十蕾llll', target: '头条新闻', value: 1 },
{ source: 'yes是我W', target: '头条新闻', value: 1 },
{ source: '鹿岚i', target: '头条新闻', value: 1 },
{ source: '睿爷的爷', target: '头条新闻', value: 1 },
{ source: 'sailingyu322', target: '头条新闻', value: 1 },
{ source: 'Siven_Han', target: '头条新闻', value: 1 },
{ source: '晓秋君尔', target: '头条新闻', value: 1 },
{ source: '香菜全球粉丝后援会会长', target: 'One_Chou', value: 1 },
{ source: 'Hsia小超', target: '头条新闻', value: 1 },
{ source: '你就是演技好', target: '脱单奔现社', value: 1 },
{ source: '同学大蒜吐你一口大粘痰', target: '头条新闻', value: 1 },
{ source: '柳随风', target: '头条新闻', value: 1 },
{ source: '张日龙在熬鷄汤', target: '一个二毫六', value: 1 },
{ source: '芝士布丁配冰棍', target: '起你妹名字啊', value: 7 },
{ source: '非野飒', target: '好起来了憨憨', value: 1 },
{ source: '芝士榴莲cj', target: 'Dingdu叮嘟', value: 1 },
{ source: '起你妹名字啊', target: '芝士布丁配冰棍', value: 6 },
{ source: '虎牙君233', target: '头条新闻', value: 1 },
{ source: '长风渡', target: '沈阗求约稿', value: 1 },
{ source: '天蝎sG', target: '头条新闻', value: 1 },
{ source: 'Summer-1928', target: '头条新闻', value: 1 },
{ source: '台州椒江扫一扫家政', target: '头条新闻', value: 1 },
{ source: '长风渡', target: '脱单奔现社', value: 1 },
{ source: '笑看社会不看股市', target: '头条新闻', value: 1 },
{ source: '一年只能修改一次先用一年', target: '脱单奔现社', value: 1 },
{ source: '擤擤Ma爱喝粥', target: '头条新闻', value: 1 },
{ source: '早睡早起身体好不秃头', target: '头条新闻', value: 1 },
{ source: '张日龙在熬鷄汤', target: '头条新闻', value: 1 },
{ source: '一个二毫六', target: '张日龙在熬鷄汤', value: 1 },
{ source: '青我你他', target: '头条新闻', value: 1 },
{ source: '冷冷酷酷不穿秋裤', target: 'Dingdu叮嘟', value: 1 },
{ source: '谁的韭菜啊', target: '头条新闻', value: 1 },
{ source: '拉忽酱', target: '头条新闻', value: 1 },
{ source: '黑人张t', target: '头条新闻', value: 1 },
{ source: '阿简zj', target: '头条新闻', value: 2 },
{ source: '晒太阳看大海', target: '头条新闻', value: 1 },
{ source: '四川轻化工Levy', target: '头条新闻', value: 1 },
{ source: '芝士布丁配冰棍', target: '芝士布丁配冰棍', value: 1 },
{ source: '宅宅在家睡大觉', target: '杨牧笛1935969121', value: 1 },
{ source: '小虫虫呀', target: 'heygirl-ya', value: 1 },
{ source: '起你妹名字啊', target: 'zytcool', value: 8 },
{ source: '动感光波-bi6238', target: '头条新闻', value: 1 },
{ source: '是甜菜叶子', target: '牧天Mutian', value: 1 },
{ source: 'One_Chou', target: '头条新闻', value: 2 },
{ source: '冷凝集试验', target: '头条新闻', value: 1 },
{ source: 'heygirl-ya', target: '小虫虫呀', value: 1 },
{ source: '番薯妹-Fei', target: 'Dingdu叮嘟', value: 1 },
{ source: 'zytcool', target: '起你妹名字啊', value: 9 },
{ source: '莹-silence', target: '头条新闻', value: 1 },
{ source: '科二挂科', target: '头条新闻', value: 1 },
{ source: '徽虎子', target: '头条新闻', value: 1 },
{ source: '杨牧笛1935969121', target: '头条新闻', value: 1 },
{ source: '刘刘yuki', target: '头条新闻', value: 1 },
{ source: 'Rachel-courage', target: '头条新闻', value: 1 },
{ source: '张日龙在熬鸡杨', target: '头条新闻', value: 1 },
{ source: '心内一米', target: '头条新闻', value: 1 },
{ source: '-朴实-无华', target: '头条新闻', value: 1 },
{ source: '起你妹名字啊', target: '脱单奔现社', value: 2 },
{ source: '西贝蓉儿', target: '头条新闻', value: 1 },
{ source: '装修苏小哥', target: '头条新闻', value: 1 },
{ source: 'CHEN七又二分之一', target: 'ailsa1345', value: 1 },
{ source: '食肉目的叛徒', target: '头条新闻', value: 1 },
{ source: '果塘湖的夏天', target: '头条新闻', value: 1 },
{ source: '揣着意大利炮的二营长', target: '头条新闻', value: 1 },
{ source: '树里潜龙', target: '头条新闻', value: 1 },
{ source: '起你妹名字啊', target: '杨瑞哇啦啦', value: 1 },
{ source: '反正记不住何必想这个昵称的意义', target: '头条新闻', value: 1 },
{ source: '杨瑞哇啦啦', target: '起你妹名字啊', value: 1 },
{ source: '义特别', target: '头条新闻', value: 1 },
{ source: '杨瑞哇啦啦', target: '头条新闻', value: 1 },
{ source: '纸重江湖', target: '头条新闻', value: 1 },
{ source: '起你妹名字啊', target: 'fenggewo', value: 1 },
{ source: '芝士布丁配冰棍', target: 'fenggewo', value: 1 },
{ source: '额就是个普通人', target: '脱单奔现社', value: 1 },
{ source: '·福气满满·', target: '头条新闻', value: 1 },
{ source: '谦虚认真努力yz', target: '脱单奔现社', value: 1 },
{ source: 'ZoeMiu-', target: '头条新闻', value: 1 },
{ source: 'zyhh121', target: '头条新闻', value: 1 },
{ source: '阿米米尼', target: '头条新闻', value: 1 },
{ source: '0寂寞的云0', target: '头条新闻', value: 1 },
{ source: 'fenggewo', target: '起你妹名字啊', value: 1 },
{ source: '吹吹冷风2017', target: '头条新闻', value: 1 },
{ source: 'Miraculous_BK', target: '头条新闻', value: 1 },
{ source: '猫九动次胖次', target: '头条新闻', value: 1 },
{ source: 'Lilylovechili', target: '头条新闻', value: 1 },
{ source: '许肉肉先生', target: '头条新闻', value: 1 },
{ source: 'Dingdu叮嘟', target: '头条新闻', value: 1 },
{ source: '深夜里的袍哥人家', target: '脱单奔现社', value: 1 },
{ source: 'qwerqwre1', target: '头条新闻', value: 1 },
{ source: 'PdsS', target: '头条新闻', value: 1 },
{ source: '军令部长', target: '头条新闻', value: 1 },
{ source: '小张在线被锤', target: '头条新闻', value: 1 },
{ source: '鸡腿你干嘛', target: '头条新闻', value: 1 },
{ source: '把时间停住', target: '头条新闻', value: 1 },
{ source: '大了个清儿', target: '头条新闻', value: 1 },
{ source: '99得81', target: '头条新闻', value: 1 },
{ source: '菩萨保佑868686', target: '头条新闻', value: 1 },
{ source: 'CHEN七又二分之一', target: '脱单奔现社', value: 1 },
{ source: 'Freedom0010', target: '头条新闻', value: 1 },
{ source: '醉逍遥6519280886', target: '头条新闻', value: 1 },
{ source: '小张很糊涂', target: '头条新闻', value: 1 },
{ source: '山竹丸', target: '头条新闻', value: 1 },
{ source: 'ailsa1345', target: '头条新闻', value: 1 },
{ source: 'URYTSTYH', target: '头条新闻', value: 1 },
{ source: '唸唸唸奴嬌', target: '头条新闻', value: 1 },
{ source: '段阿紫紫紫', target: '头条新闻', value: 1 },
{ source: 'zytcool', target: '头条新闻', value: 1 },
{ source: '期货萌新V', target: '期货萌新', value: 1 },
{ source: '小虫虫呀', target: '头条新闻', value: 1 },
{ source: '乌龟骑脚踏车', target: '头条新闻', value: 1 },
{ source: 'saki300', target: '头条新闻', value: 1 },
{ source: 'Vans-匡威-工-厂-店--', target: '头条新闻', value: 1 },
{ source: '纳兰性德·容若', target: '头条新闻', value: 1 },
{ source: '脱单奔现社', target: '头条新闻', value: 1 },
{ source: '一路上有你ZL', target: '头条新闻', value: 1 },
{ source: '小屁孩我爱', target: '头条新闻', value: 1 },
{ source: '奋斗怪青年', target: '头条新闻', value: 1 },
{ source: '武汉二手车生产队', target: '头条新闻', value: 1 },
{ source: '一句话入你心', target: '头条新闻', value: 1 },
{ source: '李淳风L', target: '头条新闻', value: 1 },
{ source: 'Commonpeople1991', target: '头条新闻', value: 1 },
{ source: '与孙先生异地恋的倒数呀', target: '头条新闻', value: 1 },
{ source: '臧柳升', target: '头条新闻', value: 1 },
{ source: '太厚', target: '头条新闻', value: 1 },
{ source: '醒麻皮别闹', target: '中国日报', value: 1 },
{ source: '栀这同轩上', target: '栀这同轩上', value: 1 },
{ source: '栀这同轩上', target: '中国日报', value: 1 },
{ source: 'miss叮', target: '中国日报', value: 2 },
{ source: 'You-xg2020', target: '中国日报', value: 1 },
{ source: '火锅和养老', target: 'XXX0004', value: 1 },
{ source: '周周周清啊', target: 'YeseniaWong', value: 1 },
{ source: '叶飞色', target: '道乎于心--DFYX', value: 1 },
{ source: 'mangomxx', target: '中国日报', value: 1 },
{ source: '期货萌新V', target: 'mangomxx', value: 1 },
{ source: '余生一个张雲雷201011', target: '中国日报', value: 1 },
{ source: '钟离白桦', target: '中国日报', value: 1 },
{ source: '安之若素201002', target: '中国日报', value: 1 },
{ source: '做一只狂飙的二哈', target: '中国日报', value: 1 },
{ source: 'A温澜潮生0211', target: '毛兜啊', value: 1 },
{ source: '战略忽悠局新闻编辑部', target: '一堆红梅', value: 1 },
{ source: 'XXX0004', target: 'Lin林琳霖淋', value: 3 },
{ source: 'Lin林琳霖淋', target: 'XXX0004', value: 3 },
{ source: 'actionpieforreal', target: '中国日报', value: 1 },
{ source: 'XXX0004', target: '才华横溢的哼哼', value: 1 },
{ source: 'XXX0004', target: '抹茶雪糕啊', value: 1 },
{ source: '恰似少年1240', target: '中国日报', value: 1 },
{ source: '速溶果子狸', target: '道乎于心--DFYX', value: 1 },
{ source: '菠萝啊哈嘿', target: '中国日报', value: 1 },
{ source: 'WQGMLLY', target: '中国日报', value: 1 },
{ source: '不雅一一', target: '中国日报', value: 1 },
{ source: '抹茶雪糕啊', target: 'XXX0004', value: 1 },
{ source: '见了鬼的大柠檬', target: '中国日报', value: 1 },
{ source: '你们熬夜但我不', target: '王桐赫', value: 1 },
{ source: '湖北人民加油哇', target: '中国日报', value: 1 },
{ source: '期货修道院', target: '中国日报', value: 1 },
{ source: '考上中传再改名', target: '中国日报', value: 1 },
{ source: '用户phrlw5iktp', target: '中国日报', value: 1 },
{ source: '我是盖世英雄lerry', target: '一堆红梅', value: 1 },
{ source: 'Rain丶stray', target: '毛兜啊', value: 1 },
{ source: 'connietable', target: '一堆红梅', value: 1 },
{ source: '才华横溢的哼哼', target: 'YeseniaWong', value: 1 },
{ source: '才华横溢的哼哼', target: 'XXX0004', value: 1 },
{ source: '毛兜啊', target: '中国日报', value: 1 },
{ source: '九州微言', target: '神楽殁兮丶', value: 1 },
{ source: '皓奇君', target: '中国日报', value: 1 },
{ source: '九州微言', target: 'XXX0004', value: 1 },
{ source: '金bulingbum', target: '中国日报', value: 1 },
{ source: '天下一人·', target: 'M傻天真作业什么的都去', value: 1 },
{ source: '天下一人·', target: '一堆红梅', value: 1 },
{ source: '燕西紫苏', target: '中国日报', value: 1 },
{ source: 'JWZ的喽哈菜', target: 'Tiunl', value: 1 },
{ source: '嘉尔灼桃', target: '中国日报', value: 1 },
{ source: '真名都能被抢占', target: '中国日报', value: 1 },
{ source: '王桐赫', target: '中国日报', value: 1 },
{ source: 'Mr杰森哥', target: '中国日报', value: 1 },
{ source: 'Minoz·Zz玲玲kL', target: '中国日报', value: 1 },
{ source: '一堆红梅', target: '中国日报', value: 1 },
{ source: 'YeseniaWong', target: '中国日报', value: 1 },
{ source: 'A0殊途', target: '中国日报', value: 1 },
{ source: 'Tiunl', target: '羊角Chips', value: 1 },
{ source: '羊角Chips', target: '羊角Chips', value: 1 },
{ source: '污鸡汤大表哥', target: '中国日报', value: 1 },
{ source: '羊角Chips', target: 'Tiunl', value: 1 },
{ source: '狂揍小豆', target: '中国日报', value: 1 },
{ source: '未来的东东东', target: '中国日报', value: 1 },
{ source: '泽越先生啊', target: '中国日报', value: 1 },
{ source: 'Tiunl', target: '中国日报', value: 1 },
{ source: '神楽殁兮丶', target: '中国日报', value: 1 },
{ source: 'DangDangJ_Elva', target: '中国日报', value: 1 },
{ source: '秋风的芦笛', target: 'CATAN-T', value: 1 },
{ source: '道乎于心--DFYX', target: '中国日报', value: 1 },
{ source: '帝幻锁死fp吹爆', target: '中国日报', value: 1 },
{ source: 'XXX0004', target: '中国日报', value: 1 },
{ source: 'M傻天真作业什么的都去', target: '中国日报', value: 1 },
{ source: '医美吖-', target: '中国日报', value: 1 },
{ source: 'CATAN-T', target: '中国日报', value: 1 },
{ source: 'starlight-晗', target: '中国日报', value: 1 },
{ source: '础础_进口冷榨椰子油', target: '中国新闻周刊', value: 1 },
{ source: '孟门江氏', target: '临蒙橙橙', value: 1 },
{ source: 'jm庸人', target: '中国新闻周刊', value: 1 },
{ source: '吕小菜-Lin', target: '中国新闻周刊', value: 1 },
{ source: '改来改去没得改', target: '谭嗣侗', value: 1 },
{ source: '不是酸奶·', target: '中国新闻周刊', value: 1 },
{ source: '仓鼠仓鼠开飞机的仓鼠', target: '中国新闻周刊', value: 1 },
{ source: 'vs麦兜儿', target: '中国新闻周刊', value: 1 },
{ source: '城市调查局', target: '中国新闻周刊', value: 1 },
{ source: '小图图tututu', target: '中国新闻周刊', value: 1 },
{ source: '临蒙橙橙', target: '中国新闻周刊', value: 1 },
{ source: '落花公子2020', target: '中国新闻周刊', value: 1 },
{ source: '只做不寻的人', target: '香菜全球粉丝后援会会长', value: 1 },
{ source: '恋上寳寳', target: '中国新闻周刊', value: 1 },
{ source: '韩77_', target: '王同学windy', value: 1 },
{ source: '企鹅电竞哒哒', target: '中国新闻周刊', value: 1 },
{ source: '未别离c', target: '中国新闻周刊', value: 1 },
{ source: '林夕pan', target: '166的小气鬼', value: 1 },
{ source: 'Inshairstyles', target: '中国新闻周刊', value: 1 },
{ source: '秋风袅袅夕阳红', target: '中国新闻周刊', value: 1 },
{ source: '王同学windy', target: '中国新闻周刊', value: 1 },
{ source: '谭嗣侗', target: '中国新闻周刊', value: 1 },
{ source: '上官明月5520715315', target: '中国新闻周刊', value: 1 },
{ source: '今天阿白爬窗格了吗', target: '孟门江氏', value: 1 },
{ source: '普宁市代办员', target: '中国新闻周刊', value: 1 },
{ source: '飞侠哎呦喂', target: '中国新闻周刊', value: 1 },
{ source: '可乐硬糖', target: '中国新闻周刊', value: 1 },
{ source: '小曾73074', target: '中国新闻周刊', value: 1 },
{ source: '丅lemontree_', target: '中国新闻周刊', value: 1 },
{ source: 'hyjq314', target: '中国新闻周刊', value: 1 },
{ source: '香菜全球粉丝后援会会长', target: '中国新闻周刊', value: 1 },
{ source: '蜉蝣不耀眼', target: '中国新闻周刊', value: 1 },
{ source: '孟门江氏', target: '中国新闻周刊', value: 1 },
{ source: '166的小气鬼', target: '中国新闻周刊', value: 1 },
{ source: '同学刘蒙蒙', target: '中国新闻周刊', value: 1 },
{ source: '提笔ding乾坤', target: '中国新闻周刊', value: 1 },
{ source: '小湾湾wanwan', target: '中国新闻周刊', value: 1 }
        ]
    }]
};