var result = {
    "data": [
        ["Location", "Whether celebrates"],
        ["Afghanistan", "0"],
        ["Albania", "1"],
        ["Algeria", "0"],
        ["Andorra", "1"],
        ["Angola", "1"],
        ["Antigua and Barbuda", "1"],
        ["Argentina", "1"],
        ["Armenia", "1"],
        ["Australia", "1"],
        ["Austria", "1"],
        ["Azerbaijan", "0.5"],
        ["Bahamas", "1"],
        ["Bahrain", "0"],
        ["Bangladesh", "1"],
        ["Barbados", "1"],
        ["Belarus", "1"],
        ["Belgium", "1"],
        ["Belize", "1"],
        ["Benin", "1"],
        ["Bhutan", "0"],
        ["Bolivia", "1"],
        ["Bosnia and Herzegovina", "1"],
        ["Botswana", "1"],
        ["Brazil", "1"],
        ["Brunei Darussalam", "1"],
        ["Bulgaria", "1"],
        ["Burkina Faso", "1"],
        ["Burundi", "1"],
        ["Cambodia", "0.5"],
        ["Cameroon", "1"],
        ["Canada", "1"],
        ["Cape Verde", "1"],
        ["Central African Republic", "1"],
        ["Chad", "1"],
        ["Chile", "1"],
        ["China", "0.5"],
        ["Colombia", "1"],
        ["Comoros", "0"],
        ["Congo", "1"],
        ["Cook Islands", "1"],
        ["Costa Rica", "1"],
        ["Cote d'Ivoire", "1"],
        ["Croatia", "1"],
        ["Cuba", "1"],
        ["Cyprus", "1"],
        ["Czech Republic", "1"],
        ["Republic of the Congo", "1"],
        ["Democratic Republic of the Congo", "1"],
        ["Denmark", "1"],
        ["Djibouti", "1"],
        ["Dominica", "1"],
        ["Dominican Republic", "1"],
        ["Ecuador", "1"],
        ["Egypt", "1"],
        ["El Salvador", "1"],
        ["Equatorial Guinea", "1"],
        ["Eritrea", "1"],
        ["Estonia", "1"],
        ["Ethiopia", "1"],
        ["Fiji", "1"],
        ["Finland", "1"],
        ["France", "1"],
        ["Gabon", "1"],
        ["Gambia", "1"],
        ["Georgia", "1"],
        ["Germany", "1"],
        ["Ghana", "1"],
        ["Greece", "1"],
        ["Grenada", "1"],
        ["Guatemala", "1"],
        ["Guinea", "1"],
        ["Guinea Bissau", "1"],
        ["Guyana", "1"],
        ["Haiti", "1"],
        ["Honduras", "1"],
        ["Hungary", "1"],
        ["Iceland", "1"],
        ["India", "1"],
        ["Indonesia", "1"],
        ["Iran", "0.5"],
        ["Iraq", "1"],
        ["Ireland", "1"],
        ["Israel", "0"],
        ["Italy", "1"],
        ["Ivory Coast", "1"],
        ["Jamaica", "1"],
        ["Japan", "0.5"],
        ["Jordan", "1"],
        ["Kazakhstan", "1"],
        ["Kenya", "1"],
        ["Kiribati", "1"],
        ["Kuwait", "0"],
        ["Kyrgyzstan", "1"],
        ["Laos", "0"],
        ["Latvia", "1"],
        ["Lebanon", "1"],
        ["Lesotho", "1"],
        ["Liberia", "1"],
        ["Libya", "0"],
        ["Lithuania", "1"],
        ["Luxembourg", "1"],
        ["Madagascar", "1"],
        ["Malawi", "1"],
        ["Malaysia", "1"],
        ["Maldives", "0"],
        ["Mali", "1"],
        ["Malta", "1"],
        ["Marshall Islands", "1"],
        ["Mauritania", "0"],
        ["Mauritius", "1"],
        ["Mexico", "1"],
        ["Micronesia (Federated States of)", "1"],
        ["Monaco", "1"],
        ["Mongolia", "0.5"],
        ["Montenegro", "1"],
        ["Morocco", "0.5"],
        ["Mozambique", "1"],
        ["Myanmar", "1"],
        ["Namibia", "1"],
        ["Nauru", "1"],
        ["Nepal", "1"],
        ["Netherlands", "1"],
        ["New Zealand", "1"],
        ["Nicaragua", "1"],
        ["Niger", "1"],
        ["Nigeria", "1"],
        ["Niue", "1"],
        ["Norway", "1"],
        ["North Korea", "0"],
        ["Oman", "0.5"],
        ["Pakistan", "0.5"],
        ["Palau", "1"],
        ["Panama", "1"],
        ["Papua New Guinea", "1"],
        ["Paraguay", "1"],
        ["Peru", "1"],
        ["Philippines", "1"],
        ["Poland", "1"],
        ["Portugal", "1"],
        ["Qatar", "0"],
        ["Republic of Korea", "1"],
        ["Republic of Moldova", "1"],
        ["Romania", "1"],
        ["Rwanda", "1"],
        ["Saint Kitts and Nevis", "1"],
        ["Saint Lucia", "1"],
        ["Saint Vincent and the Grenadines", "1"],
        ["Samoa", "1"],
        ["San Marino", "1"],
        ["Sao Tome and Principe", "1"],
        ["Saudi Arabia", "0"],
        ["Senegal", "1"],
        ["Serbia", "1"],
        ["Seychelles", "1"],
        ["Sierra Leone", "1"],
        ["Singapore", "1"],
        ["Slovakia", "1"],
        ["Slovenia", "1"],
        ["Somaliland", "1"],
        ["Somalia", "0"],
        ["South Africa", "1"],
        ["South Korea", "1"],
        ["Spain", "1"],
        ["Sri Lanka", "1"],
        ["Sudan", "1"],
        ["South Sudan", " 1"],
        ["Suriname", "1"],
        ["Swaziland", "1"],
        ["Sweden", "1"],
        ["Switzerland", "1"],
        ["Tajikistan", "0"],
        ["Thailand", "0.5"],
        ["Timor-Leste", "1"],
        ["Togo", "1"],
        ["Tonga", "1"],
        ["Trinidad and Tobago", "1"],
        ["Tunisia", "0"],
        ["Turkey", "0.5"],
        ["Turkmenistan", "0"],
        ["Tuvalu", "1"],
        ["Uganda", "1"],
        ["Ukraine", "1"],
        ["United Arab Emirates", "0.5"],
        ["United Kingdom", "1"],
        ["Uruguay", "1"],
        ["Uzbekistan", "0"],
        ["Vanuatu", "1"],
        ["Venezuela", "1"],
        ["Vietnam", "0.5"],
        ["Yemen", "0"],
        ["Zambia", "1"],
        ["Zimbabwe", "1"],
        ["United States", "1"],
        ["United Republic of Tanzania", "1"],
        ["Macedonia", "1"],
        ["Syria", "1"],
        ["Russia", "1"],
        [""]
    ],
    "errors": [],
    "meta": {
        "delimiter": ",",
        "linebreak": "\n",
        "aborted": false,
        "truncated": false,
        "cursor": 2394
    }
};


var nameMap = {
    'United States': 'United States of America'
};
myChart.setOption({
    series: [{
        type: 'map',
        map: 'world-simp',
        silent: true,
        top: 10,
        bottom: 10,
        data: result.data.map(function(item) {
            return {
                name: nameMap[item[0]] || item[0],
                value: item[1]
            };
        }),
        itemStyle: {
            normal: {
                borderColor: 'rgba(255,255,255,0.2)'
            }
        }
    }],
    visualMap: {
        type: 'piecewise',
        min: 0,
        max: 1,
        splitNumber: 3,
        left: 'left',
        top: 'bottom',
        seriesIndex: 0,
        hoverLink: false,
        itemWidth: 15,
        textGap: 5,
        textStyle: {
            color: '#fff'
        },
        pieces: [{
            max: 0.1,
            label: '不庆祝圣诞节',
            color: '#eded7c'
        }, {
            max: 0.6,
            label: '假装过圣诞节',
            color: '#f46f62'
        }, {
            max: 1.1,
            label: '国定假日',
            color: '#e4503a'
        }]
    }
});