option = {
    backgroundColor: '#000',
    title: {
        text: "Makeup 2018",
        top: "top",
        left: "center"
    },
    tooltip: {},

    toolbox: {
        show: true,
        feature: {
            dataView: {
                show: true,
                readOnly: true
            },
            restore: {
                show: true
            },
            saveAsImage: {
                show: true
            }
        }
    },
    animationDuration: 1000,
    animationEasingUpdate: 'quinticInOut',
    series: [{
        name: '招标倾向性分析',
        type: 'graph',
        layout: 'force',

        force: {
            repulsion: 500,
            edgeLength: 120
        },
        data: [
{category: 'SET',name: 'SET',value: 60,symbolSize: 60 },
{category: 'MASK',name: 'MASK',value: 57,symbolSize: 57 },
{category: 'CREAM',name: 'CREAM',value: 54,symbolSize: 54 },
{category: 'LIP STICK',name: 'LIP STICK',value: 54,symbolSize: 54 },
{category: 'CLEANSER',name: 'CLEANSER',value: 51,symbolSize: 51 },
{category: 'SERUM',name: 'SERUM',value: 48,symbolSize: 48 },
{category: 'MU REMOVER',name: 'MU REMOVER',value: 45,symbolSize: 45 },
{category: 'EYE CARE',name: 'EYE CARE',value: 42,symbolSize: 42 },
{category: 'TONER',name: 'TONER',value: 39,symbolSize: 39 },
{category: 'FOUNDATION',name: 'FOUNDATION',value: 36,symbolSize: 36 },
{category: 'BROW',name: 'BROW',value: 21,symbolSize: 21 },
{category: 'ESS LOTION',name: 'ESS LOTION',value: 21,symbolSize: 21 },
{category: 'SUN CARE',name: 'SUN CARE',value: 9,symbolSize: 9 },
{category: 'EYESHADOW',name: 'EYESHADOW',value: 6,symbolSize: 6 },
{category: 'BLUSH',name: 'BLUSH',value: 3,symbolSize: 3 },
{category: 'EYELINER',name: 'EYELINER',value: 3,symbolSize: 3 },
{category: 'LIP LIQUID',name: 'LIP LIQUID',value: 3,symbolSize: 3 }
],
        links: [
{source: 'ESS LOTION',target: 'SERUM',value: 132},
{source: 'SERUM',target: 'ESS LOTION',value: 132},
{source: 'SERUM',target: 'CREAM',value: 122},
{source: 'CREAM',target: 'SERUM',value: 122},
{source: 'ESS LOTION',target: 'CREAM',value: 120},
{source: 'CREAM',target: 'ESS LOTION',value: 120},
{source: 'EYE CARE',target: 'SERUM',value: 116},
{source: 'SERUM',target: 'EYE CARE',value: 116},
{source: 'TONER',target: 'SERUM',value: 109},
{source: 'SERUM',target: 'TONER',value: 109},
{source: 'TONER',target: 'CREAM',value: 106},
{source: 'CREAM',target: 'TONER',value: 106},
{source: 'EYE CARE',target: 'CREAM',value: 99},
{source: 'CREAM',target: 'EYE CARE',value: 99},
{source: 'TONER',target: 'CLEANSER',value: 96},
{source: 'CLEANSER',target: 'TONER',value: 96},
{source: 'TONER',target: 'EYE CARE',value: 94},
{source: 'EYE CARE',target: 'TONER',value: 94},
{source: 'SERUM',target: 'CLEANSER',value: 89},
{source: 'CLEANSER',target: 'SERUM',value: 89},
{source: 'CREAM',target: 'CLEANSER',value: 85},
{source: 'CLEANSER',target: 'CREAM',value: 85},
{source: 'EYE CARE',target: 'CLEANSER',value: 79},
{source: 'CLEANSER',target: 'EYE CARE',value: 79},
{source: 'SERUM',target: 'SET',value: 72},
{source: 'SET',target: 'SERUM',value: 72},
{source: 'ESS LOTION',target: 'SET',value: 68},
{source: 'EYE CARE',target: 'SET',value: 67},
{source: 'SET',target: 'EYE CARE',value: 67},
{source: 'EYE CARE',target: 'MASK',value: 65},
{source: 'CREAM',target: 'SET',value: 64},
{source: 'SET',target: 'CREAM',value: 64},
{source: 'ESS LOTION',target: 'MASK',value: 63},
{source: 'TONER',target: 'SET',value: 63},
{source: 'SERUM',target: 'MASK',value: 63},
{source: 'SUN CARE',target: 'SET',value: 63},
{source: 'SUN CARE',target: 'MASK',value: 60},
{source: 'CLEANSER',target: 'SET',value: 57},
{source: 'SET',target: 'CLEANSER',value: 57},
{source: 'CREAM',target: 'MASK',value: 56},
{source: 'MASK',target: 'CREAM',value: 56},
{source: 'CLEANSER',target: 'MASK',value: 56},
{source: 'MASK',target: 'CLEANSER',value: 56},
{source: 'TONER',target: 'MASK',value: 55},
{source: 'CLEANSER',target: 'MU REMOVER',value: 54},
{source: 'MU REMOVER',target: 'CLEANSER',value: 54},
{source: 'TONER',target: 'MU REMOVER',value: 51},
{source: 'SERUM',target: 'MU REMOVER',value: 51},
{source: 'EYE CARE',target: 'MU REMOVER',value: 50},
{source: 'CREAM',target: 'MU REMOVER',value: 49},
{source: 'SET',target: 'MASK',value: 49},
{source: 'MASK',target: 'SET',value: 49},
{source: 'MU REMOVER',target: 'MASK',value: 42},
{source: 'MASK',target: 'MU REMOVER',value: 42},
{source: 'SERUM',target: 'FOUNDATION',value: 42},
{source: 'CREAM',target: 'FOUNDATION',value: 40},
{source: 'TONER',target: 'FOUNDATION',value: 39},
{source: 'MU REMOVER',target: 'SET',value: 38},
{source: 'SET',target: 'MU REMOVER',value: 38},
{source: 'EYE CARE',target: 'FOUNDATION',value: 36},
{source: 'CLEANSER',target: 'FOUNDATION',value: 34},
{source: 'EYESHADOW',target: 'MASK',value: 29},
{source: 'FOUNDATION',target: 'MU REMOVER',value: 29},
{source: 'MU REMOVER',target: 'FOUNDATION',value: 29},
{source: 'FOUNDATION',target: 'SET',value: 29},
{source: 'SET',target: 'FOUNDATION',value: 29},
{source: 'CLEANSER',target: 'BROW',value: 28},
{source: 'BROW',target: 'MU REMOVER',value: 27},
{source: 'MU REMOVER',target: 'BROW',value: 27},
{source: 'CREAM',target: 'BROW',value: 26},
{source: 'LIP LIQUID',target: 'LIP STICK',value: 26},
{source: 'FOUNDATION',target: 'MASK',value: 25},
{source: 'MASK',target: 'FOUNDATION',value: 25},
{source: 'ESS LOTION',target: 'LIP STICK',value: 25},
{source: 'SERUM',target: 'LIP STICK',value: 24},
{source: 'BROW',target: 'MASK',value: 23},
{source: 'CREAM',target: 'LIP STICK',value: 22},
{source: 'TONER',target: 'LIP STICK',value: 22},
{source: 'EYE CARE',target: 'LIP STICK',value: 22},
{source: 'EYESHADOW',target: 'LIP STICK',value: 22},
{source: 'SUN CARE',target: 'LIP STICK',value: 21},
{source: 'BLUSH',target: 'LIP STICK',value: 20},
{source: 'CLEANSER',target: 'LIP STICK',value: 20},
{source: 'BROW',target: 'SET',value: 19},
{source: 'SET',target: 'LIP STICK',value: 18},
{source: 'LIP STICK',target: 'SET',value: 18},
{source: 'MU REMOVER',target: 'LIP STICK',value: 17},
{source: 'MASK',target: 'LIP STICK',value: 17},
{source: 'LIP STICK',target: 'MASK',value: 17},
{source: 'FOUNDATION',target: 'LIP STICK',value: 11},
{source: 'EYELINER',target: 'LIP STICK',value: 10},
{source: 'BROW',target: 'LIP STICK',value: 5}
],
        categories: [
{category: 'SET',name: 'SET',value: 60,symbolSize: 60 },
{category: 'MASK',name: 'MASK',value: 57,symbolSize: 57 },
{category: 'CREAM',name: 'CREAM',value: 54,symbolSize: 54 },
{category: 'LIP STICK',name: 'LIP STICK',value: 54,symbolSize: 54 },
{category: 'CLEANSER',name: 'CLEANSER',value: 51,symbolSize: 51 },
{category: 'SERUM',name: 'SERUM',value: 48,symbolSize: 48 },
{category: 'MU REMOVER',name: 'MU REMOVER',value: 45,symbolSize: 45 },
{category: 'EYE CARE',name: 'EYE CARE',value: 42,symbolSize: 42 },
{category: 'TONER',name: 'TONER',value: 39,symbolSize: 39 },
{category: 'FOUNDATION',name: 'FOUNDATION',value: 36,symbolSize: 36 },
{category: 'BROW',name: 'BROW',value: 21,symbolSize: 21 },
{category: 'ESS LOTION',name: 'ESS LOTION',value: 21,symbolSize: 21 },
{category: 'SUN CARE',name: 'SUN CARE',value: 9,symbolSize: 9 },
{category: 'EYESHADOW',name: 'EYESHADOW',value: 6,symbolSize: 6 },
{category: 'BLUSH',name: 'BLUSH',value: 3,symbolSize: 3 },
{category: 'EYELINER',name: 'EYELINER',value: 3,symbolSize: 3 },
{category: 'LIP LIQUID',name: 'LIP LIQUID',value: 3,symbolSize: 3 }
],
        focusNodeAdjacency: true,
        roam: true,
        label: {
            normal: {
                show: true,
                position: 'top',
            }
        },
        lineStyle: {
            normal: {
                color: 'source',
                curveness: 0,
                type: "solid"
            }
        }
    }]
};