option = {
    backgroundColor: '#174B78',
     
     grid:{
            x:0,
            x2:0,
            y:0,
            y2:0
        }, 


    title: {
        text: "",
        subtext: "",
        textStyle: {
            color: "#fff",
            fontSize: 18
        },
        top: "top",
        left: "center"
    },
    tooltip: {},
    legend: {},
    toolbox: {
        show: false,
        feature: {
            dataView: {
                show: true,
                readOnly: true
            },
            restore: {
                show: true
            },
            saveAsImage: {
                show: true
            }
        }
    },
    animationDuration: 3000,
    animationEasingUpdate: 'quinticInOut',
    series: [{
        name: '应急体系主题视图',
        type: 'graph',
        layout: 'force',

        force: {
           // initLayout: 'circular',
            repulsion: 240,
            gravity: 0.2,
            edgeLength: 140
        },


        data: [{
            "name": "应急体系主题",
            // "x": 0,
            // y: 0,
            "symbolSize": 24,
            "draggable": "true",
            "value": 1

        }, {
            "name": "应急管理组织指标",
            "symbolSize": 10,
            "category": "类目",
            "draggable": "true",
            "value": 1
        }, {
            "name": "应急机构组成情况",
            "symbolSize": 8,
            "category": "应急机构组成情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "应急机构数量同比增长",
            "symbolSize": 6,
            "category": "应急机构组成情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "应急知识准备情况",
            "symbolSize": 8,
            "category": "应急知识准备情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "应急知识库记录数同比增长",
            "symbolSize": 6,
            "category": "应急知识准备情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "应急管理对象指标",
            "symbolSize": 10,
            "category": "类目",
            "draggable": "true",
            "value": 1
        }, {
            "name": "危险源和风险隐患区情况",
            "symbolSize": 8,
            "category": "危险源和风险隐患区情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "自然灾害风险隐患区数量",
            "symbolSize": 6,
            "category": "危险源和风险隐患区情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "事故灾难危险源数量",
            "symbolSize": 6,
            "category": "危险源和风险隐患区情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "公共卫生危险源数量",
            "symbolSize": 6,
            "category": "危险源和风险隐患区情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "社会安全隐患数量",
            "symbolSize": 6,
            "category": "危险源和风险隐患区情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "其他危险源和风险隐患区数量",
            "symbolSize": 6,
            "category": "危险源和风险隐患区情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "防护目标情况",
            "symbolSize": 8,
            "category": "防护目标情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "重要单位防护目标数量",
            "symbolSize": 6,
            "category": "防护目标情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "关键基础设施防护目标数量",
            "symbolSize": 6,
            "category": "防护目标情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "其他防护目标数量",
            "symbolSize": 6,
            "category": "防护目标情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "应急管理能力指标",
            "symbolSize": 10,
            "category": "类目",
            "draggable": "true",
            "value": 1
        }, {
            "name": "应急保障资源情况",
            "symbolSize": 8,
            "category": "应急保障资源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "应急物资与装备资源数量",
            "symbolSize": 6,
            "category": "应急保障资源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "应急通讯资源数量",
            "symbolSize": 6,
            "category": "应急保障资源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "应急运输与物流资源数量",
            "symbolSize": 6,
            "category": "应急保障资源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "医疗卫生单位数量",
            "symbolSize": 6,
            "category": "应急保障资源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "应急避难场所数量",
            "symbolSize": 6,
            "category": "应急保障资源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "应急广播电视资源数量",
            "symbolSize": 6,
            "category": "应急保障资源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "其他应急保障资源数量",
            "symbolSize": 6,
            "category": "应急保障资源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "应急管理专家情况",
            "symbolSize": 8,
            "category": "应急管理专家情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "自然灾害事件应急专家",
            "symbolSize": 6,
            "category": "应急管理专家情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "事故灾难事件应急专家",
            "symbolSize": 6,
            "category": "应急管理专家情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "公共卫生事件应急专家",
            "symbolSize": 6,
            "category": "应急管理专家情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "社会安全事件应急专家",
            "symbolSize": 6,
            "category": "应急管理专家情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "其他突发事件应急专家",
            "symbolSize": 6,
            "category": "应急管理专家情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "应急避险场所情况",
            "symbolSize": 8,
            "category": "应急避险场所情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "应急避险场所面积同比增长",
            "symbolSize": 6,
            "category": "应急避险场所情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "应急预案情况",
            "symbolSize": 8,
            "category": "应急预案情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "区级应急预案",
            "symbolSize": 6,
            "category": "应急预案情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "企业级应急预案",
            "symbolSize": 6,
            "category": "应急预案情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "其他应急预案",
            "symbolSize": 6,
            "category": "应急预案情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "应急管理态势指标",
            "symbolSize": 10,
            "category": "类目",
            "draggable": "true",
            "value": 1
        }, {
            "name": "预警信息上报情况",
            "symbolSize": 8,
            "category": "预警信息上报情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "预警信息上报率同比增长",
            "symbolSize": 6,
            "category": "预警信息上报情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "预警信息升级率同比增长",
            "symbolSize": 6,
            "category": "预警信息上报情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "突发事件情况",
            "symbolSize": 8,
            "category": "突发事件情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "自然灾害事件数量",
            "symbolSize": 6,
            "category": "突发事件情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "事故灾难事件数量",
            "symbolSize": 6,
            "category": "突发事件情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "公共卫生事件数量",
            "symbolSize": 6,
            "category": "突发事件情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "社会安全事件数量",
            "symbolSize": 6,
            "category": "突发事件情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "其他突发事件数量",
            "symbolSize": 6,
            "category": "突发事件情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "应急事件级别情况",
            "symbolSize": 8,
            "category": "应急事件级别情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "特别重大事件数量",
            "symbolSize": 6,
            "category": "应急事件级别情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "重大事件数量",
            "symbolSize": 6,
            "category": "应急事件级别情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "较大事件数量",
            "symbolSize": 6,
            "category": "应急事件级别情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "一般事件数量",
            "symbolSize": 6,
            "category": "应急事件级别情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "应急事件处置情况",
            "symbolSize": 8,
            "category": "应急事件处置情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "上报的事件数量",
            "symbolSize": 6,
            "category": "应急事件处置情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "启动中的事件数量",
            "symbolSize": 6,
            "category": "应急事件处置情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "处置中的事件数量",
            "symbolSize": 6,
            "category": "应急事件处置情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "评估中的绩效数量",
            "symbolSize": 6,
            "category": "应急事件处置情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "结束的事件数量",
            "symbolSize": 6,
            "category": "应急事件处置情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "应急管理效能指标",
            "symbolSize": 10,
            "category": "类目",
            "draggable": "true",
            "value": 1
        }, {
            "name": "街道应急管理工作效能情况",
            "symbolSize": 8,
            "category": "街道应急管理工作效能情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "南营门街道应急管理评分",
            "symbolSize": 6,
            "category": "街道应急管理工作效能情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "劝业场街道应急管理评分",
            "symbolSize": 6,
            "category": "街道应急管理工作效能情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "五大道街道应急管理评分",
            "symbolSize": 6,
            "category": "街道应急管理工作效能情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "小白楼街道应急管理评分",
            "symbolSize": 6,
            "category": "街道应急管理工作效能情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "新兴街道应急管理评分",
            "symbolSize": 6,
            "category": "街道应急管理工作效能情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "南市街道应急管理评分",
            "symbolSize": 6,
            "category": "街道应急管理工作效能情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "区级应急管理工作效能情况",
            "symbolSize": 8,
            "category": "区级应急管理工作效能情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "应急值守工作评分",
            "symbolSize": 6,
            "category": "区级应急管理工作效能情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "应急准备工作评分",
            "symbolSize": 6,
            "category": "区级应急管理工作效能情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "应急响应工作评分",
            "symbolSize": 6,
            "category": "区级应急管理工作效能情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "突发事件处置评分",
            "symbolSize": 6,
            "category": "区级应急管理工作效能情况",
            "draggable": "true",
            "value": 1
        }],
        links: [{
            "source": "应急体系主题",
            "target": "应急管理组织指标"
        }, {
            "source": "应急管理组织指标",
            "target": "应急机构组成情况"
        }, {
            "source": "应急机构组成情况",
            "target": "应急机构数量同比增长"
        }, {
            "source": "应急管理组织指标",
            "target": "应急知识准备情况"
        }, {
            "source": "应急知识准备情况",
            "target": "应急知识库记录数同比增长"
        }, {
            "source": "应急体系主题",
            "target": "应急管理对象指标"
        }, {
            "source": "应急管理业务指标",
            "target": "危险源和风险隐患区情况"
        }, {
            "source": "危险源和风险隐患区情况",
            "target": "自然灾害风险隐患区数量"
        }, {
            "source": "危险源和风险隐患区情况",
            "target": "事故灾难危险源数量"
        }, {
            "source": "危险源和风险隐患区情况",
            "target": "公共卫生危险源数量"
        }, {
            "source": "危险源和风险隐患区情况",
            "target": "社会安全隐患数量"
        }, {
            "source": "危险源和风险隐患区情况",
            "target": "其他危险源和风险隐患区数量"
        }, {
            "source": "应急管理业务指标",
            "target": "防护目标情况"
        }, {
            "source": "防护目标情况",
            "target": "重要单位防护目标数量"
        }, {
            "source": "防护目标情况",
            "target": "关键基础设施防护目标数量"
        }, {
            "source": "防护目标情况",
            "target": "其他防护目标数量"
        }, {
            "source": "应急体系主题",
            "target": "应急管理能力指标"
        }, {
            "source": "应急管理能力指标",
            "target": "应急保障资源情况"
        }, {
            "source": "应急保障资源情况",
            "target": "应急物资与装备资源数量"
        }, {
            "source": "应急保障资源情况",
            "target": "应急通讯资源数量"
        }, {
            "source": "应急保障资源情况",
            "target": "应急运输与物流资源数量"
        }, {
            "source": "应急保障资源情况",
            "target": "医疗卫生单位数量"
        }, {
            "source": "应急保障资源情况",
            "target": "应急避难场所数量"
        }, {
            "source": "应急保障资源情况",
            "target": "应急广播电视资源数量"
        }, {
            "source": "应急保障资源情况",
            "target": "其他应急保障资源数量"
        }, {
            "source": "应急管理能力指标",
            "target": "应急管理专家情况"
        }, {
            "source": "应急管理专家情况",
            "target": "自然灾害事件应急专家"
        }, {
            "source": "应急管理专家情况",
            "target": "事故灾难事件应急专家"
        }, {
            "source": "应急管理专家情况",
            "target": "公共卫生事件应急专家"
        }, {
            "source": "应急管理专家情况",
            "target": "社会安全事件应急专家"
        }, {
            "source": "应急管理专家情况",
            "target": "其他突发事件应急专家"
        }, {
            "source": "应急管理能力指标",
            "target": "应急避险场所情况"
        }, {
            "source": "应急避险场所情况",
            "target": "应急避险场所面积同比增长"
        }, {
            "source": "应急管理能力指标",
            "target": "应急预案情况"
        }, {
            "source": "应急预案情况",
            "target": "区级应急预案"
        }, {
            "source": "应急预案情况",
            "target": "企业级应急预案"
        }, {
            "source": "应急预案情况",
            "target": "其他应急预案"
        }, {
            "source": "应急体系主题",
            "target": "应急管理态势指标"
        }, {
            "source": "应急管理态势指标",
            "target": "预警信息上报情况"
        }, {
            "source": "预警信息上报情况",
            "target": "预警信息上报率同比增长"
        }, {
            "source": "预警信息上报情况",
            "target": "预警信息升级率同比增长"
        }, {
            "source": "应急管理态势指标",
            "target": "突发事件情况"
        }, {
            "source": "突发事件情况",
            "target": "自然灾害事件数量"
        }, {
            "source": "突发事件情况",
            "target": "事故灾难事件数量"
        }, {
            "source": "突发事件情况",
            "target": "公共卫生事件数量"
        }, {
            "source": "突发事件情况",
            "target": "社会安全事件数量"
        }, {
            "source": "突发事件情况",
            "target": "其他突发事件数量"
        }, {
            "source": "应急管理态势指标",
            "target": "应急事件级别情况"
        }, {
            "source": "应急事件级别情况",
            "target": "特别重大事件数量"
        }, {
            "source": "应急事件级别情况",
            "target": "重大事件数量"
        }, {
            "source": "应急事件级别情况",
            "target": "较大事件数量"
        }, {
            "source": "应急事件级别情况",
            "target": "一般事件数量"
        }, {
            "source": "应急管理态势指标",
            "target": "应急事件处置情况"
        }, {
            "source": "应急事件处置情况",
            "target": "上报的事件数量"
        }, {
            "source": "应急事件处置情况",
            "target": "启动中的事件数量"
        }, {
            "source": "应急事件处置情况",
            "target": "处置中的事件数量"
        }, {
            "source": "应急事件处置情况",
            "target": "评估中的绩效数量"
        }, {
            "source": "应急事件处置情况",
            "target": "结束的事件数量"
        }, {
            "source": "应急体系主题",
            "target": "应急管理效能指标"
        }, {
            "source": "应急管理效能指标",
            "target": "街道应急管理工作效能情况"
        }, {
            "source": "街道应急管理工作效能情况",
            "target": "南营门街道应急管理评分"
        }, {
            "source": "街道应急管理工作效能情况",
            "target": "劝业场街道应急管理评分"
        }, {
            "source": "街道应急管理工作效能情况",
            "target": "五大道街道应急管理评分"
        }, {
            "source": "街道应急管理工作效能情况",
            "target": "小白楼街道应急管理评分"
        }, {
            "source": "街道应急管理工作效能情况",
            "target": "新兴街道应急管理评分"
        }, {
            "source": "街道应急管理工作效能情况",
            "target": "南市街道应急管理评分"
        }, {
            "source": "应急管理效能指标",
            "target": "区级应急管理工作效能情况"
        }, {
            "source": "区级应急管理工作效能情况",
            "target": "应急值守工作评分"
        }, {
            "source": "区级应急管理工作效能情况",
            "target": "应急准备工作评分"
        }, {
            "source": "区级应急管理工作效能情况",
            "target": "应急响应工作评分"
        }, {
            "source": "区级应急管理工作效能情况",
            "target": "突发事件处置评分"
        }],
        categories: [{
            "name": "类目"
        }, {
            "name": "应急机构组成情况"
        }, {
            "name": "应急知识准备情况"
        }, {
            "name": "危险源和风险隐患区情况"
        }, {
            "name": "防护目标情况"
        }, {
            "name": "应急保障资源情况"
        }, {
            "name": "应急管理专家情况"
        }, {
            "name": "应急避险场所情况"
        }, {
            "name": "应急预案情况"
        }, {
            "name": "预警信息上报情况"
        }, {
            "name": "突发事件情况"
        }, {
            "name": "应急事件级别情况"
        }, {
            "name": "应急事件处置情况"
        }, {
            "name": "街道应急管理工作效能情况"
        }, {
            "name": "区级应急管理工作效能情况"
        }],

        focusNodeAdjacency: true,
        roam: true,
        label: {
            normal: {

                show: true,
                position: 'top',
                textStyle: {fontSize: 14}
            }
        },
        lineStyle: {
            normal: {
                color: 'source',
                curveness: 0
                //type: "solid"
            }
        }
    }]
};