option = {
    "backgroundColor":"#FFFFFF",
    "title":{
        "text":"亿元",
        "target":"self",
        "textStyle":{
            "fontSize":"12px",
            "color":"#999",
            "fontWeight":"normal",
            "fontFamily":"san-serif"
        },
        "subtextStyle":{
            "color":"#999",
            "height":"20px"
        }
    },
    "tooltip":{
        "trigger":"axis",
        "show":true,
        "axisPointer":{
            "type":"shadow"
        }
    },
    "legend":[
        {
            "itemWidth":18,
            "itemHeight":10,
            "bottom":"1%",
            "x":"center",
            "icon":"circle",
            "selected":{
                "合计":true,
                "信用卡":false,
                "借记卡":false,
                "合计平均线":true,
                "信用卡平均线":false,
                "借记卡平均线":false
            },
            "data":[
                "合计",
                "合计平均线",
                "信用卡",
                "信用卡平均线",
                "借记卡",
                "借记卡平均线"
            ]
        }
    ],
    "grid":{
        "height":160,
        "left":"2%",
        "right":"3%",
        "bottom":"20%",
        "containLabel":true
    },
    "xAxis":{
        "type":"category",
        "boundaryGap":true,
        scale: true,
        "axisTick": {
            alignWithLabel: false
        },
        "axisLine":{
            onZero: false,
            "lineStyle":{
                "type":"solid",
                "color":"#999",
            }
        },
        "data":[
            "20190101",
            "20190102",
            "20190103",
            "20190104",
            "20190105",
            "20190106",
            "20190107",
            "20190108",
            "20190109",
            "20190110",
            "20190111",
            "20190112",
            "20190113",
            "20190114",
            "20190115",
            "20190116",
            "20190117",
            "20190118",
            "20190119",
            "20190120",
            "20190121",
            "20190122",
            "20190123",
            "20190124",
            "20190125",
            "20190126",
            "20190127",
            "20190128",
            "20190129",
            "20190130",
            "20190131"
        ]
    },
    "yAxis":{
        "type":"value",
        scale: true,
        "show":true,
        "boundaryGap":false,
        "splitLine":{
            "show":false
        },
        "axisTick": {
            alignWithLabel: false
        },
        "axisLine":{
            "lineStyle":{
                "type":"solid",
                "color":"#999",
                "width":"1"
            }
        }
    },
    "dataZoom":[
        {
            show: true,
            "type":"inside",
            height: 20,
            "start":0,
            "end":100
        }
    ],
    "series":[
        {
            "name":"合计",
            "type":"bar",
            "smooth":false,
            "symbol":"none",
            "sampling":"average",
            "stack":"总量",
            barGap: 0,
            barCategoryGap: 0,
            "label":{
                "normal":{
                    "show":false,
                }
            },
            "silent":true,
            "itemStyle":{
                "color":"#83accc",
                "barBorderRadius":1
            },
            "markArea":{
                "data":[
                    [
                        {
                            "itemStyle":{
                                "color":"#00ff00"
                            }
                        },
                        {
                            "xAxis":"20190110"
                        }
                    ],
                    [
                        {
                            "xAxis":"20190114",
                            "itemStyle":{
                                "color":"#ff0000"
                            }
                        },
                        {
                            "xAxis":"20190110"
                        }
                    ],
                    [
                        {
                            "xAxis":"20190114",
                            "itemStyle":{
                                "color":"#32CD32"
                            }
                        },
                        {
                            "xAxis":"20190120"
                        }
                    ],
                    [
                        {
                            "xAxis":"20190121",
                            "itemStyle":{
                                "color":"#f28274"
                            }
                        },
                        {
                            "xAxis":"20190127"
                        }
                    ],
                    [
                        {
                            "xAxis":"20190128",
                            "itemStyle":{
                                "color":"#32CD32"
                            }
                        },
                        {
                            "xAxis":"20190129"
                        }
                    ]
                ]
            },
            "data":[
                {
                    "value":974.6,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":887.5,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":786,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":1427.9,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":1449.7,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":1574.1,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":1574.1,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":1449.7,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":1427.9,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":786,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":887.5,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":974.6,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":1471.3,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":1397.5,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":1404.8,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":1414.2,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":1526.8,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":1574.1,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":1449.7,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)",
                        "borderColor":"#ffbcb5",
                        "twinkle":{
                            "enabled":true,
                            "period":1000
                        }
                    }
                },
                {
                    "value":1427.9,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":786,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":887.5,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":974.6,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":1471.3,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":1397.5,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":1404.8,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)",
                        "borderColor":"#ffbcb5",
                        "twinkle":{
                            "enabled":true,
                            "period":1000
                        }
                    }
                },
                {
                    "value":1414.2,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":1526.8,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)",
                        "borderColor":"#ed7369",
                        "twinkle":{
                            "enabled":true,
                            "period":1000
                        }
                    }
                },
                {
                    "value":1404.8,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.3)",
                        "borderType":"solid",
                        "borderColor":"rgba(131,172,204,0.3)",
                        "borderWidth":1
                    }
                },
                {
                    "value":887.5,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.3)",
                        "borderType":"solid",
                        "borderColor":"rgba(131,172,204,0.3)",
                        "borderWidth":1
                    }
                },
                {
                    "value":1574.1,
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.3)",
                        "borderType":"solid",
                        "borderColor":"rgba(131,172,204,0.3)",
                        "borderWidth":1
                    }
                }
            ]
        },
        {
            "name":"合计平均线",
            "type":"line",
            "smooth":false,
            "symbol":"none",
            "sampling":"average",
            "label":{
                "normal":{
                    "show":false,
                    "position":"insideRight"
                }
            },
            "itemStyle":{
                "color":"#83accc",
                "normal":{
                    "lineStyle":{
                        "type":"dotted"
                    }
                }
            },
            "data":[
                {
                    "value":"1394.77",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1296.68",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1190.85",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1192.81",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1199.21",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1224.44",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1239.13",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1307.0",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1384.21",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1384.21",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1307.0",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1239.13",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1224.44",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1199.21",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1192.81",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1190.85",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1296.68",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1394.77",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1462.64",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1456.45",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1369.09",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1295.18",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1232.37",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1224.44",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1199.21",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1192.81",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1190.85",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1296.68",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1296.68",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1358.15",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                },
                {
                    "value":"1372.84",
                    "itemStyle":{
                        "color":"rgba(131,172,204,0.9)"
                    }
                }
            ]
        },
        {
            "name":"信用卡",
            "type":"bar",
            "smooth":false,
            "symbol":"none",
            "sampling":"average",
            "stack":"总量",
            barGap: 0,
            barCategoryGap: 0,
            "label":{
                "normal":{
                    "show":false,
                    "position":"insideRight"
                }
            },
            "silent":true,
            "itemStyle":{
                "color":"#f28274",
                "barBorderRadius":1
            },
            "markArea":{
                "silent":true,
                "data":[
                    [
                        {
                            "xAxis":"20181231",
                            "itemStyle":{
                                "color":"#32CD32"
                            }
                        },
                        {
                            "xAxis":"20190106"
                        }
                    ],
                    [
                        {
                            "xAxis":"20190107",
                            "itemStyle":{
                                "color":"#f28274"
                            }
                        },
                        {
                            "xAxis":"20190113"
                        }
                    ],
                    [
                        {
                            "xAxis":"20190114",
                            "itemStyle":{
                                "color":"#32CD32"
                            }
                        },
                        {
                            "xAxis":"20190120"
                        }
                    ],
                    [
                        {
                            "xAxis":"20190121",
                            "itemStyle":{
                                "color":"#f28274"
                            }
                        },
                        {
                            "xAxis":"20190127"
                        }
                    ],
                    [
                        {
                            "xAxis":"20190128",
                            "itemStyle":{
                                "color":"#32CD32"
                            }
                        },
                        {
                            "xAxis":"20190129"
                        }
                    ]
                ]
            },
            "data":[
                {
                    "value":633.4,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":567.4,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":503.7,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":779.8,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":807.5,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":911.1,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":911.1,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":807.5,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":779.8,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":503.7,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":567.4,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":633.4,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":743.7,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":710.3,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":719.2,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":766.1,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":835.5,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":911.1,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":807.5,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)",
                        "borderColor":"#ffbcb5",
                        "twinkle":{
                            "enabled":true,
                            "period":1000
                        }
                    }
                },
                {
                    "value":779.8,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":503.7,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":567.4,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":633.4,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":743.7,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":710.3,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":719.2,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)",
                        "borderColor":"#ffbcb5",
                        "twinkle":{
                            "enabled":true,
                            "period":1000
                        }
                    }
                },
                {
                    "value":766.1,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":835.5,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":719.2,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.3)",
                        "borderType":"solid",
                        "borderColor":"rgba(242,130,116,0.3)",
                        "borderWidth":1
                    }
                },
                {
                    "value":567.4,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.3)",
                        "borderType":"solid",
                        "borderColor":"rgba(242,130,116,0.3)",
                        "borderWidth":1
                    }
                },
                {
                    "value":911.1,
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.3)",
                        "borderType":"solid",
                        "borderColor":"rgba(242,130,116,0.3)",
                        "borderWidth":1
                    }
                }
            ]
        },
        {
            "name":"信用卡平均线",
            "type":"line",
            "smooth":false,
            "symbol":"none",
            "sampling":"average",
            "label":{
                "normal":{
                    "show":false,
                    "position":"insideRight"
                }
            },
            "itemStyle":{
                "color":"#f28274",
                "normal":{
                    "lineStyle":{
                        "type":"dotted"
                    }
                }
            },
            "data":[
                {
                    "value":"759.9",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"710.79",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"663.39",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"665.36",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"677.98",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"706.67",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"730.58",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"755.45",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"785.8",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"785.8",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"755.45",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"730.58",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"706.67",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"677.98",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"665.36",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"663.39",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"710.79",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"759.9",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"784.77",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"789.92",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"760.41",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"738.72",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"719.77",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"706.67",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"677.98",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"665.36",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"663.39",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"710.79",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"710.79",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"723.04",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                },
                {
                    "value":"746.96",
                    "itemStyle":{
                        "color":"rgba(242,130,116,0.9)"
                    }
                }
            ]
        },
        {
            "name":"借记卡",
            "type":"bar",
            "smooth":false,
            "symbol":"none",
            "sampling":"average",
            "stack":"总量",
            barGap: 0,
            barCategoryGap: 0,
            "label":{
                "normal":{
                    "show":false,
                    "position":"insideRight"
                }
            },
            "silent":true,
            "itemStyle":{
                "color":"#f2d074",
                "barBorderRadius":1
            },
            "markArea":{
                "silent":true,
                "data":[
                    [
                        {
                            "xAxis":"20181231",
                            "itemStyle":{
                                "color":"#32CD32"
                            }
                        },
                        {
                            "xAxis":"20190106"
                        }
                    ],
                    [
                        {
                            "xAxis":"20190107",
                            "itemStyle":{
                                "color":"#f28274"
                            }
                        },
                        {
                            "xAxis":"20190113"
                        }
                    ],
                    [
                        {
                            "xAxis":"20190114",
                            "itemStyle":{
                                "color":"#32CD32"
                            }
                        },
                        {
                            "xAxis":"20190120"
                        }
                    ],
                    [
                        {
                            "xAxis":"20190121",
                            "itemStyle":{
                                "color":"#f28274"
                            }
                        },
                        {
                            "xAxis":"20190127"
                        }
                    ],
                    [
                        {
                            "xAxis":"20190128",
                            "itemStyle":{
                                "color":"#32CD32"
                            }
                        },
                        {
                            "xAxis":"20190129"
                        }
                    ]
                ]
            },
            "data":[
                {
                    "value":341.2,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":320.1,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":282.3,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":648.1,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":642.2,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":663,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":663,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":642.2,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":648.1,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":282.3,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":320.1,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":341.2,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":727.5,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":687.2,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":685.7,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":648.2,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":691.3,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":663,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":642.2,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":648.1,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":282.3,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":320.1,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":341.2,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":727.5,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":687.2,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":685.7,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":648.2,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":691.3,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":685.7,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.3)",
                        "borderType":"solid",
                        "borderColor":"rgba(247,208,116,0.3)",
                        "borderWidth":1
                    }
                },
                {
                    "value":320.1,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.3)",
                        "borderType":"solid",
                        "borderColor":"rgba(247,208,116,0.3)",
                        "borderWidth":1
                    }
                },
                {
                    "value":663,
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.3)",
                        "borderType":"solid",
                        "borderColor":"rgba(247,208,116,0.3)",
                        "borderWidth":1
                    }
                }
            ]
        },
        {
            "name":"借记卡平均线",
            "type":"line",
            "smooth":false,
            "symbol":"none",
            "sampling":"average",
            "label":{
                "normal":{
                    "show":false,
                    "position":"insideRight"
                }
            },
            "itemStyle":{
                "color":"#f2d074",
                "normal":{
                    "lineStyle":{
                        "type":"dotted"
                    }
                }
            },
            "data":[
                {
                    "value":"634.87",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"585.89",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"527.46",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"527.45",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"521.23",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"517.77",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"508.55",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"551.55",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"598.41",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"598.41",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"551.55",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"508.55",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"517.77",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"521.23",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"527.45",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"527.46",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"585.89",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"634.87",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"677.87",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"666.52",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"608.68",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"556.46",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"512.6",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"517.77",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"521.23",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"527.45",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"527.46",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"585.89",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"585.89",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"635.1",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                },
                {
                    "value":"625.88",
                    "itemStyle":{
                        "color":"rgba(247,208,116,0.9)"
                    }
                }
            ]
        }
    ]
};