 option = {
     backgroundColor: '#FFFFFF',
     title: {
         text: '各省罕见病纳入医保情况'
     },
     series: {
         type: 'sankey',
         layout: 'none',
         focusNodeAdjacency: 'allEdges',
         data: [{
             "name": "上海"
         }, {
             "name": "湖南"
         }, {
             "name": "宁夏"
         }, {
             "name": "河北"
         }, {
             "name": "河南"
         }, {
             "name": "福建"
         }, {
             "name": "甘肃"
         }, {
             "name": "云南"
         }, {
             "name": "广西"
         }, {
             "name": "贵州"
         }, {
             "name": "海南"
         }, {
             "name": "黑龙江"
         }, {
             "name": "辽宁"
         }, {
             "name": "山东"
         }, {
             "name": "天津"
         }, {
             "name": "浙江"
         }, {
             "name": "重庆"
         }, {
             "name": "安徽"
         }, {
             "name": "北京"
         }, {
             "name": "广东"
         }, {
             "name": "内蒙古"
         }, {
             "name": "山西"
         }, {
             "name": "陕西"
         }, {
             "name": "四川"
         }, {
             "name": "新疆"
         }, {
             "name": "湖北"
         }, {
             "name": "吉林"
         }, {
             "name": "江苏"
         }, {
             "name": "江西"
         }, {
             "name": "青海"
         }, {
             "name": "西藏"
         }, {
             "name": "再生障碍性贫血"
         }, {
             "name": "血友病"
         }, {
             "name": "系统性硬化症"
         }, {
             "name": "特发性肺纤维化"
         }, {
             "name": "特发性肺动脉高压"
         }, {
             "name": "糖原累积病Ⅱ型"
         }, {
             "name": "四氢生物蝶呤缺乏症"
         }, {
             "name": "全身型重症肌无力"
         }, {
             "name": "普拉德-威利综合征"
         }, {
             "name": "庞贝氏症"
         }, {
             "name": "帕金森氏综合征"
         }, {
             "name": "帕金森病"
         }, {
             "name": "黏多糖贮积症"
         }, {
             "name": "酪氨酸血症"
         }, {
             "name": "甲基丙二酸血症"
         }, {
             "name": "肌萎缩侧索硬化"
         }, {
             "name": "戈谢病"
         }, {
             "name": "高氨血症"
         }, {
             "name": "肝豆状核变性"
         }, {
             "name": "枫糖尿症"
         }, {
             "name": "肺动脉高压"
         }, {
             "name": "法布里病"
         }, {
             "name": "儿童苯丙酮尿症"
         }, {
             "name": "多发性硬化"
         }, {
             "name": "苯丙酮尿症"
         }, {
             "name": "21-羟化酶缺乏症"
         }],
         links: [{
             "source": "上海",
             "target": "苯丙酮尿症",
             "value": 1
         }, {
             "source": "上海",
             "target": "枫糖尿症",
             "value": 1
         }, {
             "source": "上海",
             "target": "肝豆状核变性",
             "value": 1
         }, {
             "source": "上海",
             "target": "戈谢病",
             "value": 1
         }, {
             "source": "上海",
             "target": "法布里病",
             "value": 1
         }, {
             "source": "上海",
             "target": "黏多糖贮积症",
             "value": 1
         }, {
             "source": "上海",
             "target": "糖原累积病Ⅱ型",
             "value": 1
         }, {
             "source": "上海",
             "target": "甲基丙二酸血症",
             "value": 1
         }, {
             "source": "上海",
             "target": "高氨血症",
             "value": 1
         }, {
             "source": "上海",
             "target": "21-羟化酶缺乏症",
             "value": 1
         }, {
             "source": "上海",
             "target": "酪氨酸血症",
             "value": 1
         }, {
             "source": "湖南",
             "target": "血友病",
             "value": 1
         }, {
             "source": "湖南",
             "target": "儿童苯丙酮尿症",
             "value": 1
         }, {
             "source": "湖南",
             "target": "帕金森病",
             "value": 1
         }, {
             "source": "湖南",
             "target": "全身型重症肌无力",
             "value": 1
         }, {
             "source": "湖南",
             "target": "肝豆状核变性",
             "value": 1
         }, {
             "source": "湖南",
             "target": "特发性肺动脉高压",
             "value": 1
         }, {
             "source": "湖南",
             "target": "普拉德-威利综合征",
             "value": 1
         }, {
             "source": "宁夏",
             "target": "全身型重症肌无力",
             "value": 1
         }, {
             "source": "宁夏",
             "target": "血友病",
             "value": 1
         }, {
             "source": "宁夏",
             "target": "帕金森病",
             "value": 1
         }, {
             "source": "宁夏",
             "target": "苯丙酮尿症",
             "value": 1
         }, {
             "source": "宁夏",
             "target": "四氢生物蝶呤缺乏症",
             "value": 1
         }, {
             "source": "宁夏",
             "target": "再生障碍性贫血",
             "value": 1
         }, {
             "source": "宁夏",
             "target": "戈谢病",
             "value": 1
         }, {
             "source": "河北",
             "target": "再生障碍性贫血",
             "value": 1
         }, {
             "source": "河北",
             "target": "系统性硬化症",
             "value": 1
         }, {
             "source": "河北",
             "target": "多发性硬化",
             "value": 1
         }, {
             "source": "河北",
             "target": "帕金森病",
             "value": 1
         }, {
             "source": "河北",
             "target": "全身型重症肌无力",
             "value": 1
         }, {
             "source": "河北",
             "target": "血友病",
             "value": 1
         }, {
             "source": "河南",
             "target": "血友病",
             "value": 1
         }, {
             "source": "河南",
             "target": "再生障碍性贫血",
             "value": 1
         }, {
             "source": "河南",
             "target": "苯丙酮尿症",
             "value": 1
         }, {
             "source": "河南",
             "target": "肌萎缩侧索硬化",
             "value": 1
         }, {
             "source": "河南",
             "target": "特发性肺纤维化",
             "value": 1
         }, {
             "source": "河南",
             "target": "多发性硬化",
             "value": 1
         }, {
             "source": "河南",
             "target": "四氢生物蝶呤缺乏症",
             "value": 1
         }, {
             "source": "福建",
             "target": "血友病",
             "value": 1
         }, {
             "source": "福建",
             "target": "全身型重症肌无力",
             "value": 1
         }, {
             "source": "福建",
             "target": "帕金森病",
             "value": 1
         }, {
             "source": "福建",
             "target": "再生障碍性贫血",
             "value": 1
         }, {
             "source": "福建",
             "target": "苯丙酮尿症",
             "value": 1
         }, {
             "source": "甘肃",
             "target": "苯丙酮尿症",
             "value": 1
         }, {
             "source": "甘肃",
             "target": "血友病",
             "value": 1
         }, {
             "source": "甘肃",
             "target": "再生障碍性贫血",
             "value": 1
         }, {
             "source": "甘肃",
             "target": "全身型重症肌无力",
             "value": 1
         }, {
             "source": "甘肃",
             "target": "帕金森病",
             "value": 1
         }, {
             "source": "云南",
             "target": "再生障碍性贫血",
             "value": 1
         }, {
             "source": "云南",
             "target": "帕金森病",
             "value": 1
         }, {
             "source": "云南",
             "target": "血友病",
             "value": 1
         }, {
             "source": "云南",
             "target": "系统性硬化症",
             "value": 1
         }, {
             "source": "云南",
             "target": "全身型重症肌无力",
             "value": 1
         }, {
             "source": "广西",
             "target": "帕金森病",
             "value": 1
         }, {
             "source": "广西",
             "target": "再生障碍性贫血",
             "value": 1
         }, {
             "source": "广西",
             "target": "全身型重症肌无力",
             "value": 1
         }, {
             "source": "广西",
             "target": "血友病",
             "value": 1
         }, {
             "source": "贵州",
             "target": "帕金森病",
             "value": 1
         }, {
             "source": "贵州",
             "target": "再生障碍性贫血",
             "value": 1
         }, {
             "source": "贵州",
             "target": "血友病",
             "value": 1
         }, {
             "source": "贵州",
             "target": "肝豆状核变性",
             "value": 1
         }, {
             "source": "海南",
             "target": "再生障碍性贫血",
             "value": 1
         }, {
             "source": "海南",
             "target": "血友病",
             "value": 1
         }, {
             "source": "海南",
             "target": "帕金森氏综合征",
             "value": 1
         }, {
             "source": "海南",
             "target": "全身型重症肌无力",
             "value": 1
         }, {
             "source": "黑龙江",
             "target": "苯丙酮尿症",
             "value": 1
         }, {
             "source": "黑龙江",
             "target": "四氢生物蝶呤缺乏症",
             "value": 1
         }, {
             "source": "黑龙江",
             "target": "再生障碍性贫血",
             "value": 1
         }, {
             "source": "黑龙江",
             "target": "帕金森病",
             "value": 1
         }, {
             "source": "辽宁",
             "target": "血友病",
             "value": 1
         }, {
             "source": "辽宁",
             "target": "全身型重症肌无力",
             "value": 1
         }, {
             "source": "辽宁",
             "target": "再生障碍性贫血",
             "value": 1
         }, {
             "source": "辽宁",
             "target": "帕金森病",
             "value": 1
         }, {
             "source": "山东",
             "target": "血友病",
             "value": 1
         }, {
             "source": "山东",
             "target": "肺动脉高压",
             "value": 1
         }, {
             "source": "山东",
             "target": "苯丙酮尿症",
             "value": 1
         }, {
             "source": "山东",
             "target": "多发性硬化",
             "value": 1
         }, {
             "source": "天津",
             "target": "戈谢病",
             "value": 1
         }, {
             "source": "天津",
             "target": "庞贝氏症",
             "value": 1
         }, {
             "source": "天津",
             "target": "血友病",
             "value": 1
         }, {
             "source": "天津",
             "target": "再生障碍性贫血",
             "value": 1
         }, {
             "source": "浙江",
             "target": "戈谢病",
             "value": 1
         }, {
             "source": "浙江",
             "target": "肌萎缩侧索硬化",
             "value": 1
         }, {
             "source": "浙江",
             "target": "苯丙酮尿症",
             "value": 1
         }, {
             "source": "浙江",
             "target": "血友病",
             "value": 1
         }, {
             "source": "重庆",
             "target": "血友病",
             "value": 1
         }, {
             "source": "重庆",
             "target": "再生障碍性贫血",
             "value": 1
         }, {
             "source": "重庆",
             "target": "苯丙酮尿症",
             "value": 1
         }, {
             "source": "重庆",
             "target": "四氢生物蝶呤缺乏症",
             "value": 1
         }, {
             "source": "安徽",
             "target": "血友病",
             "value": 1
         }, {
             "source": "安徽",
             "target": "再生障碍性贫血",
             "value": 1
         }, {
             "source": "安徽",
             "target": "全身型重症肌无力",
             "value": 1
         }, {
             "source": "北京",
             "target": "血友病",
             "value": 1
         }, {
             "source": "北京",
             "target": "再生障碍性贫血",
             "value": 1
         }, {
             "source": "北京",
             "target": "多发性硬化",
             "value": 1
         }, {
             "source": "广东",
             "target": "再生障碍性贫血",
             "value": 1
         }, {
             "source": "广东",
             "target": "血友病",
             "value": 1
         }, {
             "source": "广东",
             "target": "帕金森病",
             "value": 1
         }, {
             "source": "内蒙古",
             "target": "帕金森病",
             "value": 1
         }, {
             "source": "内蒙古",
             "target": "再生障碍性贫血",
             "value": 1
         }, {
             "source": "内蒙古",
             "target": "全身型重症肌无力",
             "value": 1
         }, {
             "source": "山西",
             "target": "血友病",
             "value": 1
         }, {
             "source": "山西",
             "target": "帕金森病",
             "value": 1
         }, {
             "source": "山西",
             "target": "全身型重症肌无力",
             "value": 1
         }, {
             "source": "陕西",
             "target": "帕金森病",
             "value": 1
         }, {
             "source": "陕西",
             "target": "苯丙酮尿症",
             "value": 1
         }, {
             "source": "陕西",
             "target": "四氢生物蝶呤缺乏症",
             "value": 1
         }, {
             "source": "四川",
             "target": "再生障碍性贫血",
             "value": 1
         }, {
             "source": "四川",
             "target": "血友病",
             "value": 1
         }, {
             "source": "四川",
             "target": "帕金森病",
             "value": 1
         }, {
             "source": "新疆",
             "target": "帕金森氏综合征",
             "value": 1
         }, {
             "source": "新疆",
             "target": "全身型重症肌无力",
             "value": 1
         }, {
             "source": "新疆",
             "target": "血友病",
             "value": 1
         }, {
             "source": "湖北",
             "target": "再生障碍性贫血",
             "value": 1
         }, {
             "source": "湖北",
             "target": "血友病",
             "value": 1
         }, {
             "source": "吉林",
             "target": "帕金森病",
             "value": 1
         }, {
             "source": "吉林",
             "target": "肝豆状核变性",
             "value": 1
         }, {
             "source": "江苏",
             "target": "血友病",
             "value": 1
         }, {
             "source": "江苏",
             "target": "儿童苯丙酮尿症",
             "value": 1
         }, {
             "source": "江西",
             "target": "儿童苯丙酮尿症",
             "value": 1
         }, {
             "source": "江西",
             "target": "血友病",
             "value": 1
         }, {
             "source": "青海",
             "target": "血友病",
             "value": 1
         }, {
             "source": "西藏",
             "target": "再生障碍性贫血",
             "value": 1
         }],
         lineStyle: {

             normal: {
                 lineWidth: 1,
                 color: 'source',
                 curveness: 0.7
             }
         }
     }
 }