
////////// 2004 年
var value3 = [
{name:'阿富汗',value:35.76},
{name:'阿尔巴尼亚',value:205.97},
{name:'阿尔及利亚',value:83.25},
{name:'安哥拉',value:117.81},
{name:'阿根廷',value:283.82},
{name:'亚美尼亚',value:337.44},
{name:'澳大利亚',value:694.45},
{name:'奥地利',value:454.36},
{name:'阿塞拜疆',value:397.6},
{name:'巴哈马',value:831.42},
{name:'巴林',value:237.85},
{name:'孟加拉国',value:104.87},
{name:'白俄罗斯',value:758.69},
{name:'比利时',value:541.5},
{name:'伯利兹',value:621.87},
{name:'贝宁',value:63.09},
{name:'玻利维亚',value:151.24},
{name:'博茨瓦纳',value:634.82},
{name:'巴西',value:163.13},
{name:'文莱',value:762.77},
{name:'保加利亚',value:703.12},
{name:'布基纳法索',value:44.78},
{name:'布隆迪',value:10.57},
{name:'柬埔寨',value:83.54},
{name:'喀麦隆',value:58.28},
{name:'加拿大',value:699.89},
{name:'中非共和国',value:112.49},
{name:'乍得',value:84.06},
{name:'智利',value:182.19},
{name:'中国',value:120.36},
{name:'哥伦比亚',value:43.56},
{name:'哥伦比亚',value:43.56},
{name:'刚果共和国',value:122.97},
{name:'刚果民主共和国',value:71.28},
{name:'哥斯达黎加',value:66},
{name:'科特迪瓦',value:94.38},
{name:'克罗地亚',value:234.66},
{name:'古巴',value:123.8},
{name:'塞浦路斯',value:271.82},
{name:'捷克共和国',value:496.45},
{name:'丹麦',value:576.82},
{name:'多米尼加',value:70.72},
{name:'厄瓜多尔',value:66.96},
{name:'埃及',value:49.98},
{name:'萨尔瓦多',value:66.24},
{name:'厄立特里亚',value:42.65},
{name:'爱沙尼亚',value:751.05},
{name:'埃塞俄比亚',value:17.13},
{name:'斐济',value:116.29},
{name:'芬兰',value:839.03},
{name:'法国',value:445.97},
{name:'加蓬',value:194.56},
{name:'冈比亚',value:118.13},
{name:'格鲁吉亚',value:382.07},
{name:'德国',value:369.3},
{name:'加纳',value:115.14},
{name:'希腊',value:359.67},
{name:'危地马拉',value:74.67},
{name:'几内亚',value:72.65},
{name:'圭亚那',value:265.48},
{name:'海地',value:20},
{name:'洪都拉斯',value:93.29},
{name:'匈牙利',value:580},
{name:'印度',value:40.54},
{name:'印尼',value:62.91},
{name:'伊朗',value:126.59},
{name:'伊拉克',value:93.95},
{name:'爱尔兰',value:285.06},
{name:'以色列',value:222.99},
{name:'意大利',value:291.85},
{name:'牙买加',value:148.65},
{name:'日本',value:198.33},
{name:'哈萨克斯坦',value:741.35},
{name:'肯尼亚',value:29.76},
{name:'韩国',value:70.84},
{name:'朝鲜',value:40.28},
{name:'科威特',value:261.48},
{name:'吉尔吉斯斯坦',value:403.83},
{name:'老挝',value:15.97},
{name:'拉脱维亚',value:524.42},
{name:'黎巴嫩',value:92.23},
{name:'利比里亚',value:75.8},
{name:'利比亚',value:335.16},
{name:'立陶宛',value:742.59},
{name:'卢森堡',value:394.51},
{name:'前南马其顿',value:193.94},
{name:'马达加斯加',value:18.98},
{name:'马拉维',value:47.39},
{name:'马来西亚',value:192.04},
{name:'马里',value:65.93},
{name:'毛里塔尼亚',value:55.69},
{name:'毛里求斯',value:79.97},
{name:'墨西哥',value:210.76},
{name:'摩尔多瓦',value:786.07},
{name:'蒙古',value:258.05},
{name:'黑山共和国',value:322.88},
{name:'摩洛哥',value:65.4},
{name:'莫桑比克',value:82.23},
{name:'缅甸',value:61.86},
{name:'纳米比亚',value:364.69},
{name:'尼泊尔',value:14.88},
{name:'荷兰',value:300.93},
{name:'新喀里多尼亚',value:400},
{name:'新西兰',value:413.73},
{name:'尼加拉瓜',value:52.29},
{name:'尼日尔',value:55.24},
{name:'尼日利亚',value:52.69},
{name:'北马里亚纳',value:1856.67},
{name:'挪威',value:531.78},
{name:'阿曼',value:373.67},
{name:'巴基斯坦',value:37.05},
{name:'巴拿马',value:110.48},
{name:'巴布亚新几内亚',value:43.81},
{name:'巴拉圭',value:241.55},
{name:'秘鲁',value:78.3},
{name:'菲律宾',value:31.17},
{name:'波兰',value:354.86},
{name:'葡萄牙',value:397.23},
{name:'波多黎各',value:214.97},
{name:'卡塔尔',value:226.56},
{name:'罗马尼亚',value:676.65},
{name:'俄罗斯',value:688.14},
{name:'卢旺达',value:9.71},
{name:'沙特阿拉伯',value:249.19},
{name:'塞内加尔',value:84.9},
{name:'塞尔维亚',value:438.87},
{name:'塞拉利昂',value:51.94},
{name:'新加坡',value:59.09},
{name:'斯洛伐克',value:500.79},
{name:'斯洛文尼亚',value:341.7},
{name:'索马里',value:31.31},
{name:'南非',value:293.47},
{name:'西班牙',value:224.14},
{name:'斯里兰卡',value:69.59},
{name:'苏丹',value:124.6},
{name:'苏里南',value:193},
{name:'斯威士兰',value:83.81},
{name:'瑞典',value:629.12},
{name:'瑞士',value:255.59},
{name:'叙利亚',value:149.61},
{name:'塔吉克斯坦',value:237.41},
{name:'坦桑尼亚',value:52.58},
{name:'泰国',value:67.47},
{name:'多哥',value:78.24},
{name:'特立尼达和多巴哥',value:225.89},
{name:'突尼斯',value:113.78},
{name:'土耳其',value:136.91},
{name:'土库曼斯坦',value:535.5},
{name:'乌干达',value:15.08},
{name:'乌克兰',value:891.64},
{name:'阿联酋',value:168.08},
{name:'英国',value:270.85},
{name:'美国',value:760.6},
{name:'美国',value:761.6},
{name:'乌拉圭',value:237.08},
{name:'乌兹别克斯坦',value:420.13},
{name:'委内瑞拉',value:127.6},
{name:'越南',value:72.47},
{name:'也门',value:25.43},
{name:'赞比亚',value:107.78},
{name:'津巴布韦',value:85.87},


//{name:'南苏丹',value:0},
//{name:'索马里兰',value:0},
//{name:'黑山',value:0},
//{name:'科索沃',value:0},
//{name:'塞尔维亚',value:0},
];

var nameMap = {
'Afghanistan':'阿富汗',
'Albania':'阿尔巴尼亚',
'Algeria':'阿尔及利亚',
'Andorra':'安道尔',
'Angola':'安哥拉',
'Antarctica':'南极洲',
'Antigua and Barbuda':'安提瓜和巴布达',
'Argentina':'阿根廷',
'Armenia':'亚美尼亚',
'Australia':'澳大利亚',
'Austria':'奥地利',
'Azerbaijan':'阿塞拜疆',
'The Bahamas':'巴哈马',
'Bahrain':'巴林',
'Bangladesh':'孟加拉国',
'Barbados':'巴巴多斯',
'Belarus':'白俄罗斯',
'Belgium':'比利时',
'Belize':'伯利兹',
'Benin':'贝宁',
'Bermuda':'百慕大',
'Bhutan':'不丹',
'Bolivia':'玻利维亚',
'Bosnia and Herzegovina':'波斯尼亚和黑塞哥维那',
'Botswana':'博茨瓦纳',
'Brazil':'巴西',
'Brunei':'文莱',
'Bulgaria':'保加利亚',
'Burkina Faso':'布基纳法索',
'Burundi':'布隆迪',
'Cambodia':'柬埔寨',
'Cameroon':'喀麦隆',
'Canada':'加拿大',
'Cape Verde':'佛得角',
'Central African Republic':'中非共和国',
'Chad':'乍得',
'Chile':'智利',
'China':'中国',
'Colombia':'哥伦比亚',
'Comoros':'科摩罗',
'Republic of the Congo':'刚果共和国',
'Costa Rica':'哥斯达黎加',
'Croatia':'克罗地亚',
'Cuba':'古巴',
'Cyprus':'塞浦路斯',
'Czech Republic':'捷克共和国',
'Denmark':'丹麦',
'Djibouti':'吉布提',
'Dominica':'多米尼加',
'Dominican Republic':'多明尼加共和国',
'Ecuador':'厄瓜多尔',
'Egypt':'埃及',
'El Salvador':'萨尔瓦多',
'Equatorial Guinea':'赤道几内亚',
'Eritrea':'厄立特里亚',
'Estonia':'爱沙尼亚',
'Ethiopia':'埃塞俄比亚',
'Falkland Islands':'福克兰群岛',
'Faroe Islands':'法罗群岛',
'Fiji':'斐济',
'Finland':'芬兰',
'France':'法国',
'French Guiana':'法属圭亚那',
'French Southern and Antarctic Lands':'法属南半球和南极领地',
'Gabon':'加蓬',
'Gambia':'冈比亚',
'Gaza Strip':'加沙',
'Georgia':'格鲁吉亚',
'Germany':'德国',
'Ghana':'加纳',
'Greece':'希腊',
'Greenland':'格陵兰',
'Grenada':'格林纳达',
'Guadeloupe':'瓜德罗普',
'Guatemala':'危地马拉',
'Guinea':'几内亚',
'Guinea Bissau':'几内亚比绍',
'Guyana':'圭亚那',
'Haiti':'海地',
'Honduras':'洪都拉斯',
'Hong Kong':'香港',
'Hungary':'匈牙利',
'Iceland':'冰岛',
'India':'印度',
'Indonesia':'印尼',
'Iran':'伊朗',
'Iraq':'伊拉克',
'Iraq-Saudi Arabia Neutral Zone':'伊拉克阿拉伯中立区',
'Ireland':'爱尔兰',
'Isle of Man':'马恩岛',
'Israel':'以色列',
'Italy':'意大利',
'Ivory Coast':'科特迪瓦',
'Jamaica':'牙买加',
'Jan Mayen':'扬马延岛',
'Japan':'日本',
'Jordan':'约旦',
'Kazakhstan':'哈萨克斯坦',
'Kenya':'肯尼亚',
'Kerguelen':'凯尔盖朗群岛',
'Kiribati':'基里巴斯',
'North Korea':'北朝鲜',
'South Korea':'韩国',
'Kuwait':'科威特',
'Kyrgyzstan':'吉尔吉斯斯坦',
'Laos':'老挝',
'Latvia':'拉脱维亚',
'Lebanon':'黎巴嫩',
'Lesotho':'莱索托',
'Liberia':'利比里亚',
'Libya':'利比亚',
'Liechtenstein':'列支敦士登',
'Lithuania':'立陶宛',
'Luxembourg':'卢森堡',
'Macau':'澳门',
'Macedonia':'马其顿',
'Madagascar':'马达加斯加',
'Malawi':'马拉维',
'Malaysia':'马来西亚',
'Maldives':'马尔代夫',
'Mali':'马里',
'Malta':'马耳他',
'Martinique':'马提尼克',
'Mauritania':'毛里塔尼亚',
'Mauritius':'毛里求斯',
'Mexico':'墨西哥',
'Moldova':'摩尔多瓦',
'Monaco':'摩纳哥',
'Mongolia':'蒙古',
'Morocco':'摩洛哥',
'Mozambique':'莫桑比克',
'Myanmar':'缅甸',
'Namibia':'纳米比亚',
'Nepal':'尼泊尔',
'Netherlands':'荷兰',
'New Caledonia':'新喀里多尼亚',
'New Zealand':'新西兰',
'Nicaragua':'尼加拉瓜',
'Niger':'尼日尔',
'Nigeria':'尼日利亚',
'Northern Mariana Islands':'北马里亚纳群岛',
'Norway':'挪威',
'Oman':'阿曼',
'Pakistan':'巴基斯坦',
'Panama':'巴拿马',
'Papua New Guinea':'巴布亚新几内亚',
'Paraguay':'巴拉圭',
'Peru':'秘鲁',
'Philippines':'菲律宾',
'Poland':'波兰',
'Portugal':'葡萄牙',
'Puerto Rico':'波多黎各',
'Qatar':'卡塔尔',
'Reunion':'留尼旺岛',
'Romania':'罗马尼亚',
'Russia':'俄罗斯',
'Rwanda':'卢旺达',
'San Marino':'圣马力诺',
'Sao Tome and Principe':'圣多美和普林西比',
'Saudi Arabia':'沙特阿拉伯',
'Senegal':'塞内加尔',
'Seychelles':'塞舌尔',
'Sierra Leone':'塞拉利昂',
'Singapore':'新加坡',
'Slovakia':'斯洛伐克',
'Slovenia':'斯洛文尼亚',
'Solomon Islands':'所罗门群岛',
'Somalia':'索马里',
'South Africa':'南非',
'Spain':'西班牙',
'Sri Lanka':'斯里兰卡',
'St. Christopher-Nevis':'圣',
'St. Lucia':'圣露西亚',
'St. Vincent and the Grenadines':'圣文森特和格林纳丁斯',
'Sudan':'苏丹',
'Suriname':'苏里南',
'Svalbard':'斯瓦尔巴特群岛',
'Swaziland':'斯威士兰',
'Sweden':'瑞典',
'Switzerland':'瑞士',
'Syria':'叙利亚',
'Taiwan':'台湾',
'Tajikistan':'塔吉克斯坦',
'United Republic of Tanzania':'坦桑尼亚',
'Thailand':'泰国',
'Togo':'多哥',
'Tonga':'汤加',
'Trinidad and Tobago':'特里尼达和多巴哥',
'Tunisia':'突尼斯',
'Turkey':'土耳其',
'Turkmenistan':'土库曼斯坦',
'Turks and Caicos Islands':'特克斯和凯科斯群岛',
'Uganda':'乌干达',
'Ukraine':'乌克兰',
'United Arab Emirates':'阿联酋',
'United Kingdom':'英国',
'United States of America':'美国',
'Uruguay':'乌拉圭',
'Uzbekistan':'乌兹别克斯坦',
'Vanuatu':'瓦努阿图',
'Venezuela':'委内瑞拉',
'Vietnam':'越南',
'Western Sahara':'西撒哈拉',
'Western Samoa':'西萨摩亚',
'Yemen':'也门',
'Yugoslavia':'南斯拉夫',
'Democratic Republic of the Congo':'刚果民主共和国',
'Zambia':'赞比亚',
'Zimbabwe':'津巴布韦',
'South Sudan':'南苏丹',
'Somaliland':'索马里兰',
'Montenegro':'黑山',
'Kosovo':'科索沃',
'Republic of Serbia':'塞尔维亚',

};

option = {
    timeline: {
        axisType: 'category',
            orient: 'vertical',
            autoPlay: true,
            inverse: true,
            playInterval: 5000,
            left: null,
            right: -105,
            top: 20,
            bottom: 20,
            width: 46,
        data: ['2016',]  
    },
    baseOption: {
        visualMap: {
        type: 'piecewise', //分段型。
        splitNumber: 6,
        inverse: true,
        pieces: [{
            min: 0,
            max: 60,
            color: '#759aa0'
        }, {
            min: 60,
            max: 90,
            color: '#73b9bc'
        }, {
            min: 90,
            max: 200,
            color: '#8dc1a9'
        }, {
            min: 200,
            max: 350,
            color: '#e69d87'
        }, {
            min: 350,
            max: 700,
            color: '#ea7e53'
        }, {
            min: 700,
            //max: 1000,
            color: '#dd6b66'
        }],
        left: 'left',
        top: 'bottom',
        textStyle: {
            color: '#000'
        },
        //min: 0,
        //max: 60000,
        //text:['High','Low'],
        //realtime: true,
        //calculable: true,
        //color: ['red','orange','lightgreen']
    },
        series: [{
            type: 'map',
            map: 'world',
            roam: true,
            itemStyle:{
                emphasis:{label:{show:false}}
            },
            nameMap: nameMap
            
        }]
    },
   
    options: [{
        title: {
            text: '1.5 世界各国人均占地面积',
            subtext: '国家基础地理信息中心',
            //sublink: 'http://esa.un.org/wpp/Excel-Data/population.htm',
            left: 'center',
            top: 'top'
        },
        tooltip: {
            trigger: 'item',
            formatter: function (params) {
                var value = (params.value);
                //value = value.toFixed(5);toFixed(3)控制小数位数      
                value = value;
                //var abc=(params.abc);
                return  params.name + ' : ' + value+' m²';
            }
        },
        series: {
            data: value3
            
        } 
    }, ]
};