option = {
  backgroundColor:'#011833',
        color: [
          "#3fdcfd",
          "#37a0d9",
          "#048deb",
          "#0471eb",
          "#96bfff",
          "#8378ea",
          "#aaa4fa",
          "#e7bcf3",
          "#e062ae",
          "#fb7293",
          "#ff7264",
          "#ffdb5c",
          "#feb300",
          "#f18209",
          "#c9dd85",
          "#b7cf64",
          "#50e09b",
          "#29bc76",
          "#14cf5a",
          "#3fdcfd",
          "#37a0d9",
          "#048deb",
        ],
        tooltip: {
          trigger: "item",
          formatter: "{a} <br/>{b} : {c} ({d}%)",
        },
        toolbox: {
          show: true,
        },
        legend: {
          type: "scroll",
          // orient: "vertical",
          left: "0%",
          bottom: "0px",
          textStyle: {
            color: "#fff",
          },
          pageIconColor: "#fff",
          pageTextStyle: {
            color: "#fff",
          },
        },
        series: [
          {
            name: "类别",
            type: "pie",
            radius: [0, 85],
            top: "0px",
            label: {
              show: true,
              formatter: "{b} ({c})",
              fontSize: 14,
            },
            data:[{"name":"人员","value":6}
            ,{"name":"机构","value":4},
            {"name":"医疗机构","value":6},
            {"name":"教育机构","value":0},
            {"name":"企业信息","value":22},
            {"name":"股东信息","value":1},
            {"name":"房产","value":8},
            {"name":"社保","value":0},
            {"name":"发票","value":0},
            {"name":"费用报销","value":4},
            {"name":"专项资金","value":25},
            {"name":"项目","value":6},
            {"name":"公共资源交易","value":22}],
          },
        ],
      };