option = {
    "xAxis":[
        {
            "type":"category",
            "data":[
                "东北",
                "华中",
                "华南",
                "西北",
                "华北",
                "西南",
                "华东"
            ]
        }
    ],
    "yAxis":[
        {
            "type":"value",
        }
    ],
    "series":[
        {
            "type":"line",
            "data":[
                {
                    "value":"12"
                },
                {
                    "value":"12"
                },
                {
                    "value":"25"
                },
                {
                    "value":"34"
                },
                {
                    "value":"48"
                },
                {
                    "value":"51"
                },
                {
                    "value":"64"
                }
            ]
        }
    ],
    "visualMap":
        {
            "type":"piecewise",
            "pieces":[
                {
                    "gte":51,
                    "color":"red"
                },
                // 当lt值为51时报错
                {
                    "lt":50,
                    "color":"#ffff00"
                }
            ]
        }
    
}