option = {
    backgroundColor: '#174B78',
    grid:{
            x:0,
            x2:0,
            y:0,
            y2:0
        }, 
    title: {
        text: "",
        subtext: "",
        textStyle: {
            color: "#fff",
            fontSize: 18
        },
        top: "top",
        left: "center"
    },
    tooltip: {},
    legend: {},
    toolbox: {
        show: false,
        feature: {
            dataView: {
                show: true,
                readOnly: true
            },
            restore: {
                show: true
            },
            saveAsImage: {
                show: true
            }
        }
    },
    animationDuration: 3000,
    animationEasingUpdate: 'quinticInOut',
    series: [{
        name: '行政执法主题视图',
        type: 'graph',
        layout: 'force',

        force: {
           // initLayout: 'circular',
            repulsion: 180,
            gravity: 0.2,
            edgeLength: 90
        },

        data: [{
            "name": "行政执法主题",
            "symbolSize": 24,
            "category": "类目",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法组织体系指标",
            "symbolSize": 10,
            "category": "类目",
            "draggable": "true",
            "value": 1
        }, {
            "name": "街道办事处执法主体",
            "symbolSize": 8,
            "category": "街道办事处执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "街道办执法人员人数",
            "symbolSize": 6,
            "category": "街道办事处执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "南市街道办事处执法人员数",
            "symbolSize": 4,
            "category": "街道办事处执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "南营门街道办事处执法人员数",
            "symbolSize": 4,
            "category": "街道办事处执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "劝业场街道办事处执法人员数",
            "symbolSize": 4,
            "category": "街道办事处执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "体育场街道办事处执法人员数",
            "symbolSize": 4,
            "category": "街道办事处执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "小白楼街道办事处执法人员数",
            "symbolSize": 4,
            "category": "街道办事处执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "新兴街道办事处执法人员数",
            "symbolSize": 4,
            "category": "街道办事处执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "街道办执法职权数",
            "symbolSize": 6,
            "category": "街道办事处执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "南市街道办事处职权数",
            "symbolSize": 4,
            "category": "街道办事处执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "南营门街道办事处职权数",
            "symbolSize": 4,
            "category": "街道办事处执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "劝业场街道办事处职权数",
            "symbolSize": 4,
            "category": "街道办事处执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "体育场街道办事处职权数",
            "symbolSize": 4,
            "category": "街道办事处执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "小白楼街道办事处职权数",
            "symbolSize": 4,
            "category": "街道办事处执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "新兴街道办事处职权数",
            "symbolSize": 4,
            "category": "街道办事处执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "委办局执法主体",
            "symbolSize": 8,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "委办局执法人员人数",
            "symbolSize": 6,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区安全生产监督管理局执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区保密局执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区机构编制委员会办公室执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区市场和质量监督管理局执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区财政局执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "和平区城市管理综合执法局执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "和平档案局执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区物价局执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "和平区房地产管理局执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市公安局和平分局执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市公安交通管理局和平分队执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区公安消防支队执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市规划局和平区规划分局执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区环境保护局执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区建设管理委员会执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "和平区教育局执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "和平区民政局执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "和平区市容园林委执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "和平区人力社保局执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区人民政府人民防空办公室执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区审计局执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区商务委员会执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区司法局执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "和平区统计局执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "和平区体育局执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "和平区卫生局执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区文化市场执法大队执法人员数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "委办局执法职权数",
            "symbolSize": 6,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区安全生产监督管理局职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区保密局职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区机构编制委员会办公室职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区市场和质量监督管理局职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区财政局职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "和平区城市管理综合执法局职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "和平档案局职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区物价局职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "和平区房地产管理局职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市公安局和平分局职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市公安交通管理局和平分队职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区公安消防支队职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市规划局和平区规划分局职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区环境保护局职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区建设管理委员会职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "和平区教育局职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "和平区民政局职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "和平区市容园林委职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "和平区人力社保局职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区人民政府人民防空办公室职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区审计局职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区商务委员会职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区司法局职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "和平区统计局职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "和平区体育局职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "和平区卫生局职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区文化市场执法大队职权数",
            "symbolSize": 4,
            "category": "委办局执法主体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法业务能力指标",
            "symbolSize": 10,
            "category": "类目",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法案件来源情况",
            "symbolSize": 8,
            "category": "执法案件来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "常发来源执法案件环比增长",
            "symbolSize": 6,
            "category": "执法案件来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "常发来源执法案件数量",
            "symbolSize": 4,
            "category": "执法案件来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "上级交办常发案件件数",
            "symbolSize": 2,
            "category": "执法案件来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "其他部门移交常发案件件数",
            "symbolSize": 2,
            "category": "执法案件来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "投诉举报常发案件件数",
            "symbolSize": 2,
            "category": "执法案件来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "现场检查常发案件件数",
            "symbolSize": 2,
            "category": "执法案件来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "其他来源常发案件件数",
            "symbolSize": 2,
            "category": "执法案件来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "偶发来源执法案件环比增长",
            "symbolSize": 6,
            "category": "执法案件来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "偶发来源执法案件数量",
            "symbolSize": 4,
            "category": "执法案件来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "上级交办偶发案件件数",
            "symbolSize": 2,
            "category": "执法案件来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "其他部门移交偶发案件件数",
            "symbolSize": 2,
            "category": "执法案件来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "投诉举报偶发案件件数",
            "symbolSize": 2,
            "category": "执法案件来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "现场检查偶发案件件数",
            "symbolSize": 2,
            "category": "执法案件来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "其他来源偶发案件件数",
            "symbolSize": 2,
            "category": "执法案件来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法案件程序情况",
            "symbolSize": 8,
            "category": "执法案件程序情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "一般程序案件环比增长",
            "symbolSize": 6,
            "category": "执法案件程序情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "一般程序案件数",
            "symbolSize": 4,
            "category": "执法案件程序情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "简易程序案件环比增长",
            "symbolSize": 6,
            "category": "执法案件程序情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "简易程序案件数",
            "symbolSize": 4,
            "category": "执法案件程序情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法案件处罚情况",
            "symbolSize": 8,
            "category": "执法案件处罚情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "常发执法案件处罚数环比增长",
            "symbolSize": 6,
            "category": "执法案件处罚情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "常发案件处罚数",
            "symbolSize": 4,
            "category": "执法案件处罚情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "常发案件警告件数",
            "symbolSize": 2,
            "category": "执法案件处罚情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "常发案件处罚件数",
            "symbolSize": 2,
            "category": "执法案件处罚情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "常发案件没收违法所得没收非法财物件数",
            "symbolSize": 2,
            "category": "执法案件处罚情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "常发案件责令停产停业件数",
            "symbolSize": 2,
            "category": "执法案件处罚情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "常发案件暂扣或吊销许可证或营业执照件数",
            "symbolSize": 2,
            "category": "执法案件处罚情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "常发案件行政拘留件数",
            "symbolSize": 2,
            "category": "执法案件处罚情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "常发案件法律行政法规规定的其他行政处罚件数",
            "symbolSize": 2,
            "category": "执法案件处罚情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "常发案件不作出行政处罚件数",
            "symbolSize": 2,
            "category": "执法案件处罚情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "偶发执法案件处罚数环比增长",
            "symbolSize": 6,
            "category": "执法案件处罚情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "偶发案件处罚数",
            "symbolSize": 4,
            "category": "执法案件处罚情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "偶发案件警告件数",
            "symbolSize": 2,
            "category": "执法案件处罚情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "偶发案件处罚件数",
            "symbolSize": 2,
            "category": "执法案件处罚情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "偶发案件没收违法所得没收非法财物件数",
            "symbolSize": 2,
            "category": "执法案件处罚情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "偶发案件责令停产停业件数",
            "symbolSize": 2,
            "category": "执法案件处罚情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "偶发案件暂扣或吊销许可证或营业执照件数",
            "symbolSize": 2,
            "category": "执法案件处罚情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "偶发案件行政拘留件数",
            "symbolSize": 2,
            "category": "执法案件处罚情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "偶发案件法律行政法规规定的其他行政处罚件数",
            "symbolSize": 2,
            "category": "执法案件处罚情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "偶发案件不作出行政处罚件数",
            "symbolSize": 2,
            "category": "执法案件处罚情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "案件监督态势指标",
            "symbolSize": 10,
            "category": "类目",
            "draggable": "true",
            "value": 1
        }, {
            "name": "监督来源情况",
            "symbolSize": 8,
            "category": "监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "自动预警监督案件数环比增长",
            "symbolSize": 6,
            "category": "监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "自动预警监督案件数",
            "symbolSize": 4,
            "category": "监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "主动抽样监督案件数环比增长",
            "symbolSize": 6,
            "category": "监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "主动抽样监督案件数",
            "symbolSize": 4,
            "category": "监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "重大案件监督案件数环比增长",
            "symbolSize": 6,
            "category": "监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "重大案件监督案件数",
            "symbolSize": 4,
            "category": "监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "投诉举报监督案件数环比增长",
            "symbolSize": 6,
            "category": "监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "投诉举报监督案件数",
            "symbolSize": 4,
            "category": "监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "交办转办监督案件数环比增长",
            "symbolSize": 6,
            "category": "监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "交办转办监督案件数",
            "symbolSize": 4,
            "category": "监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "自动预警监督来源情况",
            "symbolSize": 8,
            "category": "自动预警监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法资格预警案件数环比增长",
            "symbolSize": 6,
            "category": "自动预警监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法资格预警案件数",
            "symbolSize": 4,
            "category": "自动预警监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法主体资格预警案件件数",
            "symbolSize": 2,
            "category": "自动预警监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法人数预警案件件数",
            "symbolSize": 2,
            "category": "自动预警监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法人员资格预警案件件数",
            "symbolSize": 2,
            "category": "自动预警监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法程序预警案件数环比增长",
            "symbolSize": 6,
            "category": "自动预警监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法程序预警案件数",
            "symbolSize": 4,
            "category": "自动预警监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法过程预警案件件数",
            "symbolSize": 2,
            "category": "自动预警监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法文书预警案件件数",
            "symbolSize": 2,
            "category": "自动预警监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "录入超时预警案件件数",
            "symbolSize": 2,
            "category": "自动预警监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法结果预警案件数环比增长",
            "symbolSize": 6,
            "category": "自动预警监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法结果预警类别",
            "symbolSize": 4,
            "category": "自动预警监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "处罚决定预警案件件数",
            "symbolSize": 2,
            "category": "自动预警监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执行情况预警案件件数",
            "symbolSize": 2,
            "category": "自动预警监督来源情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "监督效能考核指标",
            "symbolSize": 10,
            "category": "类目",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法案件立案情况",
            "symbolSize": 8,
            "category": "执法案件立案情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法案件立案件率",
            "symbolSize": 6,
            "category": "执法案件立案情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法案件立案件数",
            "symbolSize": 4,
            "category": "执法案件立案情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法案件未立案件数",
            "symbolSize": 4,
            "category": "执法案件立案情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法案件执行情况",
            "symbolSize": 8,
            "category": "执法案件执行情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法案件办结率",
            "symbolSize": 6,
            "category": "执法案件执行情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法案件已结案案件数",
            "symbolSize": 4,
            "category": "执法案件执行情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法案件未结案案件数",
            "symbolSize": 4,
            "category": "执法案件执行情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法检查工作情况",
            "symbolSize": 8,
            "category": "执法检查工作情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法案件检查率",
            "symbolSize": 6,
            "category": "执法检查工作情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "日常检查总件数",
            "symbolSize": 4,
            "category": "执法检查工作情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "计划检查总件数",
            "symbolSize": 4,
            "category": "执法检查工作情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法案件监督结果",
            "symbolSize": 8,
            "category": "执法案件监督结果",
            "draggable": "true",
            "value": 1
        }, {
            "name": "执法案件准确率",
            "symbolSize": 6,
            "category": "执法案件监督结果",
            "draggable": "true",
            "value": 1
        }, {
            "name": "有问题案件件数",
            "symbolSize": 4,
            "category": "执法案件监督结果",
            "draggable": "true",
            "value": 1
        }, {
            "name": "无问题案件件数",
            "symbolSize": 4,
            "category": "执法案件监督结果",
            "draggable": "true",
            "value": 1
        }],
        links: [{
            "source": "行政执法主题",
            "target": "执法组织体系指标"
        }, {
            "source": "执法组织体系指标",
            "target": "街道办事处执法主体"
        }, {
            "source": "街道办事处执法主体",
            "target": "街道办执法人员人数"
        }, {
            "source": "街道办执法人员人数",
            "target": "南市街道办事处执法人员数"
        }, {
            "source": "街道办执法人员人数",
            "target": "南营门街道办事处执法人员数"
        }, {
            "source": "街道办执法人员人数",
            "target": "劝业场街道办事处执法人员数"
        }, {
            "source": "街道办执法人员人数",
            "target": "体育场街道办事处执法人员数"
        }, {
            "source": "街道办执法人员人数",
            "target": "小白楼街道办事处执法人员数"
        }, {
            "source": "街道办执法人员人数",
            "target": "新兴街道办事处执法人员数"
        }, {
            "source": "街道办事处执法主体",
            "target": "街道办执法职权数"
        }, {
            "source": "街道办执法职权数",
            "target": "南市街道办事处职权数"
        }, {
            "source": "街道办执法职权数",
            "target": "南营门街道办事处职权数"
        }, {
            "source": "街道办执法职权数",
            "target": "劝业场街道办事处职权数"
        }, {
            "source": "街道办执法职权数",
            "target": "体育场街道办事处职权数"
        }, {
            "source": "街道办执法职权数",
            "target": "小白楼街道办事处职权数"
        }, {
            "source": "街道办执法职权数",
            "target": "新兴街道办事处职权数"
        }, {
            "source": "执法组织体系指标",
            "target": "委办局执法主体"
        }, {
            "source": "委办局执法主体",
            "target": "委办局执法人员人数"
        }, {
            "source": "委办局执法人员人数",
            "target": "天津市和平区安全生产监督管理局执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "天津市和平区保密局执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "天津市和平区机构编制委员会办公室执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "天津市和平区市场和质量监督管理局执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "天津市和平区财政局执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "和平区城市管理综合执法局执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "和平档案局执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "天津市和平区物价局执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "和平区房地产管理局执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "天津市公安局和平分局执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "天津市公安交通管理局和平分队执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "天津市和平区公安消防支队执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "天津市规划局和平区规划分局执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "天津市和平区环境保护局执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "天津市和平区建设管理委员会执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "和平区教育局执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "和平区民政局执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "和平区市容园林委执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "和平区人力社保局执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "天津市和平区人民政府人民防空办公室执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "天津市和平区审计局执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "天津市和平区商务委员会执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "天津市和平区司法局执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "和平区统计局执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "和平区体育局执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "和平区卫生局执法人员数"
        }, {
            "source": "委办局执法人员人数",
            "target": "天津市和平区文化市场执法大队执法人员数"
        }, {
            "source": "委办局执法主体",
            "target": "委办局执法职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "天津市和平区安全生产监督管理局职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "天津市和平区保密局职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "天津市和平区机构编制委员会办公室职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "天津市和平区市场和质量监督管理局职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "天津市和平区财政局职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "和平区城市管理综合执法局职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "和平档案局职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "天津市和平区物价局职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "和平区房地产管理局职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "天津市公安局和平分局职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "天津市公安交通管理局和平分队职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "天津市和平区公安消防支队职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "天津市规划局和平区规划分局职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "天津市和平区环境保护局职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "天津市和平区建设管理委员会职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "和平区教育局职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "和平区民政局职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "和平区市容园林委职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "和平区人力社保局职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "天津市和平区人民政府人民防空办公室职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "天津市和平区审计局职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "天津市和平区商务委员会职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "天津市和平区司法局职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "和平区统计局职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "和平区体育局职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "和平区卫生局职权数"
        }, {
            "source": "委办局执法职权数",
            "target": "天津市和平区文化市场执法大队职权数"
        }, {
            "source": "行政执法主题",
            "target": "执法业务能力指标"
        }, {
            "source": "执法业务能力指标",
            "target": "执法案件来源情况"
        }, {
            "source": "执法案件来源情况",
            "target": "常发来源执法案件环比增长"
        }, {
            "source": "常发来源执法案件环比增长",
            "target": "常发来源执法案件数量"
        }, {
            "source": "常发来源执法案件数量",
            "target": "上级交办常发案件件数"
        }, {
            "source": "常发来源执法案件数量",
            "target": "其他部门移交常发案件件数"
        }, {
            "source": "常发来源执法案件数量",
            "target": "投诉举报常发案件件数"
        }, {
            "source": "常发来源执法案件数量",
            "target": "现场检查常发案件件数"
        }, {
            "source": "常发来源执法案件数量",
            "target": "其他来源常发案件件数"
        }, {
            "source": "执法案件来源情况",
            "target": "偶发来源执法案件环比增长"
        }, {
            "source": "偶发来源执法案件环比增长",
            "target": "偶发来源执法案件数量"
        }, {
            "source": "偶发来源执法案件数量",
            "target": "上级交办偶发案件件数"
        }, {
            "source": "偶发来源执法案件数量",
            "target": "其他部门移交偶发案件件数"
        }, {
            "source": "偶发来源执法案件数量",
            "target": "投诉举报偶发案件件数"
        }, {
            "source": "偶发来源执法案件数量",
            "target": "现场检查偶发案件件数"
        }, {
            "source": "偶发来源执法案件数量",
            "target": "其他来源偶发案件件数"
        }, {
            "source": "执法业务能力指标",
            "target": "执法案件程序情况"
        }, {
            "source": "执法案件程序情况",
            "target": "一般程序案件环比增长"
        }, {
            "source": "一般程序案件环比增长",
            "target": "一般程序案件数"
        }, {
            "source": "执法案件程序情况",
            "target": "简易程序案件环比增长"
        }, {
            "source": "简易程序案件环比增长",
            "target": "简易程序案件数"
        }, {
            "source": "执法业务能力指标",
            "target": "执法案件处罚情况"
        }, {
            "source": "执法案件处罚情况",
            "target": "常发执法案件处罚数环比增长"
        }, {
            "source": "常发执法案件处罚数环比增长",
            "target": "常发案件处罚数"
        }, {
            "source": "常发案件处罚数",
            "target": "常发案件警告件数"
        }, {
            "source": "常发案件处罚数",
            "target": "常发案件处罚件数"
        }, {
            "source": "常发案件处罚数",
            "target": "常发案件没收违法所得没收非法财物件数"
        }, {
            "source": "常发案件处罚数",
            "target": "常发案件责令停产停业件数"
        }, {
            "source": "常发案件处罚数",
            "target": "常发案件暂扣或吊销许可证或营业执照件数"
        }, {
            "source": "常发案件处罚数",
            "target": "常发案件行政拘留件数"
        }, {
            "source": "常发案件处罚数",
            "target": "常发案件法律行政法规规定的其他行政处罚件数"
        }, {
            "source": "常发案件处罚数",
            "target": "常发案件不作出行政处罚件数"
        }, {
            "source": "执法案件处罚情况",
            "target": "偶发执法案件处罚数环比增长"
        }, {
            "source": "偶发执法案件处罚数环比增长",
            "target": "偶发案件处罚数"
        }, {
            "source": "偶发案件处罚数",
            "target": "偶发案件警告件数"
        }, {
            "source": "偶发案件处罚数",
            "target": "偶发案件处罚件数"
        }, {
            "source": "偶发案件处罚数",
            "target": "偶发案件没收违法所得没收非法财物件数"
        }, {
            "source": "偶发案件处罚数",
            "target": "偶发案件责令停产停业件数"
        }, {
            "source": "偶发案件处罚数",
            "target": "偶发案件暂扣或吊销许可证或营业执照件数"
        }, {
            "source": "偶发案件处罚数",
            "target": "偶发案件行政拘留件数"
        }, {
            "source": "偶发案件处罚数",
            "target": "偶发案件法律行政法规规定的其他行政处罚件数"
        }, {
            "source": "偶发案件处罚数",
            "target": "偶发案件不作出行政处罚件数"
        }, {
            "source": "行政执法主题",
            "target": "案件监督态势指标"
        }, {
            "source": "案件监督态势指标",
            "target": "监督来源情况"
        }, {
            "source": "监督来源情况",
            "target": "自动预警监督案件数环比增长"
        }, {
            "source": "自动预警监督案件数环比增长",
            "target": "自动预警监督案件数"
        }, {
            "source": "监督来源情况",
            "target": "主动抽样监督案件数环比增长"
        }, {
            "source": "主动抽样监督案件数环比增长",
            "target": "主动抽样监督案件数"
        }, {
            "source": "监督来源情况",
            "target": "重大案件监督案件数环比增长"
        }, {
            "source": "重大案件监督案件数环比增长",
            "target": "重大案件监督案件数"
        }, {
            "source": "监督来源情况",
            "target": "投诉举报监督案件数环比增长"
        }, {
            "source": "投诉举报监督案件数环比增长",
            "target": "投诉举报监督案件数"
        }, {
            "source": "监督来源情况",
            "target": "交办转办监督案件数环比增长"
        }, {
            "source": "交办转办监督案件数环比增长",
            "target": "交办转办监督案件数"
        }, {
            "source": "案件监督态势指标",
            "target": "自动预警监督来源情况"
        }, {
            "source": "自动预警监督来源情况",
            "target": "执法资格预警案件数环比增长"
        }, {
            "source": "执法资格预警案件数环比增长",
            "target": "执法资格预警案件数"
        }, {
            "source": "执法资格预警案件数",
            "target": "执法主体资格预警案件件数"
        }, {
            "source": "执法资格预警案件数",
            "target": "执法人数预警案件件数"
        }, {
            "source": "执法资格预警案件数",
            "target": "执法人员资格预警案件件数"
        }, {
            "source": "自动预警监督来源情况",
            "target": "执法程序预警案件数环比增长"
        }, {
            "source": "执法程序预警案件数环比增长",
            "target": "执法程序预警案件数"
        }, {
            "source": "执法程序预警案件数",
            "target": "执法过程预警案件件数"
        }, {
            "source": "执法程序预警案件数",
            "target": "执法文书预警案件件数"
        }, {
            "source": "执法程序预警案件数",
            "target": "录入超时预警案件件数"
        }, {
            "source": "自动预警监督来源情况",
            "target": "执法结果预警案件数环比增长"
        }, {
            "source": "执法结果预警案件数环比增长",
            "target": "执法结果预警类别"
        }, {
            "source": "执法结果预警类别",
            "target": "处罚决定预警案件件数"
        }, {
            "source": "执法结果预警类别",
            "target": "执行情况预警案件件数"
        }, {
            "source": "行政执法主题",
            "target": "监督效能考核指标"
        }, {
            "source": "监督效能考核指标",
            "target": "执法案件立案情况"
        }, {
            "source": "执法案件立案情况",
            "target": "执法案件立案件率"
        }, {
            "source": "执法案件立案件率",
            "target": "执法案件立案件数"
        }, {
            "source": "执法案件立案件率",
            "target": "执法案件未立案件数"
        }, {
            "source": "监督效能考核指标",
            "target": "执法案件执行情况"
        }, {
            "source": "执法案件执行情况",
            "target": "执法案件办结率"
        }, {
            "source": "执法案件办结率",
            "target": "执法案件已结案案件数"
        }, {
            "source": "执法案件办结率",
            "target": "执法案件未结案案件数"
        }, {
            "source": "监督效能考核指标",
            "target": "执法检查工作情况"
        }, {
            "source": "执法检查工作情况",
            "target": "执法案件检查率"
        }, {
            "source": "执法案件检查率",
            "target": "日常检查总件数"
        }, {
            "source": "执法案件检查率",
            "target": "计划检查总件数"
        }, {
            "source": "监督效能考核指标",
            "target": "执法案件监督结果"
        }, {
            "source": "执法案件监督结果",
            "target": "执法案件准确率"
        }, {
            "source": "执法案件准确率",
            "target": "有问题案件件数"
        }, {
            "source": "执法案件准确率",
            "target": "无问题案件件数"
        }],
        categories: [{
            "name": "类目"
        }, {
            "name": "街道办事处执法主体"
        }, {
            "name": "委办局执法主体"
        }, {
            "name": "执法案件来源情况"
        }, {
            "name": "执法案件程序情况"
        }, {
            "name": "执法案件处罚情况"
        }, {
            "name": "监督来源情况"
        }, {
            "name": "自动预警监督来源情况"
        }, {
            "name": "执法案件立案情况"
        }, {
            "name": "执法案件执行情况"
        }, {
            "name": "执法检查工作情况"
        }, {
            "name": "执法案件监督结果"
        }],

        focusNodeAdjacency: true,
        roam: true,
        label: {
            normal: {

                show: true,
                position: 'top',
                textStyle: {
                     fontSize: 14
                }
            }
        },
        lineStyle: {
            normal: {
                color: 'source',
                curveness: 0
                //type: "solid"
            }
        }
    }]
};