var data = [
    {
    name: '进口',
    value: 2450374,
    children: 
    [
{"name":"谷物","value":"5912"},
{"name":"小麦","value":"858"},
{"name":"稻米","value":"1639"},
{"name":"大豆","value":"38087"},
{"name":"食用油","value":"4728"},
{"name":"食糖","value":"1029"},
{"name":"天然橡胶","value":"3607"},
{"name":"合成橡胶","value":"7622"},
{"name":"原木","value":"10985"},
{"name":"锯材","value":"10131"},
{"name":"纸浆","value":"19716"},
{"name":"羊毛","value":"3278"},
{"name":"棉花","value":"3172"},
{"name":"纺织纤维","value":"1079"},
{"name":"聚酯纤维","value":"284"},
{"name":"聚丙烯腈纤维","value":"424"},
{"name":"铁矿砂","value":"75922"},
{"name":"锰矿砂","value":"5811"},
{"name":"铜矿砂","value":"31935"},
{"name":"铬矿砂","value":"2853"},
{"name":"氧化铝","value":"320"},
{"name":"煤","value":"24761"},
{"name":"原油","value":"240380"},
{"name":"成品油","value":"20143"},
{"name":"乙二醇","value":"9006"},
{"name":"对苯二甲酸","value":"668"},
{"name":"己内酰胺","value":"349"},
{"name":"医药品","value":"29607"},
{"name":"肥料","value":"2724"},
{"name":"尿素","value":"45"},
{"name":"氮磷钾复合肥","value":"669"},
{"name":"磷酸氢二胺","value":"25"},
{"name":"氯化钾","value":"1848"},
{"name":"聚乙烯","value":"12334"},
{"name":"聚丙烯","value":"4194"},
{"name":"聚苯乙烯","value":"6940"},
{"name":"ABS树脂","value":"3924"},
{"name":"聚氯乙烯","value":"998"},
{"name":"聚酯切片","value":"464"},
{"name":"农药","value":"690"},
{"name":"纸及纸板","value":"5527"},
{"name":"钢材","value":"16435"},
{"name":"未锻造铜","value":"31451"},
{"name":"铜材","value":"5997"},
{"name":"未锻造铝","value":"449"},
{"name":"铝材","value":"2702"},
{"name":"锅炉","value":"25"},
{"name":"压缩机","value":"1069"},
{"name":"机床","value":"9664"},
{"name":"阀门","value":"7322"},
{"name":"自动数据处理设备","value":"32894"},
{"name":"电话机","value":"311"},
{"name":"收音设备","value":"283"},
{"name":"电视机","value":"17"},
{"name":"电视显像管","value":"0"},
{"name":"汽车","value":"50514"},
{"name":"小轿车","value":"19374"},
{"name":"货车","value":"813"},
{"name":"自卸车","value":"17"},
{"name":"汽车底盘","value":"161"},
{"name":"汽车零件","value":"0"},
{"name":"飞机","value":"27581"},
{"name":"船舶","value":"0"},
{"name":"医疗仪器","value":"11246"},
{"name":"机电产品","value":"965700"},
{"name":"高新技术产品","value":"671661"}
]},

{
    name: '出口',
    value: 3437300,
    children: [
        {"name":"活猪","value":"427"},
{"name":"活家禽","value":"1"},
{"name":"牛肉","value":"3"},
{"name":"猪肉","value":"195"},
{"name":"冻鸡","value":"238"},
{"name":"水海产品","value":"22001"},
{"name":"鲜蛋","value":"112"},
{"name":"谷物","value":"1066"},
{"name":"稻米","value":"888"},
{"name":"玉米","value":"6"},
{"name":"蔬菜","value":"12615"},
{"name":"冷藏蔬菜","value":"4637"},
{"name":"橙","value":"973"},
{"name":"苹果","value":"1299"},
{"name":"松子","value":"185"},
{"name":"大豆","value":"100"},
{"name":"花生","value":"279"},
{"name":"植物油","value":"307"},
{"name":"食糖","value":"101"},
{"name":"蜂蜜","value":"249"},
{"name":"茶叶","value":"1778"},
{"name":"辣椒干","value":"154"},
{"name":"猪肉罐头","value":"150"},
{"name":"蘑菇罐头","value":"576"},
{"name":"啤酒","value":"252"},
{"name":"肠衣","value":"1356"},
{"name":"羽毛羽绒","value":"826"},
{"name":"药材","value":"1102"},
{"name":"烤烟","value":"448"},
{"name":"纸烟","value":"721"},
{"name":"锯材","value":"178"},
{"name":"生丝","value":"291"},
{"name":"山羊绒","value":"238"},
{"name":"棉花","value":"94"},
{"name":"石墨","value":"348"},
{"name":"碳酸镁氧化镁","value":"1048"},
{"name":"萤石","value":"138"},
{"name":"硫酸钡","value":"159"},
{"name":"滑石","value":"171"},
{"name":"氧化铝","value":"784"},
{"name":"煤","value":"788"},
{"name":"焦炭","value":"2975"},
{"name":"原油","value":"1270"},
{"name":"成品油","value":"35884"},
{"name":"石蜡","value":"523"},
{"name":"仲钨酸铵","value":"156"},
{"name":"氧化锌","value":"33"},
{"name":"合成染料","value":"1619"},
{"name":"医药品","value":"17430"},
{"name":"中式成药","value":"262"},
{"name":"医用敷料","value":"1435"},
{"name":"洗衣粉","value":"358"},
{"name":"烟花爆竹","value":"866"},
{"name":"松香","value":"82"},
{"name":"轮胎","value":"15110"},
{"name":"纸及纸板","value":"7004"},
{"name":"棉纱线","value":"1766"},
{"name":"丝织物","value":"647"},
{"name":"棉机织物","value":"14336"},
{"name":"亚麻","value":"1066"},
{"name":"混纺织物","value":"2112"},
{"name":"地毯","value":"2975"},
{"name":"塑料编织袋","value":"1000"},
{"name":"水泥","value":"490"},
{"name":"平板玻璃","value":"1556"},
{"name":"玻璃制品","value":"6639"},
{"name":"陶瓷器皿","value":"11640"},
{"name":"生铁","value":"0"},
{"name":"钢坯","value":"13"},
{"name":"钢材","value":"60596"},
{"name":"未锻造铜","value":"1884"},
{"name":"铜材","value":"4268"},
{"name":"未锻造铝","value":"1216"},
{"name":"铝材","value":"15250"},
{"name":"未锻造锌","value":"75"},
{"name":"未锻造锡","value":"46"},
{"name":"未锻造锑","value":"44"},
{"name":"未锻造锰","value":"858"},
{"name":"钢铜标准件","value":"6585"},
{"name":"手用","value":"11570"},
{"name":"电扇","value":"5458"},
{"name":"纺织机械","value":"3666"},
{"name":"缝纫机","value":"1444"},
{"name":"机床","value":"4000"},
{"name":"计算器","value":"354"},
{"name":"数据处理设备","value":"171993"},
{"name":"数据处理设备零件","value":"44314"},
{"name":"轴承","value":"4261"},
{"name":"电动机","value":"11846"},
{"name":"变流器","value":"17903"},
{"name":"原电池","value":"2140"},
{"name":"蓄电池","value":"14381"},
{"name":"电话机","value":"142198"},
{"name":"收音设备","value":"3843"},
{"name":"电视机","value":"14929"},
{"name":"电容器","value":"5052"},
{"name":"保护电路装置","value":"29887"},
{"name":"二极管半导体","value":"26543"},
{"name":"电线和电缆","value":"21582"},
{"name":"集装箱","value":"10434"},
{"name":"汽车","value":"14762"},
{"name":"汽车零件","value":"0"},
{"name":"自行车","value":"3251"},
{"name":"船舶","value":"0"},
{"name":"照相机","value":"3548"},
{"name":"医疗仪器","value":"11399"},
{"name":"手表","value":"2202"},
{"name":"日用钟","value":"767"},
{"name":"家具","value":"53665"},
{"name":"非针织服装","value":"157615"},
{"name":"针织服装","value":"62580"},
{"name":"皮鞋","value":"9313"},
{"name":"橡胶或布鞋","value":"13712"},
{"name":"塑料制品","value":"43452"},
{"name":"玩具","value":"25065"},
{"name":"球","value":"473"},
{"name":"伞","value":"2383"},
{"name":"竹编","value":"141"},
{"name":"藤编","value":"81"},
{"name":"草编","value":"132"},
{"name":"柳编","value":"468"},
{"name":"机电产品","value":"1460326"},
{"name":"高新技术产品","value":"746816"}
        
        ]}

]
// var modes = ['2012Budget', '2011Budget', 'Growth'];
option = {
    title: {
        left: 0,
        top: "4%",
        text: ['{c|}' + '{d|中国进出口主要货品（2018）YM}'],
        // text:[],
        textStyle: {
            rich: {
                c: {
                    color: '#0000',
                    fontSize: 25,
                    fontWeight: 'bold',
                    width: 4,
                    height: 15,
                    backgroundColor: '#2196f3',

                },
                d: {
                 //   color: '#3e4956',
                    fontWeight: 'bold',
                    fontSize: 17,
                    padding: [0, 0, 0, 30],
                },
            }
        },
    },
    tooltip: {},
    series: [{
        name: '全部',
        type: 'treemap',
        visibleMin: 300,
        data: data,
        leafDepth: 4, //呈现层级，若为1加载时仅展开一层，接下来的每一层通过单击进入，如上面的效果图所示，  
        //每一层级呈现的样式  
        label: {
            show: true ,
            fontSize: 12,
          //  color: '#000000',
            formatter: function(params) {
                var arr = [
                    params.name,
                    params.value + '（百万美元）'
                ];
                return arr.join('\n');
            }
        },
        upperLabel: {
                    show: true,
                    height: 20
                },                
                itemStyle: {
                    borderColor: '#333'
                },
        levels: [{
                 colorSaturation: [0.2, 0.8],
                itemStyle: {
                    normal: {
                        borderColor: '#333',
                        borderWidth: 1,
                        gapWidth: 2
                    }
                }
            },
            {
                colorSaturation: [0.3, 0.7],
                colorMappingBy: 'id',
                itemStyle: {
                    normal: {
                        // borderColorSaturation: 0.7,
                        gapWidth: 2,
                        borderWidth: 2
                    }
                }
            },
        ]
    }]
};