option = {
    backgroundColor: '#174B78',

    grid: {
        x: 0,
        x2: 0,
        y: 0,
        y2: 0
    },

    title: {
        text: "",
        subtext: "",
        textStyle: {
            color: "#fff",
            fontSize: 18
        },
        top: "top",
        left: "center"
    },
    tooltip: {},
    legend: {},
    toolbox: {
        show: false,
        feature: {
            dataView: {
                show: true,
                readOnly: true
            },
            restore: {
                show: true
            },
            saveAsImage: {
                show: true
            }
        }
    },
    animationDuration: 3000,
    animationEasingUpdate: 'quinticInOut',
    series: [{
        name: '区域经济主题视图',
        type: 'graph',
        layout: 'force',

        force: {
            // initLayout: 'circular',
            repulsion: 170,
            gravity: 0.2,
            edgeLength: 90
        },

        data: [{
            "name": "区域经济主题",
            // "x": 0,
            // y: 0,
            "symbolSize": 24,
            "draggable": "true",
            "value": 1

        }, {
            "name": "主要社会经济指标",
            "symbolSize": 10,
            "category": "类目",
            "draggable": "true",
            "value": 1
        }, {
            "name": "地区生产总值情况",
            "symbolSize": 8,
            "category": "地区生产总值情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "地区生产总值同比增长",
            "symbolSize": 6,
            "category": "地区生产总值情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "地区生产总值",
            "symbolSize": 4,
            "category": "地区生产总值情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "地区生产总值计划增长",
            "symbolSize": 4,
            "category": "地区生产总值情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "第二产业同比增长",
            "symbolSize": 6,
            "category": "地区生产总值情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "第二产业总值",
            "symbolSize": 4,
            "category": "地区生产总值情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "第三产业同比增长",
            "symbolSize": 6,
            "category": "地区生产总值情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "第三产业总值",
            "symbolSize": 4,
            "category": "地区生产总值情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "现代服务业同比增长",
            "symbolSize": 6,
            "category": "地区生产总值情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "现代服务业增加值",
            "symbolSize": 4,
            "category": "地区生产总值情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "民营经济同比增长",
            "symbolSize": 6,
            "category": "地区生产总值情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "民营经济增加值",
            "symbolSize": 4,
            "category": "地区生产总值情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "财政收入情况",
            "symbolSize": 8,
            "category": "财政收入情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "财政收入同比增长",
            "symbolSize": 6,
            "category": "财政收入情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "财政收入金额",
            "symbolSize": 4,
            "category": "财政收入情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "留区一般预算财政收入同比增长",
            "symbolSize": 6,
            "category": "财政收入情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "留区一般预算财政收入金额",
            "symbolSize": 4,
            "category": "财政收入情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "区级财政支出金额同比增长",
            "symbolSize": 6,
            "category": "财政收入情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "区级财政支出金额",
            "symbolSize": 4,
            "category": "财政收入情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "税收情况",
            "symbolSize": 8,
            "category": "税收情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "地税税收同比增长",
            "symbolSize": 6,
            "category": "税收情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "地税主要税种完成税收情况",
            "symbolSize": 4,
            "category": "税收情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "营业税",
            "symbolSize": 2,
            "category": "税收情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "个人所得税",
            "symbolSize": 2,
            "category": "税收情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "城建税（地税）",
            "symbolSize": 2,
            "category": "税收情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "企业所得税（地税）",
            "symbolSize": 2,
            "category": "税收情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "其他税(含费）",
            "symbolSize": 2,
            "category": "税收情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "国税税收同比增长",
            "symbolSize": 6,
            "category": "税收情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "国税分税种完成税收情况",
            "symbolSize": 4,
            "category": "税收情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "增值税",
            "symbolSize": 2,
            "category": "税收情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "消费税",
            "symbolSize": 2,
            "category": "税收情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "企业所得税(国税)",
            "symbolSize": 2,
            "category": "税收情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "城建税(国税)",
            "symbolSize": 2,
            "category": "税收情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "区域固定资产投资情况",
            "symbolSize": 8,
            "category": "区域固定资产投资情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "区域固定资产投资同比增长",
            "symbolSize": 6,
            "category": "区域固定资产投资情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "区域固定资产投资额",
            "symbolSize": 4,
            "category": "区域固定资产投资情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "开工项目同比增长",
            "symbolSize": 6,
            "category": "区域固定资产投资情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "开工项目数",
            "symbolSize": 4,
            "category": "区域固定资产投资情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "社会事业项目数",
            "symbolSize": 2,
            "category": "区域固定资产投资情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "商业酒店写字楼项目数",
            "symbolSize": 2,
            "category": "区域固定资产投资情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "住宅公寓项目数",
            "symbolSize": 2,
            "category": "区域固定资产投资情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "开工面积同比增长",
            "symbolSize": 6,
            "category": "区域固定资产投资情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "开工面积",
            "symbolSize": 4,
            "category": "区域固定资产投资情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "社会事业面积数",
            "symbolSize": 2,
            "category": "区域固定资产投资情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "商业酒店写字楼面积数",
            "symbolSize": 2,
            "category": "区域固定资产投资情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "住宅公寓面积数",
            "symbolSize": 2,
            "category": "区域固定资产投资情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "招商引资情况",
            "symbolSize": 8,
            "category": "招商引资情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "直接利用外资同比增长",
            "symbolSize": 6,
            "category": "招商引资情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "直接利用外资到位额",
            "symbolSize": 4,
            "category": "招商引资情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "当期直接利用外资增长额",
            "symbolSize": 4,
            "category": "招商引资情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "国内招商引资同比增长",
            "symbolSize": 6,
            "category": "招商引资情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "国内招商引资到位额",
            "symbolSize": 4,
            "category": "招商引资情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "当期国内招商引资增长额",
            "symbolSize": 4,
            "category": "招商引资情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "工商登记注册情况",
            "symbolSize": 8,
            "category": "工商登记注册情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "实有经济主体数同比增长",
            "symbolSize": 6,
            "category": "工商登记注册情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "实有经济主体",
            "symbolSize": 4,
            "category": "工商登记注册情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "个体工商户注册数",
            "symbolSize": 2,
            "category": "工商登记注册情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "私营企业注册数",
            "symbolSize": 2,
            "category": "工商登记注册情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "内资企业注册数",
            "symbolSize": 2,
            "category": "工商登记注册情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "本年新增经济主体",
            "symbolSize": 4,
            "category": "工商登记注册情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "个体工商户新增数",
            "symbolSize": 2,
            "category": "工商登记注册情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "私营企业新增数",
            "symbolSize": 2,
            "category": "工商登记注册情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "内资企业新增数",
            "symbolSize": 2,
            "category": "工商登记注册情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "外资企业及分支机构注册数同比增长",
            "symbolSize": 6,
            "category": "工商登记注册情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "外资企业及分支机构注册数",
            "symbolSize": 4,
            "category": "工商登记注册情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "外资企业及分支机构新增数",
            "symbolSize": 4,
            "category": "工商登记注册情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "本年新增注册资金同比增长",
            "symbolSize": 6,
            "category": "工商登记注册情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "本年新增注册资金",
            "symbolSize": 4,
            "category": "工商登记注册情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "个体工商户新增注册资金",
            "symbolSize": 2,
            "category": "工商登记注册情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "私营企业新增注册资金",
            "symbolSize": 2,
            "category": "工商登记注册情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "内资企业新增注册资金",
            "symbolSize": 2,
            "category": "工商登记注册情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "增加就业情况",
            "symbolSize": 8,
            "category": "增加就业情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "增加就业人数同比增长",
            "symbolSize": 6,
            "category": "增加就业情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "增加就业人数",
            "symbolSize": 4,
            "category": "增加就业情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "城镇登记失业率",
            "symbolSize": 4,
            "category": "增加就业情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "企业职工基本养老保险缴费人数",
            "symbolSize": 4,
            "category": "增加就业情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "企业职工基本医疗保险缴费人数",
            "symbolSize": 4,
            "category": "增加就业情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "重点企业指标情况",
            "symbolSize": 8,
            "category": "重点企业指标情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "批发零售业前20名销售额同比增长",
            "symbolSize": 6,
            "category": "重点企业指标情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "批发零售业前20名企业销售额",
            "symbolSize": 4,
            "category": "重点企业指标情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "批发零售业前20名企业营业利润",
            "symbolSize": 4,
            "category": "重点企业指标情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "房地产业前10名企业增加值同比增长",
            "symbolSize": 6,
            "category": "重点企业指标情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "房地产业前10名企业增加值主体项之和",
            "symbolSize": 4,
            "category": "重点企业指标情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "房地产业后10名企业增加值主体项之和",
            "symbolSize": 4,
            "category": "重点企业指标情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "其他服务业增加值同比增长",
            "symbolSize": 6,
            "category": "重点企业指标情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "其他服务业前10名企业增加值主体项之和",
            "symbolSize": 4,
            "category": "重点企业指标情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "消费品零售情况",
            "symbolSize": 8,
            "category": "消费品零售情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "消费品零售额同比增长",
            "symbolSize": 6,
            "category": "消费品零售情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "消费品零售总额",
            "symbolSize": 4,
            "category": "消费品零售情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "外贸出口情况",
            "symbolSize": 8,
            "category": "外贸出口情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "外贸出口额同比增长",
            "symbolSize": 6,
            "category": "外贸出口情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "外贸出口总额",
            "symbolSize": 4,
            "category": "外贸出口情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "居民收入情况",
            "symbolSize": 8,
            "category": "居民收入情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "居民人均可支配收入同比增长",
            "symbolSize": 6,
            "category": "居民收入情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "居民人均可支配收入",
            "symbolSize": 4,
            "category": "居民收入情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "市内六区对比情况",
            "symbolSize": 8,
            "category": "市内六区对比情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "市内六区地域生产总值排名",
            "symbolSize": 6,
            "category": "市内六区对比情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "地域生产总值",
            "symbolSize": 4,
            "category": "市内六区对比情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "和平区季度生产总值",
            "symbolSize": 2,
            "category": "市内六区对比情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "南开区季度生产总值",
            "symbolSize": 2,
            "category": "市内六区对比情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "河西区季度生产总值",
            "symbolSize": 2,
            "category": "市内六区对比情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "河北区季度生产总值",
            "symbolSize": 2,
            "category": "市内六区对比情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "红桥区季度生产总值",
            "symbolSize": 2,
            "category": "市内六区对比情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "河东区季度生产总值",
            "symbolSize": 2,
            "category": "市内六区对比情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "友好城市对比情况",
            "symbolSize": 8,
            "category": "友好城市对比情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "友好城市生产总值排名",
            "symbolSize": 6,
            "category": "友好城市对比情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "友好城市生产总值",
            "symbolSize": 4,
            "category": "友好城市对比情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "天津市和平区季度生产总值",
            "symbolSize": 2,
            "category": "友好城市对比情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "北京市东城区季度生产总值",
            "symbolSize": 2,
            "category": "友好城市对比情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "北京市西城区季度生产总值",
            "symbolSize": 2,
            "category": "友好城市对比情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "深圳市罗湖区季度生产总值",
            "symbolSize": 2,
            "category": "友好城市对比情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "广州市越秀区季度生产总值",
            "symbolSize": 2,
            "category": "友好城市对比情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "杭州市下城区季度生产总值",
            "symbolSize": 2,
            "category": "友好城市对比情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "上海市徐汇区季度生产总值",
            "symbolSize": 2,
            "category": "友好城市对比情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "重庆市渝中区季度生产总值",
            "symbolSize": 2,
            "category": "友好城市对比情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "招商项目指标",
            "symbolSize": 10,
            "category": "类目",
            "draggable": "true",
            "value": 1
        }, {
            "name": "招商项目情况",
            "symbolSize": 8,
            "category": "招商项目情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "招商项目数量同比增长",
            "symbolSize": 6,
            "category": "招商项目情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "招商项目数量情况",
            "symbolSize": 4,
            "category": "招商项目情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "商务载体项目数",
            "symbolSize": 2,
            "category": "招商项目情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "商业载体项目数",
            "symbolSize": 2,
            "category": "招商项目情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "土地载体项目数",
            "symbolSize": 2,
            "category": "招商项目情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "风貌小洋楼项目数",
            "symbolSize": 2,
            "category": "招商项目情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "普通小洋楼项目数",
            "symbolSize": 2,
            "category": "招商项目情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "新建小洋楼项目数",
            "symbolSize": 2,
            "category": "招商项目情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "可招商面积同比增长",
            "symbolSize": 6,
            "category": "招商项目情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "招商项目面积情况",
            "symbolSize": 4,
            "category": "招商项目情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "商务载体可招商面积",
            "symbolSize": 2,
            "category": "招商项目情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "商业载体可招商面积",
            "symbolSize": 2,
            "category": "招商项目情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "土地载体可招商面积",
            "symbolSize": 2,
            "category": "招商项目情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "风貌小洋楼可招商面积",
            "symbolSize": 2,
            "category": "招商项目情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "普通小洋楼可招商面积",
            "symbolSize": 2,
            "category": "招商项目情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "新建小洋楼可招商面积",
            "symbolSize": 2,
            "category": "招商项目情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "楼宇经济指标",
            "symbolSize": 10,
            "category": "类目",
            "draggable": "true",
            "value": 1
        }, {
            "name": "楼宇情况",
            "symbolSize": 8,
            "category": "楼宇情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "统计楼宇数同比增长",
            "symbolSize": 6,
            "category": "楼宇情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "楼宇物业等级",
            "symbolSize": 4,
            "category": "楼宇情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "一级楼宇数",
            "symbolSize": 2,
            "category": "楼宇情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "二级楼宇数",
            "symbolSize": 2,
            "category": "楼宇情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "三级楼宇数",
            "symbolSize": 2,
            "category": "楼宇情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "其他楼宇数",
            "symbolSize": 2,
            "category": "楼宇情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "全口径税收金额同比增长",
            "symbolSize": 6,
            "category": "楼宇情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "全口径税收金额",
            "symbolSize": 4,
            "category": "楼宇情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "全口径税收类别",
            "symbolSize": 4,
            "category": "楼宇情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "亿元楼宇数",
            "symbolSize": 2,
            "category": "楼宇情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "大于5千万楼宇数",
            "symbolSize": 2,
            "category": "楼宇情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "大于3千万楼宇数",
            "symbolSize": 2,
            "category": "楼宇情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "大于1千万楼宇数",
            "symbolSize": 2,
            "category": "楼宇情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "小于1千万楼宇数",
            "symbolSize": 2,
            "category": "楼宇情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "亿元楼宇数同比增长",
            "symbolSize": 6,
            "category": "楼宇情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "亿元楼宇税收额同比增长",
            "symbolSize": 6,
            "category": "楼宇情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "注册企业情况",
            "symbolSize": 8,
            "category": "注册企业情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "注册企业数同比增长",
            "symbolSize": 6,
            "category": "注册企业情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "注册企业总数",
            "symbolSize": 4,
            "category": "注册企业情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "当期新增注册企业数",
            "symbolSize": 4,
            "category": "注册企业情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "亿元楼宇企业数",
            "symbolSize": 4,
            "category": "注册企业情况",
            "draggable": "true",
            "value": 1
        }, {
            "name": "互联网电商指标",
            "symbolSize": 10,
            "category": "类目",
            "draggable": "true",
            "value": 1
        }, {
            "name": "总体指标",
            "symbolSize": 8,
            "category": "总体指标",
            "draggable": "true",
            "value": 1
        }, {
            "name": "区域电商指数",
            "symbolSize": 6,
            "category": "总体指标",
            "draggable": "true",
            "value": 1
        }, {
            "name": "区域人口质量",
            "symbolSize": 6,
            "category": "总体指标",
            "draggable": "true",
            "value": 1
        }, {
            "name": "区域幸福指数",
            "symbolSize": 6,
            "category": "总体指标",
            "draggable": "true",
            "value": 1
        }, {
            "name": "网商指标",
            "symbolSize": 8,
            "category": "网商指标",
            "draggable": "true",
            "value": 1
        }, {
            "name": "网商指数",
            "symbolSize": 6,
            "category": "网商指标",
            "draggable": "true",
            "value": 1
        }, {
            "name": "店铺活跃度",
            "symbolSize": 6,
            "category": "网商指标",
            "draggable": "true",
            "value": 1
        }, {
            "name": "网商指数排名",
            "symbolSize": 6,
            "category": "网商指标",
            "draggable": "true",
            "value": 1
        }, {
            "name": "网购指标",
            "symbolSize": 8,
            "category": "网购指标",
            "draggable": "true",
            "value": 1
        }, {
            "name": "网购指数",
            "symbolSize": 6,
            "category": "网购指标",
            "draggable": "true",
            "value": 1
        }, {
            "name": "消费活跃度",
            "symbolSize": 6,
            "category": "网购指标",
            "draggable": "true",
            "value": 1
        }, {
            "name": "网购指数排名",
            "symbolSize": 6,
            "category": "网购指标",
            "draggable": "true",
            "value": 1
        }],
        links: [{
            "source": "区域经济主题",
            "target": "主要社会经济指标"
        }, {
            "source": "主要社会经济指标",
            "target": "地区生产总值情况"
        }, {
            "source": "地区生产总值情况",
            "target": "地区生产总值同比增长"
        }, {
            "source": "地区生产总值同比增长",
            "target": "地区生产总值"
        }, {
            "source": "地区生产总值同比增长",
            "target": "地区生产总值计划增长"
        }, {
            "source": "地区生产总值情况",
            "target": "第二产业同比增长"
        }, {
            "source": "第二产业同比增长",
            "target": "第二产业总值"
        }, {
            "source": "地区生产总值情况",
            "target": "第三产业同比增长"
        }, {
            "source": "第三产业同比增长",
            "target": "第三产业总值"
        }, {
            "source": "地区生产总值情况",
            "target": "现代服务业同比增长"
        }, {
            "source": "现代服务业同比增长",
            "target": "现代服务业增加值"
        }, {
            "source": "地区生产总值情况",
            "target": "民营经济同比增长"
        }, {
            "source": "民营经济同比增长",
            "target": "民营经济增加值"
        }, {
            "source": "主要社会经济指标",
            "target": "财政收入情况"
        }, {
            "source": "财政收入情况",
            "target": "财政收入同比增长"
        }, {
            "source": "财政收入同比增长",
            "target": "财政收入金额"
        }, {
            "source": "财政收入情况",
            "target": "留区一般预算财政收入同比增长"
        }, {
            "source": "留区一般预算财政收入同比增长",
            "target": "留区一般预算财政收入金额"
        }, {
            "source": "财政收入情况",
            "target": "区级财政支出金额同比增长"
        }, {
            "source": "区级财政支出金额同比增长",
            "target": "区级财政支出金额"
        }, {
            "source": "主要社会经济指标",
            "target": "税收情况"
        }, {
            "source": "税收情况",
            "target": "地税税收同比增长"
        }, {
            "source": "地税税收同比增长",
            "target": "地税主要税种完成税收情况"
        }, {
            "source": "地税主要税种完成税收情况",
            "target": "营业税"
        }, {
            "source": "地税主要税种完成税收情况",
            "target": "个人所得税"
        }, {
            "source": "地税主要税种完成税收情况",
            "target": "城建税（地税）"
        }, {
            "source": "地税主要税种完成税收情况",
            "target": "企业所得税（地税）"
        }, {
            "source": "地税主要税种完成税收情况",
            "target": "其他税(含费）"
        }, {
            "source": "税收情况",
            "target": "国税税收同比增长"
        }, {
            "source": "国税税收同比增长",
            "target": "国税分税种完成税收情况"
        }, {
            "source": "国税分税种完成税收情况",
            "target": "增值税"
        }, {
            "source": "国税分税种完成税收情况",
            "target": "消费税"
        }, {
            "source": "国税分税种完成税收情况",
            "target": "企业所得税(国税)"
        }, {
            "source": "国税分税种完成税收情况",
            "target": "城建税(国税)"
        }, {
            "source": "主要社会经济指标",
            "target": "区域固定资产投资情况"
        }, {
            "source": "域固定资产投资情况",
            "target": "区域固定资产投资同比增长"
        }, {
            "source": "区域固定资产投资同比增长",
            "target": "区域固定资产投资额"
        }, {
            "source": "域固定资产投资情况",
            "target": "开工项目同比增长"
        }, {
            "source": "开工项目同比增长",
            "target": "开工项目数"
        }, {
            "source": "开工项目数",
            "target": "社会事业项目数"
        }, {
            "source": "开工项目数",
            "target": "商业酒店写字楼项目数"
        }, {
            "source": "开工项目数",
            "target": "住宅公寓项目数"
        }, {
            "source": "域固定资产投资情况",
            "target": "开工面积同比增长"
        }, {
            "source": "开工面积同比增长",
            "target": "开工面积"
        }, {
            "source": "开工面积",
            "target": "社会事业面积数"
        }, {
            "source": "开工面积",
            "target": "商业酒店写字楼面积数"
        }, {
            "source": "开工面积",
            "target": "住宅公寓面积数"
        }, {
            "source": "主要社会经济指标",
            "target": "招商引资情况"
        }, {
            "source": "招商引资情况",
            "target": "直接利用外资同比增长"
        }, {
            "source": "直接利用外资同比增长",
            "target": "直接利用外资到位额"
        }, {
            "source": "直接利用外资同比增长",
            "target": "当期直接利用外资增长额"
        }, {
            "source": "招商引资情况",
            "target": "国内招商引资同比增长"
        }, {
            "source": "国内招商引资同比增长",
            "target": "国内招商引资到位额"
        }, {
            "source": "国内招商引资同比增长",
            "target": "当期国内招商引资增长额"
        }, {
            "source": "主要社会经济指标",
            "target": "工商登记注册情况"
        }, {
            "source": "工商登记注册情况",
            "target": "实有经济主体数同比增长"
        }, {
            "source": "实有经济主体数同比增长",
            "target": "实有经济主体"
        }, {
            "source": "实有经济主体",
            "target": "个体工商户注册数"
        }, {
            "source": "实有经济主体",
            "target": "私营企业注册数"
        }, {
            "source": "实有经济主体",
            "target": "内资企业注册数"
        }, {
            "source": "实有经济主体数同比增长",
            "target": "本年新增经济主体"
        }, {
            "source": "本年新增经济主体",
            "target": "个体工商户新增数"
        }, {
            "source": "本年新增经济主体",
            "target": "私营企业新增数"
        }, {
            "source": "本年新增经济主体",
            "target": "内资企业新增数"
        }, {
            "source": "工商登记注册情况",
            "target": "外资企业及分支机构注册数同比增长"
        }, {
            "source": "外资企业及分支机构注册数同比增长",
            "target": "外资企业及分支机构注册数"
        }, {
            "source": "外资企业及分支机构注册数同比增长",
            "target": "外资企业及分支机构新增数"
        }, {
            "source": "工商登记注册情况",
            "target": "本年新增注册资金同比增长"
        }, {
            "source": "本年新增注册资金同比增长",
            "target": "本年新增注册资金"
        }, {
            "source": "本年新增注册资金",
            "target": "个体工商户新增注册资金"
        }, {
            "source": "本年新增注册资金",
            "target": "私营企业新增注册资金"
        }, {
            "source": "本年新增注册资金",
            "target": "内资企业新增注册资金"
        }, {
            "source": "主要社会经济指标",
            "target": "增加就业情况"
        }, {
            "source": "增加就业情况",
            "target": "增加就业人数同比增长"
        }, {
            "source": "增加就业人数同比增长",
            "target": "增加就业人数"
        }, {
            "source": "增加就业人数同比增长",
            "target": "城镇登记失业率"
        }, {
            "source": "增加就业人数同比增长",
            "target": "企业职工基本养老保险缴费人数"
        }, {
            "source": "增加就业人数同比增长",
            "target": "企业职工基本医疗保险缴费人数"
        }, {
            "source": "主要社会经济指标",
            "target": "重点企业指标情况"
        }, {
            "source": "重点企业指标情况",
            "target": "批发零售业前20名销售额同比增长"
        }, {
            "source": "批发零售业前20名销售额同比增长",
            "target": "批发零售业前20名企业销售额"
        }, {
            "source": "批发零售业前20名销售额同比增长",
            "target": "批发零售业前20名企业营业利润"
        }, {
            "source": "重点企业指标情况",
            "target": "房地产业前10名企业增加值同比增长"
        }, {
            "source": "房地产业前10名企业增加值同比增长",
            "target": "房地产业前10名企业增加值主体项之和"
        }, {
            "source": "房地产业前10名企业增加值同比增长",
            "target": "房地产业后10名企业增加值主体项之和"
        }, {
            "source": "重点企业指标情况",
            "target": "其他服务业增加值同比增长"
        }, {
            "source": "其他服务业增加值同比增长",
            "target": "其他服务业前10名企业增加值主体项之和"
        }, {
            "source": "主要社会经济指标",
            "target": "消费品零售情况"
        }, {
            "source": "消费品零售情况",
            "target": "消费品零售额同比增长"
        }, {
            "source": "消费品零售额同比增长",
            "target": "消费品零售总额"
        }, {
            "source": "主要社会经济指标",
            "target": "外贸出口情况"
        }, {
            "source": "外贸出口情况",
            "target": "外贸出口额同比增长"
        }, {
            "source": "外贸出口额同比增长",
            "target": "外贸出口总额"
        }, {
            "source": "主要社会经济指标",
            "target": "居民收入情况"
        }, {
            "source": "居民收入情况",
            "target": "居民人均可支配收入同比增长"
        }, {
            "source": "居民人均可支配收入同比增长",
            "target": "居民人均可支配收入"
        }, {
            "source": "主要社会经济指标",
            "target": "市内六区对比情况"
        }, {
            "source": "市内六区对比情况",
            "target": "市内六区地域生产总值排名"
        }, {
            "source": "市内六区地域生产总值排名",
            "target": "地域生产总值"
        }, {
            "source": "地域生产总值",
            "target": "和平区季度生产总值"
        }, {
            "source": "地域生产总值",
            "target": "南开区季度生产总值"
        }, {
            "source": "地域生产总值",
            "target": "河西区季度生产总值"
        }, {
            "source": "地域生产总值",
            "target": "河北区季度生产总值"
        }, {
            "source": "地域生产总值",
            "target": "红桥区季度生产总值"
        }, {
            "source": "地域生产总值",
            "target": "河东区季度生产总值"
        }, {
            "source": "主要社会经济指标",
            "target": "友好城市对比情况"
        }, {
            "source": "友好城市对比情况",
            "target": "友好城市生产总值排名"
        }, {
            "source": "友好城市生产总值排名",
            "target": "友好城市生产总值"
        }, {
            "source": "友好城市生产总值",
            "target": "天津市和平区季度生产总值"
        }, {
            "source": "友好城市生产总值",
            "target": "北京市东城区季度生产总值"
        }, {
            "source": "友好城市生产总值",
            "target": "北京市西城区季度生产总值"
        }, {
            "source": "友好城市生产总值",
            "target": "深圳市罗湖区季度生产总值"
        }, {
            "source": "友好城市生产总值",
            "target": "广州市越秀区季度生产总值"
        }, {
            "source": "友好城市生产总值",
            "target": "杭州市下城区季度生产总值"
        }, {
            "source": "友好城市生产总值",
            "target": "上海市徐汇区季度生产总值"
        }, {
            "source": "友好城市生产总值",
            "target": "重庆市渝中区季度生产总值"
        }, {
            "source": "区域经济主题",
            "target": "招商项目指标"
        }, {
            "source": "招商项目指标",
            "target": "招商项目情况"
        }, {
            "source": "招商项目情况",
            "target": "招商项目数量同比增长"
        }, {
            "source": "招商项目数量同比增长",
            "target": "招商项目数量情况"
        }, {
            "source": "招商项目数量情况",
            "target": "商务载体项目数"
        }, {
            "source": "招商项目数量情况",
            "target": "商业载体项目数"
        }, {
            "source": "招商项目数量情况",
            "target": "土地载体项目数"
        }, {
            "source": "招商项目数量情况",
            "target": "风貌小洋楼项目数"
        }, {
            "source": "招商项目数量情况",
            "target": "普通小洋楼项目数"
        }, {
            "source": "招商项目数量情况",
            "target": "新建小洋楼项目数"
        }, {
            "source": "招商项目情况",
            "target": "可招商面积同比增长"
        }, {
            "source": "可招商面积同比增长",
            "target": "招商项目面积情况"
        }, {
            "source": "招商项目面积情况",
            "target": "商务载体可招商面积"
        }, {
            "source": "招商项目面积情况",
            "target": "商业载体可招商面积"
        }, {
            "source": "招商项目面积情况",
            "target": "土地载体可招商面积"
        }, {
            "source": "招商项目面积情况",
            "target": "风貌小洋楼可招商面积"
        }, {
            "source": "招商项目面积情况",
            "target": "普通小洋楼可招商面积"
        }, {
            "source": "招商项目面积情况",
            "target": "新建小洋楼可招商面积"
        }, {
            "source": "区域经济主题",
            "target": "楼宇经济指标"
        }, {
            "source": "楼宇经济指标",
            "target": "楼宇情况"
        }, {
            "source": "楼宇情况",
            "target": "统计楼宇数同比增长"
        }, {
            "source": "统计楼宇数同比增长",
            "target": "楼宇物业等级"
        }, {
            "source": "楼宇物业等级",
            "target": "一级楼宇数"
        }, {
            "source": "楼宇物业等级",
            "target": "二级楼宇数"
        }, {
            "source": "楼宇物业等级",
            "target": "三级楼宇数"
        }, {
            "source": "楼宇物业等级",
            "target": "其他楼宇数"
        }, {
            "source": "楼宇情况",
            "target": "全口径税收金额同比增长"
        }, {
            "source": "全口径税收金额同比增长",
            "target": "全口径税收金额"
        }, {
            "source": "全口径税收金额同比增长",
            "target": "全口径税收类别"
        }, {
            "source": "全口径税收类别",
            "target": "亿元楼宇数"
        }, {
            "source": "全口径税收类别",
            "target": "大于5千万楼宇数"
        }, {
            "source": "全口径税收类别",
            "target": "大于3千万楼宇数"
        }, {
            "source": "全口径税收类别",
            "target": "大于1千万楼宇数"
        }, {
            "source": "全口径税收类别",
            "target": "小于1千万楼宇数"
        }, {
            "source": "楼宇情况",
            "target": "亿元楼宇数同比增长"
        }, {
            "source": "楼宇情况",
            "target": "亿元楼宇税收额同比增长"
        }, {
            "source": "楼宇经济指标",
            "target": "注册企业情况"
        }, {
            "source": "注册企业情况",
            "target": "注册企业数同比增长"
        }, {
            "source": "注册企业数同比增长",
            "target": "注册企业总数"
        }, {
            "source": "注册企业数同比增长",
            "target": "当期新增注册企业数"
        }, {
            "source": "注册企业数同比增长",
            "target": "亿元楼宇企业数"
        }, {
            "source": "区域经济主题",
            "target": "互联网电商指标"
        }, {
            "source": "互联网电商指标",
            "target": "总体指标"
        }, {
            "source": "总体指标",
            "target": "区域电商指数"
        }, {
            "source": "总体指标",
            "target": "区域人口质量"
        }, {
            "source": "总体指标",
            "target": "区域幸福指数"
        }, {
            "source": "互联网电商指标",
            "target": "网商指标"
        }, {
            "source": "网商指标",
            "target": "网商指数"
        }, {
            "source": "网商指标",
            "target": "店铺活跃度"
        }, {
            "source": "网商指标",
            "target": "网商指数排名"
        }, {
            "source": "互联网电商指标",
            "target": "网购指标"
        }, {
            "source": "网购指标",
            "target": "网购指数"
        }, {
            "source": "网购指标",
            "target": "消费活跃度"
        }, {
            "source": "网购指标",
            "target": "网购指数排名"
        }],
        categories: [{
            "name": "地区生产总值情况"
        }, {
            "name": "财政收入情况"
        }, {
            "name": "税收情况"
        }, {
            "name": "区域固定资产投资情况"
        }, {
            "name": "招商引资情况"
        }, {
            "name": "工商登记注册情况"
        }, {
            "name": "增加就业情况"
        }, {
            "name": "重点企业指标情况"
        }, {
            "name": "消费品零售情况"
        }, {
            "name": "外贸出口情况"
        }, {
            "name": "居民收入情况"
        }, {
            "name": "市内六区对比情况"
        }, {
            "name": "友好城市对比情况"
        }, {
            "name": "招商项目情况"
        }, {
            "name": "类目"
        }, {
            "name": "楼宇情况"
        }, {
            "name": "注册企业情况"
        }, {
            "name": "总体指标"
        }, {
            "name": "网商指标"
        }, {
            "name": "网购指标"
        }],
        focusNodeAdjacency: true,
        roam: true,
        label: {
            normal: {

                show: true,
                position: 'top',
                textStyle: {
                    fontSize: 14
                }
            }
        },
        lineStyle: {
            normal: {
                color: 'source',
                curveness: 0
                //type: "solid"
            }
        }
    }]
};