var alldata = [{
        "name": "大兴安岭地区漠河县北极镇",
        "formatted_address": "黑龙江省大兴安岭地区漠河县北极村",
        "feature": "北极之光",
        "type": "旅游发展型",
        "lng": "122.359563",
        "lat": "53.481561",
        "area": "26.31",
        "gdp": "3.7"
    }, {
        "name": "成都市郫县德源镇",
        "formatted_address": "四川省成都市郫都区德源镇",
        "feature": "创客特色小镇",
        "type": "产业发展型",
        "lng": "103.848002",
        "lat": "30.770537",
        "area": "30.7",
        "gdp": "31.76"
    }, {
        "name": "阿勒泰地区富蕴县可可托海镇",
        "formatted_address": "新疆维吾尔自治区阿勒泰地区富蕴县可可托海镇",
        "feature": "稀有金属小镇",
        "type": "旅游发展型",
        "lng": "89.811189",
        "lat": "47.221611",
        "area": "32",
        "gdp": "0.58"
    }, {
        "name": "杨陵区五泉镇",
        "formatted_address": "陕西省咸阳市杨陵区五泉镇",
        "feature": "生态农科小镇",
        "type": "农业服务型",
        "lng": "108.004645",
        "lat": "34.299226",
        "area": "32.2",
        "gdp": "15"
    }, {
        "name": "南充市西充县多扶镇",
        "formatted_address": "四川省南充市西充县多扶镇",
        "feature": "西部绿谷",
        "type": "农业服务型",
        "lng": "105.974228",
        "lat": "30.963005",
        "area": "34.9",
        "gdp": "101"
    }, {
        "name": "房山区长沟镇",
        "formatted_address": "北京市房山区长沟镇",
        "feature": "基金小镇",
        "type": "商贸流通型",
        "lng": "115.900836",
        "lat": "39.580128",
        "area": "39.05",
        "gdp": "18"
    }, {
        "name": "泰州市姜堰区溱潼镇",
        "formatted_address": "江苏省泰州市姜堰区溱潼镇",
        "feature": "湿地古镇",
        "type": "历史文化型",
        "lng": "120.083139",
        "lat": "32.64218",
        "area": "40",
        "gdp": "18"
    }, {
        "name": "娄底市双峰县荷叶镇",
        "formatted_address": "湖南省娄底市双峰县荷叶镇",
        "feature": "国藩故里",
        "type": "旅游发展型",
        "lng": "112.44062",
        "lat": "27.408763",
        "area": "40.89",
        "gdp": "8.03"
    }, {
        "name": "泰安市新泰市西张庄镇",
        "formatted_address": "山东省泰安市新泰市西张庄镇",
        "feature": "多彩毛呢小镇",
        "type": "产业发展型",
        "lng": "117.596615",
        "lat": "35.956387",
        "area": "47",
        "gdp": "51.6"
    }, {
        "name": "中山市古镇镇",
        "formatted_address": "广东省中山市古镇镇",
        "feature": "灯饰特色小镇",
        "type": "产业发展型",
        "lng": "113.190869",
        "lat": "22.613406",
        "area": "47.8",
        "gdp": "111.8"
    }, {
        "name": "威海市经济技术开发区崮山镇",
        "formatted_address": "山东省威海市环翠区崮山镇",
        "feature": "日光幸福小镇",
        "type": "产业发展型",
        "lng": "122.245202",
        "lat": "37.407039",
        "area": "49",
        "gdp": "35.6"
    }, {
        "name": "许昌市禹州市神垕镇",
        "formatted_address": "河南省许昌市禹州市神垕镇",
        "feature": "钧瓷之都",
        "type": "产业发展型",
        "lng": "113.229875",
        "lat": "34.122346",
        "area": "49.1",
        "gdp": "25.4"
    }, {
        "name": "松江区车墩镇",
        "formatted_address": "上海市松江区车墩镇",
        "feature": "影视特色小镇",
        "type": "旅游发展型",
        "lng": "121.315067",
        "lat": "31.014986",
        "area": "50.4",
        "gdp": "65.8"
    }, {
        "name": "衡水市武强县周窝镇",
        "formatted_address": "河北省衡水市武强县周窝镇",
        "feature": "音乐小镇",
        "type": "产业发展型",
        "lng": "115.891818",
        "lat": "37.997813",
        "area": "51.3",
        "gdp": "3.5"
    }, {
        "name": "绍兴市诸暨市大唐镇",
        "formatted_address": "浙江省绍兴市诸暨市大唐镇",
        "feature": "袜艺小镇",
        "type": "产业发展型",
        "lng": "120.167553",
        "lat": "29.693705",
        "area": "53.8",
        "gdp": "77.59"
    }, {
        "name": "南昌市进贤县文港镇",
        "formatted_address": "江西省南昌市进贤县文港镇",
        "feature": "毛笔之乡",
        "type": "产业发展型",
        "lng": "116.127227",
        "lat": "28.290004",
        "area": "54.53",
        "gdp": "34.06"
    }, {
        "name": "焦作市温县赵堡镇",
        "formatted_address": "河南省焦作市温县赵堡镇",
        "feature": "太极圣地",
        "type": "农业服务型",
        "lng": "113.168431",
        "lat": "34.96418",
        "area": "55",
        "gdp": "19.4"
    }, {
        "name": "成都市大邑县安仁镇",
        "formatted_address": "四川省成都市大邑县安仁镇",
        "feature": "博物馆小镇",
        "type": "历史文化型",
        "lng": "103.616057",
        "lat": "30.514155",
        "area": "56.9",
        "gdp": "16.9"
    }, {
        "name": "江门市开平市赤坎镇",
        "formatted_address": "广东省江门市开平市赤坎镇",
        "feature": "侨乡小镇",
        "type": "历史文化型",
        "lng": "112.578178",
        "lat": "22.326471",
        "area": "62.1",
        "gdp": "25.4"
    }, {
        "name": "嘉兴市桐乡市濮院镇",
        "formatted_address": "浙江省嘉兴市桐乡市濮院镇",
        "feature": "毛衫时尚小镇",
        "type": "产业发展型",
        "lng": "120.618585",
        "lat": "30.67705",
        "area": "64",
        "gdp": "77.3"
    }, {
        "name": "临夏州和政县松鸣镇",
        "formatted_address": "甘肃省临夏回族自治州和政县松鸣镇",
        "feature": "度假雪国",
        "type": "旅游发展型",
        "lng": "103.39764",
        "lat": "35.350449",
        "area": "67",
        "gdp": "1.13"
    }, {
        "name": "昌平区小汤山镇",
        "formatted_address": "北京市昌平区小汤山镇",
        "feature": "汤泉古镇",
        "type": "农业服务型",
        "lng": "116.399758",
        "lat": "40.177806",
        "area": "70.1",
        "gdp": "暂无"
    }, {
        "name": "铜陵市郊区大通镇",
        "formatted_address": "安徽省铜陵市郊区大通镇",
        "feature": "江豚小镇",
        "type": "历史文化型",
        "lng": "117.749852",
        "lat": "30.811726",
        "area": "70.72",
        "gdp": "27.2"
    }, {
        "name": "盐城市东台市安丰镇",
        "formatted_address": "江苏省盐城市东台市安丰镇",
        "feature": "智造小镇",
        "type": "产业发展型",
        "lng": "120.40199",
        "lat": "32.735416",
        "area": "71.2",
        "gdp": "37.24"
    }, {
        "name": "宜宾市翠屏区李庄镇",
        "formatted_address": "四川省宜宾市翠屏区李庄镇",
        "feature": "文化抗战名镇",
        "type": "历史文化型",
        "lng": "104.80233",
        "lat": "28.805453",
        "area": "71.52",
        "gdp": "4.6"
    }, {
        "name": "晋城市阳城县润城镇",
        "formatted_address": "山西省晋城市阳城县润城镇",
        "feature": "古堡重镇",
        "type": "历史文化型",
        "lng": "112.527819",
        "lat": "35.493407",
        "area": "72",
        "gdp": "3.2"
    }, {
        "name": "青岛市胶州市李哥庄镇",
        "formatted_address": "山东省青岛市胶州市李哥庄镇",
        "feature": "空港小镇",
        "type": "商贸流通型",
        "lng": "120.158977",
        "lat": "36.352812",
        "area": "75",
        "gdp": "138"
    }, {
        "name": "北海市铁山港区南康镇",
        "formatted_address": "广西壮族自治区北海市铁山港区南康镇",
        "feature": "北海银滩小镇",
        "type": "商贸流通型",
        "lng": "109.44932",
        "lat": "21.588904",
        "area": "75.4",
        "gdp": "52.3"
    }, {
        "name": "湘西土家族苗族自治州花垣县边城镇",
        "formatted_address": "湖南省湘西土家族苗族自治州花垣县边城镇",
        "feature": "书里的小镇",
        "type": "历史文化型",
        "lng": "109.28448",
        "lat": "28.501756",
        "area": "76.95",
        "gdp": "1.63"
    }, {
        "name": "邢台市隆尧县莲子镇镇",
        "formatted_address": "河北省邢台市隆尧县莲子镇镇",
        "feature": "方便面小镇",
        "type": "产业发展型",
        "lng": "114.857429",
        "lat": "37.292268",
        "area": "78",
        "gdp": "41"
    }, {
        "name": "万州区武陵镇",
        "formatted_address": "重庆市万州区武陵镇",
        "feature": "三峡移民小镇",
        "type": "农业服务型",
        "lng": "108.25307",
        "lat": "30.504589",
        "area": "80.7",
        "gdp": "9.53"
    }, {
        "name": "密云区古北口镇",
        "formatted_address": "北京市密云区古北口镇",
        "feature": "京北水镇",
        "type": "历史文化型",
        "lng": "117.16382",
        "lat": "40.692169",
        "area": "85.52",
        "gdp": "6.2"
    }, {
        "name": "吕梁市汾阳市杏花村镇",
        "formatted_address": "山西省吕梁市汾阳市杏花村镇",
        "feature": "酒都小镇",
        "type": "产业发展型",
        "lng": "111.90985",
        "lat": "37.334705",
        "area": "86",
        "gdp": "151"
    }, {
        "name": "安庆市岳西县温泉镇",
        "formatted_address": "安徽省安庆市岳西县温泉镇",
        "feature": "养生温泉乡",
        "type": "旅游发展型",
        "lng": "116.342605",
        "lat": "30.892725",
        "area": "86",
        "gdp": "9.76"
    }, {
        "name": "鹰潭市龙虎山风景名胜区上清镇",
        "formatted_address": "江西省鹰潭市贵溪市上清镇",
        "feature": "中国道教第一古镇",
        "type": "旅游发展型",
        "lng": "117.043407",
        "lat": "28.043337",
        "area": "86",
        "gdp": "2.2195"
    }, {
        "name": "琼海市潭门镇",
        "formatted_address": "海南省琼海市潭门镇",
        "feature": "传统工艺小镇",
        "type": "产业发展型",
        "lng": "110.61694",
        "lat": "19.24169",
        "area": "89.5",
        "gdp": "38.26"
    }, {
        "name": "秦皇岛市卢龙县石门镇",
        "formatted_address": "河北省秦皇岛市卢龙县石门镇",
        "feature": "新型工业小镇",
        "type": "产业发展型",
        "lng": "118.851149",
        "lat": "39.730368",
        "area": "90.3",
        "gdp": "2"
    }, {
        "name": "武清区崔黄口镇",
        "formatted_address": "天津市武清区崔黄口镇",
        "feature": "电子商务小镇",
        "type": "商贸流通型",
        "lng": "117.197903",
        "lat": "39.533815",
        "area": "90.51",
        "gdp": "38"
    }, {
        "name": "金山区枫泾镇",
        "formatted_address": "上海市金山区枫泾镇",
        "feature": "科创小镇",
        "type": "历史文化型",
        "lng": "121.010356",
        "lat": "30.888329",
        "area": "91.7",
        "gdp": "63"
    }, {
        "name": "佛山市顺德区北滘镇",
        "formatted_address": "广东省佛山市顺德区北滘镇",
        "feature": "岭南制造小镇",
        "type": "产业发展型",
        "lng": "113.207187",
        "lat": "22.928305",
        "area": "92",
        "gdp": "493"
    }, {
        "name": "温州市乐清市柳市镇",
        "formatted_address": "浙江省温州市乐清市柳市镇",
        "feature": "中国电器之都",
        "type": "产业发展型",
        "lng": "120.892196",
        "lat": "28.038249",
        "area": "92.3",
        "gdp": "220"
    }, {
        "name": "贵阳市花溪区青岩镇",
        "formatted_address": "贵州省贵阳市花溪区青岩镇",
        "feature": "中华诗词之乡",
        "type": "民族聚居型",
        "lng": "106.691177",
        "lat": "26.33405",
        "area": "92.3",
        "gdp": "16.75"
    }, {
        "name": "丽水市莲都区大港头镇",
        "formatted_address": "浙江省丽水市莲都区大港头镇",
        "feature": "古堰画乡",
        "type": "旅游发展型",
        "lng": "119.741956",
        "lat": "28.295804",
        "area": "94.22",
        "gdp": "5.4"
    }, {
        "name": "宣城市旌德县白地镇",
        "formatted_address": "安徽省宣城市旌德县白地镇",
        "feature": "宣砚小镇",
        "type": "产业发展型",
        "lng": "118.37666",
        "lat": "30.201715",
        "area": "95.8",
        "gdp": "1"
    }, {
        "name": "苏州市吴江区震泽镇",
        "formatted_address": "江苏省苏州市吴江区震泽镇",
        "feature": "丝绸小镇",
        "type": "历史文化型",
        "lng": "120.509538",
        "lat": "30.912356",
        "area": "96",
        "gdp": "112.6"
    }, {
        "name": "海口市云龙镇",
        "formatted_address": "海南省海口市琼山区云龙镇",
        "feature": "工贸服务小镇",
        "type": "产业发展型",
        "lng": "110.473184",
        "lat": "19.871734",
        "area": "96",
        "gdp": "38.1"
    }, {
        "name": "滨海新区中塘镇",
        "formatted_address": "天津市滨海新区中塘镇",
        "feature": "汽车橡塑小镇",
        "type": "产业发展型",
        "lng": "117.38538",
        "lat": "38.866464",
        "area": "97",
        "gdp": "61.92"
    }, {
        "name": "邵阳市邵东县廉桥镇",
        "formatted_address": "湖南省邵阳市邵东县廉桥镇",
        "feature": "南国药都",
        "type": "农业服务型",
        "lng": "111.848971",
        "lat": "27.323549",
        "area": "98",
        "gdp": "36.2"
    }, {
        "name": "淄博市淄川区昆仑镇",
        "formatted_address": "山东省淄博市淄川区昆仑镇",
        "feature": "陶瓷风情小镇",
        "type": "产业发展型",
        "lng": "117.919034",
        "lat": "36.588962",
        "area": "99.8",
        "gdp": "72.19"
    }, {
        "name": "海东市化隆回族自治县群科镇",
        "formatted_address": "青海省海东市化隆回族自治县群科镇",
        "feature": "拉面风情小镇",
        "type": "旅游发展型",
        "lng": "101.973806",
        "lat": "36.042122",
        "area": "100.12",
        "gdp": "暂无"
    }, {
        "name": "泉州市安溪县湖头镇",
        "formatted_address": "福建省泉州市安溪县湖头镇",
        "feature": "光电小镇",
        "type": "产业发展型",
        "lng": "118.035349",
        "lat": "25.232677",
        "area": "101.2",
        "gdp": "148.5"
    }, {
        "name": "烟台市蓬莱市刘家沟镇",
        "formatted_address": "山东省烟台市蓬莱市刘家沟镇",
        "feature": "葡萄酒风情小镇",
        "type": "产业发展型",
        "lng": "120.901533",
        "lat": "37.772722",
        "area": "101.7",
        "gdp": "141.6"
    }, {
        "name": "德宏州瑞丽市畹町镇",
        "formatted_address": "云南省德宏傣族景颇族自治州瑞丽市畹町镇",
        "feature": "边境口岸贸易镇",
        "type": "商贸流通型",
        "lng": "98.064638",
        "lat": "24.078662",
        "area": "103",
        "gdp": "3"
    }, {
        "name": "黔江区濯水镇",
        "formatted_address": "重庆市黔江区濯水镇",
        "feature": "土家小镇",
        "type": "民族聚居型",
        "lng": "108.7734",
        "lat": "29.297891",
        "area": "105",
        "gdp": "4.15"
    }, {
        "name": "保定市高阳县庞口镇",
        "formatted_address": "河北省保定市高阳县庞口镇",
        "feature": "农机商贸小镇",
        "type": "产业发展型",
        "lng": "115.949606",
        "lat": "38.646272",
        "area": "110",
        "gdp": "23"
    }, {
        "name": "安顺市西秀区旧州镇",
        "formatted_address": "贵州省安顺市西秀区旧州镇",
        "feature": "屯堡小镇",
        "type": "旅游发展型",
        "lng": "106.14248",
        "lat": "26.25021",
        "area": "116",
        "gdp": "30"
    }, {
        "name": "潼南区双江镇",
        "formatted_address": "重庆市潼南区双江镇",
        "feature": "双江古镇",
        "type": "历史文化型",
        "lng": "105.74706",
        "lat": "30.216376",
        "area": "119.4",
        "gdp": "9.71"
    }, {
        "name": "苏州市吴中区甪直镇",
        "formatted_address": "江苏省苏州市吴中区甪直镇",
        "feature": "神州水乡第一镇",
        "type": "历史文化型",
        "lng": "120.863057",
        "lat": "31.267106",
        "area": "120",
        "gdp": "100.9"
    }, {
        "name": "徐州市邳州市碾庄镇",
        "formatted_address": "江苏省徐州市邳州市碾庄镇",
        "feature": "五金之乡",
        "type": "产业发展型",
        "lng": "117.778735",
        "lat": "34.297013",
        "area": "121",
        "gdp": "70.7"
    }, {
        "name": "金华市东阳市横店镇",
        "formatted_address": "浙江省金华市东阳市横店镇",
        "feature": "东方好莱坞",
        "type": "旅游发展型",
        "lng": "120.287396",
        "lat": "29.156073",
        "area": "121",
        "gdp": "138"
    }, {
        "name": "肇庆市高要区回龙镇",
        "formatted_address": "广东省肇庆市高要区回龙镇",
        "feature": "广府文化特色小镇",
        "type": "历史文化型",
        "lng": "112.634842",
        "lat": "22.932913",
        "area": "124.25",
        "gdp": "33"
    }, {
        "name": "泸州市纳溪区大渡口镇",
        "formatted_address": "四川省泸州市纳溪区大渡口镇",
        "feature": "泸州酒镇",
        "type": "产业发展型",
        "lng": "105.229785",
        "lat": "28.74236",
        "area": "129.6",
        "gdp": "24.94"
    }, {
        "name": "青浦区朱家角镇",
        "formatted_address": "上海市青浦区朱家角镇",
        "feature": "水乡古镇",
        "type": "历史文化型",
        "lng": "121.046555",
        "lat": "31.103775",
        "area": "138",
        "gdp": "71.7"
    }, {
        "name": "兰州市榆中县青城镇",
        "formatted_address": "甘肃省兰州市榆中县青城镇",
        "feature": "黄河千年古镇",
        "type": "历史文化型",
        "lng": "104.188676",
        "lat": "36.327427",
        "area": "138",
        "gdp": "52"
    }, {
        "name": "郴州市汝城县热水镇",
        "formatted_address": "湖南省郴州市汝城县热水镇",
        "feature": "中国第一氡泉镇",
        "type": "旅游发展型",
        "lng": "113.9134",
        "lat": "25.527637",
        "area": "138.74",
        "gdp": "2.39"
    }, {
        "name": "达州市宣汉县南坝镇",
        "formatted_address": "四川省达州市宣汉县南坝镇",
        "feature": "川东商贸名镇",
        "type": "商贸流通型",
        "lng": "108.011328",
        "lat": "31.359953",
        "area": "143.5",
        "gdp": "15.3"
    }, {
        "name": "红河州建水县西庄镇",
        "formatted_address": "云南省红河哈尼族彝族自治州建水县西庄镇",
        "feature": "彝族小镇",
        "type": "民族聚居型",
        "lng": "102.766747",
        "lat": "23.645298",
        "area": "144.5",
        "gdp": "7.1"
    }, {
        "name": "南京市高淳区桠溪镇",
        "formatted_address": "江苏省南京市高淳区桠溪镇",
        "feature": "国际第一慢城",
        "type": "旅游发展型",
        "lng": "119.167292",
        "lat": "31.368979",
        "area": "149.2",
        "gdp": "397.6"
    }, {
        "name": "长沙市浏阳市大瑶镇",
        "formatted_address": "湖南省长沙市浏阳市大瑶镇",
        "feature": "烟花小镇",
        "type": "产业发展型",
        "lng": "113.723392",
        "lat": "27.97486",
        "area": "149.3",
        "gdp": "98.5"
    }, {
        "name": "辽阳市弓长岭区汤河镇",
        "formatted_address": "辽宁省辽阳市弓长岭区汤河镇",
        "feature": "温泉旅游小镇",
        "type": "旅游发展型",
        "lng": "123.376518",
        "lat": "41.126872",
        "area": "152.7",
        "gdp": "11.53"
    }, {
        "name": "厦门市同安区汀溪镇",
        "formatted_address": "福建省厦门市同安区汀溪镇",
        "feature": "乐活小镇",
        "type": "旅游发展型",
        "lng": "118.138296",
        "lat": "24.77754",
        "area": "155.85",
        "gdp": "0.98"
    }, {
        "name": "攀枝花市盐边县红格镇",
        "formatted_address": "四川省攀枝花市盐边县红格镇",
        "feature": "康养健身小镇",
        "type": "旅游发展型",
        "lng": "101.929682",
        "lat": "26.530449",
        "area": "160",
        "gdp": "10"
    }, {
        "name": "丽水市龙泉市上垟镇",
        "formatted_address": "浙江省丽水市龙泉市上垟镇",
        "feature": "中国青瓷小镇",
        "type": "产业发展型",
        "lng": "118.873299",
        "lat": "27.965968",
        "area": "162",
        "gdp": "6.52"
    }, {
        "name": "涪陵区蔺市镇",
        "formatted_address": "重庆市涪陵区蔺市镇",
        "feature": "涪陵千年古镇",
        "type": "农业服务型",
        "lng": "107.199496",
        "lat": "29.660829",
        "area": "163",
        "gdp": "17"
    }, {
        "name": "临沂市费县探沂镇",
        "formatted_address": "山东省临沂市费县探沂镇",
        "feature": "板材木业小镇",
        "type": "产业发展型",
        "lng": "118.134619",
        "lat": "35.202726",
        "area": "168",
        "gdp": "72.8"
    }, {
        "name": "武威市凉州区清源镇",
        "formatted_address": "甘肃省武威市凉州区清源镇",
        "feature": "中国波尔多",
        "type": "农业服务型",
        "lng": "102.847219",
        "lat": "37.881755",
        "area": "168.8",
        "gdp": "5.35"
    }, {
        "name": "宜春市明月山温泉风景名胜区温汤镇",
        "formatted_address": "江西省宜春市袁州区温汤镇",
        "feature": "天然氧吧",
        "type": "旅游发展型",
        "lng": "114.291688",
        "lat": "27.68399",
        "area": "171.6",
        "gdp": "9"
    }, {
        "name": "盘锦市大洼区赵圈河镇",
        "formatted_address": "辽宁省盘锦市大洼区赵圈河镇",
        "feature": "红海滩•生态旅游小镇",
        "type": "旅游发展型",
        "lng": "121.987833",
        "lat": "40.972106",
        "area": "172",
        "gdp": "13.6"
    }, {
        "name": "西安市蓝田县汤峪镇",
        "formatted_address": "陕西省西安市蓝田县汤峪镇",
        "feature": "温泉小镇",
        "type": "旅游发展型",
        "lng": "109.217823",
        "lat": "34.019342",
        "area": "173",
        "gdp": "15"
    }, {
        "name": "银川市西夏区镇北堡镇",
        "formatted_address": "宁夏回族自治区银川市西夏区镇北堡镇",
        "feature": "西夏风情小镇",
        "type": "旅游发展型",
        "lng": "106.066876",
        "lat": "38.627542",
        "area": "174",
        "gdp": "10"
    }, {
        "name": "固原市泾源县泾河源镇",
        "formatted_address": "宁夏回族自治区固原市泾源县泾河源镇",
        "feature": "避暑风情小镇",
        "type": "旅游发展型",
        "lng": "106.40365",
        "lat": "35.418149",
        "area": "176",
        "gdp": "24"
    }, {
        "name": "驻马店市确山县竹沟镇",
        "formatted_address": "河南省驻马店市确山县竹沟镇",
        "feature": "红色圣地",
        "type": "旅游发展型",
        "lng": "113.729908",
        "lat": "32.786374",
        "area": "185",
        "gdp": "8.22"
    }, {
        "name": "湖州市德清县莫干山镇",
        "formatted_address": "浙江省湖州市德清县莫干山镇",
        "feature": "民国风情小镇",
        "type": "旅游发展型",
        "lng": "119.901161",
        "lat": "30.599482",
        "area": "185.8",
        "gdp": "10.56"
    }, {
        "name": "晋中市昔阳县大寨镇",
        "formatted_address": "山西省晋中市昔阳县大寨镇",
        "feature": "红色小镇",
        "type": "旅游发展型",
        "lng": "113.719424",
        "lat": "37.571261",
        "area": "186",
        "gdp": "12"
    }, {
        "name": "大理州大理市喜洲镇",
        "formatted_address": "云南省大理白族自治州大理市喜洲镇",
        "feature": "白族第一镇",
        "type": "民族聚居型",
        "lng": "100.130699",
        "lat": "25.850338",
        "area": "186.5",
        "gdp": "41"
    }, {
        "name": "梅州市梅县区雁洋镇",
        "formatted_address": "广东省梅州市梅县区雁洋镇",
        "feature": "客家文化旅游小镇",
        "type": "历史文化型",
        "lng": "116.331916",
        "lat": "24.413897",
        "area": "188",
        "gdp": "48"
    }, {
        "name": "黔东南州雷山县西江镇",
        "formatted_address": "贵州省黔东南苗族侗族自治州雷山县西江镇",
        "feature": "苗寨风情小镇",
        "type": "民族聚居型",
        "lng": "108.17324",
        "lat": "26.49366",
        "area": "188",
        "gdp": "6.7"
    }, {
        "name": "黄山市黟县宏村镇",
        "formatted_address": "安徽省黄山市黟县宏村镇",
        "feature": "中国画里乡村",
        "type": "历史文化型",
        "lng": "117.983362",
        "lat": "29.998748",
        "area": "188.95",
        "gdp": "7.36"
    }, {
        "name": "六安市裕安区独山镇",
        "formatted_address": "安徽省六安市裕安区独山镇",
        "feature": "六安茶谷",
        "type": "农业服务型",
        "lng": "116.23186",
        "lat": "31.607619",
        "area": "189",
        "gdp": "9.6"
    }, {
        "name": "遵义市仁怀市茅台镇",
        "formatted_address": "贵州省遵义市仁怀市茅台镇",
        "feature": "国酒之心",
        "type": "产业发展型",
        "lng": "106.375723",
        "lat": "27.85194",
        "area": "189.25",
        "gdp": "403"
    }, {
        "name": "大连市瓦房店市谢屯镇",
        "formatted_address": "辽宁省大连市瓦房店市谢屯镇",
        "feature": "休闲养老小镇",
        "type": "旅游发展型",
        "lng": "121.540749",
        "lat": "39.452633",
        "area": "192.5",
        "gdp": "67.5"
    }, {
        "name": "南平市邵武市和平镇",
        "formatted_address": "福建省南平市邵武市和平镇",
        "feature": "太极文化小镇",
        "type": "历史文化型",
        "lng": "117.30254",
        "lat": "27.158461",
        "area": "193",
        "gdp": "暂无"
    }, {
        "name": "无锡市宜兴市丁蜀镇",
        "formatted_address": "江苏省无锡市宜兴市丁蜀镇",
        "feature": "陶都明珠",
        "type": "产业发展型",
        "lng": "119.841473",
        "lat": "31.26926",
        "area": "205",
        "gdp": "109"
    }, {
        "name": "六盘水市六枝特区郎岱镇",
        "formatted_address": "贵州省六盘水市六枝特区郎岱镇",
        "feature": "农旅小镇",
        "type": "农业服务型",
        "lng": "105.348767",
        "lat": "26.085924",
        "area": "206.42",
        "gdp": "2.1315"
    }, {
        "name": "汉中市宁强县青木川镇",
        "formatted_address": "陕西省汉中市宁强县青木川镇",
        "feature": "传奇古镇",
        "type": "历史文化型",
        "lng": "105.571372",
        "lat": "32.828692",
        "area": "208",
        "gdp": "6"
    }, {
        "name": "丹东市东港市孤山镇",
        "formatted_address": "辽宁省丹东市东港市孤山镇",
        "feature": "文化旅游小镇",
        "type": "旅游发展型",
        "lng": "123.574103",
        "lat": "39.88217",
        "area": "214",
        "gdp": "42.3"
    }, {
        "name": "龙岩市上杭县古田镇",
        "formatted_address": "福建省龙岩市上杭县古田镇",
        "feature": "红色圣地",
        "type": "历史文化型",
        "lng": "116.823773",
        "lat": "25.223654",
        "area": "227",
        "gdp": "38.1"
    }, {
        "name": "随州市随县长岗镇",
        "formatted_address": "湖北省随州市随县长岗镇",
        "feature": "养生天堂",
        "type": "旅游发展型",
        "lng": "112.979916",
        "lat": "31.550993",
        "area": "232.5",
        "gdp": "6.2"
    }, {
        "name": "铜川市耀州区照金镇",
        "formatted_address": "陕西省铜川市耀州区照金镇",
        "feature": "红色旅游小镇",
        "type": "旅游发展型",
        "lng": "108.638371",
        "lat": "35.057569",
        "area": "244",
        "gdp": "30"
    }, {
        "name": "延边朝鲜族自治州龙井市东盛涌镇",
        "formatted_address": "吉林省延边朝鲜族自治州龙井市东盛涌镇",
        "feature": "朝鲜族风情小镇",
        "type": "民族聚居型",
        "lng": "129.505471",
        "lat": "42.811429",
        "area": "254.33",
        "gdp": "7"
    }, {
        "name": "宜昌市夷陵区龙泉镇",
        "formatted_address": "湖北省宜昌市夷陵区龙泉镇",
        "feature": "白酒小镇",
        "type": "产业发展型",
        "lng": "111.494946",
        "lat": "30.725884",
        "area": "257",
        "gdp": "489"
    }, {
        "name": "福州市永泰县嵩口镇",
        "formatted_address": "福建省福州市永泰县嵩口镇",
        "feature": "文创旅游小镇",
        "type": "历史文化型",
        "lng": "118.58997",
        "lat": "25.79992",
        "area": "257.6",
        "gdp": "130.9"
    }, {
        "name": "齐齐哈尔市甘南县兴十四镇",
        "formatted_address": "黑龙江省齐齐哈尔市甘南县",
        "feature": "黑土明珠",
        "type": "农业服务型",
        "lng": "123.7008253",
        "lat": "47.86860204",
        "area": "260",
        "gdp": "20.4"
    }, {
        "name": "宝鸡市眉县汤峪镇",
        "formatted_address": "陕西省宝鸡市眉县汤峪镇",
        "feature": "中国最美温泉小镇",
        "type": "旅游发展型",
        "lng": "107.87823",
        "lat": "34.14847",
        "area": "264",
        "gdp": "10.84"
    }, {
        "name": "河源市江东新区古竹镇",
        "formatted_address": "广东省河源市紫金县古竹镇",
        "feature": "南越风情小镇",
        "type": "历史文化型",
        "lng": "114.70736",
        "lat": "23.518915",
        "area": "278.1",
        "gdp": "31.1"
    }, {
        "name": "喀什地区巴楚县色力布亚镇",
        "formatted_address": "新疆维吾尔自治区喀什地区巴楚县色力布亚镇",
        "feature": "南疆巴扎",
        "type": "旅游发展型",
        "lng": "77.823975",
        "lat": "39.302799",
        "area": "280",
        "gdp": "5"
    }, {
        "name": "杭州市桐庐县分水镇",
        "formatted_address": "浙江省杭州市桐庐县分水镇",
        "feature": "制笔小镇",
        "type": "产业发展型",
        "lng": "119.445721",
        "lat": "29.927669",
        "area": "299",
        "gdp": "32.54"
    }, {
        "name": "南阳市西峡县太平镇",
        "formatted_address": "河南省南阳市西峡县太平镇",
        "feature": "天然中药库",
        "type": "农业服务型",
        "lng": "111.735196",
        "lat": "33.618353",
        "area": "304",
        "gdp": "3.87"
    }, {
        "name": "拉萨市尼木县吞巴乡",
        "formatted_address": "西藏自治区拉萨市尼木县吞巴乡",
        "feature": "藏香之都",
        "type": "农业服务型",
        "lng": "90.288611",
        "lat": "29.333365",
        "area": "311",
        "gdp": "0.59"
    }, {
        "name": "上饶市婺源县江湾镇",
        "formatted_address": "江西省上饶市婺源县江湾镇",
        "feature": "画里婺源",
        "type": "旅游发展型",
        "lng": "118.055224",
        "lat": "29.370409",
        "area": "316",
        "gdp": "4.6"
    }, {
        "name": "通化市辉南县金川镇",
        "formatted_address": "吉林省通化市辉南县金川镇",
        "feature": "长白山小镇",
        "type": "旅游发展型",
        "lng": "126.395225",
        "lat": "42.349857",
        "area": "317.5",
        "gdp": "11"
    }, {
        "name": "桂林市恭城瑶族自治县莲花镇",
        "formatted_address": "广西壮族自治区桂林市恭城瑶族自治县莲花镇",
        "feature": "月柿之乡",
        "type": "农业服务型",
        "lng": "110.875218",
        "lat": "24.728027",
        "area": "361",
        "gdp": "14.92"
    }, {
        "name": "黄冈市红安县七里坪镇",
        "formatted_address": "湖北省黄冈市红安县七里坪镇",
        "feature": "红色荆楚",
        "type": "旅游发展型",
        "lng": "114.654843",
        "lat": "31.462915",
        "area": "362",
        "gdp": "19.5"
    }, {
        "name": "荆门市东宝区漳河镇",
        "formatted_address": "湖北省荆门市东宝区漳河镇",
        "feature": "爱飞客镇",
        "type": "产业发展型",
        "lng": "112.08055",
        "lat": "30.954729",
        "area": "363",
        "gdp": "26"
    }, {
        "name": "襄阳市枣阳市吴店镇",
        "formatted_address": "湖北省襄阳市枣阳市吴店镇",
        "feature": "古帝乡里",
        "type": "产业发展型",
        "lng": "112.77615",
        "lat": "31.98167",
        "area": "366",
        "gdp": "200"
    }, {
        "name": "赤峰市宁城县八里罕镇",
        "formatted_address": "内蒙古自治区赤峰市宁城县八里罕镇",
        "feature": "塞外酒乡",
        "type": "产业发展型",
        "lng": "118.750421",
        "lat": "41.516739",
        "area": "374",
        "gdp": "11.6"
    }, {
        "name": "柳州市鹿寨县中渡镇",
        "formatted_address": "广西壮族自治区柳州市鹿寨县中渡镇",
        "feature": "文化旅游小镇",
        "type": "历史文化型",
        "lng": "109.698181",
        "lat": "24.679054",
        "area": "374",
        "gdp": "10.4"
    }, {
        "name": "贺州市八步区贺街镇",
        "formatted_address": "广西壮族自治区贺州市八步区贺街镇",
        "feature": "宗祠文脉小镇",
        "type": "历史文化型",
        "lng": "111.661146",
        "lat": "24.32888",
        "area": "377",
        "gdp": "11.39"
    }, {
        "name": "辽源市东辽县辽河源镇",
        "formatted_address": "吉林省辽源市东辽县辽河源镇",
        "feature": "生态农业小镇",
        "type": "农业服务型",
        "lng": "125.479801",
        "lat": "42.951664",
        "area": "410",
        "gdp": "15.9"
    }, {
        "name": "潍坊市寿光市羊口镇",
        "formatted_address": "山东省潍坊市寿光市羊口镇",
        "feature": "中国海盐之都",
        "type": "产业发展型",
        "lng": "118.886383",
        "lat": "37.240403",
        "area": "471",
        "gdp": "67.5"
    }, {
        "name": "第八师石河子市北泉镇",
        "formatted_address": "新疆维吾尔自治区石河子市北泉镇",
        "feature": "军垦小镇",
        "type": "旅游发展型",
        "lng": "86.016731",
        "lat": "44.333841",
        "area": "475",
        "gdp": "54"
    }, {
        "name": "牡丹江市宁安市渤海镇",
        "formatted_address": "黑龙江省牡丹江市宁安市渤海镇",
        "feature": "中华第一米城",
        "type": "农业服务型",
        "lng": "129.169549",
        "lat": "44.121149",
        "area": "506",
        "gdp": "22"
    }, {
        "name": "通辽市科尔沁左翼中旗舍伯吐镇",
        "formatted_address": "内蒙古自治区通辽市科尔沁左翼中旗舍伯吐镇",
        "feature": "黄牛小镇",
        "type": "农业服务型",
        "lng": "121.99002",
        "lat": "44.031139",
        "area": "654",
        "gdp": "33"
    }, {
        "name": "山南市扎囊县桑耶镇",
        "formatted_address": "西藏自治区山南市扎囊县桑耶镇",
        "feature": "藏原之乡",
        "type": "农业服务型",
        "lng": "91.509387",
        "lat": "29.323089",
        "area": "824",
        "gdp": "0.52"
    }, {
        "name": "海西蒙古族藏族自治州乌兰县茶卡镇",
        "formatted_address": "青海省海西蒙古族藏族自治州乌兰县茶卡镇",
        "feature": "天空之境",
        "type": "旅游发展型",
        "lng": "99.078923",
        "lat": "36.791405",
        "area": "1900",
        "gdp": "0.7"
    }, {
        "name": "呼伦贝尔市额尔古纳市莫尔道嘎镇",
        "formatted_address": "内蒙古自治区呼伦贝尔市额尔古纳市莫尔道嘎镇",
        "feature": "北国璞玉",
        "type": "旅游发展型",
        "lng": "120.785635",
        "lat": "51.255739",
        "area": "9384",
        "gdp": "2.1"
    }, {
        "name": "塔城地区沙湾县乌兰乌苏镇",
        "formatted_address": "新疆维吾尔自治区塔城地区沙湾县乌兰乌苏镇",
        "feature": "绿色农业小镇",
        "type": "旅游发展型",
        "lng": "85.870135",
        "lat": "44.305992",
        "area": "暂无",
        "gdp": "13.5"
    },

];


var convertData = function(data) {
    var res = [];
    for (var i = 0; i < data.length; i++) {
        var geoCoord = [data[i].lng, data[i].lat];
        res.push({
            name: data[i].formatted_address,
            value: geoCoord.concat([data[i].feature, data[i].type, data[i].area, data[i].gdp])
        });
    }
    return res;
};

var convertData2 = function(data) {
    var res = [];
    for (var i = 0; i < data.length; i++) {
        res.push({
            name: data[i].formatted_address,
            value: data[i].type
        });
    }
    return res;
};

option = {
    title: {
        text: '特色小镇空间分布',
        left: 'center',
        textStyle: {
            fontSize: 28,
            color: '#000'
        }
    },
    tooltip: {
        formatter: function(params) {
            name = params.data.name;
            feature = params.data.value[2];
            type = params.data.value[3];
            area = params.data.value[4];
            gdp = params.data.value[5];
            res = '<strong>' + name + ' </strong> ' + type + '<br />' +
                feature + '<br />' +
                'Area:' + area + '平方公里,' + 'GDP:' + gdp + '亿元';
            return res;
        }
    },
    visualMap: [{
            min: 0,
            max: 500,
            left: "right",
            top: 'center',
            text: ['GDP'],
            dimension: 5,
            inRange: {
                color: ['lightskyblue', 'yellow', 'orangered', ]
            },
            itemHeight: 400,
            calculable: true
        },

        {
            min: 25,
            max: 9500,
            left: 'left',
            top: 'center',
            dimension: 4,
            inRange: {
                symbolSize: [10, 100]
            },
            itemHeight: 400,
            calculable: true
        },
    ],
    geo: {
        map: 'china',
        roam: true,
    },
    series: [{
        name: 'town',
        type: 'scatter',
        coordinateSystem: 'geo',
        data: convertData(alldata),
        itemStyle: {
            normal: {
                color: '#FF6C00',
            }
        }
    },
    // {
    //     id: 'barplot',
    //     zlevel:2,
    //     name: 'Category',
    //     type: 'bar',
    //     data: [15,23,47]
    // }
    ]
};