option ={
    backgroundColor:"#0E233E",
    "series":[
        {
            "name":"外汇",
            "type":"pie",
            "hoverAnimation":false,
            "center":[
                "50%",
                "50%"
            ],
            "z":7,
            "radius":[
                0,
                "80%"
            ],
            "data":[
                {
                    "z":1,
                    "itemStyle":{
                        "opacity":0.7,
                        "color":"#5686F9"
                    },
                    "label":{
                        "show":false
                    },
                    "labelLine":{
                        "lineStyle":{
                            "opacity":0
                        }
                    },
                    "value":0
                },
                {
                    "name":"外汇",
                    "value":0.4,
                    "z":4,
                    "itemStyle":{
                        "opacity":0.7,
                        "color":"#5686F9"
                    },
                    "label":{
                        "show":false,
                        "position":"outside",
                        "formatter":"{d}%{a}",
                        "color":"#9bb0e2",
                        "fontSize":"16"
                    },
                    "emphasis":{
                        "label":{
                            "show":true
                        }
                    },
                    "labelLine":{
                        "show":false,
                        "length":10,
                        "lineStyle":{

                        },
                        "length2":10
                    }
                },
                {
                    "z":1,
                    "itemStyle":{
                        "opacity":0
                    },
                    "label":{
                        "show":false
                    },
                    "labelLine":{
                        "lineStyle":{
                            "opacity":0
                        }
                    },
                    "value":0.6
                }
            ]
        },
        {
            "name":"贵金属",
            "type":"pie",
            "hoverAnimation":false,
            "center":[
                "50%",
                "50%"
            ],
            "z":6,
            "radius":[
                0,
                "73%"
            ],
            "data":[
                {
                    "z":1,
                    "itemStyle":{
                        "opacity":0.7,
                        "color":"#4876E6"
                    },
                    "label":{
                        "show":false
                    },
                    "labelLine":{
                        "lineStyle":{
                            "opacity":0
                        }
                    },
                    "value":0.4
                },
                {
                    "name":"贵金属",
                    "value":0.2,
                    "z":4,
                    "itemStyle":{
                        "opacity":0.7,
                        "color":"#4876E6"
                    },
                    "label":{
                        "show":false,
                        "position":"outside",
                        "formatter":"{d}%{a}",
                        "color":"#9bb0e2",
                        "fontSize":"16"
                    },
                    "emphasis":{
                        "label":{
                            "show":true
                        }
                    },
                    "labelLine":{
                        "show":false,
                        "length":10,
                        "lineStyle":{

                        },
                        "length2":19
                    }
                },
                {
                    "z":1,
                    "itemStyle":{
                        "opacity":0
                    },
                    "label":{
                        "show":false
                    },
                    "labelLine":{
                        "lineStyle":{
                            "opacity":0
                        }
                    },
                    "value":0.39999999999999997
                }
            ]
        },
        {
            "name":"能源",
            "type":"pie",
            "hoverAnimation":false,
            "center":[
                "50%",
                "50%"
            ],
            "z":5,
            "radius":[
                0,
                "66%"
            ],
            "data":[
                {
                    "z":1,
                    "itemStyle":{
                        "opacity":0.7,
                        "color":"#3C69D6"
                    },
                    "label":{
                        "show":false
                    },
                    "labelLine":{
                        "lineStyle":{
                            "opacity":0
                        }
                    },
                    "value":0.6000000000000001
                },
                {
                    "name":"能源",
                    "value":0.07,
                    "z":4,
                    "itemStyle":{
                        "opacity":0.7,
                        "color":"#3C69D6"
                    },
                    "label":{
                        "show":false,
                        "position":"outside",
                        "formatter":"{d}%{a}",
                        "color":"#9bb0e2",
                        "fontSize":"16"
                    },
                    "emphasis":{
                        "label":{
                            "show":true
                        }
                    },
                    "labelLine":{
                        "show":false,
                        "length":10,
                        "lineStyle":{

                        },
                        "length2":28
                    }
                },
                {
                    "z":1,
                    "itemStyle":{
                        "opacity":0
                    },
                    "label":{
                        "show":false
                    },
                    "labelLine":{
                        "lineStyle":{
                            "opacity":0
                        }
                    },
                    "value":0.3299999999999999
                }
            ]
        },
        {
            "name":"大宗商品",
            "type":"pie",
            "hoverAnimation":false,
            "center":[
                "50%",
                "50%"
            ],
            "z":4,
            "radius":[
                0,
                "59%"
            ],
            "data":[
                {
                    "z":1,
                    "itemStyle":{
                        "opacity":0.7,
                        "color":"#315CC4"
                    },
                    "label":{
                        "show":false
                    },
                    "labelLine":{
                        "lineStyle":{
                            "opacity":0
                        }
                    },
                    "value":0.6700000000000002
                },
                {
                    "name":"大宗商品",
                    "value":0.003,
                    "z":4,
                    "itemStyle":{
                        "opacity":0.7,
                        "color":"#315CC4"
                    },
                    "label":{
                        "show":false,
                        "position":"outside",
                        "formatter":"{d}%{a}",
                        "color":"#9bb0e2",
                        "fontSize":"16"
                    },
                    "emphasis":{
                        "label":{
                            "show":true
                        }
                    },
                    "labelLine":{
                        "show":false,
                        "length":10,
                        "lineStyle":{

                        },
                        "length2":37
                    }
                },
                {
                    "z":1,
                    "itemStyle":{
                        "opacity":0
                    },
                    "label":{
                        "show":false
                    },
                    "labelLine":{
                        "lineStyle":{
                            "opacity":0
                        }
                    },
                    "value":0.32699999999999985
                }
            ]
        },
        {
            "name":"指数",
            "type":"pie",
            "hoverAnimation":false,
            "center":[
                "50%",
                "50%"
            ],
            "z":3,
            "radius":[
                0,
                "52%"
            ],
            "data":[
                {
                    "z":1,
                    "itemStyle":{
                        "opacity":0.7,
                        "color":"#2852B6"
                    },
                    "label":{
                        "show":false
                    },
                    "labelLine":{
                        "lineStyle":{
                            "opacity":0
                        }
                    },
                    "value":0.6730000000000002
                },
                {
                    "name":"指数",
                    "value":0.08,
                    "z":4,
                    "itemStyle":{
                        "opacity":0.7,
                        "color":"#2852B6"
                    },
                    "label":{
                        "show":false,
                        "position":"outside",
                        "formatter":"{d}%{a}",
                        "color":"#9bb0e2",
                        "fontSize":"16"
                    },
                    "emphasis":{
                        "label":{
                            "show":true
                        }
                    },
                    "labelLine":{
                        "show":false,
                        "length":10,
                        "lineStyle":{

                        },
                        "length2":46
                    }
                },
                {
                    "z":1,
                    "itemStyle":{
                        "opacity":0
                    },
                    "label":{
                        "show":false
                    },
                    "labelLine":{
                        "lineStyle":{
                            "opacity":0
                        }
                    },
                    "value":0.24699999999999983
                }
            ]
        },
        {
            "name":"A股",
            "type":"pie",
            "hoverAnimation":false,
            "center":[
                "50%",
                "50%"
            ],
            "z":2,
            "radius":[
                0,
                "45%"
            ],
            "data":[
                {
                    "z":1,
                    "itemStyle":{
                        "opacity":0.7,
                        "color":"#1C44A4"
                    },
                    "label":{
                        "show":false
                    },
                    "labelLine":{
                        "lineStyle":{
                            "opacity":0
                        }
                    },
                    "value":0.7530000000000001
                },
                {
                    "name":"A股",
                    "value":0.1,
                    "z":4,
                    "itemStyle":{
                        "opacity":0.7,
                        "color":"#1C44A4"
                    },
                    "label":{
                        "show":false,
                        "position":"outside",
                        "formatter":"{d}%{a}",
                        "color":"#9bb0e2",
                        "fontSize":"16"
                    },
                    "emphasis":{
                        "label":{
                            "show":true
                        }
                    },
                    "labelLine":{
                        "show":false,
                        "length":10,
                        "lineStyle":{

                        },
                        "length2":55
                    }
                },
                {
                    "z":1,
                    "itemStyle":{
                        "opacity":0
                    },
                    "label":{
                        "show":false
                    },
                    "labelLine":{
                        "lineStyle":{
                            "opacity":0
                        }
                    },
                    "value":0.14699999999999988
                }
            ]
        },
        {
            "name":"港美股",
            "type":"pie",
            "hoverAnimation":false,
            "center":[
                "50%",
                "50%"
            ],
            "z":1,
            "radius":[
                0,
                "38%"
            ],
            "data":[
                {
                    "z":1,
                    "itemStyle":{
                        "opacity":0.7,
                        "color":"#133791"
                    },
                    "label":{
                        "show":false
                    },
                    "labelLine":{
                        "lineStyle":{
                            "opacity":0
                        }
                    },
                    "value":0.8530000000000001
                },
                {
                    "name":"港美股",
                    "value":0.18,
                    "z":4,
                    "itemStyle":{
                        "opacity":0.7,
                        "color":"#133791"
                    },
                    "label":{
                        "show":false,
                        "position":"outside",
                        "formatter":"{d}%{a}",
                        "color":"#9bb0e2",
                        "fontSize":"16"
                    },
                    "emphasis":{
                        "label":{
                            "show":true
                        }
                    },
                    "labelLine":{
                        "show":false,
                        "length":10,
                        "lineStyle":{

                        },
                        "length2":64
                    }
                },
                {
                    "z":1,
                    "itemStyle":{
                        "opacity":0
                    },
                    "label":{
                        "show":false
                    },
                    "labelLine":{
                        "lineStyle":{
                            "opacity":0
                        }
                    },
                    "value":-0.033000000000000085
                }
            ]
        },
        {
            "name":"债券",
            "type":"pie",
            "hoverAnimation":false,
            "center":[
                "50%",
                "50%"
            ],
            "z":0,
            "radius":[
                0,
                "31%"
            ],
            "data":[
                {
                    "z":1,
                    "itemStyle":{
                        "opacity":0.7,
                        "color":"#0A2975"
                    },
                    "label":{
                        "show":false
                    },
                    "labelLine":{
                        "lineStyle":{
                            "opacity":0
                        }
                    },
                    "value":1.0330000000000001
                },
                {
                    "name":"债券",
                    "value":0.005,
                    "z":4,
                    "itemStyle":{
                        "opacity":0.7,
                        "color":"#0A2975"
                    },
                    "label":{
                        "show":false,
                        "position":"outside",
                        "formatter":"{d}%{a}",
                        "color":"#9bb0e2",
                        "fontSize":"16"
                    },
                    "emphasis":{
                        "label":{
                            "show":true
                        }
                    },
                    "labelLine":{
                        "show":false,
                        "length":10,
                        "lineStyle":{

                        },
                        "length2":73
                    }
                },
                {
                    "z":1,
                    "itemStyle":{
                        "opacity":0
                    },
                    "label":{
                        "show":false
                    },
                    "labelLine":{
                        "lineStyle":{
                            "opacity":0
                        }
                    },
                    "value":-0.03800000000000014
                }
            ]
        }
    ]
}