//如图，如何把 “市直”里的各个点，都放在一个圆圈里？例如直线图中的 markArea
//例如：https://observablehq.com/@d3/zoomable-circle-packing ， 不过它是关系图，还有连线。


option ={
    "tooltip":{
        "formatter":"{b}"
    },
    "animationDuration":1000,
    "animationEasingUpdate":"quinticInOut",
    "series":[
        {
            "name":"知识图谱",
            "type":"graph",
            "layout":"force",
            "force":{
                "repulsion":390,
                "gravity":0.1,
                "edgeLength":75,
                "layoutAnimation":true
            },
            "data":[
                {
                    "x":0,
                    "y":60,
                    "name":"市直",
                    "symbolSize":80,
                    "category":0,
                    "draggable":"true"
                },
                {
                    "x":50,
                    "y":80,
                    "name":"市发改委",
                    "symbolSize":60,
                    "category":0,
                    "draggable":"true"
                },
                {
                    "x":100,
                    "y":100,
                    "name":"市经贸委",
                    "symbolSize":60,
                    "category":0,
                    "draggable":"true"
                },
                {
                    "x":150,
                    "y":120,
                    "name":"市民政局",
                    "symbolSize":60,
                    "category":0,
                    "draggable":"true"
                },
                {
                    "x":200,
                    "y":140,
                    "name":"市人事局",
                    "symbolSize":60,
                    "category":0,
                    "draggable":"true"
                },
                {
                    "x":250,
                    "y":160,
                    "name":"市规划局",
                    "symbolSize":60,
                    "category":0,
                    "draggable":"true"
                },
                {
                    "x":300,
                    "y":180,
                    "name":"市粮食局",
                    "symbolSize":60,
                    "category":0,
                    "draggable":"true"
                },
                {
                    "x":350,
                    "y":200,
                    "name":"市审计局",
                    "symbolSize":60,
                    "category":0,
                    "draggable":"true"
                },
                {
                    "x":400,
                    "y":220,
                    "name":"市法制办",
                    "symbolSize":60,
                    "category":0,
                    "draggable":"true"
                },
                {
                    "x":450,
                    "y":240,
                    "name":"市信访局",
                    "symbolSize":60,
                    "category":0,
                    "draggable":"true"
                },
                {
                    "x":500,
                    "y":260,
                    "name":"市食品药品局",
                    "symbolSize":60,
                    "category":0,
                    "draggable":"true"
                },
                {
                    "x":550,
                    "y":280,
                    "name":"市农业局",
                    "symbolSize":60,
                    "category":0,
                    "draggable":"true"
                },
                {
                    "x":600,
                    "y":300,
                    "name":"团市委",
                    "symbolSize":60,
                    "category":0,
                    "draggable":"true"
                },
                {
                    "x":650,
                    "y":320,
                    "name":"市地税局",
                    "symbolSize":60,
                    "category":0,
                    "draggable":"true"
                },
                {
                    "x":700,
                    "y":340,
                    "name":"市招标局",
                    "symbolSize":60,
                    "category":0,
                    "draggable":"true"
                },
                {
                    "x":750,
                    "y":360,
                    "name":"市招商局",
                    "symbolSize":60,
                    "category":0,
                    "draggable":"true"
                },
                {
                    "x":0,
                    "y":60,
                    "name":"区县",
                    "symbolSize":80,
                    "category":1,
                    "draggable":"true"
                },
                {
                    "x":50,
                    "y":80,
                    "name":"沙县",
                    "symbolSize":60,
                    "category":1,
                    "draggable":"true"
                },
                {
                    "x":100,
                    "y":100,
                    "name":"建宁县",
                    "symbolSize":60,
                    "category":1,
                    "draggable":"true"
                },
                {
                    "x":150,
                    "y":120,
                    "name":"大田县",
                    "symbolSize":60,
                    "category":1,
                    "draggable":"true"
                },
                {
                    "x":200,
                    "y":140,
                    "name":"尤溪县",
                    "symbolSize":60,
                    "category":1,
                    "draggable":"true"
                },
                {
                    "x":250,
                    "y":160,
                    "name":"梅列区",
                    "symbolSize":60,
                    "category":1,
                    "draggable":"true"
                },
                {
                    "x":300,
                    "y":180,
                    "name":"三元区",
                    "symbolSize":60,
                    "category":1,
                    "draggable":"true"
                },
                {
                    "x":350,
                    "y":200,
                    "name":"明溪县",
                    "symbolSize":60,
                    "category":1,
                    "draggable":"true"
                },
                {
                    "x":400,
                    "y":220,
                    "name":"泰宁县",
                    "symbolSize":60,
                    "category":1,
                    "draggable":"true"
                },
                {
                    "x":450,
                    "y":240,
                    "name":"将乐县",
                    "symbolSize":60,
                    "category":1,
                    "draggable":"true"
                },
                {
                    "x":0,
                    "y":60,
                    "name":"中心",
                    "symbolSize":90,
                    "category":3,
                    "draggable":"true"
                }
            ],
            "links":[
                {
                    "source":"市直",
                    "target":"市直",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"市发改委",
                    "target":"市直",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"市经贸委",
                    "target":"市直",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"市民政局",
                    "target":"市直",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"市人事局",
                    "target":"市直",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"市规划局",
                    "target":"市直",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"市粮食局",
                    "target":"市直",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"市审计局",
                    "target":"市直",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"市法制办",
                    "target":"市直",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"市信访局",
                    "target":"市直",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"市食品药品局",
                    "target":"市直",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"市农业局",
                    "target":"市直",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"团市委",
                    "target":"市直",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"市地税局",
                    "target":"市直",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"市招标局",
                    "target":"市直",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"市招商局",
                    "target":"市直",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"区县",
                    "target":"区县",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"沙县",
                    "target":"区县",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"建宁县",
                    "target":"区县",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"大田县",
                    "target":"区县",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"尤溪县",
                    "target":"区县",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"梅列区",
                    "target":"区县",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"三元区",
                    "target":"区县",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"明溪县",
                    "target":"区县",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"泰宁县",
                    "target":"区县",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"将乐县",
                    "target":"区县",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"市直",
                    "target":"中心",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"区县",
                    "target":"中心",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"检查",
                    "target":"中心",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                },
                {
                    "source":"疾病",
                    "target":"中心",
                    "lineStyle":{
                        "normal":{
                            "color":"source"
                        }
                    }
                }
            ],
            "categories":[
                {
                    "name":"市直"
                },
                {
                    "name":"区县"
                },
                {
                    "name":"检查"
                },
                {
                    "name":"疾病"
                }
            ],
            "roam":false,
            "label":{
                "normal":{
                    "show":true,
                    "position":"inside",
                    "formatter":"{b}",
                    "fontSize":12,
                    "fontStyle":"400"
                }
            },
            "lineStyle":{
                "normal":{
                    "opacity":0.9,
                    "width":1,
                    "curveness":0
                }
            }
        }
    ]
}