option = {
    title: {
        text: ''
    },
    tooltip: {},
    animationDurationUpdate: 1500,
    animationEasingUpdate: 'quinticInOut',
    label: {
        normal: {
            show: true,
            textStyle: {
                fontSize: 12
            },
        }
    },
    legend: {
        x: "center",
        show: false,
        data: ["普通合伙人", "有限合伙人", '有限合伙企业']
    },
    series: [

        {
            type: 'graph',
            layout: 'force',
            symbolSize: 45,
            focusNodeAdjacency: true,
            roam: true,
            categories: [{
                name: '普通合伙人',
                itemStyle: {
                    normal: {
                        color: "#009800",
                    }
                }
            }, {
                name: '有限合伙人',
                itemStyle: {
                    normal: {
                        color: "#4592FF",
                    }
                }
            }, {
                name: '有限合伙企业',
                itemStyle: {
                    normal: {
                        color: "#3592F",
                    }
                }
            }],
            label: {
                normal: {
                    show: true,
                    textStyle: {
                        fontSize: 12
                    },
                }
            },
            force: {
                repulsion: 1000
            },
            edgeSymbolSize: [4, 50],
            edgeLabel: {
                normal: {
                    show: true,
                    textStyle: {
                        fontSize: 10
                    },
                    formatter: "{c}"
                }
            },
            data: [{
                name: '天津恩讯有限合伙企业',
                category:1,
                draggable: true,
            }, {
                name: '天津恩信信息合伙企业',
                category: 0,
                draggable: true,
            }, {
                name: '天津恩源信息科技有限合伙企业',
                category: 0,
                draggable: true,
            }, {
                name: '北京恩源科技有限公司',
                draggable: true,
            }, {
                name: '普通合伙1',
                category: 1,
                draggable: true,
            }, {
                name: '普通合伙2',
                category: 1,
                draggable: true,
            }, {
                name: '普通合伙N',
                category: 1,
                draggable: true,
            }, {
                name: '有限合伙1',
                category: 1,
                draggable: true,
            }, {
                name: '有限合伙2',
                category: 1,
                draggable: true,
            }, {
                name: '有限合伙人N',
                category: 1,
                draggable: true,
            }, {
                name: '有限合伙企业1',
                category: 1,
                draggable: true,
            }, {
                name: '有限合伙企业2',
                category: 1,
                draggable: true,
            }, {
                name: '有限合伙企业3',
                category: 1,
                draggable: true,
            }, {
                name: '有限合伙企业4',
                category: 1,
                draggable: true,
            }, {
                name: '有限合伙企业5',
                category: 1,
                draggable: true,
            }, {
                name: '有限合伙企业6',
                category: 1,
                draggable: true,
            }, {
                name: '有限合伙企业7',
                category: 1,
                draggable: true,
            }, {
                name: '有限合伙企业N',
                category: 1,
                draggable: true,
            }, {
                name: '服务中心1',
                category: 1,
                draggable: true,
            },  {
                name: '服务中心2',
                category: 1,
                draggable: true,
            }, {
                name: '服务中心3',
                category: 1,
                draggable: true,
            }, {
                name: '服务中心4',
                category: 1,
                draggable: true,
            }, {
                name: '服务中心5',
                category: 1,
                draggable: true,
            }, {
                name: '服务中心6',
                category: 1,
                draggable: true,
            }, {
                name: '服务中心7',
                category: 1,
                draggable: true,
            }, {
                name: '服务中心8',
                category: 1,
                draggable: true,
            }, {
                name: '服务中心9',
                category: 1,
                draggable: true,
            }, {
                name: '服务中心10',
                category:1,
                draggable: true,
            }, {
                name: '服务中心11',
                category: 1,
                draggable: true,
            }, {
                name: '服务中心12',
                category: 1,
                draggable: true,
            }, {
                name: '服务中心13',
                category: 1,
                draggable: true,
            }, {
                name: '服务中心14',
                category: 1,
                draggable: true,
            }, {
                name: '服务中心15',
                category: 1,
                draggable: true,
            }, {
                name: '服务中心16',
                category: 1,
                draggable: true,
            }, {
                name: '服务中心N',
                category: 1,
                draggable: true,
            }],
            links: [{
                source: 0,
                target: 2,
                category:0,
                value: '股东'
            },  {
                source: 4,
                target: 2,
                value: '股东'
            },  {
                source: 5,
                target: 2,
                value: '股东'
            }, {
                source: 7,
                target: 2,
                value: '股东'
            },  {
                source: 6,
                target: 1,
                value: '股东'
            }, {
                source: 8,
                target: 2,
                value: '股东'
            }, {
                source: 10,
                target: 2,
                value: '股东'
            }, {
                source: 11,
                target: 2,
                value: '股东'
            }, {
                source: 12,
                target: 2,
                value: '股东'
            }, {
                source: 13,
                target: 2,
                value: '股东'
            }, {
                source: 14,
                target: 2,
                value: '股东'
            }, {
                source: 15,
                target: 2,
                value: '股东'
            }, {
                source: 16,
                target: 2,
                value: '股东'
            }, {
                source: 17,
                target: 1,
                value: '股东'
            }, {
                source: 9,
                target: 1,
                value: '股东'
            }, {
                source: 1,
                target: 3,
                value: '0.01股份'
            }, {
                source: 2,
                target: 3,
                value: '99.9股份'
            }, {
                source: 3,
                target: 18,
                value: '控股'
            }, {
                source: 3,
                target: 19,
                value: '控股'
            }, {
                source: 3,
                target: 20,
                value: '控股'
            }, {
                source: 3,
                target: 21,
                value: '控股'
            }, {
                source: 3,
                target: 22,
                value: '控股'
            }, {
                source: 3,
                target: 23,
                value: '控股'
            }, {
                source: 3,
                target: 24,
                value: '控股'
            }, {
                source: 3,
                target: 25,
                value: '控股'
            }, {
                source: 3,
                target: 26,
                value: '控股'
            }, {
                source: 3,
                target: 27,
                value: '控股'
            }, {
                source: 3,
                target: 28,
                value: '控股'
            }, {
                source: 3,
                target: 29,
                value: '控股'
            }, {
                source: 3,
                target: 30,
                value: '控股'
            }, {
                source: 3,
                target: 31,
                value: '控股'
            }, {
                source: 3,
                target: 32,
                value: '控股'
            }, {
                source: 3,
                target: 33,
                value: '控股'
            }, {
                source: 3,
                target: 34,
                value: '控股'
            }],
            lineStyle: {
                normal: {
                    opacity: 0.9,
                    width: 1,
                    curveness: 0
                }
            }
        }
    ]
};