var uploadedDataURL = "/asset/get/s/data-1547608545485-yyRMUge-X.json";

var uploadedDataURL = "/asset/get/s/data-1547609362135-8Hiih-zS1.json";
var obj= {"type":"Feature","UTF8Encoding":false,"feature":{"id":"510100","geometry":{"type":"MultiPolygon","coordinates":[["@@A@BB","@@@CGDF@","@@HBJJJADE@CCMFIBGHGJO@KBAHEPO@EAGLEFG@IEIEAIAKEKIWWCK@W@GDGDCLELSJCDI\\KJMAEIEACBIPSAEIKBIJML@LIK@@A@AH@D@@AFBBACC@ECA@EDED@HBDCBBD@DF@BDBFGFFF@DCAEHB@CFAF@BEHEAEDADBFEJIBEDGJ@BBB@DG@CHIBCAAGABECODCD@@EHALGCEAEBADEAABCAA@ABBBAACDEECAIGCBAHAFBJCACIAGE@CLBFC@AC@@CF@CCF@BCFERE@AAAAADA@GNENABGBBBA@MACB@@CXCNI@IACLGBCFAAADCCC@AJABEFAVCABB@BADBC@@DD@BA@ABAA@BAL@J@@EGACC@GDED@BBD@PGZEDG@AJACEF@BFD@DEHCDENKBKEAACHKBMCEAGGGFI@EKAAKACA@G@AC@WCAMAAA@EHAFQPAFJH@HBDCDEDCF@FDNGPFPBBAFC@CAEBAJBDKFCB@DFDBLIDCB@FF\\APHFHFBDCBGDAD@JFXAND\\GLAJGPCHFJLLBBA@CB@LFBHFADCBADNJFCHDHNVBHJHDADAFEHAFMFADBDLDFBLBDH@HID@\\JNDPEFDFALAFBBHFADFD@BDPBDELAFCHAHB@CLGHADEHDPEJDPQXKBCG[@QAEGCGG@GBCL@^ENGlKLGTETDB@FGNIBKFCN@RHH@DEHMJG\\CZGTADCBCHCF@FATBHCBA@CEEAEBIPQBELeAEGD@A@IFCJBHFDFHDHABCFYFKBCJGBA@CEKAEJEDCCIDEDALBF@DCB@FBD@BAAE@GBAHDHBNALBJABC@CIIAGBOAKBCBAF@TABADIJGBCBKJOBEFUAMFCF@FLP@JD@ELK@IAIIKIEAIGI@EAAE@AA@EGCGIBCCCBA@EAACBAABAAABAAADAAEDCCCFADBBBFADB@BHFJCDDDA@NJEDBDIBDDBBDHB@CBA@ABCFCDEB@BODEFCBCHCBGAEBCFAFHHDD@HE@C@UCEAGOWBKGACAAIUB[KKHQFOAOAO@IECCBKBI@CA@E@CCCBAAC@EACBAAEBCACDIGA@CCWACD@BJFDDABKBBBDD@BK@BFEDBFQHWFMDBXCDALELEBUFOHWHKFEFAJDXBJNHBBLRBFADG@IFQD@BCDC@@DC@CC@B@BABBBC@A@A@EEAD@B@BC@ABA@C@@EEBACEA@BABBFE@EBEB@DGAADA@EFCCADCCC@@CCAC@@DBDEBABIBAABCAAGB@DCAA@@@BDCBEBKPGFC@OEC@KRAH@BC@MGACAMAEAAEBYJCAAFEE@AFCCCEACDCC@AEBAD@@D@@BI@CB@GBAFAAAIBACCBFE@ACADEICE@E@GKOI@GAAE@KFAA@GACEBMCGDGB]KQ@A@GHUEMJYDGAEAIGAKCGAGBOJOIQAcEC@EDGFEHCHBFCBE@CCGCA_OACDKBECGGECAaHM@AAEICAOBGCOAAB@FHFBDERKXIJIDCCAIBAN@BC@AEIHKCCGAYASPGBCHIBAAAIEE]QUCGACCEEAEBCJG@CUGEEACBAHEFBNDPCBAACSaSUAADG@CGAM@GAKKAEBMAKCAMCACBOAQOOEISSAGDK@GMSGAEIGGEC@CBEEUCGKI@ICICEKIEMGGAGAaCCMKKEGAECEEMAGBEFAJIDODEDGNABCBMCCDBHEDA@GCGBEHENC@GGGBCD@FCDC@]KC@@BCLCBKGEBC@QIO@EBINKJCLMHCHAJDP@FMHENEFSFUTAHMXBHLJ@BI@WFICICCE@CHIBIACICB@CCAKAAODG@UEEB@FCFAHGLEF@PCACICAYCMECA_D_AQ@OFC@SIcSGIDM@CAAC@EDC@MACCASEBICEFCBM@EC@GTW@GAEE@IDE@GGIAGKIMCAI@GBABB@FBEBGACG@@OFA@AA@KJE@IJCACB@CA@CBCDCQIMCmEGAEKAI@AJIAIFK@KACE@QJIDINCDA@EOOWECIACDDFDF@B]DGCI@IIC@GBSGGCCIEA_ISEDKNSB@BCCEQU[KIECOACAAGDEAMMMQIQCAA@APCHCDGFABDLALICE@GHM@E@CC@CFKDCNELIDK@CCICEGEEAG@IBCDAFIPAFFHAD@DHBDDCDGFAAMCBGFACE@IACECE@A@GNE@EEICW[ECG@EBGFANQHCHIJBHEHADEHIBCD@FPHFNENFPCFQFCD@FBDFFDF@DGJ@HJFHJALHHBH@JCTKBEFOBMHGCKD[IGBADDTCNGNCDWFM@OAOBu[UMGQESEGBGAEEGMEGBEDCHBNCJCNEFCFEDC@IGABUVCBGCGOOQUcEEMEW@GACDEFIDP@DDJ@FAHKNBNA\\MBCDAFAFDNLdMP@HDHDDLDNVD@DCFBLFVVv|@HCHEDKDADDJFTADEJBREFJJDNGP@BDLDBD@LGJAH@DH@BADQHIHADBDJFPRFJJFRFDCBEH@@D@BFHBHFDBHLNDNJJFF@DGPCB@DBDUAKBKDAFNbDTCLEFMLEHAP@DEBUEMHCHCH@FBD@VBFJNDJCXBVAJCFKLCNIHS@KDIFEHGV[TAFDREFCBI@yYIAE@AB@FDZ@BGLSTOHMNOZELAJ@JAHHBHBFDFH@FFDPBjT`@DBPLPJN@LATKNEZMNEBAFAJFLNHXDFJBJHNJR`LFHDH@JCTDJATMHAHALBPCJBNDNAHDFDF@LQBAHCLCLBH@JIFIDMPEF@`RRNPAHPHNTXPBLFTJJF`@VD`^D@LANJHBPPDLDLAjDNRV\\Rp\\FLDBRBD@BF@@EFAPDPFHBJ@NETAVEHQHAFJRHLHFFLBHAXHJHHBDEL@JHFDPFBPVFNDPJNFDDDBDAFJNF^HBLHPRBDAdKPHdBR@JOVIHBZR\\BFING\\@HBJCNAHBNDDDBNA^DJFHLB@HAHGR@LCBBJJHBTDVEVHHHDHJJFJTNLLDDBJJBT@NFP@HDLDFHDN@JLJTHTFJFVJF@HEN@DAFBFHD@HAFCDSVSDANFNCRBPHLHD@JIFCF@"]],"encodeOffsets":[[[106606,31777],[105927,30843],[106375,32170]]]},"properties":{"cp":[104.065735,30.659462],"name":"成都","childNum":3}}}

myChart.showLoading();

$.getJSON(uploadedDataURL, function (usaJson) {
    myChart.hideLoading();
    echarts.registerMap('Custom', obj);
    option = {
        
        tooltip: {
            trigger: 'item',
            showDelay: 0,
            transitionDuration: 0.2,
            formatter: function (params) {
                var value = (params.value + '').split('.');
                value = value[0].replace(/(\d{1,3})(?=(?:\d{3})+(?!\d))/g, '$1,');
                return params.seriesName + '<br/>' + params.name + ': ' + value;
            }
        },
        visualMap: {
            left: 'right',
            min: 500000,
            max: 38000000,
            color: ['orangered','yellow','lightskyblue'],
            text:['High','Low'],           // 文本，默认为数值文本
            calculable: true
        },
        toolbox: {
            show: true,
            //orient: 'vertical',
            left: 'left',
            top: 'top',
            feature: {
                dataView: {readOnly: false},
                restore: {},
                saveAsImage: {}
            }
        },
        series: [
            {
                name: 'Custom map',
                type: 'map',
                roam: true,
                map: 'Custom',
                itemStyle:{
                    emphasis:{label:{show:true}}
                },
                // 文本位置修正
                textFixed: {
                    Alaska: [20, -20]
                },
                data:[
                   
                ]
            }
        ]
    };

    myChart.setOption(option);
});