var option = {
        xAxis:{
            type:"category",
            data:[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]
        },
        yAxis:{
            type:'value'
        },
        dataZoom:{
            type:'inside'
        },
        toolbox:{
            orient:'horizontal',
            feature:{
                restore:{
                    title:"还原",   
                }
            },
            itemSize:18,
            iconStyle:{
                textAlign:'rght',
            }
        },
        grid:{
            left:50
        },
        series:[
            {
                data:[10,12,13,14,20,16,17,18,29,20,21,12,23,24,30,17,15,8,24,28,29,1,8,20,16],
                type:'line',
                lineStyle:{
                    color:'green'
                },
                itemStyle:{
                    color:"tblue"
                }
            }
        ]
    }