option = {
    series: {
        type: 'sankey',
        layout:'none',
        focusNodeAdjacency: 'allEdges',
        links: [{'source': 'From USA', 'target': 'To USA', 'value': 13592}, {'source': 'From CHN', 'target': 'To CHN', 'value': 11107}, {'source': 'From JPN', 'target': 'To JPN', 'value': 3315}, {'source': 'From USA', 'target': 'To CHN', 'value': 2799}, {'source': 'From CHN', 'target': 'To USA', 'value': 2509}, {'source': 'From KOR', 'target': 'To KOR', 'value': 1937}, {'source': 'From FRA', 'target': 'To FRA', 'value': 1899}, {'source': 'From IND', 'target': 'To IND', 'value': 1439}, {'source': 'From GBR', 'target': 'To GBR', 'value': 1394}, {'source': 'From DEU', 'target': 'To DEU', 'value': 1178}, {'source': 'From ITA', 'target': 'To ITA', 'value': 1038}, {'source': 'From USA', 'target': 'To GBR', 'value': 898}, {'source': 'From GBR', 'target': 'To USA', 'value': 812}, {'source': 'From USA', 'target': 'To KOR', 'value': 811}, {'source': 'From ESP', 'target': 'To ESP', 'value': 794}, {'source': 'From USA', 'target': 'To IND', 'value': 726}, {'source': 'From DEU', 'target': 'To USA', 'value': 725}, {'source': 'From JPN', 'target': 'To USA', 'value': 705}, {'source': 'From USA', 'target': 'To JPN', 'value': 694}, {'source': 'From KOR', 'target': 'To USA', 'value': 689}, {'source': 'From CAN', 'target': 'To USA', 'value': 670}, {'source': 'From IND', 'target': 'To USA', 'value': 670}, {'source': 'From USA', 'target': 'To DEU', 'value': 669}, {'source': 'From AUS', 'target': 'To AUS', 'value': 648}, {'source': 'From USA', 'target': 'To CAN', 'value': 615}, {'source': 'From CAN', 'target': 'To CAN', 'value': 517}, {'source': 'From FRA', 'target': 'To USA', 'value': 509}, {'source': 'From USA', 'target': 'To FRA', 'value': 507}, {'source': 'From NLD', 'target': 'To NLD', 'value': 446}, {'source': 'From BRA', 'target': 'To BRA', 'value': 358}, {'source': 'From USA', 'target': 'To AUS', 'value': 325}, {'source': 'From AUS', 'target': 'To USA', 'value': 309}, {'source': 'From ITA', 'target': 'To USA', 'value': 280}, {'source': 'From USA', 'target': 'To NLD', 'value': 278}, {'source': 'From GBR', 'target': 'To CHN', 'value': 273}, {'source': 'From ESP', 'target': 'To USA', 'value': 271}, {'source': 'From ISR', 'target': 'To USA', 'value': 264}, {'source': 'From USA', 'target': 'To ESP', 'value': 260}, {'source': 'From USA', 'target': 'To ITA', 'value': 258}, {'source': 'From NLD', 'target': 'To USA', 'value': 254}],
        data: [{'name': 'From ISR'}, {'name': 'To ISR'}, {'name': 'From GBR'}, {'name': 'To GBR'}, {'name': 'From JPN'}, {'name': 'To JPN'}, {'name': 'From USA'}, {'name': 'To USA'}, {'name': 'From ESP'}, {'name': 'To ESP'}, {'name': 'From CAN'}, {'name': 'To CAN'}, {'name': 'From NLD'}, {'name': 'To NLD'}, {'name': 'From CHN'}, {'name': 'To CHN'}, {'name': 'From ITA'}, {'name': 'To ITA'}, {'name': 'From BRA'}, {'name': 'To BRA'}, {'name': 'From FRA'}, {'name': 'To FRA'}, {'name': 'From DEU'}, {'name': 'To DEU'}, {'name': 'From AUS'}, {'name': 'To AUS'}, {'name': 'From IND'}, {'name': 'To IND'}, {'name': 'From KOR'}, {'name': 'To KOR'}],
    }
};
