
////////// 2012 年
var value1 = [
    {name: '美国', gold: 46, silver: 29, copper: 29, value: 104},
    {name: '中国', gold: 38, silver: 27, copper: 23, value: 88},
    {name: '英国', gold: 29, silver: 17, copper: 19, value: 65},
    {name: '俄罗斯', gold: 24, silver: 25, copper: 33, value: 82},
    {name: '韩国', gold: 13, silver: 8, copper: 7, value: 28},
    {name: '德国', gold: 11, silver: 19, copper: 14, value: 44},
    {name: '法国', gold: 11, silver: 11, copper: 12, value: 34},
    {name: '意大利', gold: 8, silver: 9, copper: 11, value: 28},
    {name: '匈牙利', gold: 8, silver: 4, copper: 5, value: 17},
    {name: '澳大利亚', gold: 7, silver: 16, copper: 12, value: 35},
    {name: '日本', gold: 7, silver: 14, copper: 17, value: 38},
    {name: '哈萨克斯坦', gold: 7, silver: 1, copper: 5, value: 13},
    {name: '荷兰', gold: 6, silver: 6, copper: 8, value: 20},
    {name: '乌克兰', gold: 6, silver: 5, copper: 9, value: 20},
    {name: '古巴', gold: 5, silver: 3, copper: 6, value: 14},
    {name: '新西兰', gold: 5, silver: 3, copper: 5, value: 13},
    {name: '伊朗', gold: 4, silver: 5, copper: 3, value: 12},
    {name: '牙买加', gold: 4, silver: 4, copper: 4, value: 12},
    {name: '捷克', gold: 4, silver: 3, copper: 3, value: 10},
    {name: '朝鲜', gold: 4, silver: 0, copper: 2, value: 6},
    {name: '西班牙', gold: 3, silver: 10, copper: 4, value: 17},
    {name: '巴西', gold: 3, silver: 5, copper: 9, value: 17},
    {name: '白俄罗斯', gold: 3, silver: 5, copper: 5, value: 13},
    {name: '南非', gold: 3, silver: 2, copper: 1, value: 6},
    {name: '埃塞俄比亚', gold: 3, silver: 1, copper: 3, value: 7},
    {name: '克罗地亚', gold: 3, silver: 1, copper: 2, value: 6},
    {name: '罗马尼亚', gold: 2, silver: 5, copper: 2, value: 9},
    {name: '肯尼亚', gold: 2, silver: 4, copper: 5, value: 11},
    {name: '丹麦', gold: 2, silver: 4, copper: 3, value: 9},
    {name: '波兰', gold: 2, silver: 2, copper: 6, value: 10},
    {name: '阿塞拜疆', gold: 2, silver: 2, copper: 6, value: 10},
    {name: '土耳其', gold: 2, silver: 2, copper: 1, value: 5},
    {name: '瑞士', gold: 2, silver: 2, copper: 0, value: 4},
    {name: '立陶宛', gold: 2, silver: 1, copper: 2, value: 5},
    {name: '挪威', gold: 2, silver: 1, copper: 1, value: 4},
    {name: '加拿大', gold: 1, silver: 5, copper: 12, value: 18},
    {name: '瑞典', gold: 1, silver: 4, copper: 3, value: 8},
    {name: '哥伦比亚', gold: 1, silver: 3, copper: 4, value: 8},
    {name: '格鲁吉亚', gold: 1, silver: 3, copper: 3, value: 7},
    {name: '墨西哥', gold: 1, silver: 3, copper: 3, value: 7},
    {name: '爱尔兰', gold: 1, silver: 1, copper: 3, value: 5},
    {name: '塞尔维亚', gold: 1, silver: 1, copper: 2, value: 4},
    {name: '斯洛文尼亚', gold: 1, silver: 1, copper: 2, value: 4},
    {name: '阿根廷', gold: 1, silver: 1, copper: 2, value: 4},
    {name: '突尼斯', gold: 1, silver: 1, copper: 1, value: 3},
    {name: '多米尼加', gold: 1, silver: 1, copper: 0, value: 2},
    {name: '乌兹别克斯坦', gold: 1, silver: 0, copper: 3, value: 4},
    {name: '特立尼达和多巴哥', gold: 1, silver: 0, copper: 3, value: 4},
    {name: '拉脱维亚', gold: 1, silver: 0, copper: 1, value: 2},
    {name: '格林纳达', gold: 1, silver: 0, copper: 0, value: 1},
    {name: '巴哈马', gold: 1, silver: 0, copper: 0, value: 1},
    {name: '乌干达', gold: 1, silver: 0, copper: 0, value: 1},
    {name: '委内瑞拉', gold: 1, silver: 0, copper: 0, value: 1},
    {name: '阿尔及利亚', gold: 1, silver: 0, copper: 0, value: 1},
    {name: '印度', gold: 0, silver: 2, copper: 4, value: 6},
    {name: '蒙古', gold: 0, silver: 2, copper: 3, value: 5},
    {name: '泰国', gold: 0, silver: 2, copper: 1, value: 3},
    {name: '埃及', gold: 0, silver: 2, copper: 0, value: 2},
    {name: '斯洛伐克', gold: 0, silver: 1, copper: 3, value: 4},
    {name: '比利时', gold: 0, silver: 1, copper: 2, value: 3},
    {name: '芬兰', gold: 0, silver: 1, copper: 2, value: 3},
    {name: '亚美尼亚', gold: 0, silver: 1, copper: 2, value: 3},
    {name: '马来西亚', gold: 0, silver: 1, copper: 1, value: 2},
    {name: '中华台北', gold: 0, silver: 1, copper: 1, value: 2},
    {name: '爱沙尼亚', gold: 0, silver: 1, copper: 1, value: 2},
    {name: '保加利亚', gold: 0, silver: 1, copper: 1, value: 2},
    {name: '印度尼西亚', gold: 0, silver: 1, copper: 1, value: 2},
    {name: '波多黎各', gold: 0, silver: 1, copper: 1, value: 2},
    {name: '黑山', gold: 0, silver: 1, copper: 0, value: 1},
    {name: '博茨瓦纳', gold: 0, silver: 1, copper: 0, value: 1},
    {name: '塞浦路斯', gold: 0, silver: 1, copper: 0, value: 1},
    {name: '葡萄牙', gold: 0, silver: 1, copper: 0, value: 1},
    {name: '加蓬', gold: 0, silver: 1, copper: 0, value: 1},
    {name: '危地马拉', gold: 0, silver: 1, copper: 0, value: 1},
    {name: '卡塔尔', gold: 0, silver: 0, copper: 2, value: 2},
    {name: '新加坡', gold: 0, silver: 0, copper: 2, value: 2},
    {name: '希腊', gold: 0, silver: 0, copper: 2, value: 2},
    {name: '摩尔多瓦', gold: 0, silver: 0, copper: 2, value: 2},
    {name: '巴林', gold: 0, silver: 0, copper: 1, value: 1},
    {name: '塔吉克斯坦', gold: 0, silver: 0, copper: 1, value: 1},
    {name: '中国香港', gold: 0, silver: 0, copper: 1, value: 1},
    {name: '摩洛哥', gold: 0, silver: 0, copper: 1, value: 1},
    {name: '沙特阿拉伯', gold: 0, silver: 0, copper: 1, value: 1},
    {name: '科威特', gold: 0, silver: 0, copper: 1, value: 1},
    {name: '阿富汗', gold: 0, silver: 0, copper: 1, value: 1}
];

////////// 2008 年
var value2 = [
    {name: '中国', gold: 51, silver: 21, copper: 28, value: 100},
    {name: '美国', gold: 36, silver: 38, copper: 36, value: 110},
    {name: '俄罗斯', gold: 23, silver: 21, copper: 28, value: 72},
    {name: '英国', gold: 19, silver: 13, copper: 15, value: 47},
    {name: '德国', gold: 16, silver: 10, copper: 15, value: 41},
    {name: '澳大利亚', gold: 14, silver: 15, copper: 17, value: 46},
    {name: '韩国', gold: 13, silver: 10, copper: 8, value: 31},
    {name: '日本', gold: 9, silver: 6, copper: 10, value: 25},
    {name: '意大利', gold: 8, silver: 10, copper: 10, value: 28},
    {name: '法国', gold: 7, silver: 16, copper: 17, value: 40},
    {name: '乌克兰', gold: 7, silver: 5, copper: 15, value: 27},
    {name: '荷兰', gold: 7, silver: 5, copper: 4, value: 16},
    {name: '牙买加', gold: 6, silver: 3, copper: 2, value: 11},
    {name: '西班牙', gold: 5, silver: 10, copper: 3, value: 18},
    {name: '肯尼亚', gold: 5, silver: 5, copper: 4, value: 14},
    {name: '白俄罗斯', gold: 4, silver: 5, copper: 10, value: 19},
    {name: '罗马尼亚', gold: 4, silver: 1, copper: 3, value: 8},
    {name: '埃塞俄比亚', gold: 4, silver: 1, copper: 2, value: 7},
    {name: '加拿大', gold: 3, silver: 9, copper: 6, value: 18},
    {name: '波兰', gold: 3, silver: 6, copper: 1, value: 10},
    {name: '匈牙利', gold: 3, silver: 5, copper: 2, value: 10},
    {name: '挪威', gold: 3, silver: 5, copper: 2, value: 10},
    {name: '巴西', gold: 3, silver: 4, copper: 8, value: 15},
    {name: '捷克', gold: 3, silver: 3, copper: 0, value: 6},
    {name: '斯洛伐克', gold: 3, silver: 2, copper: 1, value: 6},
    {name: '新西兰', gold: 3, silver: 1, copper: 5, value: 9},
    {name: '格鲁吉亚', gold: 3, silver: 0, copper: 3, value: 6},
    {name: '古巴', gold: 2, silver: 11, copper: 11, value: 24},
    {name: '哈萨克斯坦', gold: 2, silver: 4, copper: 7, value: 13},
    {name: '丹麦', gold: 2, silver: 2, copper: 3, value: 7},
    {name: '泰国', gold: 2, silver: 2, copper: 0, value: 4},
    {name: '蒙古', gold: 2, silver: 2, copper: 0, value: 4},
    {name: '朝鲜', gold: 2, silver: 1, copper: 3, value: 6},
    {name: '瑞士', gold: 2, silver: 0, copper: 4, value: 6},
    {name: '阿根廷', gold: 2, silver: 0, copper: 4, value: 6},
    {name: '墨西哥', gold: 2, silver: 0, copper: 1, value: 3},
    {name: '土耳其', gold: 1, silver: 4, copper: 3, value: 8},
    {name: '津巴布韦', gold: 1, silver: 3, copper: 0, value: 4},
    {name: '阿塞拜疆', gold: 1, silver: 2, copper: 4, value: 7},
    {name: '乌兹别克斯坦', gold: 1, silver: 2, copper: 3, value: 6},
    {name: '斯洛文尼亚', gold: 1, silver: 2, copper: 2, value: 5},
    {name: '印度尼西亚', gold: 1, silver: 1, copper: 3, value: 5},
    {name: '保加利亚', gold: 1, silver: 1, copper: 3, value: 5},
    {name: '芬兰', gold: 1, silver: 1, copper: 2, value: 4},
    {name: '拉脱维亚', gold: 1, silver: 1, copper: 1, value: 3},
    {name: '爱沙尼亚', gold: 1, silver: 1, copper: 0, value: 2},
    {name: '葡萄牙', gold: 1, silver: 1, copper: 0, value: 2},
    {name: '多米尼加', gold: 1, silver: 1, copper: 0, value: 2},
    {name: '比利时', gold: 1, silver: 1, copper: 0, value: 2},
    {name: '印度', gold: 1, silver: 0, copper: 2, value: 3},
    {name: '伊朗', gold: 1, silver: 0, copper: 1, value: 2},
    {name: '突尼斯', gold: 1, silver: 0, copper: 0, value: 1},
    {name: '喀麦隆', gold: 1, silver: 0, copper: 0, value: 1},
    {name: '巴拿马', gold: 1, silver: 0, copper: 0, value: 1},
    {name: '巴林', gold: 1, silver: 0, copper: 0, value: 1},
    {name: '瑞典', gold: 0, silver: 4, copper: 1, value: 5},
    {name: '克罗地亚', gold: 0, silver: 2, copper: 3, value: 5},
    {name: '立陶宛', gold: 0, silver: 2, copper: 3, value: 5},
    {name: '希腊', gold: 0, silver: 2, copper: 2, value: 4},
    {name: '特立尼达和多巴哥', gold: 0, silver: 2, copper: 0, value: 2},
    {name: '尼日利亚', gold: 0, silver: 1, copper: 3, value: 4},
    {name: '奥地利', gold: 0, silver: 1, copper: 2, value: 3},
    {name: '塞尔维亚', gold: 0, silver: 1, copper: 2, value: 3},
    {name: '爱尔兰', gold: 0, silver: 1, copper: 2, value: 3},
    {name: '阿尔及利亚', gold: 0, silver: 1, copper: 1, value: 2},
    {name: '塔吉克斯坦', gold: 0, silver: 1, copper: 1, value: 2},
    {name: '哥伦比亚', gold: 0, silver: 1, copper: 1, value: 2},
    {name: '吉尔吉斯斯坦', gold: 0, silver: 1, copper: 1, value: 2},
    {name: '摩洛哥', gold: 0, silver: 1, copper: 1, value: 2},
    {name: '巴哈马', gold: 0, silver: 1, copper: 1, value: 2},
    {name: '越南', gold: 0, silver: 1, copper: 0, value: 1},
    {name: '厄瓜多尔', gold: 0, silver: 1, copper: 0, value: 1},
    {name: '智利', gold: 0, silver: 1, copper: 0, value: 1},
    {name: '新加坡', gold: 0, silver: 1, copper: 0, value: 1},
    {name: '马来西亚', gold: 0, silver: 1, copper: 0, value: 1},
    {name: '南非', gold: 0, silver: 1, copper: 0, value: 1},
    {name: '苏丹', gold: 0, silver: 1, copper: 0, value: 1},
    {name: '冰岛', gold: 0, silver: 1, copper: 0, value: 1},
    {name: '亚美尼亚', gold: 0, silver: 0, copper: 6, value: 6},
    {name: '中华台北', gold: 0, silver: 0, copper: 4, value: 4},
    {name: '多哥', gold: 0, silver: 0, copper: 1, value: 1},
    {name: '埃及', gold: 0, silver: 0, copper: 1, value: 1},
    {name: '以色列', gold: 0, silver: 0, copper: 1, value: 1},
    {name: '委内瑞拉', gold: 0, silver: 0, copper: 1, value: 1},
    {name: '阿富汗', gold: 0, silver: 0, copper: 1, value: 1},
    {name: '毛里求斯', gold: 0, silver: 0, copper: 1, value: 1},
    {name: '摩尔多瓦', gold: 0, silver: 0, copper: 1, value: 1}
];

////////// 2004 年
var value3 = [
    {name: '美国', gold: 35, silver: 39, copper: 29, value: 103},
    {name: '中国', gold: 32, silver: 17, copper: 14, value: 63},
    {name: '俄罗斯', gold: 27, silver: 27, copper: 38, value: 92},
    {name: '澳大利亚', gold: 17, silver: 16, copper: 16, value: 49},
    {name: '日本', gold: 16, silver: 9, copper: 12, value: 37},
    {name: '德国', gold: 14, silver: 16, copper: 18, value: 48},
    {name: '法国', gold: 11, silver: 9, copper: 13, value: 33},
    {name: '意大利', gold: 10, silver: 11, copper: 11, value: 32},
    {name: '韩国', gold: 9, silver: 12, copper: 9, value: 30},
    {name: '英国', gold: 9, silver: 9, copper: 12, value: 30},
    {name: '古巴', gold: 9, silver: 7, copper: 11, value: 27},
    {name: '匈牙利', gold: 9, silver: 6, copper: 3, value: 18},
    {name: '乌克兰', gold: 9, silver: 5, copper: 9, value: 23},
    {name: '罗马尼亚', gold: 8, silver: 5, copper: 6, value: 19},
    {name: '希腊', gold: 6, silver: 6, copper: 4, value: 16},
    {name: '挪威', gold: 5, silver: 0, copper: 1, value: 6},
    {name: '荷兰', gold: 4, silver: 9, copper: 9, value: 22},
    {name: '巴西', gold: 4, silver: 3, copper: 3, value: 10},
    {name: '瑞典', gold: 4, silver: 1, copper: 2, value: 7},
    {name: '西班牙', gold: 3, silver: 11, copper: 5, value: 19},
    {name: '加拿大', gold: 3, silver: 6, copper: 3, value: 12},
    {name: '土耳其', gold: 3, silver: 3, copper: 4, value: 10},
    {name: '波兰', gold: 3, silver: 2, copper: 5, value: 10},
    {name: '新西兰', gold: 3, silver: 2, copper: 0, value: 5},
    {name: '泰国', gold: 3, silver: 1, copper: 4, value: 8},
    {name: '白俄罗斯', gold: 2, silver: 6, copper: 7, value: 15},
    {name: '奥地利', gold: 2, silver: 4, copper: 1, value: 7},
    {name: '埃塞俄比亚', gold: 2, silver: 3, copper: 2, value: 7},
    {name: '斯洛伐克', gold: 2, silver: 2, copper: 2, value: 6},
    {name: '伊朗', gold: 2, silver: 2, copper: 2, value: 6},
    {name: '中国台北', gold: 2, silver: 2, copper: 1, value: 5},
    {name: '格鲁吉亚', gold: 2, silver: 2, copper: 0, value: 4},
    {name: '保加利亚', gold: 2, silver: 1, copper: 9, value: 12},
    {name: '牙买加', gold: 2, silver: 1, copper: 2, value: 5},
    {name: '乌兹别克斯坦', gold: 2, silver: 1, copper: 2, value: 5},
    {name: '摩洛哥', gold: 2, silver: 1, copper: 0, value: 3},
    {name: '丹麦', gold: 2, silver: 0, copper: 6, value: 8},
    {name: '阿根廷', gold: 2, silver: 0, copper: 4, value: 6},
    {name: '智利', gold: 2, silver: 0, copper: 1, value: 3},
    {name: '哈萨克斯坦', gold: 1, silver: 4, copper: 3, value: 8},
    {name: '肯尼亚', gold: 1, silver: 4, copper: 2, value: 7},
    {name: '捷克', gold: 1, silver: 3, copper: 4, value: 8},
    {name: '南非', gold: 1, silver: 3, copper: 2, value: 6},
    {name: '克罗地亚', gold: 1, silver: 2, copper: 2, value: 5},
    {name: '立陶宛', gold: 1, silver: 2, copper: 0, value: 3},
    {name: '埃及', gold: 1, silver: 1, copper: 3, value: 5},
    {name: '瑞士', gold: 1, silver: 1, copper: 3, value: 5},
    {name: '印度尼西亚', gold: 1, silver: 1, copper: 2, value: 4},
    {name: '津巴布韦', gold: 1, silver: 1, copper: 1, value: 3},
    {name: '阿塞拜疆', gold: 1, silver: 0, copper: 4, value: 5},
    {name: '比利时', gold: 1, silver: 0, copper: 2, value: 3},
    {name: '以色列', gold: 1, silver: 0, copper: 1, value: 2},
    {name: '巴哈马', gold: 1, silver: 0, copper: 1, value: 2},
    {name: '喀麦隆', gold: 1, silver: 0, copper: 0, value: 1},
    {name: '阿联酋', gold: 1, silver: 0, copper: 0, value: 1},
    {name: '多米尼加共和国', gold: 1, silver: 0, copper: 0, value: 1},
    {name: '爱尔兰', gold: 1, silver: 0, copper: 0, value: 1},
    {name: '朝鲜', gold: 0, silver: 4, copper: 1, value: 5},
    {name: '拉脱维亚', gold: 0, silver: 4, copper: 0, value: 4},
    {name: '墨西哥', gold: 0, silver: 3, copper: 1, value: 4},
    {name: '葡萄牙', gold: 0, silver: 2, copper: 1, value: 3},
    {name: '塞黑', gold: 0, silver: 2, copper: 0, value: 2},
    {name: '芬兰', gold: 0, silver: 2, copper: 0, value: 2},
    {name: '斯洛文尼亚', gold: 0, silver: 1, copper: 3, value: 4},
    {name: '爱沙尼亚', gold: 0, silver: 1, copper: 2, value: 3},
    {name: '中国香港', gold: 0, silver: 1, copper: 0, value: 1},
    {name: '巴拉圭', gold: 0, silver: 1, copper: 0, value: 1},
    {name: '印度', gold: 0, silver: 1, copper: 0, value: 1},
    {name: '尼日利亚', gold: 0, silver: 0, copper: 2, value: 2},
    {name: '委内瑞拉', gold: 0, silver: 0, copper: 2, value: 2},
    {name: '特立尼达和多巴哥', gold: 0, silver: 0, copper: 1, value: 1},
    {name: '哥伦比亚', gold: 0, silver: 0, copper: 1, value: 1},
    {name: '叙利亚', gold: 0, silver: 0, copper: 1, value: 1},
    {name: '蒙古', gold: 0, silver: 0, copper: 1, value: 1},
    {name: '厄立特里亚', gold: 0, silver: 0, copper: 1, value: 1}
];

var nameMap = {
    'Afghanistan':'阿富汗',
    'Angola':'安哥拉',
    'Albania':'阿尔巴尼亚',
    'United Arab Emirates':'阿联酋',
    'Argentina':'阿根廷',
    'Armenia':'亚美尼亚',
    'French Southern and Antarctic Lands':'法属南半球和南极领地',
    'Australia':'澳大利亚',
    'Austria':'奥地利',
    'Azerbaijan':'阿塞拜疆',
    'Burundi':'布隆迪',
    'Belgium':'比利时',
    'Benin':'贝宁',
    'Burkina Faso':'布基纳法索',
    'Bangladesh':'孟加拉国',
    'Bulgaria':'保加利亚',
    'The Bahamas':'巴哈马',
    'Bosnia and Herzegovina':'波斯尼亚和黑塞哥维那',
    'Belarus':'白俄罗斯',
    'Belize':'伯利兹',
    'Bermuda':'百慕大',
    'Bolivia':'玻利维亚',
    'Brazil':'巴西',
    'Brunei':'文莱',
    'Bhutan':'不丹',
    'Botswana':'博茨瓦纳',
    'Central African Republic':'中非共和国',
    'Canada':'加拿大',
    'Switzerland':'瑞士',
    'Chile':'智利',
    'China':'中国',
    'Ivory Coast':'象牙海岸',
    'Cameroon':'喀麦隆',
    'Democratic Republic of the Congo':'刚果民主共和国',
    'Republic of the Congo':'刚果共和国',
    'Colombia':'哥伦比亚',
    'Costa Rica':'哥斯达黎加',
    'Cuba':'古巴',
    'Northern Cyprus':'北塞浦路斯',
    'Cyprus':'塞浦路斯',
    'Czech Republic':'捷克共和国',
    'Germany':'德国',
    'Djibouti':'吉布提',
    'Denmark':'丹麦',
    'Dominican Republic':'多明尼加共和国',
    'Algeria':'阿尔及利亚',
    'Ecuador':'厄瓜多尔',
    'Egypt':'埃及',
    'Eritrea':'厄立特里亚',
    'Spain':'西班牙',
    'Estonia':'爱沙尼亚',
    'Ethiopia':'埃塞俄比亚',
    'Finland':'芬兰',
    'Fiji':'斐',
    'Falkland Islands':'福克兰群岛',
    'France':'法国',
    'Gabon':'加蓬',
    'United Kingdom':'英国',
    'Georgia':'格鲁吉亚',
    'Ghana':'加纳',
    'Guinea':'几内亚',
    'Gambia':'冈比亚',
    'Guinea Bissau':'几内亚比绍',
    'Equatorial Guinea':'赤道几内亚',
    'Greece':'希腊',
    'Greenland':'格陵兰',
    'Guatemala':'危地马拉',
    'French Guiana':'法属圭亚那',
    'Guyana':'圭亚那',
    'Honduras':'洪都拉斯',
    'Croatia':'克罗地亚',
    'Haiti':'海地',
    'Hungary':'匈牙利',
    'Indonesia':'印尼',
    'India':'印度',
    'Ireland':'爱尔兰',
    'Iran':'伊朗',
    'Iraq':'伊拉克',
    'Iceland':'冰岛',
    'Israel':'以色列',
    'Italy':'意大利',
    'Jamaica':'牙买加',
    'Jordan':'约旦',
    'Japan':'日本',
    'Kazakhstan':'哈萨克斯坦',
    'Kenya':'肯尼亚',
    'Kyrgyzstan':'吉尔吉斯斯坦',
    'Cambodia':'柬埔寨',
    'South Korea':'韩国',
    'Kosovo':'科索沃',
    'Kuwait':'科威特',
    'Laos':'老挝',
    'Lebanon':'黎巴嫩',
    'Liberia':'利比里亚',
    'Libya':'利比亚',
    'Sri Lanka':'斯里兰卡',
    'Lesotho':'莱索托',
    'Lithuania':'立陶宛',
    'Luxembourg':'卢森堡',
    'Latvia':'拉脱维亚',
    'Morocco':'摩洛哥',
    'Moldova':'摩尔多瓦',
    'Madagascar':'马达加斯加',
    'Mexico':'墨西哥',
    'Macedonia':'马其顿',
    'Mali':'马里',
    'Myanmar':'缅甸',
    'Montenegro':'黑山',
    'Mongolia':'蒙古',
    'Mozambique':'莫桑比克',
    'Mauritania':'毛里塔尼亚',
    'Malawi':'马拉维',
    'Malaysia':'马来西亚',
    'Namibia':'纳米比亚',
    'New Caledonia':'新喀里多尼亚',
    'Niger':'尼日尔',
    'Nigeria':'尼日利亚',
    'Nicaragua':'尼加拉瓜',
    'Netherlands':'荷兰',
    'Norway':'挪威',
    'Nepal':'尼泊尔',
    'New Zealand':'新西兰',
    'Oman':'阿曼',
    'Pakistan':'巴基斯坦',
    'Panama':'巴拿马',
    'Peru':'秘鲁',
    'Philippines':'菲律宾',
    'Papua New Guinea':'巴布亚新几内亚',
    'Poland':'波兰',
    'Puerto Rico':'波多黎各',
    'North Korea':'北朝鲜',
    'Portugal':'葡萄牙',
    'Paraguay':'巴拉圭',
    'Qatar':'卡塔尔',
    'Romania':'罗马尼亚',
    'Russia':'俄罗斯',
    'Rwanda':'卢旺达',
    'Western Sahara':'西撒哈拉',
    'Saudi Arabia':'沙特阿拉伯',
    'Sudan':'苏丹',
    'South Sudan':'南苏丹',
    'Senegal':'塞内加尔',
    'Solomon Islands':'所罗门群岛',
    'Sierra Leone':'塞拉利昂',
    'El Salvador':'萨尔瓦多',
    'Somaliland':'索马里兰',
    'Somalia':'索马里',
    'Republic of Serbia':'塞尔维亚共和国',
    'Suriname':'苏里南',
    'Slovakia':'斯洛伐克',
    'Slovenia':'斯洛文尼亚',
    'Sweden':'瑞典',
    'Swaziland':'斯威士兰',
    'Syria':'叙利亚',
    'Chad':'乍得',
    'Togo':'多哥',
    'Thailand':'泰国',
    'Tajikistan':'塔吉克斯坦',
    'Turkmenistan':'土库曼斯坦',
    'East Timor':'东帝汶',
    'Trinidad and Tobago':'特里尼达和多巴哥',
    'Tunisia':'突尼斯',
    'Turkey':'土耳其',
    'United Republic of Tanzania':'坦桑尼亚联合共和国',
    'Uganda':'乌干达',
    'Ukraine':'乌克兰',
    'Uruguay':'乌拉圭',
    'United States of America':'美国',
    'Uzbekistan':'乌兹别克斯坦',
    'Venezuela':'委内瑞拉',
    'Vietnam':'越南',
    'Vanuatu':'瓦努阿图',
    'West Bank':'西岸',
    'Yemen':'也门',
    'South Africa':'南非',
    'Zambia':'赞比亚',
    'Zimbabwe':'津巴布韦'
};

option = {
    timeline: {
        axisType: 'category',
        data: ['2004', '2008', '2012']  
    },
    baseOption: {
        visualMap: {
            max: 120,
            calculable: true,
            inRange: {
                color: ['#313695', '#4575b4', '#74add1', '#abd9e9', '#e0f3f8', '#ffffbf', '#fee090', '#fdae61', '#f46d43', '#d73027', '#a50026']
            }
        },
        series: [{
            type: 'map',
            map: 'world',
            roam: true,
            nameMap: nameMap
        }]
    },
    options: [{
        series: {
            data: value3
        } 
    }, {
        series: {
            data: value2
        }
    }, {
        series: {
            data: value1
        }
    }]
};