option = {
  textStyle: {
    fontFamily: 'Microsoft YaHei',
  },
  color: [
    '#6395F9',
    '#D3DEFA',
    '#87DCB2',
    '#D6F2E4',
    '#829BCD',
    '#CFD3DE',
    '#E37568',
    '#F1B171',
    '#ECC24A',
    '#F7CDBD',
    '#B9AAA5',
    '#A59CFF',
    '#D5D0F9',
    '#92D2F6',
    '#C7E7A4',
    '#DAEEF7',
  ],
  legend: {
    show: true,
    itemWidth: 16,
    itemHeight: 8,
    icon: 'path://M150,171H250a50,50,0,0,1,0,100H150A50,50,0,0,1,150,171Z',
    textStyle: {
      fontSize: 14,
      fontWeight: 400,
    },
  },
  tooltip: {
    show: true,
  },
  polar: {
    radius: '62%',
    center: ['50%', '50%'],
  },
  angleAxis: {
    min: 0,
    max: 100,
    axisLabel: {
      show: false,
    },
  },
  radiusAxis: [
    {
      type: 'category',
      axisLabel: {
        interval: 0,
        fontSize: 16,
        fontWeight: 'bold',
        color: '#162440',
      },
      data: ['通知', '活期', '定期'],
    },
  ],
  dataset: [
    {
      source: [
        ['bank', '通知', '活期', '定期'],
        ['工商银行', 6, 6, 6],
        ['农业银行', 6, 6, 6],
        ['中国银行', 6, 6, 6],
        ['建设银行', 6, 6, 6],
        ['交通银行', 6, 6, 6],
        ['邮储银行', 6, 6, 6],
        ['红塔银行', 6, 6, 6],
        ['光大银行', 6, 6, 6],
        ['云南农信', 8, 8, 8],
        ['招商银行', 6, 6, 6],
        ['华夏银行', 6, 6, 6],
        ['民生银行', 6, 6, 6],
        ['广发银行', 8, 8, 8],
        ['平安银行', 6, 6, 6],
        ['浦发银行', 6, 6, 6],
        ['中信银行', 6, 6, 6],
      ],
    },
  ],
  series: [
    {
      name: '定期',
      type: 'pie',
      radius: ['45%', '60%'],
      center: ['50%', '50%'],
      z: 0,
      label: {
        position: 'outside',
        fontFamily: 'Microsoft YaHei',
        fontWeight: 400,
        fontSize: 16,
        color: '#162440',
      },
      labelLine: { show: true },
      emphasis: {
        scale: false,
        scaleSize: 10,
        focus: 'self',
      },
      datasetIndex: 0,
      seriesLayoutBy: 'column',
      encode: { itemName: 0, value: 1 },
    },
    {
      name: '活期',
      type: 'pie',
      radius: ['25%', '40%'],
      center: ['50%', '50%'],
      z: 0,
      label: { show: false },
      emphasis: {
        scale: false,
        scaleSize: 10,
        focus: 'self',
      },
      datasetIndex: 0,
      seriesLayoutBy: 'column',
      encode: { itemName: 0, value: 2 },
    },
    {
      name: '通知',
      type: 'pie',
      radius: ['5%', '20%'],
      center: ['50%', '50%'],
      z: 0,
      label: { show: false },
      emphasis: {
        scale: false,
        scaleSize: 10,
        focus: 'self',
      },
      datasetIndex: 0,
      seriesLayoutBy: 'column',
      encode: { itemName: 0, value: 3 },
    },
  ],
};
