option = {
    "tooltip":{
        "trigger":"item"
    },
    "series":[
        {
            "name":"当前",
            "type":"pie",
            "label":{
                "show":false
            },
            "radius":"90%",
            "startAngle":90,
            "center":[
                "45%",
                "50%"
            ],
            "data":[
                {
                    "value":180,
                    "name":"__other",
                    "itemStyle":{
                        "normal":{
                            "color":"rgba(0,0,0,0)"
                        }
                    }
                },
                {
                    "name":"鄱阳湖",
                    "value":54,
                    "itemStyle":{
                        "normal":{
                            "color":"#5C4BFF"
                        }
                    }
                },
                {
                    "name":"井冈山",
                    "value":22,
                    "itemStyle":{
                        "normal":{
                            "color":"#2B73F8"
                        }
                    }
                },
                {
                    "name":"三清山",
                    "value":22,
                    "itemStyle":{
                        "normal":{
                            "color":"#55C8FF"
                        }
                    }
                },
                {
                    "name":"婺源",
                    "value":22,
                    "itemStyle":{
                        "normal":{
                            "color":"#5AFFA4"
                        }
                    }
                },
                {
                    "name":"庐山",
                    "value":60,
                    "itemStyle":{
                        "normal":{
                            "color":"#E1FF67"
                        }
                    }
                }
            ],
            "itemStyle":{
                "emphasis":{
                    "shadowBlur":10,
                    "shadowOffsetX":0,
                    "shadowColor":"rgba(0, 0, 0, 0.5)"
                },
                "normal":{
                    "shadowBlur":0
                }
            }
        },
        {
            "name":"往期",
            "type":"pie",
            "label":{
                "show":false
            },
            "startAngle":90,
            "radius":"90%",
            "center":[
                "50%",
                "50%"
            ],
            "data":[
                {
                    "name":"庐山",
                    "value":35,
                    "itemStyle":{
                        "normal":{
                            "color":"#E1FF67"
                        }
                    }
                },
                {
                    "name":"滕王阁",
                    "value":80,
                    "itemStyle":{
                        "normal":{
                            "color":"#5AFFA4"
                        }
                    }
                },
                {
                    "name":"武功山",
                    "value":30,
                    "itemStyle":{
                        "normal":{
                            "color":"#55C8FF"
                        }
                    }
                },
                {
                    "name":"庐山三叠泉",
                    "value":45,
                    "itemStyle":{
                        "normal":{
                            "color":"#2B73F8"
                        }
                    }
                },
                {
                    "name":"鄱阳湖",
                    "value":50,
                    "itemStyle":{
                        "normal":{
                            "color":"#5C4BFF"
                        }
                    }
                },
                {
                    "value":240,
                    "name":"__other",
                    "itemStyle":{
                        "normal":{
                            "color":"rgba(0,0,0,0)"
                        }
                    }
                }
            ],
            "itemStyle":{
                "emphasis":{
                    "shadowBlur":10,
                    "shadowOffsetX":0,
                    "shadowColor":"rgba(0, 0, 0, 0.5)"
                }
            }
        }
    ]
}